Fix PAM control flag for pam_pwhistory.so
ComplianceAsCode/content pull request #10021
Opened 2023-01-04 13:44 UTC by marcusburghardt

#### Description:

Newer versions of RHEL8 and RHEL9 are using authselect for PAM configurations.
When the feature `with_pwhistory` for pam_pwhistory is available, it uses `requisite` as control flag for `pam_pwhistory.so` module instead of `required`.

#### Rationale:

Although the man for `pam_pwhistory.so` contains examples to configure the module using `required` control flag, this is not the default control flag in RHEL8 and RHEL9 when using authselect.
For RHEL7 there is no authselect. However, it makes sense to keep it aligned.

In practical, changing from `required` to `requisite` has no technical impact for this case but only user experience impact since using the `requisite` control flag the user will be informed immediately.

- Fixes #10019

2023-01-04 16:30 UTC, mildas commented
I understand there is no technical impact, but might it be a problem for DISA? @Mab879 

For RHEL7 (CentOS7), do you think it will fix https://artifacts.dev.testing-farm.io/7a51726e-fd3d-400c-ac21-e72905b06a77/ ? If so, it would be amazing because it could unblock #9942

2023-01-04 16:37 UTC, marcusburghardt commented
> I understand there is no technical impact, but might it be a problem for DISA? @Mab879
> 
> For RHEL7 (CentOS7), do you think it will fix https://artifacts.dev.testing-farm.io/7a51726e-fd3d-400c-ac21-e72905b06a77/ ? If so, it would be amazing because it would unblock #9942

Yes, it fixes these rules in RHEL7 too. I successfully reproduced the error and confirmed the fix locally.

2023-01-04 16:40 UTC, marcusburghardt commented
> I understand there is no technical impact, but might it be a problem for DISA? @Mab879
> 
> For RHEL7 (CentOS7), do you think it will fix https://artifacts.dev.testing-farm.io/7a51726e-fd3d-400c-ac21-e72905b06a77/ ? If so, it would be amazing because it would unblock #9942

@Mab879 @ggbecker , we should communicate DISA to update this control flag in the "Fix Text". The assessment is already fine. For CIS I already proposed the change for RHEL7. CIS RHEL8 and RHEL9 are already aligned to use `requisite`.

2023-01-04 20:47 UTC, marcusburghardt commented
/retest

2023-01-05 08:44 UTC, marcusburghardt commented
/retest

2023-01-05 14:06 UTC, mildas approved these changes
Changes look good. The rules are passing in TF CI now (they are not being waived anymore).

2023-01-05 14:13 UTC, Mab879 commented
> > I understand there is no technical impact, but might it be a problem for DISA? @Mab879
> > For RHEL7 (CentOS7), do you think it will fix https://artifacts.dev.testing-farm.io/7a51726e-fd3d-400c-ac21-e72905b06a77/ ? If so, it would be amazing because it would unblock #9942
> 
> @Mab879 @ggbecker , we should communicate DISA to update this control flag in the "Fix Text". The assessment is already fine. For CIS I already proposed the change for RHEL7. CIS RHEL8 and RHEL9 are already aligned to use `requisite`.

We can get this in our next round of feedback to them.

2023-01-05 14:21 UTC, vojtapolasek requested changes
I discovered one failing test scenario in RHEL7:
ERROR - Script rhel7_correct_value_cis_l2.pass.sh using profile xccdf_org.ssgproject.content_profile_cis found issue:
ERROR - Rule evaluation resulted in fail, instead of expected pass during initial stage

2023-01-06 12:58 UTC, marcusburghardt commented
/retest

2023-01-06 13:38 UTC, vojtapolasek approved these changes

2023-01-06 15:04 UTC, vojtapolasek commented
I am merging this PR, thank you @marcusburghardt  for the fix. The Ansible lint test is broken now.

2023-01-06 15:05 UTC, merged