accounts_passwords_pam_tally2: bash: Move to bash_ensure_pam_module_option
ComplianceAsCode/content pull request #10058
Opened 2023-01-13 13:41 UTC by dodys

#### Description:

- As discussed in Gitter, this change removes the degree character and move remediation to new macro `bash_ensure_pam_module_option`.

2023-01-18 11:07 UTC, marcusburghardt reviewed
@dodys , there is also a equivalent macro for Ansible. Do you plan to also update the Ansible remediation?

2023-01-20 15:32 UTC, dodys commented
> @dodys , there is also a equivalent macro for Ansible. Do you plan to also update the Ansible remediation?

Pushed a new PR for that, hopefully got it right as I don't have a way to test it right now.

2023-01-23 13:52 UTC, marcusburghardt requested changes
There is just a small syntax issue in the Ansible remediation and it should be fine to be merged.

2023-01-23 13:52 UTC, marcusburghardt commented on linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/ansible/shared.yml
> +{{{ ansible_ensure_pam_module_option('/etc/pam.d/common-auth', 'auth', 'required', 'pam_tally2.so', 'deny', "${var_password_pam_tally2}", '') }}}
```suggestion
{{{ ansible_ensure_pam_module_option('/etc/pam.d/common-auth', 'auth', 'required', 'pam_tally2.so', 'deny', "{{ var_password_pam_tally2 }}", '') }}}
```

2023-01-23 14:46 UTC, dodys commented on linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_passwords_pam_tally2/ansible/shared.yml
> +{{{ ansible_ensure_pam_module_option('/etc/pam.d/common-auth', 'auth', 'required', 'pam_tally2.so', 'deny', "${var_password_pam_tally2}", '') }}}
done! thanks!

2023-01-23 16:29 UTC, marcusburghardt approved these changes

2023-01-23 17:17 UTC, merged