Add osbuild platform
ComplianceAsCode/content pull request #10074
Opened 2023-01-18 04:09 UTC by evgenyz

#### Description:

- This is a platform for OSBuild pipeline.
- It is based on the value of the `container` environment variable (`bwrap-osbuild`).

#### Rationale:

- This platform is a prerequisite for fixing: https://github.com/ComplianceAsCode/content/issues/9536

2023-01-18 10:46 UTC, vojtapolasek requested changes
Hello @evgenyz  and thank you for the new platform. Please fix the OVAL as suggested, that should make  tests happy.

2023-01-18 10:46 UTC, vojtapolasek commented on shared/checks/oval/installed_env_is_osbuild.xml
> +  <ind:environmentvariable58_test check_existence="all_exist"
```suggestion
  <ind:environmentvariable58_test check="all" check_existence="all_exist"
```

2023-01-18 20:05 UTC, evgenyz commented on shared/checks/oval/installed_env_is_osbuild.xml
> +  <ind:environmentvariable58_test check_existence="all_exist"
Yeah, thanks.

2023-01-19 08:26 UTC, vojtapolasek commented
/retest

2023-01-19 10:42 UTC, evgenyz commented
This platform has absolutely nothing to do with OCP, we can ignore it.

2023-01-19 15:13 UTC, vojtapolasek commented
/retest

2023-01-20 09:47 UTC, vojtapolasek approved these changes
Thank you for the new platform. The CI failures seem to happen due to infrastructure problems. Also the platform should not affect the OCP in any way... mainly because it is not used in the content yet.

2023-01-20 10:05 UTC, merged