Change sshd_disable_compression applicability
ComplianceAsCode/content pull request #10072
Opened 2023-01-17 16:23 UTC by jan-cerny

#### Description:
Makes the rule sshd_disable_compression not applicable for RHEL 7.4 and newer.

#### Rationale:
RHEL 7 STIG v3r10 says in STIG ID RHEL-07-040470 that "for RHEL 7.4 and above, this requirement is not applicable.".

2023-01-17 16:25 UTC, jan-cerny commented
Discussion/question: This applicability change is done for RHEL 7 STIG and will affect also other RHEL 7 profiles, eg. HIPAA, NCP, rhelh-stig, rhelh-vpp. Should we instead create a different rule just for STIG to not affect the other profiles?

2023-01-18 13:37 UTC, yuumasato commented
> Discussion/question: This applicability change is done for RHEL 7 STIG and will affect also other RHEL 7 profiles, eg. HIPAA, NCP, rhelh-stig, rhelh-vpp. Should we instead create a different rule just for STIG to not affect the other profiles?

I don't think we need a new rule.
The applicability is related to a behavior that changed in RHEL 7.4 and the profiles should be fine incorporating the new applicability.

2023-01-20 08:46 UTC, yuumasato requested changes

2023-01-20 08:46 UTC, yuumasato commented on shared/checks/oval/rhel7_older_than_7_4.xml
> +    <ind:subexpression operation="less than">7.4</ind:subexpression>
@jan-cerny I get the following error:
`OpenSCAP Error: Invalid type of operation in string evaluation: 8. [oval_cmp_basic.c:195]`

```suggestion
    <ind:subexpression operation="less than" datatype="float">7.4</ind:subexpression>
```

2023-01-20 16:13 UTC, yuumasato approved these changes

2023-01-20 16:17 UTC, yuumasato commented on shared/checks/oval/rhel7_older_than_7_4.xml
> +    <ind:subexpression operation="less than">7.4</ind:subexpression>
Yeah, `version` is much better!

2023-01-20 17:12 UTC, jan-cerny commented
I have changed the data types in the applicability OVAL file.

2023-01-23 08:22 UTC, jan-cerny commented
/retest

2023-01-23 10:35 UTC, merged