New rule for SLE 15 unnecessary_firewalld_services_ports_disabled
ComplianceAsCode/content pull request #10090
Opened 2023-01-19 13:02 UTC by rumch-se

#### Description:

- _New rule for SLE 15 which covers CIS requirement 3.5.1.6 Ensure unnecessary services and ports are not accepted_

#### Rationale:

- At the moment CIS profile for SLE 15 does not include this requirement.  The control cannot be automated, and should be addressed manually.

2023-01-26 18:38 UTC, Mab879 requested changes
Thanks for the PR. I have do a few suggestions.

2023-01-26 18:38 UTC, Mab879 commented on linux_os/guide/system/network/network-firewalld/unnecessary_firewalld_services_ports_disabled/rule.yml
> +    - <tt>ACCEPT</tt> - you accept all incoming packets except those disabled by a specific rule.
```suggestion
    - <tt>ACCEPT</tt> - accept all incoming packets except those disabled by a specific rule.
```

2023-01-26 18:38 UTC, Mab879 commented on linux_os/guide/system/network/network-firewalld/unnecessary_firewalld_services_ports_disabled/rule.yml
> +    - <tt>REJECT</tt> - you disable all incoming packets except those that you have allowed in
```suggestion
    - <tt>REJECT</tt> - disables all incoming packets except those that have been allowed in by
```

2023-01-26 18:38 UTC, Mab879 commented on linux_os/guide/system/network/network-firewalld/unnecessary_firewalld_services_ports_disabled/rule.yml
> +    - <tt>DROP</tt> - you disable all incoming packets except those that you have allowed in
```suggestion
    - <tt>DROP</tt> - disables all incoming packets except those that been have allowed in by
```

2023-01-26 18:38 UTC, Mab879 commented on linux_os/guide/system/network/network-firewalld/unnecessary_firewalld_services_ports_disabled/rule.yml
> +ocil_clause: 'Your system accepts all incoming packets for unnecessary services and ports'
```suggestion
ocil_clause: 'the system accepts all incoming packets for unnecessary services and ports'
```

2023-01-26 18:38 UTC, Mab879 commented on linux_os/guide/system/network/network-firewalld/unnecessary_firewalld_services_ports_disabled/rule.yml
> +    If your have to remove an unnecessary service run the following command:
```suggestion
    To remove an unnecessary service, run the following command: 
```

2023-01-26 18:38 UTC, Mab879 commented on linux_os/guide/system/network/network-firewalld/unnecessary_firewalld_services_ports_disabled/rule.yml
> +    If you have to remove an unnecessary port run the following command:
```suggestion
    To remove an unnecessary port, run the following command:
```

2023-01-26 18:38 UTC, Mab879 commented on linux_os/guide/system/network/network-firewalld/unnecessary_firewalld_services_ports_disabled/rule.yml
> +title: 'Ensure unnecessary services and ports are not accepted'
```suggestion
title: 'Ensure Unnecessary Services and Ports Are Not Accepted'
```

2023-01-26 18:38 UTC, Mab879 commented on linux_os/guide/system/network/network-firewalld/unnecessary_firewalld_services_ports_disabled/rule.yml
> +    For every zone, you can set a default behavior that handles incoming traffic that is not
```suggestion
    For every zone, a default behavior can be set that handles incoming traffic that is not
```

2023-01-27 08:27 UTC, rumch-se commented
Hello @Mab879 
Thank you for your feedback.
I have corrected the rule.
Have a nice day
Rumen

2023-02-03 13:37 UTC, Mab879 requested changes
Sorry, Just one last minor change.

2023-02-03 13:37 UTC, Mab879 commented on linux_os/guide/system/network/network-firewalld/unnecessary_firewalld_services_ports_disabled/rule.yml
> +ocil_clause: 'The system accepts all incoming packets for unnecessary services and ports'
```suggestion
ocil_clause: 'the system accepts incoming packets for unnecessary services and ports'
```

2023-02-06 15:05 UTC, rumch-se commented
Hello @Mab879 
I have done the requested change.
Have a nice day
Rumen

2023-02-06 16:00 UTC, merged