Ol8 v1r5 small updates - update policy text & remove rule for OL08-00-010510
ComplianceAsCode/content pull request #10093
Opened 2023-01-19 17:04 UTC by Xeicker

#### Description:

- Update policy in rule `ssh_host_key_permissions`
- Remove rule `sshd_disable_compression` from OL8 & RHEL8

#### Rationale:

- This is to align with latest DISA STIG requirements. v1r5 for OL8 and v1r9 for RHEL8

2023-01-19 19:00 UTC, Mab879 requested changes
Thanks for the PR. Make sure that you update the variable in the RHEL 8 profile stability as well.

2023-01-19 19:00 UTC, Mab879 commented on products/rhel8/profiles/stig.profile
> -    - var_sshd_disable_compression=no
This also needs to be removed from the profile stability.

2023-01-23 21:51 UTC, Mab879 approved these changes
Thanks for the PR!

2023-01-24 13:48 UTC, vojtapolasek commented
/ok-to-test

2023-01-25 08:27 UTC, vojtapolasek commented
@ComplianceAsCode/oracle-maintainers  Could you please accept these changes?

2023-01-25 16:33 UTC, freddieRv approved these changes

2023-01-25 17:40 UTC, merged