New SLE 15 rule service_nftables_enabled
ComplianceAsCode/content pull request #10113
Opened 2023-01-23 12:44 UTC by rumch-se

#### Description:

- _New SLE 15 rule which covers CIS recommendation 3.5.2.9 Ensure nftables service is enabled (Automated)_

#### Rationale:

- At the moment CIS profile for SLE 15 does not include this rule.

2023-01-23 16:17 UTC, Mab879 requested changes
Thanks for the PR; just one minor change.

2023-01-23 16:17 UTC, Mab879 commented on linux_os/guide/system/network/network-nftables/service_nftables_enabled/rule.yml
> +title: 'Verify nftables service is enabled'
```suggestion
title: 'Verify nftables Service Is Enabled'
```

2023-01-23 16:17 UTC, Mab879 commented on linux_os/guide/system/network/network-nftables/service_nftables_enabled/rule.yml
> +title: 'Verify nftables service is enabled'
The title of rules needs to be in title case.

2023-01-24 09:38 UTC, rumch-se commented
Hello @Mab879 
I have made the proposed small change. (https://github.com/ComplianceAsCode/content/pull/10113/commits/b98d058855e3baa99b2eb0444524617ccd090874) 
Have a nice day
Rumen

2023-01-24 18:24 UTC, Mab879 approved these changes

2023-01-25 17:53 UTC, Mab879 commented
/packit retest-failed

2023-01-25 20:27 UTC, Mab879 commented
The Automatus failures are expected due to the prodtype.

2023-01-25 20:27 UTC, merged