OCP: Automated apiserver tls checks
ComplianceAsCode/content pull request #10118
Opened 2023-01-24 07:01 UTC by Vincent056

Automate `api_server_oauth_https_serving_cert` and `api_server_openshift_https_serving_cert` checks. It is possible to check if tls is being used under `/apis/config.openshift.io/v1/apiservers/cluster`.

By default API-Server uses `intermediate` TLS security profile, we want to check that `old` is not being used as TLS security profile.[https://docs.openshift.com/container-platform/4.8/security/tls-security-profiles.html]

2023-01-24 10:24 UTC, jhrozek requested changes

2023-01-24 10:24 UTC, jhrozek commented on applications/openshift/api-server/api_server_openshift_https_serving_cert/rule.yml
> +    yamlpath: "spec.tlsSecurityProfile.type"
I'm not sure about the `entity_check`, doesn't it correspond to the object as opposed to the path? By default the object doesn't contain `spec.tlsSecurityProfile.type` and that's why the rule fails. Locally it helped to add `check_existence: "any_exist"`, but I'm not sure if that is the right thing.

2023-01-30 21:21 UTC, jhrozek commented
I think this is fine and if you want, I'll ack this patch, but here's a question: What if we turn this rule into one that pretty much just mirrors what `applications/openshift/api-server/api_server_tls_security_profile/` does, just with the OAuth specific OCIL, so that this rule would have a custom OVAL that would and `api_server_tls_security_profile_not_old` with `api_server_tls_security_profile_custom_min_tls_version`? The reason is that the current implementation of the rule misses Custom profiles with old TLS version.

We could even reuse the variable for the TLS profile in the `applications/openshift/api-server/api_server_tls_security_profile/` rule...

2023-01-31 01:05 UTC, Vincent056 commented
> is that the current implementation of the rule misses Custom profiles with old TLS version.
> 
> We could even reuse the variable for the TLS profile in the `applications/openshift/api-server/api_server_tls_security_profile/` rule...

So this will essentially duplicate the `api_server_tls_security_profile` rule

2023-01-31 09:13 UTC, jhrozek commented
AWS terraform provider says no
/retest

2023-01-31 09:13 UTC, jhrozek approved these changes
great, simple and to the point
/lgtm

2023-01-31 21:09 UTC, merged