New SLE 15 rule set_nftables_table
ComplianceAsCode/content pull request #10128
Opened 2023-01-26 11:30 UTC by rumch-se

#### Description:

- _New SLE 15 rule which covers CIS requirement 3.5.2.4 Ensure a table exists (Automated)_

#### Rationale:

- At the moment CIS profile for SLE 15 does not include this rule.

2023-01-26 19:35 UTC, Mab879 requested changes
Thanks for the PR. I have a few suggestions. Please also add Automatus tests for this rule as well.

2023-01-26 19:35 UTC, Mab879 commented on linux_os/guide/system/network/network-nftables/set_nftables_table/ansible/shared.yml
> +- name: Collect existing nftables
```suggestion
- name: Collect Existing Nftables 
```

2023-01-26 19:35 UTC, Mab879 commented on linux_os/guide/system/network/network-nftables/set_nftables_table/ansible/shared.yml
> +- name: Set nftable table
```suggestion
- name: Set Nftable Table
```

2023-01-26 19:35 UTC, Mab879 commented on linux_os/guide/system/network/network-nftables/set_nftables_table/rule.yml
> +
Please add warning like [this](https://github.com/ComplianceAsCode/content/blob/1b538dfc48ab5bd43f8d9d9a1b6823707dcdbf71/linux_os/guide/services/ssh/ssh_server/sshd_use_strong_rng/rule.yml#L55) about risk of losing connectivity to the system.

2023-01-26 19:35 UTC, Mab879 commented on linux_os/guide/system/network/network-nftables/var_nftables_family.var
> +    <tt>bdidge</tt>Tables of this family see traffic/packets traversing bridges
```suggestion
    <tt>bridge</tt>Tables of this family see traffic/packets traversing bridges 
```

2023-01-26 19:35 UTC, Mab879 commented on linux_os/guide/system/network/network-nftables/set_nftables_table/rule.yml
> +    Nftables doesn't have any default tables. Without a table being build, nftables will not filter
```suggestion
    Nftables doesn't have any default tables. Without a table being built, nftables will not filter
```

2023-01-26 19:35 UTC, Mab879 commented on linux_os/guide/system/network/network-nftables/set_nftables_table/rule.yml
> +ocil_clause: 'nftables table does not exist'
```suggestion
ocil_clause: 'a nftables table does not exist'
```

2023-01-26 19:35 UTC, Mab879 commented on controls/cis_sle15.yml
> +       The audit (OVAL check) cannot be automated,
Just a side note, if you are willing to not be SCAP compliant SCE (script check engine) content could be used on this rule to automate the check.

2023-01-27 09:05 UTC, rumch-se commented
Hello @Mab879 
Thank you for your feedback.
I have done the corrections proposed.
Have a nice day
Rumen

2023-01-30 14:46 UTC, marcusburghardt commented on linux_os/guide/system/network/network-nftables/var_nftables_table.var
> +
```suggestion
```

2023-02-02 20:27 UTC, Mab879 approved these changes
Thanks for the PR!

2023-02-02 20:35 UTC, Mab879 commented
@teacup-on-rockingchair can you please take a look at this?

2023-02-03 09:08 UTC, teacup-on-rockingchair commented
> @teacup-on-rockingchair can you please take a look at this?

LGTM, not sure what I can add, besides maybe a clause on nftables package in the remediation for bash:
```
{{{ bash_package_install("nftables") }}}

``` 
and ansible:

```
- name: "Ensure nftables is installed"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - nftables
```

otherwise on  my broken SLE15 setup the remediation passes, assuming nftables commands work, when there is no nft command at all.

2023-02-15 17:56 UTC, Mab879 commented
Overriding CODEOWNERS since an SUSE approver is not available currently.

2023-02-15 17:56 UTC, merged