Extends rsyslog_logfiles_attributes_modify template for permissions
ComplianceAsCode/content pull request #10139
Opened 2023-01-30 13:53 UTC by marcusburghardt

#### Description:

The PR #9789 introduced a new template to check and remediate rsyslog log files attributes.
The initial template covers `ownership` and `group-ownership` attributes, which satisfy these two rules:

- rsyslog_files_ownership
- rsyslog_files_groupownership

The template is already compatible to both legacy and RainerScript syntax.
This PR is a extension of the `rsyslog_logfiles_attributes_modify` template in order to also cover `permissions` attributes of rsyslog log files, which satisfy the following additional rule:

- rsyslog_files_permissions

#### Rationale:

These are the only three relevant rules for rsyslog log files attributes, which are now aligned to the same approach through this new template. In addition:

- Many test scenario scripts were removed in favor of the templated ones
- The same OVAL, Bash and Ansible logic is used for the three rules
- RainerScript syntax is now supported to find rsyslog log files
- Legacy syntax remains compatible in all rules

#### Review Hints:

- Better to review the PR commit by commit in sequence.
- I recommend automatus to check the rules:

./build_product rhel7 rhel8 rhel9 ...

Example of `automatus` command for testing these 3 rules:
```bash
for rule in rsyslog_files_permissions rsyslog_files_groupownership rsyslog_files_ownership; do
  for flavor in bash ansible; do
    ./tests/automatus.py rule --libvirt qemu:///session <VM NAME> --datastream build/ssg-rhel8-ds.xml --dontclean --remediate-using $flavor $rule
  done
done
```

2023-01-30 13:53 UTC, marcusburghardt commented
FYI @dodys and @teacup-on-rockingchair

2023-01-30 15:40 UTC, marcusburghardt commented
`Automatus CS9 / Run Tests (pull_request)` is failing for Bash remediation because there is no `which` command in the container.

2023-01-31 08:35 UTC, marcusburghardt commented
> `Automatus CS9 / Run Tests (pull_request)` is failing for Bash remediation because there is no `which` command in the container.

In any case, I fixed this in the last commit.

2023-01-31 11:49 UTC, marcusburghardt commented
/retest

2023-01-31 14:41 UTC, marcusburghardt commented
/retest

2023-01-31 16:17 UTC, yuumasato requested changes

2023-02-01 09:11 UTC, marcusburghardt commented on shared/templates/rsyslog_logfiles_attributes_modify/tests/rainer_include_correct_attr.pass.sh
> +ATTR_VALUE="0600"
In all current cases, the expected permission is `0600` or `0640` and a stricter permission is accepted. So for the test scenarios in `template`, using `0600` is enough for the correct permission. In a similar logic, in all current cases, no permission for "others" is allowed. So `0666` is also sufficient for the test scenarios in this template.

Something interesting would be to include an additional test scenario specific to Ubuntu and SLE in the `rsyslog_files_permissions` rule. I will include.

2023-02-01 09:21 UTC, marcusburghardt commented on shared/templates/rsyslog_logfiles_attributes_modify/tests/legafy_incorrect_attr.fail.sh
> +#!/bin/bash
Fixed

2023-02-01 09:21 UTC, marcusburghardt commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_files_permissions/rule.yml
> +    value: '0600'
Verified the respective benchmarks and updated the `rule.yml` file.

2023-02-01 09:22 UTC, marcusburghardt commented on shared/templates/rsyslog_logfiles_attributes_modify/bash.template
> +        FILE_CMD="chmod"
Improved the bash template.

2023-02-01 09:23 UTC, marcusburghardt commented on shared/templates/rsyslog_logfiles_attributes_modify/ansible.template
> +    mode: '{{ ( "{{{ ATTRIBUTE }}}" is match("permissions")) | ternary("{{{ VALUE }}}" , omit) }}'
There was issues with this suggestion. I fixed them and amended the commit.

2023-02-02 10:47 UTC, marcusburghardt commented on shared/templates/rsyslog_logfiles_attributes_modify/tests/rainer_include_correct_attr.pass.sh
> +ATTR_VALUE="0600"
Done.

2023-02-02 10:51 UTC, marcusburghardt commented
/packit retest-failed

2023-02-02 12:56 UTC, yuumasato approved these changes
Nice work

2023-02-02 13:01 UTC, yuumasato commented
The failure on c9s is unrelated to this PR:
```
:: [ 11:08:46 ] :: [   FAIL   ] :: Rules not passing after remediation:

xccdf_org.ssgproject.content_rule_service_rngd_enabled - fail
```

2023-02-02 13:01 UTC, merged