improve applicability of rule package_rear_installed (master branch)
ComplianceAsCode/content pull request #10156
Opened 2023-02-02 10:35 UTC by vojtapolasek

This is a port of https://github.com/ComplianceAsCode/content/pull/10144 into master branch. Original description and rationale follow:

#### Description:

Create appropriate platforms to fullfill the following:
Make the rule not applicable in following cases:
- arch is s390x and RHEL <= 8.4
- arch is aarch64 and RHEL or OL >= 9.0

#### Rationale:

- the rear package is not available on some arches and RHEL / OL versions

#### Review Hints:

- build the content
- instantiate some RHEL (OL) machine on s390x / aarch64 machine
- test that OVALs are applicable / not applicable in correct cases
- do the same with Ansible - you can use the e8 Ansible playbook with --tag=package_rear_installed
- tip: modify the /etc/os-release version_id line to simulate various distro versions

2023-02-02 20:16 UTC, Mab879 commented
/packit test

2023-02-02 20:18 UTC, Mab879 commented
/retest

2023-02-03 11:26 UTC, Mab879 requested changes
Can you please rebase? That should fix the issues with packit tests.

2023-02-06 08:01 UTC, vojtapolasek commented
/retest

2023-02-06 13:48 UTC, vojtapolasek commented
@Mab879  rebased and checks are passing.

2023-02-06 14:02 UTC, Mab879 approved these changes

2023-02-06 14:02 UTC, merged