Shorten rule title
ComplianceAsCode/content pull request #10196
Opened 2023-02-10 09:13 UTC by jan-cerny

Rule titles should be brief. The very long rule title causes text overflows in HTML report and causes vertical scrolling in SCAP Workbench.

2023-02-10 17:53 UTC, Mab879 requested changes

2023-02-10 17:53 UTC, Mab879 commented on linux_os/guide/system/software/sudo/sudo_require_reauthentication/rule.yml
> +title: 'Require re-authentication when using the sudo command'
```suggestion
title: 'Require Re-Authentication When Using the sudo Command'
```
This must be in title case, per the [style guide](https://complianceascode.readthedocs.io/en/latest/manual/developer/04_style_guide.html#rule-sections)

2023-02-13 08:14 UTC, jan-cerny commented
good to know thx

I think we can have a check that enforces the case and also maximum length

2023-02-13 09:47 UTC, marcusburghardt commented
> good to know thx
> 
> I think we can have a check that enforces the case and also maximum length

That would be great. I would be happy to review this proposal.

2023-02-13 10:27 UTC, merged