postfix_prevent_unrestricted_relay: allow whitespaces and no comma for 'smtpd_client_restrictions' value
ComplianceAsCode/content pull request #10219
Opened 2023-02-16 15:52 UTC by rmetrich

Rule **xccdf_org.ssgproject.content_rule_postfix_prevent_unrestricted_relay**

#### Description:

The `postconf(5)` manpage specifies that values can be separated by commas and/or whitespace for **smtpd_client_restrictions** property.

#### Rationale:

The following specifications should be valid:
~~~
smtpd_client_restrictions = permit_mynetworks,reject smtpd_client_restrictions = permit_mynetworks, reject smtpd_client_restrictions = permit_mynetworks reject smtpd_client_restrictions = permit_mynetworks  ,  reject
smtpd_client_restrictions = permit_mynetworks    reject
~~~

2023-02-16 21:39 UTC, Mab879 commented
/ok-to-test

2023-02-17 14:40 UTC, marcusburghardt requested changes
Could you include a test scenarios these variations, please?

2023-02-20 13:05 UTC, marcusburghardt approved these changes
All tests have passed in local VMs too.
I am fine to merge this PR as it is, but I have three comments that would be good to keep in mind for next PRs:
- in general, after a request for changes, it is preferable to send more commits instead of amending the previous commits and forcibly pushing the changes. This way we can see the last changes and it makes the review time much faster.
- the `ok` prefix is not necessary in `pass` test scenarios
- each test scenario increases a little bit the testing time, it is not the case here but consider to unify similar tests whenever reasonable

Thanks for the fix and hope to see more PRs from you. : )

2023-02-20 13:22 UTC, merged

2023-02-20 13:55 UTC, rmetrich commented on linux_os/guide/services/mail/postfix_harden_os/postfix_server_cfg/postfix_server_relay/postfix_prevent_unrestricted_relay/tests/ok_comma_multiple_whitespaces_left.pass.sh
> +#!/bin/bash
Comments noted for next time. I'm used to squash things because usually other projects do not tolerate unsquashed commits...