Add UFW related rule for CIS on Ubuntu
ComplianceAsCode/content pull request #10248
Opened 2023-02-22 14:15 UTC by dodys

#### Description:

- This PR adds a few rules related to UFW (Uncomplicated Firewall) for CIS on Ubuntu:
  - ufw_rules_for_open_ports
  - set_ufw_loopback_traffic
  - set_ufw_default_rule

#### Rationale:

- Those rules are needed for CIS on Ubuntu 22.04 and/or 20.04.

2023-02-23 13:32 UTC, jan-cerny commented
@dodys We're sorry but we had an issue with the CI jobs and unfortunately they're required to pass before merging. Could you please rebase this PR on the top of the latest upstream master branch? That will include fix from https://github.com/ComplianceAsCode/content/pull/10250 to this PR and will unblock the CI.

2023-02-27 10:45 UTC, marcusburghardt requested changes
My comments are more related to style guide.

2023-02-27 10:45 UTC, marcusburghardt commented on linux_os/guide/system/network/network-ufw/set_ufw_default_rule/rule.yml
> +title: 'Ensure ufw default deny firewall policy'
In alignment to [Style Guide](https://complianceascode.readthedocs.io/en/latest/manual/developer/04_style_guide.html#rule-sections) it must be in [Title case](https://en.wikipedia.org/wiki/Title_case)

2023-02-27 10:45 UTC, marcusburghardt commented on linux_os/guide/system/network/network-ufw/set_ufw_default_rule/rule.yml
> +    deny will be blocked
```suggestion
    deny will be blocked.
```

2023-02-27 10:45 UTC, marcusburghardt commented on linux_os/guide/system/network/network-ufw/set_ufw_default_rule/rule.yml
> +    usage than to black list unacceptable usage.
```suggestion
    is not configured to be denied. It is easier to allow acceptable
    usage than to block unacceptable usage.
```

2023-02-27 10:45 UTC, marcusburghardt commented on linux_os/guide/system/network/network-ufw/set_ufw_default_rule/sce/shared.sh
> +#
```suggestion
```

2023-02-27 10:45 UTC, marcusburghardt commented on linux_os/guide/system/network/network-ufw/set_ufw_default_rule/sce/shared.sh
> +#
```suggestion
```

2023-02-27 10:45 UTC, marcusburghardt commented on linux_os/guide/system/network/network-ufw/set_ufw_loopback_traffic/rule.yml
> +title: 'Set UFW loopback traffic'
```suggestion
title: 'Set UFW Loopback Traffic'
```

2023-02-27 10:45 UTC, marcusburghardt commented on linux_os/guide/system/network/network-ufw/set_ufw_loopback_traffic/rule.yml
> +warnings:
It should go after `ocil`

2023-02-27 10:45 UTC, marcusburghardt commented on linux_os/guide/system/network/network-ufw/set_ufw_loopback_traffic/sce/shared.sh
> +#
```suggestion
```

2023-02-27 10:45 UTC, marcusburghardt commented on linux_os/guide/system/network/network-ufw/ufw_rules_for_open_ports/sce/shared.sh
> +#
```suggestion
```

2023-02-27 11:33 UTC, marcusburghardt commented on linux_os/guide/system/network/network-ufw/set_ufw_loopback_traffic/rule.yml
> +documentation_complete: true
```suggestion
documentation_complete: true

prodtype: ubuntu2004,ubuntu2204
```

2023-02-27 11:34 UTC, marcusburghardt commented on linux_os/guide/system/network/network-ufw/set_ufw_loopback_traffic/rule.yml
> +documentation_complete: true
Could you include `prodtype`, please? Then we limit this rule to not appear in other data streams.

2023-02-27 12:44 UTC, marcusburghardt approved these changes

2023-02-28 09:21 UTC, marcusburghardt commented
Automatus CS8 and CS9 tests are failing because the rules are restricted to `prodtype: ubuntu2004,ubuntu2204`. Waived.

Overriding CODEOWNERS since a @dodys can't approve his own PRs.

2023-02-28 09:21 UTC, merged