Include rule for checking password last change in RHEL
ComplianceAsCode/content pull request #10243
Opened 2023-02-21 14:23 UTC by marcusburghardt

#### Description:

The `accounts_password_last_change_is_in_past` rule also satisfies the CIS requirements for RHEL7, RHEL8 and RHEL9.

#### Rationale:

Better CIS coverage for RHEL.

- Fixes #5537

2023-02-22 10:13 UTC, jan-cerny approved these changes

2023-02-22 12:32 UTC, jan-cerny requested changes
The CI fail looks legit:

xccdf_org.ssgproject.content_rule_accounts_password_last_change_is_in_past:unknown

from a quick look I can't find what it is

2023-02-27 07:25 UTC, marcusburghardt commented
> The CI fail looks legit:
> 
> xccdf_org.ssgproject.content_rule_accounts_password_last_change_is_in_past:unknown
> 
> from a quick look I can't find what it is

The https://github.com/ComplianceAsCode/content/pull/10243/commits/8def7b55c011d18f13208ffeefd71b5e807ccbb2 fixes this issue. More details in the commit description.

2023-02-27 10:39 UTC, jan-cerny approved these changes
Thank you, I have checked that the rule has been tested by Automatus on cs8 and cs9.

2023-02-27 10:39 UTC, merged