sudo_add_use_pty: depend on sudo being installed
ComplianceAsCode/content pull request #10315
Opened 2023-03-09 16:41 UTC by candrews

#### Description:

sudo_add_use_pty: depend on sudo being installed

#### Rationale:

sudo_add_use_pty only makes sense if sudo is installed, so it should express that with "platform: package[sudo]" as other rules (such as sudo_add_use_pty) already do.

#### Review Hints:

With this change applied, `oscap-podman ubuntu:20.04 xccdf eval --report report.html --profile xccdf_org.ssgproject.content_profile_cis_level2_workstation /usr/share/xml/scap/ssg/content/ssg-ubuntu2004-ds.xml`  should yield a report indicating that the "Ensure Only Users Logged In To Real tty Can Execute Sudo - sudo use_pty" rule is "Not Applicable"

2023-03-15 15:26 UTC, jan-cerny requested changes
I think that you will have to add a `# packages = sudo` line to the headers of all test scenario files in the `tests` directory of this rule directory because if the tests are executed in CI on a container back end they don't have the sudo available and they failed to setup.

2023-03-15 16:03 UTC, candrews commented
Makes sense, thank you!

I've updated this PR accordingly.

2023-03-16 14:43 UTC, jan-cerny approved these changes
```
[jcerny@thinkpad scap-security-guide{pr/10315}]$ python3 tests/automatus.py rule --libvirt qemu:///system ssgts_rhel9 sudo_add_use_pty
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/jcerny/work/git/scap-security-guide/logs/rule-custom-2023-03-16-1537/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_sudo_add_use_pty
INFO - Script use_pty_absent.fail.sh using profile (all) OK
INFO - Script use_pty_enabled.pass.sh using profile (all) OK
INFO - Script use_pty_enabled_dir.pass.sh using profile (all) OK
[jcerny@thinkpad scap-security-guide{pr/10315}]$ python3 tests/automatus.py rule --libvirt qemu:///system ssgts_rhel9 --remediate-using ansible sudo_add_use_pty
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/jcerny/work/git/scap-security-guide/logs/rule-custom-2023-03-16-1540/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_sudo_add_use_pty
INFO - Script use_pty_absent.fail.sh using profile (all) OK
INFO - Script use_pty_enabled.pass.sh using profile (all) OK
INFO - Script use_pty_enabled_dir.pass.sh using profile (all) OK
```

2023-03-16 14:48 UTC, jan-cerny commented
The problem with CentOS stream 8 is unrelated to the contents of this PR and is probably caused by https://status.testing-farm.io/issues/2023-03-16-centos-stream-8/

2023-03-17 15:23 UTC, jan-cerny commented
I'm skipping the CentOS Stream 8 because the aforementioned disruption is still in progress.

2023-03-17 15:23 UTC, merged