SRG-APP-000414-CTR-001010 is completely manual
ComplianceAsCode/content pull request #10342
Opened 2023-03-20 15:34 UTC by jhrozek

#### Description:

- This SRG is completely manual

#### Rationale:

- OCP4 STIG coverage

#### Review Hints:

- I will post the link to the SRG export later

2023-03-20 19:55 UTC, Mab879 requested changes
Minor formatting issue. I have not reviewed the technical changes.

2023-03-20 19:55 UTC, Mab879 commented on controls/srg_ctr/SRG-APP-000414-CTR-001010.yml
> +    https://docs.openshift.com/container-platform/latest/authentication/using-service-accounts-in-applications.html
Please add a blank line at the end of the file.

2023-03-27 08:16 UTC, jhrozek commented
/test e2e-aws-ocp4-high
/test e2e-aws-ocp4-stig-node

2023-03-27 09:36 UTC, jhrozek commented
@rhmdnd @Vincent056 PTAL

2023-04-03 22:19 UTC, Vincent056 approved these changes
/lgtm

2023-04-03 22:21 UTC, merged