Rebased hagenest set nftables loopback traffic
ComplianceAsCode/content pull request #10366
Opened 2023-03-26 06:51 UTC by teacup-on-rockingchair

#### Description:

- Add SLE15 based implementation of nftables_rules_permanent rule

#### Rationale:
- Allocate CCE for the nftables_rules_permanent rule and add rule to the CIS profile
- _The nftables_rules_permanent rule is based on the CIS requirement 3.5.2.10
    There are some internal decisions made for the rule based on the facts that:
    - Requirement assumes the system firewall is managed explicitely by nftables package and relevant kernel modules, i.e. no firewalld, no iptables installed
    - SLE 15 nftables package comes with following number of configuration files:
      - /etc/nftables/arp-filter
      - /etc/nftables/bridge-filter
      - /etc/nftables/inet-filter
      - /etc/nftables/ipv4-filter
      - /etc/nftables/ipv4-mangle
      - /etc/nftables/ipv4-nat
      - /etc/nftables/ipv4-raw
      - /etc/nftables/ipv6-filter
      - /etc/nftables/ipv6-mangle
      - /etc/nftables/ipv6-nat
      - /etc/nftables/ipv6-raw
    , where bridge, arp and inet(ipv4+ipv6), should cover L2+L3 layers of the IP stack, which are mainly addressed in other nftables requirements
    
#### Review Hints:

The design of the OVAL checks and Ansible and Bash remediation was made in a way that the rule will check that there is top-level configuration file,
    as described by the requirement /etc/sysconfig/nftables, which will include per protocol family configuration files that come with the native package.

The contents of the actual configuration as far as I understand the requirement should be left to the customer site policy.

The main idea of the rule as I tried to follow it was to make sure that there exists a configuration which to be applied on boot.

All of the changes made were SLE15 specific, since I based my logic on how the native nftables package for SUSE SLE15 looks like.

- Since the original PR #10201 was frozen for some time and @hagenest could not work on it I took the original changes, rebased them and added some improvements to it. If this one goes ok we can close the other PR without merging.

2023-04-05 08:08 UTC, jan-cerny commented
@teacup-on-rockingchair You mentioned OVAL checks in the PR description but I can't see any OVAL checks in the changed files. Is it an omission?

2023-04-05 08:12 UTC, teacup-on-rockingchair commented
> @teacup-on-rockingchair You mentioned OVAL checks in the PR description but I can't see any OVAL checks in the changed files. Is it an omission?

This was remain from the initial PR that I copied pasted by mistake I think. In its final option it was decided not to go for the OVAL check

2023-04-26 04:36 UTC, teacup-on-rockingchair commented
/retest

2023-04-26 04:37 UTC, teacup-on-rockingchair commented
/packit retest

2023-04-26 07:12 UTC, marcusburghardt commented
/packit retest-failed

2023-05-02 09:14 UTC, marcusburghardt requested changes
There are some comments about Style Guide. Also, do you plan to include any check + test scenarios?

2023-05-02 09:14 UTC, marcusburghardt commented on linux_os/guide/system/network/network-nftables/set_nftables_loopback_traffic/ansible/shared.yml
> +  command: nft add rule inet filter input iif lo accept
Please, use fully-qualified collection names [(FQCN)](https://ansible-lint.readthedocs.io/rules/fqcn/)
https://complianceascode.readthedocs.io/en/latest/manual/developer/04_style_guide.html#ansible

Also valid for other tasks in this file.

2023-05-02 09:14 UTC, marcusburghardt commented on linux_os/guide/system/network/network-nftables/set_nftables_loopback_traffic/ansible/shared.yml
> +- name: Implement loopback rules
In alignment to Style Guide, task names must be in [Title case](https://en.wikipedia.org/wiki/Title_case)

2023-05-02 09:14 UTC, marcusburghardt commented on linux_os/guide/system/network/network-nftables/set_nftables_loopback_traffic/ansible/shared.yml
> +  shell: |
Maybe this `shell` task can be replaced by `lineinfile` and `assert`. Or `find`?

2023-05-02 09:14 UTC, marcusburghardt commented on linux_os/guide/system/network/network-nftables/set_nftables_loopback_traffic/rule.yml
> +title: 'Set nftables configuration for loopback traffic'
In alignment to Style Guide, task names must be in [Title case](https://en.wikipedia.org/wiki/Title_case)

2023-05-02 09:18 UTC, marcusburghardt commented on linux_os/guide/system/network/network-nftables/set_nftables_loopback_traffic/rule.yml
> +    - general: |-
I also think it would be useful to include a warning informing the remediation is not permanent.

2023-05-03 05:11 UTC, teacup-on-rockingchair commented
> There are some comments about Style Guide. Also, do you plan to include any check + test scenarios?

After reviewing this carefully one more time, I came to conclusion that it would be best if I draft this for now. Rebase it on the effort of #10249 and re-implement the remediations and add checks and tests. Sorry I wasted your time on this :bow:

2023-05-15 13:23 UTC, marcusburghardt requested changes

2023-05-15 13:23 UTC, marcusburghardt commented on linux_os/guide/system/network/network-nftables/set_nftables_loopback_traffic/ansible/shared.yml
> +    [ -n "$passing" ] && passing=""
It doesn't seem necessary to set `passing` to false or true here. You can simply use the `ipv6_status` result code in the last tasks.

2023-05-15 14:35 UTC, marcusburghardt commented on linux_os/guide/system/network/network-nftables/set_nftables_loopback_traffic/tests/valid_config_file_handle_lo.pass.sh
> +	chain input		{
```suggestion
	chain input		{
```

2023-05-15 14:37 UTC, marcusburghardt commented on linux_os/guide/system/network/network-nftables/set_nftables_loopback_traffic/oval/sle15.xml
> +
```suggestion

```

2023-05-15 14:37 UTC, marcusburghardt commented on linux_os/guide/system/network/network-nftables/set_nftables_loopback_traffic/oval/sle15.xml
> +
There are some extra spaces...

2023-05-16 10:26 UTC, teacup-on-rockingchair commented on linux_os/guide/system/network/network-nftables/set_nftables_loopback_traffic/rule.yml
> +title: 'Set nftables Configuration for Loopback Traffic'
Done in [d86addb](https://github.com/ComplianceAsCode/content/pull/10366/commits/d86addb95123f64a765eaba01bb7e267c64e5263)

2023-05-17 06:36 UTC, marcusburghardt commented
Automatus CS8, CS9 and Fedora tests are failing because this rule is restricted to `sle15`. Waived.

2023-05-17 06:36 UTC, marcusburghardt approved these changes
LGTM

2023-05-17 06:37 UTC, marcusburghardt commented
Overriding CODEOWNERS as @teacup-on-rockingchair can't approve his own PR.

2023-05-17 06:37 UTC, merged