No remediation warning for `fapolicy_default_deny`
ComplianceAsCode/content pull request #10433
Opened 2023-04-06 09:51 UTC by mildas

#### Description:
`fapolicy_default_deny` doesn't have remediation because the rule requires to employ deny-all policy and allowing only whitelisted software. Automatic remediation could cause system non-administrable.

#### Rationale:
To inform users, remediation is missing intentionally.

2023-04-06 12:33 UTC, marcusburghardt commented on linux_os/guide/services/fapolicyd/fapolicy_default_deny/rule.yml
> +      This rule doesn't come with a remediation. Before remediating the sysadmin needs to create whitelist of authorized software.
```suggestion
      This rule doesn't come with a remediation. Before remediating the sysadmin needs to create allowlist of authorized software.
```

2023-04-06 12:35 UTC, marcusburghardt approved these changes

2023-04-06 13:45 UTC, Mab879 requested changes
I have one minor revision. Thanks!

2023-04-06 13:45 UTC, Mab879 commented on linux_os/guide/services/fapolicyd/fapolicy_default_deny/rule.yml
> +      This rule doesn't come with a remediation. Before remediating the sysadmin needs to create allowlist of authorized software.
```suggestion
      This rule doesn't come with a remediation. Before remediating the system administrator needs to create an allowlist of authorized software.
```

2023-04-11 13:12 UTC, Mab879 approved these changes

2023-04-13 16:00 UTC, merged