Add rule package_mailx_installed
ComplianceAsCode/content pull request #10495
Opened 2023-04-26 18:51 UTC by Xeicker

#### Description:

- Created rule `package_mailx_installed`

#### Rationale:

- This covers `OL08-00-010358` STIG id

#### Review Hints:

- This uses a few well established templates, so automatus results should be enough to validate this.
- This also applies to `RHEL-08-010358` so let me know if you want me to add it to RHEL profile

2023-04-26 19:23 UTC, freddieRv approved these changes
Changes LGTM

2023-04-27 13:10 UTC, Mab879 requested changes
Just one minor change.

Thanks for the PR!

2023-04-27 13:10 UTC, Mab879 commented on linux_os/guide/services/mail/package_mailx_installed/rule.yml
> +title: 'The mailx package is installed'
```suggestion
title: 'The mailx Package Is Installed'
```

2023-04-27 18:13 UTC, Mab879 approved these changes
Thanks!

2023-04-27 19:20 UTC, Mab879 commented
Waving the Automatus tests rule is not applicable for that test.

2023-04-27 19:21 UTC, merged