Update Add Product Guide
ComplianceAsCode/content pull request #10533
Opened 2023-05-05 21:29 UTC by Mab879

#### Description:

Update add products guide.

#### Rationale:
Make life easier for developers.

2023-05-16 13:47 UTC, vojtapolasek requested changes
Hello @Mab879  and thank you for this update, it is really helpful because I can imagine it can cause pain for those who try to add new products.
I think that some changes are not needed. Please see my comments.

2023-05-16 13:47 UTC, vojtapolasek commented on docs/manual/developer/03_creating_content.md
> -```
Not sure why this line is changed... I think it should stay the same.

2023-05-16 13:47 UTC, vojtapolasek commented on docs/manual/developer/03_creating_content.md
> -cat << EOF >> $NEW_PRODUCT/CMakeLists.txt
I see multiple instances of such changes in this PR. But I think they are not correct - this command is using Bash heredoc to insert contents into a file and the change you propose breaks it.
Heredoc is denoted with <<.
https://www.howtogeek.com/719058/how-to-use-here-documents-in-bash-on-linux/

2023-05-16 13:47 UTC, vojtapolasek commented on docs/manual/developer/03_creating_content.md
Additional .. should be added here as well.

2023-05-17 20:20 UTC, Mab879 commented on docs/manual/developer/03_creating_content.md
The update you requested should be in now.

2023-05-18 14:49 UTC, vojtapolasek approved these changes
Looks good now. Thank you.

2023-05-18 14:49 UTC, merged