Fixes of cron package/service for SLE 12/15
ComplianceAsCode/content pull request #10549
Opened 2023-05-10 13:37 UTC by rumch-se

#### Description:

- _Changes in profiles and rules related to cron package/service for SLE 12/15_

#### Rationale:

- The rules package_cron_installed and service_cron_enabled are not correct.

2023-05-26 03:02 UTC, teacup-on-rockingchair requested changes

2023-05-26 03:02 UTC, teacup-on-rockingchair commented on linux_os/guide/services/cron_and_at/package_cron_installed/rule.yml
> +    cis@ubuntu2204: 5.1.1
```suggestion
    cis@ubuntu2204: 5.1.1
```
drop the extra spaces added by mistake I guess

2023-05-26 06:11 UTC, rumch-se commented
Hello @teacup-on-rockingchair 
The change was done
Rumen

2023-06-15 02:51 UTC, teacup-on-rockingchair approved these changes

2023-06-15 02:52 UTC, merged