products/anolis23: supports Anolis OS 23
ComplianceAsCode/content pull request #10548
Opened 2023-05-10 02:27 UTC by rain-Qing

Signed-off-by: YuQing [yyq0391@163.com](mailto:yyq0391@163.com)
Signed-off-by: YiLin.Li [YiLin.Li@linux.alibaba.com](mailto:YiLin.Li@linux.alibaba.com)

Description:
products/anolis8: supports Anolis OS 23

Rationale:
OpenSCAP now supports many products. Anolis OS 23 is an upstream native community-oriented independent selection based on the theory of operating system hierarchy classification by the OpenAnolis community;  natively building a full-stack hardware and software collaborative next generation OS version.So I want to add the produce/anolis23 into OpenSCAP.

Fixes https://github.com/ComplianceAsCode/content/issues/10538

2023-05-15 19:37 UTC, Mab879 commented
Please take a look at the CI failures. The `utils/fix_rules.py` should be in fixing the error reported by CI.

2023-05-16 03:48 UTC, rain-Qing commented
> Please take a look at the CI failures. The `utils/fix_rules.py` should be in fixing the error reported by CI.

Thanks for your advice, I have repaired the code again and submitted it. The CI test has been passed.

2023-06-09 03:11 UTC, rain-Qing commented
@Mab879 I have resolved the conflict and resubmitted.

Please review it again. Thank you.

2023-06-16 13:34 UTC, Mab879 requested changes
Thanks for the PR! Please take look at my comments.

2023-06-16 13:34 UTC, Mab879 commented on products/anolis23/transforms/constants.xslt
> +<xsl:include href="../../shared/transforms/shared_constants.xslt"/>
```suggestion
<xsl:include href="../../../shared/transforms/shared_constants.xslt"/>
```

2023-06-16 13:34 UTC, Mab879 commented on products/anolis23/transforms/table-style.xslt
> +<xsl:import href="../../shared/transforms/shared_table-style.xslt"/>
```suggestion
<xsl:import href="../../../shared/transforms/shared_table-style.xslt"/>
```

2023-06-16 13:34 UTC, Mab879 commented on products/anolis23/transforms/xccdf-apply-overlay-stig.xslt
> +<?xml version="1.0"?>
Unless this product has  STIG please remove this file.

2023-06-26 07:28 UTC, rain-Qing commented
@Mab879 
Thank you for your comments.  I have processed and pushed again.
Please review it again. Thank you.

2023-07-03 17:13 UTC, Mab879 requested changes
Looks like a couple paths are still wrong.

Once these are fixed this should be ready to merge.

2023-07-03 17:13 UTC, Mab879 commented on products/anolis23/transforms/xccdf2table-cce.xslt
> +<xsl:import href="../../shared/transforms/shared_xccdf2table-cce.xslt"/>
```suggestion
<xsl:import href="../../../shared/transforms/shared_xccdf2table-cce.xslt"/>
```

2023-07-03 17:13 UTC, Mab879 commented on products/anolis23/transforms/xccdf2table-profileccirefs.xslt
> +<xsl:import href="../../shared/transforms/shared_xccdf2table-profileccirefs.xslt"/>
```suggestion
<xsl:import href="../../../shared/transforms/shared_xccdf2table-profileccirefs.xslt"/>
```

2023-07-05 15:36 UTC, Mab879 approved these changes

2023-07-06 08:32 UTC, rain-Qing commented
@Mab879 
Thank you for your review and comments.
Now I see that the CI/CD test has passed. (links and screenshots of some of the test results are below)
Is there anything else I need to do before the merger?

[test](https://github.com/rain-Qing/content/actions/runs/5472026122/jobs/9963746209)
![image](https://github.com/ComplianceAsCode/content/assets/102015846/8dc16555-955b-4fd9-800b-74d471f7961e)

2023-07-06 12:43 UTC, merged