Some SLE 12/15 fixes related to the rule accounts_passwords_pam_tally2
ComplianceAsCode/content pull request #10566
Opened 2023-05-15 07:48 UTC by rumch-se

#### Description:

- _This PR fixes the rule accounts_passwords_pam_tally2 according to SLE 12/15 requirements_

#### Rationale:

- 1/In some profiles the variable var_password_pam_tally2 was not set 2/The rule was excluded from ANSSI profile and 3/the rule in SLE 12/15 uses /etc/pam.d/login file to set configuration parameters

2023-05-17 09:06 UTC, dodys approved these changes
thanks for keeping this change self-contained!

2023-05-21 10:22 UTC, teacup-on-rockingchair requested changes

2023-05-30 07:33 UTC, rumch-se commented
Hi @teacup-on-rockingchair 
I have made the proposed corrections.
All the best
Rumen

2023-05-31 04:40 UTC, teacup-on-rockingchair approved these changes
Nice improvement :bow:

2023-05-31 04:41 UTC, merged