bugfix: dir_perms_world_writable_root_owned: do not modify files under /proc
ComplianceAsCode/content pull request #10563
Opened 2023-05-14 19:58 UTC by maage

#### Description:

At least under containerized env (podman) /proc can have files that are not modifiable even with root. This makes test or bash remediate fail.

#### Rationale:

This issue would be kernel regression and should be handled in another way.

#### Review Hints:

Probably should see how bash remediation survives.

2023-05-14 23:29 UTC, maage commented
This fail is because containers do not have capability to load kernel modules, here knfsd and start nfs-server. Unrelated issue, see #10387 
```
ERROR - Rule 'dir_perms_world_writable_root_owned' test setup script 'world_writable_dir_on_nonlocal_fs.fail.sh' failed with exit code 32
```

2023-05-15 08:26 UTC, marcusburghardt requested changes
Could you also update the Ansible remediation to be aligned to the Bash, please?

2023-05-26 21:36 UTC, Mab879 commented
@maage I'm looking into Ansible remediation. There is also issue with it on master.

2023-07-12 10:45 UTC, marcusburghardt commented
> > Could you also update the Ansible remediation to be aligned to the Bash, please?
> 
> Updated, but ansible remediation needs to be checked. My ansible remediation test in now broken due to unrelated changes.
> 
> Maybe I'm understanding something wrong, but in my view `excludes: excluded_paths` should be `excludes: "{{{ excluded_paths }}}"`, these module fields are not like `when` and variants where format is `jinja`, here format is either `str` or `list`. And remediation checks should have failed, so I guess something is wrong with tests too.
> 
> Edit: added missing not

The issue is that `excludes` option in the `find` module considers the `basename` only so it won't match `/proc`. I also found opportunities to improve performance in this Ansible Playbook and I would be happy to work on it.
@maage , could you remove the Ansible changes in this PR, please? Then we can merge it and I send a PR for the Ansible remediation write after the merge. Thanks.

2023-07-13 14:43 UTC, marcusburghardt approved these changes
There are some issues with the Ansible remediation but they are not related to the changes in this PR. In fact, the changes in this PR helped us to find the issues. The Ansible remediation needs to be refactored and I will propose a PR for this right after merging this.

2023-07-13 14:43 UTC, merged