SLE 12/15 profile updates
ComplianceAsCode/content pull request #10577
Opened 2023-05-16 14:10 UTC by rumch-se

#### Description:

- _These updates covers SLE 12/15 profiles which include rules cracklib_accounts_password_pam_xxxx _

#### Rationale:

- Some of current profiles do not include rules and variable definitions used by these rules

2023-05-16 16:20 UTC, brett060102 approved these changes
LGTM

2023-05-21 10:21 UTC, teacup-on-rockingchair requested changes

2023-05-22 06:37 UTC, rumch-se commented
Hello @teacup-on-rockingchair 
The proposed change was done
Have a nice day
Rumen

2023-05-25 06:32 UTC, teacup-on-rockingchair approved these changes

2023-05-25 06:32 UTC, merged