fix: ssg_test_suite.get_product_context: fake Product
ComplianceAsCode/content pull request #10582
Opened 2023-05-17 19:35 UTC by maage

#### Description:

Product does not have __setitem__ and here product_yaml is made as dict to mock real product.

But we want to change Product for testing. So just update and thus product_yaml type is not changed.

```
Traceback (most recent call last):
  File "/home/runner/work/content/content/tests/automatus.py", line 511, in <module>
    main()
  File "/home/runner/work/content/content/tests/automatus.py", line 507, in main
    options.func(options)
  File "/home/runner/work/content/content/tests/ssg_test_suite/rule.py", line 686, in perform_rule_check
    checker.test_target()
  File "/home/runner/work/content/content/tests/ssg_test_suite/oscap.py", line 683, in test_target
    self._test_target()
  File "/home/runner/work/content/content/tests/ssg_test_suite/rule.py", line 445, in _test_target
    rules_to_test = self._get_rules_to_test()
  File "/home/runner/work/content/content/tests/ssg_test_suite/rule.py", line 298, in _get_rules_to_test
    product_yaml = common.get_product_context(product)
  File "/home/runner/work/content/content/tests/ssg_test_suite/common.py", line 285, in get_product_context
    product_yaml['cmake_build_type'] = 'Debug'
TypeError: 'Product' object does not support item assignment
Error: Process completed with exit code 1.
```

#### Rationale:

Allow modify `Product` like at `ssg_test_suite` but not at `ssg`.

#### Review Hints:

See failed test at #10574

2023-05-17 19:57 UTC, Mab879 commented
/packit build

2023-05-18 09:24 UTC, vojtapolasek requested changes
Hello @maage and thank you for the quick fix. Althought I can confirm that the fix solves the problem, I think it would be better to equip the ssg.products.Product class with the proper __setitem__ method instead. Your fix would create a difference in product_yaml in the test suite and product_yaml in the rest of the project. As the whole concept of accessing product properties is going to be changed, I think my suggestion will make later work easier by keeping the API the same.
Tagging @matejak  because he introduced the Product class.

2023-05-18 12:26 UTC, merged

2023-05-18 12:36 UTC, maage commented
Okay. Thank you for looking further.

I think `tests/ssg_test_suite/common.py` `get_product_context` should require product always. `automatus` seems to ensure `test_env.product` is set. And all calls for `get_product_context` come from `tests/ssg_test_suite/rule.py` and value as `self.test_env.product`, so essentially `automatus rule`. But I think that should be part of comprehensive lookout here.

This issue could have been catched by `mypy` as the variable has one type and at assignment value has another.

2023-05-18 14:37 UTC, vojtapolasek commented
Just for posterity, the relevant issue is https://github.com/ComplianceAsCode/content/issues/10583