Use platform_package_overrides in bash and ansible macros
ComplianceAsCode/content pull request #10626
Opened 2023-05-23 20:52 UTC by maage

#### Description:

Use `platform_package_overrides` in `bash_package_install` and `bash_package_remove`.

Add `ansible_package_install` and it uses `platform_package_overrides`

#### Rationale:

Using this fully would simplify code I guess and avoid issues like: 

Why even this was not already the case?

#### Review Hints:

This is generally not tested at all.

2023-05-23 21:44 UTC, Mab879 requested changes
Thanks for the PR!

A couple of changes to align to the style guide.

2023-05-23 21:44 UTC, Mab879 commented on shared/macros/10-ansible.jinja
> +- name: "Ensure {{{ name }}} is installed"
```suggestion
- name: "{{{ rule_title }}} - Ensure the {{{ name }}} Package Is Installed"
```

2023-05-23 21:44 UTC, Mab879 commented on shared/macros/10-ansible.jinja
> +  package:
```suggestion
  ansible.builtin.package:
```

2023-05-24 06:35 UTC, maage commented on shared/macros/10-ansible.jinja
> +- name: "Ensure {{{ name }}} is installed"
Yes

2023-05-24 06:35 UTC, maage commented on shared/macros/10-ansible.jinja
> +  package:
Yes

2023-05-24 06:37 UTC, maage commented
Fixed issues raised in review. Added doc to `ansible_package_install`, used modern python typing format for types.

2023-06-06 11:56 UTC, jan-cerny commented
@maage This is great stuff! Is it still a work in progress or do you want to click on "Ready for review"?

2023-06-19 20:00 UTC, maage commented
Now added other ansible *package:* sections, but `aide_periodic_cron_checking` has this `cron_pkg_name` setup and I am not going to extend this PR to cover that.

2023-06-21 09:39 UTC, jan-cerny commented on shared/macros/10-ansible.jinja
> +- name: "{{{ rule_title }}} - Ensure {{{ name }}} {{% if packages | length > 1 %}}Packages Are{{% else %}}Package Is{{% endif %}} Installed"
It would be better if the overridden package name would be also used in the task name.

2023-06-21 09:39 UTC, jan-cerny commented on linux_os/guide/system/network/network-wireless/wireless_software/wireless_disable_interfaces/ansible/shared.yml
> +{{{ ansible_package_install(["NetworkManager"]) }}}
Attention at the task below this. The task uses "when:" statement where the package name will have to be overridden as well

2023-07-03 07:48 UTC, jan-cerny commented
@maage please check the review above and please resolve the conflicts.

2023-08-14 07:13 UTC, jan-cerny commented
Closing for no reaction for more than a month. If you still plan to work on this PR, please address the feedback and reopen the PR.

2023-08-14 07:13 UTC, closed without merging