Update rule aide_scan_notification for sle 15
ComplianceAsCode/content pull request #10620
Opened 2023-05-23 12:18 UTC by svet-se

#### Description:

- _Update rule aide_scan_notification for sle 15_

#### Rationale:

- _Accoring DISA recommendations Version 1, Release 9 from 26 January 2023 about SLE 15 STIG - "SLES-15-010570 - Verify the SUSE operating system notifies the SA when AIDE discovers anomalies in the operation of any security functions"_

2023-05-25 06:48 UTC, marcusburghardt approved these changes

2023-05-25 10:54 UTC, teacup-on-rockingchair requested changes
Changes look perfect to me, but my tests showed that remediations/oval checks are not behaving correct on my SLES15 setup. I observed two issues:
1. explicit package dependency of `crontabs`, which looks not like a universal package name, for SUSE platforms, the correct package seem to be `cronie`.
 @svet-se can you please double check with your setup.
 @marcusburghardt  if my theory is correct we might have same issue on other platforms also or I am missing something else in the picture? If it is generic problem across all platforms maybe it deserves an issue and dedicated PR :) ?
 2. The oval checks verify for cron entries in `/var/spool/cron/root` and `/etc/cron.(d|daily|weekly|monthly`, while the ansible cron procedure places the cron entry in a drop-in configuration file `/var/spool/cron/tabs/root`. @marcusburghardt I am suspecting here again generic issue, what do you think?

2023-05-25 11:02 UTC, svet-se commented
@teacup-on-rockingchair I also noticed this, and communicate with maage who submitted this PR which added the crontabs logic (it affected other rules too). Will see if this will be fixed in the next PR-s, but IMHO this issue should be fixed in another PR.

2023-05-30 08:56 UTC, teacup-on-rockingchair approved these changes
LGTM :+1:

2023-05-30 08:56 UTC, merged