add rules UBTU-20-010045
ComplianceAsCode/content pull request #10720
Opened 2023-06-15 14:57 UTC by dexterle

#### Description:

- Update `sshd_use_approved_kex_ordered_stig` to include ubuntu 20.04

#### Rationale:

- According to DISA Canonical Ubuntu 20.04 LTS Security Guide, Version 1, and Revision 8 contains a new rule which specifies: "The Ubuntu operating system SSH server must be configured to use only FIPS-validated key exchange algorithms."

2023-06-15 15:12 UTC, dodys requested changes
a few issues
but just a heads up that we cannot merge this, as this is from revision 8
the profile is still at revision 1

2023-06-15 15:12 UTC, dodys commented on linux_os/guide/services/ssh/ssh_server/sshd_use_approved_kex_ordered_stig/ansible/shared.yml
> -# platform = Red Hat Enterprise Linux 7,Oracle Linux 7,multi_platform_sle
please use `multi_platform_ubuntu`

2023-06-15 15:12 UTC, dodys commented on linux_os/guide/services/ssh/ssh_server/sshd_use_approved_kex_ordered_stig/bash/shared.sh
> -# platform = Red Hat Enterprise Linux 7,Oracle Linux 7,multi_platform_sle
please use `multi_platform_ubuntu`

2023-06-15 15:38 UTC, dexterle commented on linux_os/guide/services/ssh/ssh_server/sshd_use_approved_kex_ordered_stig/bash/shared.sh
> -# platform = Red Hat Enterprise Linux 7,Oracle Linux 7,multi_platform_sle
Applied suggestion.

2023-06-15 15:40 UTC, dexterle commented
> a few issues but just a heads up that we cannot merge this, as this is from revision 8 the profile is still at revision 1

Thanks for the heads up, I didn't realize that the profile was still at revision 1... I've removed the changes to the `stig.profile`.

2023-06-26 10:47 UTC, dodys approved these changes
LGTM, thanks!

2023-06-26 10:47 UTC, merged