Add a section guiding through the process of rule divergence
ComplianceAsCode/content pull request #10763
Opened 2023-06-28 08:44 UTC by matejak

#### Description:

Expand the dev guide with content regarding how to deal with changes in systems that could be typically solved either by complicating existing rules, or creating new ones. The new section makes it easier to pick the right poison.

#### Rationale:

Although that class of problems typically doesn't have clearly good or clearly bad solutions, approaching the problem systematically is always beneficial.

2023-06-28 13:24 UTC, Mab879 commented
The failures on Fedora Rawhide is expected due to OpenSCAP/openscap#1995.

2023-06-28 14:33 UTC, Mab879 requested changes
Thanks for the PR I have left many comments through the file.

I will note that I had hard time figuring out how the headings where working under "Aspects to consider when picking one approach" section. I would suggest at least using bold for text that you are using a header. 


For example:
```Stability

##### Conditionals
```

If I'm reading the markdown file I think that is something missing (it's not as bad when viewing the rendered file, but screen readers that depend section headers might get confused. I  was assuming header was starting something new. However, I believe that you using `Stability` as some sort of header that is above (logically) Conditionals.

If you have any other questions please reach out.

2023-06-28 14:33 UTC, Mab879 commented on docs/manual/developer/03_creating_content.md
> +## Preventing problems
```suggestion
## Preventing Problems
```

2023-06-28 14:33 UTC, Mab879 commented on docs/manual/developer/03_creating_content.md
> +Profile and control selections
Seems like something is missing here

2023-06-28 14:33 UTC, Mab879 commented on docs/manual/developer/03_creating_content.md
> +
```suggestion
```

2023-06-28 14:33 UTC, Mab879 commented on docs/manual/developer/03_creating_content.md
> +Content Clarity
I would suggest making these pseudo headings bold, to help communicate these are heading like objects.

2023-06-28 14:33 UTC, Mab879 commented on docs/manual/developer/03_creating_content.md
> +- Configuration of [systemd's StopIdleSessionSec](https://github.com/ComplianceAsCode/content/blob/328eac5d78ee756d158c389a91633f5dd74a5d60/linux_os/guide/system/accounts/accounts-physical/logind_ses
```suggestion
- Configuration of [systemd's StopIdleSessionSec](https://github.com/ComplianceAsCode/content/blob/328eac5d78ee756d158c389a91633f5dd74a5d60/linux_os/guide/system/accounts/accounts-physical/logind_session_timeout/rule.yml#L22), which are available on rhel >= 8.7 and rhel > 9.0.
```

2023-06-29 08:48 UTC, matejak commented on docs/manual/developer/03_creating_content.md
> +##### Spawning
no cons from this POV.

2023-06-29 08:57 UTC, matejak commented on docs/manual/developer/03_creating_content.md
> +Profile and control selections
Headings should be there.

2023-06-29 15:34 UTC, Mab879 commented
Waving the Automatus Sanity, the fail is not related to this PR.

2023-06-29 15:34 UTC, merged