Implement rules for CIS OCP Section 1.3
ComplianceAsCode/content pull request #10776
Opened 2023-06-30 19:10 UTC by rhmdnd

Now that we have a profile and control files for CIS 1.4.0, we can start
wiring up the existing rules.

This commit ports all the existing rules we were using for the CIS
OpenShift profile into the CIS 1.4.0 version.

2023-07-03 11:34 UTC, jhrozek commented
/test e2e-aws-ocp4-cis-node

2023-07-03 11:34 UTC, jhrozek commented
/test e2e-aws-ocp4-cis

2023-07-03 11:56 UTC, jhrozek requested changes
the rule assignments in the control file look good, but the references from the rules should be fixed.

2023-07-03 11:56 UTC, jhrozek commented on controls/cis_ocp_1_4_0/section-1.yml
> +        - rbac_debug_role_protects_pprof
Since the original 1.3.1 control was removed, could we fix the control references in the rules?

2023-07-03 11:58 UTC, jhrozek commented
/test e2e-aws-ocp4-cis-node

2023-07-03 11:58 UTC, jhrozek commented
/test e2e-aws-ocp4-cis

2023-07-03 12:58 UTC, jhrozek commented
/test e2e-aws-ocp4-cis

2023-07-04 07:02 UTC, jhrozek commented
/test e2e-aws-ocp4-cis

2023-07-04 07:02 UTC, jhrozek commented
/test e2e-aws-ocp4-cis-node

2023-07-11 13:59 UTC, rhmdnd commented
/test e2e-aws-ocp4-cis-node
/test e2e-aws-ocp4-cis

2023-07-12 12:08 UTC, jhrozek reviewed
Rule `rbac_debug_role_protects_pprof` references both 1.3.1 but also 1.4.1. We don't have a patch for section 1.4 and the rule 1.4.1 is marked as pending. Should we remove that reference from the rule or add the rule to the control file?

2023-07-12 12:10 UTC, jhrozek commented
Only that one question, otherwise looks good!

2023-07-12 15:35 UTC, rhmdnd commented
> Rule `rbac_debug_role_protects_pprof` references both 1.3.1 but also 1.4.1. We don't have a patch for section 1.4 and the rule 1.4.1 is marked as pending. Should we remove that reference from the rule or add the rule to the control file?

I think we can keep the reference there and correct the reference when we get a patch up for section 1.4.

2023-07-12 18:18 UTC, Vincent056 approved these changes
/lgtm

2023-07-12 19:20 UTC, jhrozek approved these changes

2023-07-12 19:22 UTC, merged