Implement rules for CIS OCP Section 4.2
ComplianceAsCode/content pull request #10781
Opened 2023-06-30 19:53 UTC by rhmdnd

Now that we have a profile and control files for CIS 1.4.0, we can start
wiring up the existing rules.

This commit ports all the existing rules we were using for the CIS
OpenShift profile into the CIS 1.4.0 version.

2023-07-04 07:28 UTC, jhrozek commented
/test e2e-aws-ocp4-cis
/test e2e-aws-ocp4-cis-node

2023-07-04 07:57 UTC, jhrozek requested changes
references should be fixed + remove the obsolete rule

2023-07-04 07:57 UTC, jhrozek commented on controls/cis_ocp_1_4_0/section-4.yml
> +        - kubelet_eviction_thresholds_set_hard_memory_available
These rules need to have their references fixed

2023-07-04 07:57 UTC, jhrozek commented on controls/cis_ocp_1_4_0/section-4.yml
> +        - kubelet_anonymous_auth
The following rule's reference seems to be off-by-one

2023-07-04 07:57 UTC, jhrozek commented on controls/cis_ocp_1_4_0/section-4.yml
> +        - kubelet_configure_tls_cert_pre_4_9
I think this rule can be just removed at this point

2023-07-11 21:52 UTC, rhmdnd commented
/test e2e-aws-ocp4-cis
/test e2e-aws-ocp4-cis-node

2023-07-12 12:32 UTC, jhrozek approved these changes
LGTM

2023-07-12 12:33 UTC, jhrozek commented
The patch looks good. I kicked the test runs if they keep failing, let's ping the cac developers for a waiver.

2023-07-12 19:26 UTC, rhmdnd commented
Rebased to pickup fixes for the build jobs.

2023-07-13 14:33 UTC, rhmdnd commented
Rebased and resolved merge conflicts.

2023-07-13 17:10 UTC, merged