Set accounts-physical as machine only
ComplianceAsCode/content pull request #10811
Opened 2023-07-07 01:44 UTC by candrews

#### Description:

Set accounts-physical as machine only

#### Rationale:

This group's intent is to "Protect Physical Console Access" - since there is no physical console to access in containers, the group is not applicable to containers, and should only apply to actual machines.

2023-07-07 09:53 UTC, marcusburghardt requested changes
There are some rules in this group which already have `platform: machine` defined. I would recommend you to remove the `platform: machine` from these rules since the platform will be ensured by the `group.yml`.

2023-07-07 13:59 UTC, candrews commented
> There are some rules in this group which already have `platform: machine` defined. I would recommend you to remove the `platform: machine` from these rules since the platform will be ensured by the `group.yml`.

Makes sense to me - I've updated this PR accordingly.

2023-07-11 08:07 UTC, marcusburghardt commented
/retest

2023-07-11 08:52 UTC, marcusburghardt commented
/packit test

2023-07-11 10:52 UTC, marcusburghardt approved these changes
Thanks

2023-07-11 10:52 UTC, merged