RHEL 8 STIG V1R11 - stablizaiton
ComplianceAsCode/content pull request #10903
Opened 2023-07-25 20:08 UTC by Mab879

#### Description:
This PR updates the RHEL 8 STIG to V1R11.

#### Rationale:

* Keep the STIG updated
* Downstream processes

2023-07-26 11:37 UTC, vojtapolasek commented
@Mab879  I think you accidentally put the SCAP file instead of XCCDF manual.

2023-07-26 12:00 UTC, marcusburghardt requested changes

2023-07-26 13:23 UTC, Mab879 commented on linux_os/guide/system/software/integrity/crypto/harden_sshd_macs_opensshserver_conf_crypto_policy/tests/rhel8_stig_incorrect_policy.fail.sh
> +=stig_extended
Fixed.

2023-07-27 07:42 UTC, marcusburghardt approved these changes
LGTM. Thanks

2023-07-28 08:36 UTC, vojtapolasek commented
I can confirm that fails of Automatus on Fedora are acceptable... this rule is not designed for Fedora and I tested it is working on RHEL 8.

2023-07-28 09:36 UTC, mildas commented
/packit retest-failed

2023-07-28 16:16 UTC, merged