Fix association of nfs-utils package with rpcbind service
ComplianceAsCode/content pull request #10907
Opened 2023-07-26 15:10 UTC by marcusburghardt

#### Description:

When investigating #10901 it was noticed that the `nfs-utils` package was associated with the `rpcbind` service when calling the `service_disabled` template in the `service_rpcbind_disabled rule`.

This association is not correct and has been fixed in this PR.

#### Rationale:

Bugfix

2023-07-26 17:09 UTC, Mab879 requested changes
Please take a look at the CI failure for components.

2023-07-27 07:19 UTC, marcusburghardt commented
> Please take a look at the CI failure for components.

Thanks. It is fixed now.

2023-07-27 15:32 UTC, Mab879 approved these changes
LGTM, thanks!

2023-07-28 09:36 UTC, mildas commented
/packit retest-failed

2023-07-28 10:15 UTC, mildas commented
/packit retest-failed

2023-07-28 19:10 UTC, merged