accounts_umask_etc_bashrc: depend on bash being installed
ComplianceAsCode/content pull request #10915
Opened 2023-07-27 19:34 UTC by candrews

#### Description:

accounts_umask_etc_bashrc: depend on bash being installed

#### Rationale:

/etc/bashrc is only used if bash is installed.

2023-07-27 21:35 UTC, Mab879 requested changes
Thanks for the PR! Please take look at the CI failures as they do appear to be valid (at least the GitHub Actions, save Fedora rawhide). Let me know any help.

2023-07-28 01:40 UTC, candrews commented
> Thanks for the PR! Please take look at the CI failures as they do appear to be valid (at least the GitHub Actions, save Fedora rawhide). Let me know any help.

I believe I have addressed that problem. Thank you for pointing it out!

2023-07-28 09:35 UTC, mildas commented
/packit retest-failed

2023-07-28 10:15 UTC, mildas commented
/packit retest-failed

2023-07-31 06:29 UTC, jan-cerny commented
/packit retest-failed

2023-07-31 08:48 UTC, jan-cerny commented
/packit retest-failed

2023-08-01 12:36 UTC, jan-cerny approved these changes

2023-08-01 12:37 UTC, merged