OCPBUGS-10508: Add quotes around SCC audit procedure
ComplianceAsCode/content pull request #10940
Opened 2023-08-01 18:15 UTC by rhmdnd

The json query we're using to help users detect SCCs they need to
monitor is rather complicated and should be quoted. Otherwise, it will
fail to run, which is frustrating for users if they're copy/pasting the
command out of the CRD (which is common).

2023-08-01 18:20 UTC, rhmdnd commented
cc: @xiaojiey

2023-08-02 01:52 UTC, xiaojiey commented on applications/openshift/scc/scc_limit_container_allowed_capabilities/rule.yml
> +    <pre>$ oc get scc -o json | jq "{{{ jqfilter }}}"</pre>
@rhmdnd Could you use single quotes instead? Thanks.
```
$ oc get scc -o json | jq "[.items[] | select(.metadata.name | test("^privileged$|^hostnetwork-v2$|^restricted-v2$|^nonroot-v2$"; "") | not) | select(.allowedCapabilities != null) | .metadata.name]"
jq: error: syntax error, unexpected INVALID_CHARACTER (Unix shell quoting issues?) at <top-level>, line 1:
[.items[] | select(.metadata.name | test(^privileged$                                         
jq: 1 compile error
bash: ^restricted-v2$: command not found...
bash: ^nonroot-v2; ) | not) | select(.allowedCapabilities != null) | .metadata.name]: command not found...
bash: ^hostnetwork-v2$: command not found...
[xiyuan@MiWiFi-RA69-srv 410]$ oc get scc -o json | jq '[.items[] | select(.metadata.name | test("^privileged$|^hostnetwork-v2$|^restricted-v2$|^nonroot-v2$"; "") | not) | select(.allowedCapabilities != null) | .metadata.name]'
[
  "nfs-provisioner"
]

```

2023-08-09 17:22 UTC, Vincent056 requested changes
I think it looks good except the single quote Xiaojie mentioned

2023-08-10 09:13 UTC, Vincent056 approved these changes
/lgtm

2023-08-10 13:14 UTC, yuumasato commented
`testing-farm:centos-stream-8-x86_64 ` failed on these rules:
```
:: [ 18:07:08 ] :: [   FAIL   ] :: Rules not passing after remediation:
xccdf_org.ssgproject.content_rule_configure_gnutls_tls_crypto_policy - fail
xccdf_org.ssgproject.content_rule_harden_sshd_ciphers_openssh_conf_crypto_policy - fail
xccdf_org.ssgproject.content_rule_harden_sshd_ciphers_opensshserver_conf_crypto_policy - fail
xccdf_org.ssgproject.content_rule_harden_sshd_macs_openssh_conf_crypto_policy - fail
xccdf_org.ssgproject.content_rule_harden_sshd_macs_opensshserver_conf_crypto_policy - fail 
```
Which is  unrelated to this PR.

I have rerun the test, but it may require a rebase to pass CI.

2023-08-10 16:01 UTC, yuumasato commented
> `testing-farm:centos-stream-8-x86_64 ` failed on these rules:

So this test is not required temporarily.
https://github.com/ComplianceAsCode/content/issues/10978

2023-08-11 06:14 UTC, BhargaviGudi commented
/hold for testing

2023-08-11 07:52 UTC, BhargaviGudi commented
Verification passed with 4.10.0-0.nightly-2023-08-03-212145 + compliance-operator.v1.2.0
```
1. Install CO
2.  Check for rule ocp4-scc-limit-container-allowed-capabilities instructions
$ oc get rule upstream-ocp4-scc-limit-container-allowed-capabilities -o=jsonpath={.instructions}
This rule checks the SCCs with allowedCapabilities set to non-null
and fails if there are more such SCCs than those allowed in the variable
named ocp4-var-sccs-with-allowed-capabilities-regex. To debug the rule,
check the variable value, e.g:
$ oc get variable ocp4-var-sccs-with-allowed-capabilities-regex  -ojsonpath='{.value}' 
Then use following command to list the SCCs that would fail the test:
$ oc get scc -o json | jq '[.items[] | select(.metadata.name | test("^privileged$|^hostnetwork-v2$|^restricted-v2$|^nonroot-v2$"; "") | not) | select(.allowedCapabilities != null) | .metadata.name]'
Please replace the regular expression in the test command with the value read from the variable
ocp4-var-sccs-with-allowed-capabilities-regex. You can read the variable
value with:
$ oc get variable ocp4-var-sccs-with-allowed-capabilities-regex -ojsonpath='{.value}' -n openshift-compliance
3. 
$ oc get variable ocp4-var-sccs-with-allowed-capabilities-regex  -ojsonpath='{.value}' 
^privileged$|^hostnetwork-v2$|^restricted-v2$|^nonroot-v2
$ oc get scc -o json | jq '[.items[] | select(.metadata.name | test("^privileged$|^hostnetwork-v2$|^restricted-v2$|^nonroot-v2$"; "") | not) | select(.allowedCapabilities != null) | .metadata.name]'
[]
```

2023-08-11 07:53 UTC, BhargaviGudi commented
/unhold

2023-08-11 07:53 UTC, BhargaviGudi commented
/qe-approved

2023-08-11 07:55 UTC, yuumasato commented
It seems that tests `testing-farm:centos-stream-9-x86_64` and `testing-farm:fedora-38-x86_64` are not reporting back, but they passed in a previous run.

2023-08-11 07:56 UTC, merged