Add manifests to zipfile target
ComplianceAsCode/content pull request #10944
Opened 2023-08-02 15:23 UTC by Mab879

#### Description:

Add the manifest JSON files to the release zip file.

#### Rationale:

So that this data can used later to compare across releases.

2023-08-03 07:41 UTC, marcusburghardt approved these changes

2023-08-03 08:28 UTC, jan-cerny requested changes
I have built the zip file and I have found that the manifests dir in the zip file is empty.

2023-08-03 13:22 UTC, Mab879 commented
> I have built the zip file and I have found that the manifests dir in the zip file is empty.

I'm unable to reproduce this. Here are the steps I did:

```
$ ./build_product -j10 rhel9 rhel8 rhel7 debian10 debian11
<snip>
$  ninja zipfile  
<snip>
scap-security-guide-0.1.70/tables/tables-rhel8-all.html
scap-security-guide-0.1.70/tables/tables-rhel9-all.html
scap-security-guide-0.1.70/manifests
scap-security-guide-0.1.70/manifests/manifest-debian10.json
scap-security-guide-0.1.70/manifests/manifest-debian11.json
scap-security-guide-0.1.70/manifests/manifest-rhel7.json
scap-security-guide-0.1.70/manifests/manifest-rhel8.json
scap-security-guide-0.1.70/manifests/manifest-rhel9.json
$ pwd 
/home/mburket/code/ComplianceAsCode/content/build
$ ls zipfile/scap-security-guide-0.1.70/manifests 
manifest-debian10.json  manifest-rhel7.json  manifest-rhel9.json
manifest-debian11.json  manifest-rhel8.json
```

2023-08-04 07:42 UTC, jan-cerny commented
@Mab879  I did it the standard way: cd build; rm -rf *; cmake .. && make zipfile; It could be a target dependency issue.

2023-08-07 09:46 UTC, jan-cerny approved these changes
I have checked that the generated zip file contain JSON manifests for all built products.

2023-08-07 09:46 UTC, merged