Copy files before remediating if they are symlinks
ComplianceAsCode/content pull request #11002
Opened 2023-08-17 12:53 UTC by ggbecker

#### Description:
- Copy files before remediating if they are symlinks
  - Crypto policies sometimes use symlinks and when we edit them, they might get reverted if they are not copied first because they belong to crypto-policies package and the source is not considered configuration files.

#### Rationale:

- This workaround does not discard the fact that the optimal solution is to create a subpolicy in crypto-policies, for example `FIPS:STIG` to accommodate exactly the ciphers required by STIG.
- Fixes #10978

#### Review Hints:

- Test `testing-farm:centos-stream-8-x86_64` should pass.

2023-08-21 09:27 UTC, marcusburghardt requested changes
I am not sure if the PR fixes the mentioned issue but it is a good improvement. I have some minor comments about the tasks names. Also, the same errors reported in `Automatus CS8` are happening in local VMs. Could you take a look, please?

2023-08-21 09:50 UTC, marcusburghardt commented
These rules include `rhel9` in `prodtype` but their test scenario scripts are restricted to RHEL8. It should also be reviewed and updated. Currently, they are reporting `not applicable` when tested in RHEL9. Could you also review and update the test scenario scripts, please?

2023-08-21 09:50 UTC, marcusburghardt commented
These rules include `rhel9` in `prodtype` but their test scenario scripts are restricted to RHEL8. It should also be reviewed and updated. Currently, they are reporting `not applicable` when tested in RHEL9. Could you also review and update the test scenario scripts, please?

2023-08-23 12:05 UTC, ggbecker commented
/packit retest-failed

2023-09-14 10:26 UTC, marcusburghardt commented
The CI tests errors seem legit.

2023-11-08 09:31 UTC, marcusburghardt commented
@ggbecker what are your plans to move forward with this PR? I believe it is almost ready.

2023-12-05 14:20 UTC, marcusburghardt commented
@ggbecker , can we try to finish this PR? I believe it is almost ready.

2024-01-29 10:36 UTC, marcusburghardt commented
> @ggbecker , can we try to finish this PR? I believe it is almost ready.

@ggbecker , can you provide an update on this PR, please?

2024-02-05 15:10 UTC, ggbecker commented
> > @ggbecker , can we try to finish this PR? I believe it is almost ready.
> 
> @ggbecker , can you provide an update on this PR, please?

I don't have any plans for this PR at the moment. Feel free to follow up and propose any changes needed to make this mergeable.

2024-02-12 11:19 UTC, marcusburghardt commented
> > > @ggbecker , can we try to finish this PR? I believe it is almost ready.
> > 
> > 
> > @ggbecker , can you provide an update on this PR, please?
> 
> I don't have any plans for this PR at the moment. Feel free to follow up and propose any changes needed to make this mergeable.

I already proposed the changes in my previous comments.
Could you close this PR if you are no longer interested on finishing it, please?

2024-02-14 12:25 UTC, closed without merging