Modify adie db exist path for UBTU-20-010450
ComplianceAsCode/content pull request #11064
Opened 2023-09-07 20:45 UTC by dexterle

This commit will add in a stat check path for ubuntu. Upon running aideinit, the new db file is named as "aide.db.new" similarly to SLE remediation methods.

#### Description:

- _Description here. Replace this text. Don't use the italics format!_

#### Rationale:

- _Rationale here. Replace this text. Don't use the italics format!_

- Fixes # _Issue number here (e.g. #26) or remove this line if no issue exists._

#### Review Hints:

- _Review hints here. Replace this text. Don't use the italics format!_

- _Use this optional section to give any relevant information which could help the reviewer to more quickly and assertively understand and test the changes._

- _Good examples are useful commands, if it is better to review all commits together or in a suggested sequence, any relevant discussion in other PRs or issues, etc._

2023-09-11 14:58 UTC, dexterle commented
This should be consolidated with https://github.com/ComplianceAsCode/content/pull/11058

2023-09-11 21:59 UTC, dodys requested changes
you should create a separate ubuntu ansible remediation, following the bash implementation.
Our OVAL check is different from other and so our remediation.

2023-09-15 13:51 UTC, dexterle commented
> you should create a separate ubuntu ansible remediation, following the bash implementation. Our OVAL check is different from other and so our remediation.

Taking a look at this now...

2023-09-15 15:32 UTC, dexterle commented
Should `linux_os/guide/system/software/integrity/software-integrity/aide/aide_build_database/ansible/shared.yml` be reverted removing ubuntu specific tasks?

I've added in ansible remediation for Ubuntu that follows bash remediation.

2023-09-15 15:45 UTC, dodys commented
> Should `linux_os/guide/system/software/integrity/software-integrity/aide/aide_build_database/ansible/shared.yml` be reverted removing ubuntu specific tasks?
> 
> I've added in ansible remediation for Ubuntu that follows bash remediation.

yes, please

2023-09-15 16:46 UTC, dexterle commented
Reverted ubuntu specific on shared ansible remediation. I also shortened some of the logic and use proper styling.

2023-09-19 13:51 UTC, marcusburghardt commented
I believe it can already be merged, correct?

2023-09-21 14:15 UTC, merged