Fix path for aide to /etc/aide/aide.conf for UBTU-20-010205
ComplianceAsCode/content pull request #11066
Opened 2023-09-07 20:52 UTC by dexterle

This commit will fix the path from /etc/aide.conf to /etc/aide/aide.conf by adding in jinja conditional

#### Description:

- _Description here. Replace this text. Don't use the italics format!_

#### Rationale:

- _Rationale here. Replace this text. Don't use the italics format!_

- Fixes # _Issue number here (e.g. #26) or remove this line if no issue exists._

#### Review Hints:

- _Review hints here. Replace this text. Don't use the italics format!_

- _Use this optional section to give any relevant information which could help the reviewer to more quickly and assertively understand and test the changes._

- _Good examples are useful commands, if it is better to review all commits together or in a suggested sequence, any relevant discussion in other PRs or issues, etc._

2023-09-08 06:52 UTC, marcusburghardt approved these changes

2023-09-12 20:51 UTC, dodys requested changes

2023-09-12 20:51 UTC, dodys commented on linux_os/guide/system/software/integrity/software-integrity/aide/aide_check_audit_tools/ansible/shared.yml
> +    path: {{{ aide_conf_path }}}
missing multi_platform_ubuntu

2023-09-13 18:05 UTC, dexterle commented on linux_os/guide/system/software/integrity/software-integrity/aide/aide_check_audit_tools/ansible/shared.yml
> +    path: {{{ aide_conf_path }}}
thanks for the catch

2023-10-18 08:45 UTC, dodys approved these changes
lgtm, thanks!

2023-10-18 08:45 UTC, merged