Fix rule ubtu 20 010072
ComplianceAsCode/content pull request #11074
Opened 2023-09-07 21:08 UTC by dexterle

#### Description:

- _Description here. Replace this text. Don't use the italics format!_

#### Rationale:

- _Rationale here. Replace this text. Don't use the italics format!_

- Fixes # _Issue number here (e.g. #26) or remove this line if no issue exists._

#### Review Hints:

- _Review hints here. Replace this text. Don't use the italics format!_

- _Use this optional section to give any relevant information which could help the reviewer to more quickly and assertively understand and test the changes._

- _Good examples are useful commands, if it is better to review all commits together or in a suggested sequence, any relevant discussion in other PRs or issues, etc._

2023-09-07 21:09 UTC, dexterle commented
feedback:
https://github.com/ComplianceAsCode/content/pull/10738/commits/ee58feb5cc914c4dafac37e0785f331d4577cf72#r1319035461
https://github.com/ComplianceAsCode/content/pull/10738/commits/af5bbd3964d170363ce3c04e75fd593d3a6be20d#r1319027544

2023-09-11 20:34 UTC, dodys commented
/packit retest-failed

2023-09-11 20:35 UTC, dodys commented
/retest-failed

2023-09-11 20:37 UTC, dodys commented
/test

2023-09-11 20:40 UTC, dodys commented
/retest

2023-09-13 18:15 UTC, dodys requested changes
do not break the oval check into multiple checks, that is the only way to test the order of configuration, because it matters.
Also DISA's configuration is missing the preauth IMO

2023-12-07 17:48 UTC, dodys commented
closing this in favor of #11355

2023-12-07 17:48 UTC, closed without merging