Fix rule ubtu 20 010066
ComplianceAsCode/content pull request #11078
Opened 2023-09-08 13:42 UTC by dexterle

#### Description:

- _Description here. Replace this text. Don't use the italics format!_

#### Rationale:

- _Rationale here. Replace this text. Don't use the italics format!_

- Fixes # _Issue number here (e.g. #26) or remove this line if no issue exists._

#### Review Hints:

- _Review hints here. Replace this text. Don't use the italics format!_

- _Use this optional section to give any relevant information which could help the reviewer to more quickly and assertively understand and test the changes._

- _Good examples are useful commands, if it is better to review all commits together or in a suggested sequence, any relevant discussion in other PRs or issues, etc._

2023-09-13 18:05 UTC, dodys requested changes

2023-09-13 18:05 UTC, dodys commented on linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_configure_crl/oval/shared.xml
> +    <ind:subexpression operation="pattern match">(^|,\s*)(crl_auto|crl_offline)(\s*,|$|;)</ind:subexpression>
I think the way you did should be fine

2024-08-02 05:50 UTC, jan-cerny commented
ping

2024-08-02 06:15 UTC, dodys commented
dexterle reached out last week about continuing work on this PRs, and I've asked to open new ones for a clean state. Therefore closing this one.

2024-08-02 06:15 UTC, closed without merging