Fix UBTU-20-010179 to use proper parameters and key
ComplianceAsCode/content pull request #11080
Opened 2023-09-08 13:47 UTC by dexterle

This commit will fix the init_module and finit_module for UBTU-20-010179 which will apply proper parameters and keys.

#### Description:

- _Description here. Replace this text. Don't use the italics format!_

#### Rationale:

- _Rationale here. Replace this text. Don't use the italics format!_

- Fixes # _Issue number here (e.g. #26) or remove this line if no issue exists._

#### Review Hints:

- _Review hints here. Replace this text. Don't use the italics format!_

- _Use this optional section to give any relevant information which could help the reviewer to more quickly and assertively understand and test the changes._

- _Good examples are useful commands, if it is better to review all commits together or in a suggested sequence, any relevant discussion in other PRs or issues, etc._

2023-09-11 20:17 UTC, dexterle commented on linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_finit/ansible/shared.yml
>  # disruption = low
Given https://github.com/ComplianceAsCode/content/commit/e7d99c03246ebc5eacba43156987e3548a6ea73e

Ensure that `multi_platform_ubuntu` is added

2023-09-11 20:17 UTC, dexterle commented on linux_os/guide/system/auditing/auditd_configure_rules/audit_kernel_module_loading/audit_rules_kernel_module_loading_init/ansible/shared.yml
>  # disruption = low
Given https://github.com/ComplianceAsCode/content/commit/e7d99c03246ebc5eacba43156987e3548a6ea73e

Ensure that `multi_platform_ubuntu` is added

2023-09-11 20:48 UTC, dodys requested changes
check your own comments, there are still things to add

2023-09-12 20:59 UTC, dexterle commented
added multi_platform_ubuntu given the original PR feedback

2023-09-13 15:12 UTC, dodys approved these changes
lgtm, thanks!

2023-09-13 15:12 UTC, merged