Add ansible remediation for log perm for UBTU-20-010122
ComplianceAsCode/content pull request #11091
Opened 2023-09-08 15:42 UTC by dexterle

This commit will add log perm ansible remediation for ensuring all audit logs are 600 or less permissible.

#### Description:

- _Description here. Replace this text. Don't use the italics format!_

#### Rationale:

- _Rationale here. Replace this text. Don't use the italics format!_

- Fixes # _Issue number here (e.g. #26) or remove this line if no issue exists._

#### Review Hints:

- _Review hints here. Replace this text. Don't use the italics format!_

- _Use this optional section to give any relevant information which could help the reviewer to more quickly and assertively understand and test the changes._

- _Good examples are useful commands, if it is better to review all commits together or in a suggested sequence, any relevant discussion in other PRs or issues, etc._

2023-09-08 15:42 UTC, dexterle commented
feedback: https://github.com/ComplianceAsCode/content/pull/10738/commits/114455d829f5db3fd0cd1113cdad6b23f294a49a#r1319043421

2023-09-11 16:54 UTC, dexterle commented
> feedback: [114455d#r1319043421](https://github.com/ComplianceAsCode/content/commit/114455d829f5db3fd0cd1113cdad6b23f294a49a#r1319043421)

I believe that this PR can be enhanced if it removes the second `command` task with similar changes here: https://github.com/ComplianceAsCode/content/pull/11092

2023-09-12 09:09 UTC, dodys requested changes

2023-09-12 09:09 UTC, dodys commented on linux_os/guide/system/auditing/auditd_configure_rules/file_permissions_var_log_audit/ansible/shared.yml
> +{{% if 'ol' not in product and "rhel" not in product and "ubuntu" not in product %}}
this deviates from the bash remediation, please check it

2024-08-02 05:51 UTC, jan-cerny commented
ping

2024-08-02 06:14 UTC, dodys commented
dexterle reached out last week about continuing work on this PRs, and I've asked to open new ones for a clean state. Therefore closing this one.

2024-08-02 06:14 UTC, closed without merging