Add ansible for gnome messsage banner UBTU-20-010003
ComplianceAsCode/content pull request #11090
Opened 2023-09-08 15:40 UTC by dexterle

This commit will add in the ansible remediation for the gnome message banner text for ubuntu.

#### Description:

- _Description here. Replace this text. Don't use the italics format!_

#### Rationale:

- _Rationale here. Replace this text. Don't use the italics format!_

- Fixes # _Issue number here (e.g. #26) or remove this line if no issue exists._

#### Review Hints:

- _Review hints here. Replace this text. Don't use the italics format!_

- _Use this optional section to give any relevant information which could help the reviewer to more quickly and assertively understand and test the changes._

- _Good examples are useful commands, if it is better to review all commits together or in a suggested sequence, any relevant discussion in other PRs or issues, etc._

2023-09-12 10:26 UTC, dodys requested changes
please check bash remediation and add the bit of editing dconf database

2023-09-12 13:51 UTC, dexterle commented on linux_os/guide/system/accounts/accounts-banners/gui_login_banner/dconf_gnome_login_banner_text/ansible/ubuntu.yml
> +- name: "{{{ rule_title }}}"
Use a more descriptive name, follow the style guide

2024-08-02 05:51 UTC, jan-cerny commented
ping

2024-08-02 06:14 UTC, dodys commented
dexterle reached out last week about continuing work on this PRs, and I've asked to open new ones for a clean state. Therefore closing this one.

2024-08-02 06:14 UTC, closed without merging