Add ansible remediation for audispd plugin UBTU-20-010216
ComplianceAsCode/content pull request #11093
Opened 2023-09-08 15:45 UTC by dexterle

This commit will add in ansible remediation for audispd plugin which also ensures that the plugin is enabled within au-remote.conf.

#### Description:

- _Description here. Replace this text. Don't use the italics format!_

#### Rationale:

- _Rationale here. Replace this text. Don't use the italics format!_

- Fixes # _Issue number here (e.g. #26) or remove this line if no issue exists._

#### Review Hints:

- _Review hints here. Replace this text. Don't use the italics format!_

- _Use this optional section to give any relevant information which could help the reviewer to more quickly and assertively understand and test the changes._

- _Good examples are useful commands, if it is better to review all commits together or in a suggested sequence, any relevant discussion in other PRs or issues, etc._

2023-09-12 06:40 UTC, marcusburghardt commented on linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_configure_remote_server/ansible/ubuntu.yml
> +# platform = multi_platform_ubuntu
Please, consider the adoption of the existing `shared.yml` instead.

2023-09-12 06:40 UTC, marcusburghardt commented on linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_configure_remote_server/ansible/ubuntu.yml
> +# platform = multi_platform_ubuntu
Please, consider the adoption of the existing `shared.yml` instead.

2023-09-12 08:54 UTC, dodys requested changes
since the bash remediation is shared, so should the ansible.

2023-10-03 08:53 UTC, dodys requested changes
now you should add the ubuntu specific bits, see bash

2023-11-02 13:50 UTC, jan-cerny commented
@dexterle @dodys Do you plan to continue working on this PR?

2023-11-02 17:39 UTC, dodys commented
> @dexterle @dodys Do you plan to continue working on this PR?

I sent a message to dexterle on gitter last week to get some feedback, if we don't hear anything until November 13th, then we will start adding the missing bits on top of the open PRs.

2023-12-01 17:32 UTC, dodys commented
> @dodys I was able to get in touch with a colleague who more recently spoke with @dexterle and they mentioned that they are focusing on other personal matters so if you all wouldn't mind helping taking the handful of open pull requests to the finish line I'd really appreciate it. Unfortunately these days I don't have any time to help personally but will continue to direct folks to help out.
> 
> It's also worth noting that I have been doing my best to get vendors to contribute directly and have seen some success with SUSE so I'm focused on Canonical this next year.

thanks for the heads up, I spoke with Dexter a month ago and we will be continuing his work.
@mpurg is currently on it and already provided one PR #11325

2023-12-08 22:04 UTC, aghassemlouei commented
> c

Appreciate your efforts @dodys and @mpurg; as we start ramping back up post-holidays we'll have more engineers contributing and supporting the project.

2024-04-18 09:07 UTC, marcusburghardt commented
Could you resolve the conflict, please?

2024-08-02 05:51 UTC, jan-cerny commented
ping

2024-08-02 06:13 UTC, dodys commented
dexterle reached out last week about continuing work on this PRs, and I've asked to open new ones for a clean state. Therefore closing this one.

2024-08-02 06:13 UTC, closed without merging