Enable ansible and bash remediation for sssd for UBTU-20-010441
ComplianceAsCode/content pull request #11097
Opened 2023-09-08 16:33 UTC by dexterle

This commit will enable the applicable ansible and bash remediation methods for ensuring that sssd is properly configured.

#### Description:

- _Description here. Replace this text. Don't use the italics format!_

#### Rationale:

- _Rationale here. Replace this text. Don't use the italics format!_

- Fixes # _Issue number here (e.g. #26) or remove this line if no issue exists._

#### Review Hints:

- _Review hints here. Replace this text. Don't use the italics format!_

- _Use this optional section to give any relevant information which could help the reviewer to more quickly and assertively understand and test the changes._

- _Good examples are useful commands, if it is better to review all commits together or in a suggested sequence, any relevant discussion in other PRs or issues, etc._

2023-09-12 06:29 UTC, marcusburghardt requested changes

2023-09-12 06:29 UTC, marcusburghardt commented on linux_os/guide/services/sssd/sssd_offline_cred_expiration/ansible/shared.yml
> +# platform = Red Hat Virtualization 4,multi_platform_fedora,multi_platform_ol,multi_platform_rhel,multi_platform_sle,multi_platform_ubuntu
```suggestion
# platform = multi_platform_all
```

2023-09-12 06:29 UTC, marcusburghardt commented on linux_os/guide/services/sssd/sssd_offline_cred_expiration/bash/shared.sh
> +# platform = Red Hat Virtualization 4,multi_platform_fedora,multi_platform_ol,multi_platform_rhel,multi_platform_sle,multi_platform_ubuntu
```suggestion
# platform = multi_platform_all
```

2023-09-15 16:50 UTC, dexterle commented on linux_os/guide/services/sssd/sssd_offline_cred_expiration/bash/shared.sh
> +# platform = Red Hat Virtualization 4,multi_platform_fedora,multi_platform_ol,multi_platform_rhel,multi_platform_sle,multi_platform_ubuntu
thanks!

2023-09-15 16:50 UTC, dexterle commented on linux_os/guide/services/sssd/sssd_offline_cred_expiration/ansible/shared.yml
> +# platform = Red Hat Virtualization 4,multi_platform_fedora,multi_platform_ol,multi_platform_rhel,multi_platform_sle,multi_platform_ubuntu
thanks!

2023-09-18 08:28 UTC, marcusburghardt approved these changes

2023-09-18 10:15 UTC, dodys approved these changes
lgtm, thanks!

2023-09-18 10:22 UTC, merged