Add rhel9 stig
ComplianceAsCode/content pull request #11193
Opened 2023-10-11 14:23 UTC by Mab879

#### Description:

* Add RHEL 9 STIG IDs
* Make the RHEL 9 STIG not a draft

#### Rationale:
Make the RHEL 9 STIG not a draft.

2023-10-24 11:40 UTC, ggbecker commented on controls/stig_rhel9.yml
> +        status: automated
Sounds like the service_rngd_enabled must be completely purged out from the RHEL9 STIG: https://github.com/ComplianceAsCode/content/pull/10153

If that is really true, then we have to request this back to DISA.

2023-10-24 13:33 UTC, ggbecker commented
@vojtapolasek this is the comment about comparison of profiles I mentioned: https://github.com/ComplianceAsCode/content/issues/8580#issuecomment-1104050717

The strategy here is basically to build the profile using the main branch, then save the built profile that you can find in `build/rhel9/profiles/stig.profile`, then switch to the contents of this pull request, build again and compare the built profile with the older one.

There should be no differences between the two profiles, unless there is something required to be removed/added.

Commands will look like this:

`./build_product rhel9 --debug --datastream-only`

`python build-scripts/profile_tool.py sub --profile2 build/rhel9/profiles/stig.profile --profile1 old_stig.profile --ssg-root . --product rhel9 --build-config-yaml build/build_config.yml`

2023-10-25 08:59 UTC, jan-cerny commented on utils/refchecker.py
> +                        help="A comma separated list  of rules to be ignored")
```suggestion
                        help="A comma separated list of rules to be ignored")
```

2023-10-25 08:59 UTC, jan-cerny commented on tests/CMakeLists.txt
> +    # This can moved back the macro once enable_authselect has a stigid
Don't increase technical debt. I think it would be better to add a parameter to the macro instead of copying the macro code.

2023-10-25 08:59 UTC, jan-cerny commented on controls/stig_rhel9.yml
> +        title: RHEL 9 must require a boot loader superuser password.
Empty line 104 causes a visually confusing formatting.

2023-10-27 08:22 UTC, vojtapolasek requested changes
Hello @Mab879  and thank you for this important contribution.
I have reviewed the profile. Actually, Instead of the tool @ggbecker  suggested, I built old and new profile, sorted both files, and performed a diff. The result is very similar, but sometimes it provides better context.
See my suggestions.
I have one general question - I see that we do not build STIG HTML tables for RHEL 9. Is this intentional?

2023-10-27 12:56 UTC, Mab879 commented on controls/stig_rhel9.yml
> +            - sysctl_net_ipv4_conf_all_forwarding
I think we should keep `sysctl_net_ipv4_conf_all_forwarding`.

See https://stigaview.com/products/rhel9/v1r1/RHEL-09-253075/

2023-10-30 13:38 UTC, vojtapolasek commented on controls/stig_rhel9.yml
> +            - sysctl_net_ipv4_conf_all_forwarding
I agree.

2023-10-30 13:39 UTC, vojtapolasek commented
Hello @Mab879  and thank you for changes. I see you modified the control file, but you did not modify references in rule.yml. Here is output of ctest:
```
Rule aide_scan_notification lacks required reference stigid or stigid@rhel9
Rule dconf_gnome_disable_autorun lacks required reference stigid or stigid@rhel9
Rule sysctl_kernel_unprivileged_bpf_disabled lacks required reference stigid or stigid@rhel9
Rule audit_rules_privileged_commands_mount lacks required reference stigid or stigid@rhel9
```
Please fix these references. Also please ensure that you remove STIG RHEL 9 references from rules which we decided to remove from the profile.

2023-10-31 09:52 UTC, vojtapolasek approved these changes

2023-10-31 09:54 UTC, vojtapolasek commented
Thank you @Mab879  for adding the new STIG profile. I am merging the PR.
I don't see SLE 15 automatus failure as relevant for this PR because the PR touches rules only with regards to their references, it does not touch functionality.
The Codeclimate warning is valid, but I think it should be solved as part of a different PR.

2023-10-31 09:54 UTC, merged