Daily prod issue fix: invalid HTML URLs
ComplianceAsCode/content pull request #11222
Opened 2023-10-25 12:17 UTC by vojtapolasek

#### Description:

It was found during daily upstream productization that some HTML links are no longer pointing to valid resources. This is being fixed.

#### Rationale:

- keeping the content helpful means that links work

#### Review Hints:

see commits and try to access old and new URLs

2023-10-25 12:26 UTC, jan-cerny requested changes
@vojtapolasek I confirm all 3 new links work fine. But, I have found that are multiple other occurrences of `https://www.iso.org/standard/54534.html` in our project. I think that they need to be changed as well.

2023-10-25 12:44 UTC, vojtapolasek commented
@jan-cerny  you are right, I overlooked these. Now they should be fixed.

2023-10-25 14:20 UTC, jan-cerny approved these changes

2023-10-26 08:54 UTC, ggbecker commented
@ComplianceAsCode/ubuntu-maintainers @ComplianceAsCode/suse-maintainers @ComplianceAsCode/oracle-maintainers 

I am overriding the need of your approvals since this is not really affecting products other than having wrong URLs in the project.

2023-10-26 08:54 UTC, merged