Add utilities for OSCAL Component Definitions from policies
ComplianceAsCode/content pull request #11292
Opened 2023-11-20 21:21 UTC by jpower432

#### Description:

This PR adds utilities under the `utils` directory to create OSCAL component definitions using the files under the `controls` directory to populate the implemented requirements and mapping to the rules.

##### What was added?

- Core logic under `utils/oscal`
- Unit tests under `test/unit/utils/oscal`
- Documentation for the utilities

#### Rationale:

The policy was used to initially fill in the control responses because it contains all the required information for a component definition (status, description, rule mapping). However, the class `ComponentDefinitionGenerator` takes a `ControlSelector` class in order to allow how control response information is selected and constructed separate from the generation logic.

- Fixes #11106 

#### Review Hints:

This is PR is part two to #11286.

##### Important Notes

- To support installing `compliance-trestle` during CI job execution for testing, changes were made to the workflow files in the following commits:
https://github.com/ComplianceAsCode/content/commit/85d0f5b7b2fce7ce4ce9235b6dafa5ada0e8ac28
https://github.com/ComplianceAsCode/content/commit/9c11097070b6763f6023de14738579aea364161b
https://github.com/ComplianceAsCode/content/commit/9d4ea0e33b8b5c0bb88c66adf1fe46de33352e3b

- It performs a mapping from SSG status to OSCAL implementation status in the `OscalStatus` class
- The script uses the "Section *letter*:" convention in the control notes to create statements under the implemented requirements.
- The script maps parameter to rules uses the `xccdf_variable` field under `template.vars`
- To determine what responses will mapped to the controls in the OSCAL profile the control id and label property from the resolved catalog is searched.

##### How to test

An example of how to execute the script:

```bash
$ ./build_product ocp4
$ ./utils/rule_dir_json.py
$ ./utils/oscal/build_cd_from_policy.py -o build/ocp4.json -p fedramp_rev4_high -pr ocp4 -c nist_ocp4:high
``

2023-12-11 22:45 UTC, Mab879 commented
/packit build

2023-12-12 18:21 UTC, Mab879 commented
/packit build

2024-01-05 19:27 UTC, Mab879 requested changes
Thanks for the PR. I do have a few comments.

2024-01-09 22:57 UTC, Mab879 requested changes

2024-01-09 22:57 UTC, Mab879 commented on utils/oscal/__init__.py
I think code might better moved to `__main__.py` in this folder. So it can be called with `python -m utils.oscal`. If don't plan making that file executable then please remove the shebang.

2024-01-09 22:57 UTC, Mab879 commented on utils/oscal/control_selector.py
> +#!/usr/bin/env python3
This file has no main method, please remove the shebang.

2024-01-09 22:57 UTC, Mab879 commented on utils/oscal/params_extractor.py
> +#!/usr/bin/env python3
This file has no main method, please remove the shebang.

2024-01-09 22:57 UTC, Mab879 commented on utils/oscal/rules_transformer.py
> +#!/usr/bin/env python3
This file has no main method, please remove the shebang.

2024-01-09 22:57 UTC, Mab879 commented on utils/oscal/cd_generator.py
> +#!/usr/bin/env python3
This file has no main method, please remove the shebang.

2024-01-10 17:02 UTC, jpower432 commented on utils/oscal/__init__.py
Appreciate the feedback @Mab879. Interested in discussing what the logic should be when running `utils.oscal`. I expected that there would additional directly executed scripts under `utils.oscal` from different sources other than control file. Can you expand on what you think should be moved to `__main__.py`?

2024-01-10 18:40 UTC, Mab879 commented on utils/oscal/__init__.py
I though I saw a main method in this file, I was wrong. I think just removing the shebang will work here.

2024-01-15 15:59 UTC, Mab879 commented
Waving Automatus tests as the test rules don't need tests.

2024-01-15 16:41 UTC, Mab879 commented
/packit retest-failed

2024-01-15 17:28 UTC, Mab879 approved these changes

2024-01-15 17:29 UTC, merged