OCP4: Update k8s action to build image on new PR
ComplianceAsCode/content pull request #11384
Opened 2023-12-13 23:23 UTC by Vincent056

This triggers the K8S image action to run on every new PR created

2023-12-14 15:18 UTC, Mab879 commented
/packit retest-failed

2023-12-14 16:15 UTC, Vincent056 commented
I think this worked: ghcr.io/complianceascode/k8scontent:11384

2023-12-20 16:58 UTC, yuumasato approved these changes
LGTM.

I was able to deploy the content by doing: `CONTENT_IMAGE=ghcr.io/complianceascode/k8scontent:11384 make deploy-local`

And how about, for visibility purposes, posting a comment to the PR?
For example, the final tasks of this workflow post a comment to the PR:
https://github.com/ComplianceAsCode/content/blob/41ad1904aa2cdb1b3359f13563bdf5e9b3cb33db/.github/workflows/compare-ds.yaml#L90

2024-01-16 17:12 UTC, yuumasato requested changes
@Vincent056 One more  round and should be excelent

2024-01-16 17:12 UTC, yuumasato commented on .github/workflows/k8s-content-pr.yaml
> +            :robot: The image for this PR is available at ghcr.io/complianceascode/k8scontent:${{ needs.get-pr-number.outputs.pr-number }}
@Vincent056 The test for  EOF failed. Please ensure  there is newline at the end of the file.

2024-01-16 17:12 UTC, yuumasato commented on .github/workflows/k8s-content-pr.yaml
> +            :robot: The image for this PR is available at ghcr.io/complianceascode/k8scontent:${{ needs.get-pr-number.outputs.pr-number }}
I suggest the comment is updated or inserted, and a formatting that makes it easy to copy the URL.
```suggestion
          message: |
            :robot: The image for this PR is available at:
            `ghcr.io/complianceascode/k8scontent:${{ needs.get-pr-number.outputs.pr-number }}`
          comment_tag: kubernetes_content_image
```

2024-01-16 20:49 UTC, Vincent056 commented on .github/workflows/k8s-content-pr.yaml
> +          comment_tag: kubernetes_content_image
```suggestion
          comment_tag: kubernetes_content_image

```
Adding a new line to EOF

2024-01-18 16:04 UTC, yuumasato approved these changes
Looking great!

2024-01-19 06:06 UTC, xiaojiey commented
/hold for test

2024-01-19 15:07 UTC, xiaojiey commented
/lgtm
tried before commands to deploy pb with the custom content image
"export CONTENT_IMAGE=ghcr.io/complianceascode/k8scontent:11384
# make images && make push && make catalog && make catalog-deploy
make images && make push && make deploy"
$ oc get pb
NAME     CONTENTIMAGE                                CONTENTFILE         STATUS
ocp4     ghcr.io/complianceascode/k8scontent:11384   ssg-ocp4-ds.xml     VALID
rhcos4   ghcr.io/complianceascode/k8scontent:11384   ssg-rhcos4-ds.xml   VALID

2024-01-19 15:07 UTC, xiaojiey commented
/unhold

2024-01-19 15:10 UTC, yuumasato commented
Test `Gate / Build, Test on Debian 10 (Container) (push) ` has been failing consistently, although I see it passing in other PRs.
This patch doesn't affect Debian builds in any way, so I'm merging.
Thank you @Vincent056

2024-01-19 15:11 UTC, merged