Validate levels in controls
ComplianceAsCode/content pull request #11427
Opened 2024-01-08 16:06 UTC by vojtapolasek

#### Description:

- add a function which will check if a control does not include invalid level
- valid levels are defined in the policy, any other levels are invalid

#### Rationale:

Inspired while verifying #11417 

#### Review Hints:

- choose a policy which has defined levels, change a control to contain undefined level and build any product
- choose a policy which does not use level and define a level for a particular control, build any product

2024-01-08 16:46 UTC, Mab879 requested changes
LGTM, but please rewrite to that it works on Python 2.7 on CentOS 7.

2024-01-08 16:46 UTC, Mab879 commented on ssg/controls.py
> +                if levels != ["default"]:
We cannot use f-strings since this code this needs to run on Python 2.7.

2024-01-08 16:46 UTC, Mab879 commented on ssg/controls.py
> +                    msg = (f"Invalid levels {levels} used in control {c.id} "
We cannot use f-strings since this code this needs to run on Python 2.7.

2024-01-08 16:46 UTC, Mab879 commented on ssg/controls.py
> +                    msg = (f"Invalid level {lvl} used in control {c.id} "
We cannot use f-strings since this code this needs to run on Python 2.7.

2024-01-09 13:59 UTC, vojtapolasek commented
/packit retest

2024-01-09 16:19 UTC, Mab879 commented
/packit retest-failed

2024-01-09 19:54 UTC, Mab879 commented
/packit rebuild-failed

2024-01-09 21:17 UTC, Mab879 commented
/packit rebuild-failed

2024-01-10 10:48 UTC, vojtapolasek commented
/packit retest-failed

2024-01-10 12:53 UTC, vojtapolasek commented
@Mab879  I think I fixed everything I could. I consider extracting code from controls.py to satisfy the requirement on number of lines as out of scope.

2024-01-10 14:25 UTC, Mab879 commented
> @Mab879 I think I fixed everything I could. I consider extracting code from controls.py to satisfy the requirement on number of lines as out of scope.

Agreed. Thanks for the work. Reviewing.

2024-01-10 14:34 UTC, Mab879 approved these changes
LGTM.

Thanks for your work.

2024-01-10 14:34 UTC, merged