Review CIS RHEL8 v3.0.0 Section 4 and Section 5
ComplianceAsCode/content pull request #11454
Opened 2024-01-18 07:40 UTC by marcusburghardt

#### Description:

Review the cis_rhel8.yml control file and update the following sections  in alignment to CIS RHEL 8 v3.0.0:
- Section 4 - Access, Authentication and Authorization
- Section 5 - Logging and Auditing

Also update references in related rules.

#### Rationale:

Keep RHEL 8 profiles updated with CIS RHEL 8 last version.

#### Review Hints:

NOTE: Section 4 can already be reviewed but many issues should be reported by CI tests because many requirements were swapped between section 4 and 5. This is the reason this PR will include the review of both sections. Commits related to section 5 will come soon.

The easiest way is to open the CIS RHEL8 v3.0.0 policy and compare the changes in commits with the respective requirements.

2024-01-19 09:48 UTC, marcusburghardt commented
The conflicts here are basically the same I had to resolve in https://github.com/ComplianceAsCode/content/pull/11455.
I will wait https://github.com/ComplianceAsCode/content/pull/11455 to be merged first then I rebase this PR.

2024-01-24 14:55 UTC, marcusburghardt commented
I rebased this PR on top of the latest upstream master branch.

2024-01-24 15:47 UTC, marcusburghardt commented
Rebased again.

2024-01-25 14:07 UTC, vojtapolasek requested changes
Hello @marcusburghardt  and thank you for this big update. I have only minor comments, it looks mostly good.

2024-01-25 14:14 UTC, marcusburghardt commented on controls/cis_rhel8.yml
> +      - file_groupowner_at_allow
In combination with the rule to ensure there is no at.deny file I consider enough to satisfy this requirement. But I think it is worth for a note. I will include a note here.

2024-01-25 14:26 UTC, marcusburghardt commented on controls/cis_rhel8.yml
> +      - sshd_use_approved_ciphers
Great

2024-01-25 14:31 UTC, marcusburghardt commented on controls/cis_rhel8.yml
> +      Rule sshd_use_strong_kex needs to be enabled for rhel8.
For sure. I was not sure about this some days ago. : ) I am updating now.

2024-01-25 14:36 UTC, marcusburghardt commented on controls/cis_rhel8.yml
> +      Rule sshd_use_strong_macs needs to be enabled for rhel8.
done.

2024-01-25 14:42 UTC, marcusburghardt commented on controls/cis_rhel8.yml
> +      - accounts_passwords_pam_faillock_unlock_time
Its a fair point. I will include a note.

2024-01-25 14:45 UTC, marcusburghardt commented on controls/cis_rhel8.yml
> +      - accounts_umask_interactive_users
Aligned.

2024-01-25 14:46 UTC, marcusburghardt commented on controls/cis_rhel8.yml
> +      - file_groupowner_at_allow
Done.

2024-01-25 14:46 UTC, marcusburghardt commented on controls/cis_rhel8.yml
>      status: automated
Done

2024-01-25 14:47 UTC, marcusburghardt commented on controls/cis_rhel8.yml
> +      - sshd_use_approved_ciphers
Done

2024-01-25 14:47 UTC, marcusburghardt commented on controls/cis_rhel8.yml
> +      Rule sshd_use_strong_kex needs to be enabled for rhel8.
Done

2024-01-25 14:47 UTC, marcusburghardt commented on controls/cis_rhel8.yml
> +      - accounts_passwords_pam_faillock_unlock_time
Done

2024-01-25 14:49 UTC, marcusburghardt commented on controls/cis_rhel8.yml
>      status: automated
Done.

2024-01-25 14:50 UTC, marcusburghardt commented
> Hello @marcusburghardt and thank you for this big update. I have only minor comments, it looks mostly good.

Thanks for the review @vojtapolasek . I addressed all the comments in the last commits.

2024-01-25 15:46 UTC, vojtapolasek commented
Looks great now @marcusburghardt , just waiting for CI to finish.

2024-01-25 15:47 UTC, vojtapolasek approved these changes

2024-01-25 15:59 UTC, vojtapolasek commented
Waiving tests on Rawhide, Rawhide is currently broken. The PR does not touch anything related to Kubernetes so waiving as well.

2024-01-25 15:59 UTC, merged