Align RHEL 7 CIS control file with CIS v4.0.0 - Section 5
ComplianceAsCode/content pull request #11456
Opened 2024-01-18 13:37 UTC by jan-cerny

#### Description:

In this PR, we change the control file, change references, add existing rules. But, we don't add new rules, and we don't modify other content.

#### Rationale:
Align RHEL 7 CIS control file with CIS v4.0.0

#### Review Hints:

2024-01-19 09:38 UTC, jan-cerny commented
The CI fail on Rawhide is caused by https://github.com/aio-libs/multidict/issues/926 and isn't related to the pull request.

2024-01-22 10:34 UTC, jan-cerny commented
I have rebased this PR on the top of the latest upstream master branch.

2024-01-23 11:46 UTC, marcusburghardt requested changes
Nice work. I only have some few comments to take a look.

2024-01-23 13:00 UTC, jan-cerny commented
I have done changes according to @marcusburghardt's comments.

2024-01-23 13:39 UTC, marcusburghardt commented on controls/cis_rhel7.yml
> +    status: partial
The status now can be updated to `automated` and the commend can be removed.

2024-01-24 08:16 UTC, jan-cerny commented
I have updated the status and removed the comment.

2024-01-24 08:19 UTC, marcusburghardt approved these changes
Great. Thanks for the nice work @jan-cerny . I will wait the CI tests to confirm everything is good and merge it.

2024-01-24 10:11 UTC, marcusburghardt commented
I checked the failed Automatus tests and they are failing during the clean-up, after the rule tests.
There are no issues testing the rules, so the tests can be safely waived in this particular case.

We are investigating the issue with automatus task "Delete datastream artifact".

2024-01-24 10:11 UTC, merged