New rule kernel_config_modules
ComplianceAsCode/content pull request #11558
Opened 2024-02-08 07:17 UTC by jan-cerny

Add a rule that checks if support for kernel modules is disabled. If the system can function without support for kernel modules, the support for them should be disabled. Include the rule to ANSSI R23 as a related rule.

2024-02-08 22:46 UTC, Mab879 requested changes
Thanks for your work on this.

However, I do have some reservations about accepting this PR.
 
If we are not including this in a profile why are creating a rule?

I'm happy to discuss this with you further offline.

2024-02-08 22:46 UTC, Mab879 commented on controls/anssi.yml
> +    # This rule isn't included in any profile therefore it won't appear in the built data stream.
This comment, doesn't explain the why it here and not in the rules section. Please update this comment to reflect that.

2024-02-09 07:14 UTC, jan-cerny commented
> If we are not including this in a profile why are creating a rule?

I assume we wanted to create it to provide broader context in the controls file. But, I don't like it. The rule won't be present in the built data stream, so the rule is useless.

2024-02-09 13:10 UTC, jan-cerny commented
replaced by https://github.com/ComplianceAsCode/content/pull/11571

2024-02-09 13:10 UTC, closed without merging