Add new rule file_permissions_sudo
ComplianceAsCode/content pull request #11584
Opened 2024-02-13 16:05 UTC by Mab879

#### Description:

Add new rule file_permissions_sudo

#### Rationale:
To cover ANSSI R38

2024-02-13 18:35 UTC, Mab879 commented
/packit retest-failed

2024-02-14 09:16 UTC, jan-cerny commented
/packit retest-failed

2024-02-14 09:25 UTC, jan-cerny requested changes

2024-02-14 09:25 UTC, jan-cerny commented on linux_os/guide/system/software/sudo/file_permissions_sudo/rule.yml
> +    cce@rhel9: CCE-86951-1
Please remove these CCEs from `shared/references/cce-redhat-avail.txt`.

2024-02-15 08:08 UTC, jan-cerny commented
@Mab879 Testing farm fail is legit, it fail in the rule file_permissions_sudo in the ANSSI profile. The actual permissions are of `/usr/bin/sudo` are 4111.

2024-02-15 22:32 UTC, Mab879 commented
/packit retest-failed

2024-02-15 22:33 UTC, Mab879 commented
> @Mab879 Testing farm fail is legit, it fail in the rule file_permissions_sudo in the ANSSI profile. The actual permissions are of `/usr/bin/sudo` are 4111.

So I misread the permissions in ANSSI, they are looking for 4110, but that might not be possible.

2024-02-16 07:14 UTC, jan-cerny commented on linux_os/guide/system/software/sudo/file_permissions_sudo/rule.yml
> +        filemode: '4110'
CI still fails.

So is it 4110 or 4111?

The HTML report from the testing farm https://artifacts.dev.testing-farm.io/ae6aeb0b-5999-4a1d-ad23-2291c000eb50/work-ansible-anssivlxuhmw6/tests/fmf-plans/ansible-anssi/execute/data/guest/default-0/Sanity/ansible-machine-hardening/anssi_bp28_high-1/data/anssi_bp28_high.html indicates that 4111 .

On my machine:

```
jcerny@fedora:~$ stat -c %a /usr/bin/sudo
4111
```

But I haven't investigated it further.

2024-02-16 07:14 UTC, jan-cerny commented on linux_os/guide/system/software/sudo/file_permissions_sudo/rule.yml
> +{{{ describe_file_permissions("/usr/bin/sudo", "4750") | indent(4) }}}
the value of the permissions will have to be the same as in the template section

2024-02-16 13:01 UTC, Mab879 commented
Moving to 4111 as 4110 doesn't seem possible.

2024-02-19 08:13 UTC, jan-cerny commented
/packit retest-failed

2024-02-19 13:48 UTC, jan-cerny commented
/packit retest-failed

2024-02-20 07:40 UTC, jan-cerny commented
/packit retest- failed

2024-02-20 14:06 UTC, jan-cerny commented
/packit retest-failed

2024-02-21 10:46 UTC, jan-cerny commented
/packit retest-failed

2024-02-22 07:32 UTC, jan-cerny commented
/packit retest-failed

2024-02-22 08:11 UTC, jan-cerny commented
/packit retest-failed

2024-02-22 10:20 UTC, jan-cerny commented
/packit retest-failed

2024-02-22 10:56 UTC, jan-cerny commented
/packit retest-failed

2024-02-22 12:29 UTC, merged