Add Script to Import DISA STIG to Policy Specific Content
ComplianceAsCode/content pull request #11611
Opened 2024-02-20 21:12 UTC by Mab879

#### Description:

This PR adds a script that takes the SRG Requirement, Fix text, check text, and Vulnerability discussion from the DISA STIG XML files and imports them to the Policy Specific Content (PSC) files.

#### Rationale:

Help prep for the next STIG.

#### Review Hints:
```
$ ./utils/import_disa_stig.py --product rhel9 --control stig_rhel9 shared/references/disa-stig-rhel9-v1r2-xccdf-manual.xml
```

Observe that under the rules used by the STIG the PSC content is updated.

2024-02-22 15:20 UTC, jan-cerny commented
/packit build

2024-02-23 13:15 UTC, jan-cerny requested changes

2024-02-23 13:15 UTC, jan-cerny commented on utils/srg_utils/__init__.py
> +        replace_yaml_section(section, changed, rule_dir_json)
```
[jcerny@fedora content]$  ./utils/import_disa_stig.py --product rhel9 --control stig_rhel9 shared/references/disa-stig-rhel9-v1r2-xccdf-manual.xml
Traceback (most recent call last):
  File "/home/jcerny/work/git/content/./utils/import_disa_stig.py", line 111, in <module>
    raise SystemExit(main())
                     ^^^^^^
  File "/home/jcerny/work/git/content/./utils/import_disa_stig.py", line 86, in main
    update_row(changed_fixtext, stig_srg_requirement, rule_obj, 'srg_requirement')
  File "/home/jcerny/work/git/content/utils/srg_utils/__init__.py", line 37, in update_row
    replace_yaml_section(section, changed, rule_dir_json)
    ^^^^^^^^^^^^^^^^^^^^
NameError: name 'replace_yaml_section' is not defined
```

2024-02-23 13:15 UTC, jan-cerny commented on utils/import_disa_stig.py
> +        if rule.checktext != stig_checktext:
rule_checktext ?

2024-02-26 23:04 UTC, Mab879 commented on utils/import_disa_stig.py
> +    for stig_id, stig_rule in srgs.items():
I have cleaned up the main method a bit, but moving the code the edits the file results in very ugly method signatures.

2024-02-27 13:49 UTC, Mab879 commented
/packit retest-failed

2024-02-28 12:00 UTC, jan-cerny commented
/packit retest-failed

2024-02-28 12:38 UTC, jan-cerny approved these changes
I have executed the script and it updated the policy specific content as expected.

2024-02-28 15:22 UTC, merged