Improve ANSSI R28
ComplianceAsCode/content pull request #11626
Opened 2024-02-26 15:43 UTC by jan-cerny

#### Description:

Create new rule `systemd_tmp_mount` that checks if the systemd `tmp.mount` mount unit is enabled.

This rule uses a new template that is also added by this PR.

#### Rationale:

We will add this rule to ANSSI R28 because it aligns with the requirement to clean after reboot or be preferably type tmpfs.

2024-02-27 09:47 UTC, jan-cerny commented
From the CI results we can see that the new rule conflicts with accounts_polyinstantiated_tmp which is also a part of the ANSSI profile.

2024-03-08 13:51 UTC, Mab879 requested changes
Just one minor item.

2024-03-08 13:51 UTC, Mab879 commented on linux_os/guide/system/software/disk_partitioning/systemd_tmp_mount_enabled/rule.yml
> +    {{{ systemd_mount_enabled("tmp") }}}
This will be need to updated as well.

2024-03-11 08:22 UTC, jan-cerny commented
I have renamed the OCIL macro.

2024-03-13 14:15 UTC, jan-cerny commented
/packit retest-failed

2024-03-14 14:29 UTC, Mab879 commented
Automatus passes locally

```
$ ./automatus.py rule --datastream ../build/ssg-rhel8-ds.xml --libvirt qemu:///system automatus_rhel8_10 systemd_tmp_mount_enabled,accounts_polyinstantiated_tmp
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/mburket/review/ComplianceAsCode/content3/tests/logs/rule-custom-2024-03-14-0924/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_accounts_polyinstantiated_tmp
INFO - Script correct.pass.sh using profile (all) OK
INFO - Script line_not_there.fail.sh using profile (all) OK
INFO - Script wrong_mode.fail.sh using profile (all) OK
INFO - Script directory_doesnt_exist.pass.sh using profile (all) OK
INFO - xccdf_org.ssgproject.content_rule_systemd_tmp_mount_enabled
INFO - Script mount_enabled.pass.sh using profile (all) OK
INFO - Script mount_disabled.fail.sh using profile (all) OK
$ ./automatus.py rule --datastream ../build/ssg-rhel8-ds.xml --libvirt qemu:///system automatus_rhel8_10 systemd_tmp_mount_enabled,accounts_polyinstantiated_tmp
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/mburket/review/ComplianceAsCode/content3/tests/logs/rule-custom-2024-03-14-0924/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_accounts_polyinstantiated_tmp
INFO - Script correct.pass.sh using profile (all) OK
INFO - Script line_not_there.fail.sh using profile (all) OK
INFO - Script wrong_mode.fail.sh using profile (all) OK
INFO - Script directory_doesnt_exist.pass.sh using profile (all) OK
INFO - xccdf_org.ssgproject.content_rule_systemd_tmp_mount_enabled
INFO - Script mount_enabled.pass.sh using profile (all) OK
INFO - Script mount_disabled.fail.sh using profile (all) OK
```

2024-03-15 08:18 UTC, jan-cerny commented
great!

2024-03-15 12:20 UTC, Mab879 approved these changes

2024-03-15 12:20 UTC, merged