CMP-2247: Add a new profile for CIS OpenShift 1.5.0
ComplianceAsCode/content pull request #11636
Opened 2024-02-29 19:06 UTC by rhmdnd

CIS released version 1.5.0 in December 2023. There are no technical
differences between version 1.4.0 and 1.5.0. This change simplify
updates the version to reflect the latest version of the CIS OpenShift
benchmark.

It also keeps version available for people who may want to pin their
scans to that version.

2024-02-29 19:08 UTC, rhmdnd commented
/test

2024-02-29 19:09 UTC, rhmdnd commented
/test 4.13-e2e-aws-ocp4-cis
/test 4.13-e2e-aws-ocp4-cis-node
/test 4.15-e2e-aws-ocp4-cis
/test 4.15-e2e-aws-ocp4-cis-node
/test 4.16-e2e-aws-ocp4-cis
/test 4.16-e2e-aws-ocp4-cis-node
/test e2e-aws-ocp4-cis
/test e2e-aws-ocp4-cis-node

2024-02-29 20:26 UTC, rhmdnd commented
Failed standing up the metrics server:

```
{"level":"error","ts":"2024-02-29T19:52:02.415Z","logger":"setup","msg":"Error creating metrics service/secret","error":"compliance-operator-serving-cert not found - restarting, as the service may have just been created","stacktrace":"github.com/ComplianceAsCode/compliance-operator/cmd/manager.addMetrics\n\tgithub.com/ComplianceAsCode/compliance-operator/cmd/manager/operator.go:369\ngithub.com/ComplianceAsCode/compliance-operator/cmd/manager.RunOperator\n\tgithub.com/ComplianceAsCode/compliance-operator/cmd/manager/operator.go:321\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.8.0/command.go:987\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.8.0/command.go:1115\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.8.0/command.go:1039\nmain.main\n\tgithub.com/openshift/compliance-operator/main.go:46\nruntime.main\n\truntime/proc.go:267"}
```

2024-02-29 20:26 UTC, rhmdnd commented
/test 4.15-e2e-aws-ocp4-cis-node

2024-03-01 14:51 UTC, yuumasato requested changes

2024-03-01 14:51 UTC, yuumasato commented on products/ocp4/profiles/cis-1-5.profile
> +    Red Hat OpenShift Container Platform 4 Benchmark™, V1.4.
Update the description version to `1.5`

2024-03-01 14:51 UTC, yuumasato commented on products/ocp4/profiles/cis-node-1-5.profile
> +    Red Hat OpenShift Container Platform 4 Benchmark™, V1.4.
Same here, :)

2024-03-01 14:51 UTC, yuumasato commented on products/ocp4/profiles/cis-node.profile
> +    version: 1.5.0
The Benchmark version in the description needs to be bumped as well.

2024-03-01 14:51 UTC, yuumasato commented on products/ocp4/profiles/cis.profile
> +    version: 1.5.0
Bump the description as well.

2024-03-04 03:47 UTC, xiaojiey commented
/hold for test

2024-03-04 09:09 UTC, xiaojiey commented
```
 % oc get profile.compliance | grep upstream | grep cis
upstream-ocp4-cis                         23m    1.5.0
upstream-ocp4-cis-1-4                     23m    1.4.0
upstream-ocp4-cis-1-5                     23m    1.5.0
upstream-ocp4-cis-node                    23m    1.5.0
upstream-ocp4-cis-node-1-4                23m    1.4.0
upstream-ocp4-cis-node-1-5                23m    1.5.0
% cat ssb_cis.yaml 
apiVersion: compliance.openshift.io/v1alpha1
kind: ScanSettingBinding
metadata:
  name: cis-compliance
  namespace: openshift-compliance
profiles:
  - name: upstream-ocp4-cis-node
    kind: Profile
    apiGroup: compliance.openshift.io/v1alpha1
  - name: upstream-ocp4-cis
    kind: Profile
    apiGroup: compliance.openshift.io/v1alpha1
settingsRef:
  name: default
  kind: ScanSetting
  apiGroup: compliance.openshift.io/v1alpha1
 % oc apply -f ssb_cis.yaml
scansettingbinding.compliance.openshift.io/cis-compliance created
% cat ssb_cis_1-5.yaml 
apiVersion: compliance.openshift.io/v1alpha1
kind: ScanSettingBinding
metadata:
  name: cis-compliance-1-5
  namespace: openshift-compliance
profiles:
  - name: upstream-ocp4-cis-node-1-5
    kind: Profile
    apiGroup: compliance.openshift.io/v1alpha1
  - name: upstream-ocp4-cis-1-5
    kind: Profile
    apiGroup: compliance.openshift.io/v1alpha1
settingsRef:
  name: default
  kind: ScanSetting
  apiGroup: compliance.openshift.io/v1alpha1
% oc apply -f ssb_cis_1-5.yaml
scansettingbinding.compliance.openshift.io/cis-compliance-1-5 created                                                                                                                                                                                 % oc get ccr -l compliance.openshift.io/check-status=PASS,compliance.openshift.io/suite=cis-compliance --no-headers | wc -l
     197
 % oc get ccr -l compliance.openshift.io/check-status=FAIL,compliance.openshift.io/suite=cis-compliance --no-headers | wc -l
      10
% oc get ccr -l compliance.openshift.io/check-status=MANUAL,compliance.openshift.io/suite=cis-compliance --no-headers | wc -l
      21
% cat ssb_cis_1-4.yaml                                                                                               
apiVersion: compliance.openshift.io/v1alpha1
kind: ScanSettingBinding
metadata:
  name: cis-compliance-1-4
  namespace: openshift-compliance
profiles:
  - name: upstream-ocp4-cis-node-1-4
    kind: Profile
    apiGroup: compliance.openshift.io/v1alpha1
  - name: upstream-ocp4-cis-1-4
    kind: Profile
    apiGroup: compliance.openshift.io/v1alpha1
settingsRef:
  name: default
  kind: ScanSetting
  apiGroup: compliance.openshift.io/v1alpha1
% oc apply -f ssb_cis_1-4.yaml                                                                                               
scansettingbinding.compliance.openshift.io/cis-compliance-1-4 created
 % oc get suite -w
NAME                 PHASE       RESULT
cis-compliance       DONE        NON-COMPLIANT
cis-compliance-1-4   LAUNCHING   NOT-AVAILABLE
cis-compliance-1-5   DONE        NON-COMPLIANT
cis-compliance-1-4   LAUNCHING   NOT-AVAILABLE
cis-compliance-1-4   LAUNCHING   NOT-AVAILABLE
cis-compliance-1-4   RUNNING     NOT-AVAILABLE
cis-compliance-1-4   RUNNING     NOT-AVAILABLE
cis-compliance-1-4   RUNNING     NOT-AVAILABLE
cis-compliance-1-4   RUNNING     NOT-AVAILABLE
cis-compliance-1-4   AGGREGATING   NOT-AVAILABLE
cis-compliance-1-4   AGGREGATING   NOT-AVAILABLE
cis-compliance-1-4   DONE          NON-COMPLIANT
cis-compliance-1-4   DONE          NON-COMPLIANT
^C%                                                                                                                                                                                 
 % oc get ccr -l compliance.openshift.io/check-status=PASS,compliance.openshift.io/suite=cis-compliance-1-5 --no-headers | wc -l
     197
% oc get ccr -l compliance.openshift.io/check-status=FAIL,compliance.openshift.io/suite=cis-compliance-1-5 --no-headers | wc -l
      10
% oc get ccr -l compliance.openshift.io/check-status=MANUAL,compliance.openshift.io/suite=cis-compliance-1-5 --no-headers | wc -l
      21
 % oc get ccr -l compliance.openshift.io/check-status=PASS,compliance.openshift.io/suite=cis-compliance-1-4 --no-headers | wc -l 
     197
% oc get ccr -l compliance.openshift.io/check-status=FAIL,compliance.openshift.io/suite=cis-compliance-1-4 --no-headers | wc -l
      10
% oc get ccr -l compliance.openshift.io/check-status=MANUAL,compliance.openshift.io/suite=cis-compliance-1-4 --no-headers | wc -l
      21
```

2024-03-04 09:09 UTC, xiaojiey commented
/unhold

2024-03-04 14:12 UTC, rhmdnd commented on products/ocp4/profiles/cis-1-5.profile
> +    Red Hat OpenShift Container Platform 4 Benchmark™, V1.4.
Good catch, thank you.

2024-03-04 14:13 UTC, rhmdnd commented
/test 4.13-e2e-aws-ocp4-cis
/test 4.13-e2e-aws-ocp4-cis-node
/test 4.15-e2e-aws-ocp4-cis
/test 4.15-e2e-aws-ocp4-cis-node
/test 4.16-e2e-aws-ocp4-cis
/test 4.16-e2e-aws-ocp4-cis-node
/test e2e-aws-ocp4-cis
/test e2e-aws-ocp4-cis-node

2024-03-05 09:56 UTC, yuumasato commented
4.16 deployment is broken

2024-03-05 09:56 UTC, yuumasato approved these changes

2024-03-05 09:57 UTC, merged