Update ansible_playbook_to_role util for RHEL 9
ComplianceAsCode/content pull request #11654
Opened 2024-03-06 01:58 UTC by dmc5179

#### Description:
Update ansible_playbook_to_role util for RHEL 9
Switch default branch from master to main
Remove unsupported characters in role names during conversion process; i.e [ and ]

#### Rationale:

Util needs to be updated to support converting the ansible playbooks from this repo into ansible roles as has been done for RHEL 7 and RHEL 8.

#### Review Hints:

After building this main content repo, the following command is used to convert the playbooks into roles, which needs the added RHEL 9 support

```
./utils/ansible_playbook_to_role.py --product rhel9 --profile $p --organization RedHatOfficial --tag-release --token ${GIT_TOKEN} --build-playbooks-dir ./build/ansible/
```

I have used the updated version of the script for the last few content releases but did not have a chance until now to submit a PR.

2024-03-06 11:23 UTC, Mab879 commented
Please resolve the merge conflicts.

2024-03-28 13:23 UTC, Mab879 requested changes
Please fix the the PEP8 issues and remove the merge commit from this branch.

2024-03-28 13:23 UTC, Mab879 commented on utils/ansible_playbook_to_role.py
> +            sh.sed('-i','s/\[DRAFT\]/DRAFT/g',abs_path)
```suggestion
            sh.sed('-i','s/\[DRAFT\]/DRAFT/g', abs_path)
```

2024-03-28 13:23 UTC, Mab879 commented on utils/ansible_playbook_to_role.py
>  class RoleGithubUpdater(object):
```suggestion

class RoleGithubUpdater(object):
```

2024-04-19 23:34 UTC, dmc5179 commented
@Mab879 I'm not sure how to do that last part, remove the merge commit from this branch.

2024-04-26 18:49 UTC, Mab879 commented
> @Mab879 I'm not sure how to do that last part, remove the merge commit from this branch.

First all, thanks for the work.

Reviewing the changes I wondering if we can just close this PR.

The [DRAFT] to DRAFT change should no longer be needed as we now use "DRAFT - " as the prefix.

So that only leaves that print statement.

If you want that print statement, with all the recent changes it might be best just to open a new PR based on the latest master.

Again, thanks for the your work and happy to help.

2024-06-10 15:30 UTC, Mab879 commented
Thanks again for this PR.

However, I don't think the changes are necessary.

Please feel free to open a new PR to make additional changes.

2024-06-10 15:30 UTC, closed without merging