Implement ANSSI requirement R69 for RHEL
ComplianceAsCode/content pull request #11663
Opened 2024-03-07 15:44 UTC by vojtapolasek

#### Description:

- add three similar rules which check for presence of obsolete services in /etc/nsswitch.conf
- each rule has only OVAL check, as remediation should be done manually
- services are NIS, NIS+ and Hesiod
- the wording of the requirement is updated

#### Rationale:

- ANSSI 2.0 alignment

2024-03-07 18:17 UTC, Mab879 commented
The failure on building the HTML seems suspicious, can you please investigate?

2024-03-08 09:02 UTC, jan-cerny commented
The utils/gen_rendered_policies_index.py doesn't support jinja macros in control files, you need to change that because jinja macros should be allowed in control files.

2024-03-08 09:41 UTC, vojtapolasek commented
The error while generating HTML pages is caused by the script gen_rendered_policies_index because it can't handle Jinja. Investigating...

2024-03-08 13:52 UTC, vojtapolasek commented
I propose fix here: https://github.com/ComplianceAsCode/content/pull/11667

2024-03-08 18:46 UTC, Mab879 commented
I merged #11667 so you should be able rebase this PR to resolve the CI issues.

2024-03-11 18:59 UTC, Mab879 requested changes
Just a few issues. 

Thanks for the PR!

2024-03-11 18:59 UTC, Mab879 commented on linux_os/guide/services/obsolete/nis/no_nis_in_nsswitch/rule.yml
> +    If a line is returned and it    contains the word <tt>nis</tt> in the list
```suggestion
    If a line is returned and it contains the word <tt>nis</tt> in the list
```

2024-03-11 18:59 UTC, Mab879 commented on linux_os/guide/services/obsolete/no_hesiod_in_nsswitch/rule.yml
> +    implementation in the GNU C library.  The various services provided are
```suggestion
    implementation in the GNU C library. The various services provided are
```

2024-03-11 18:59 UTC, Mab879 commented on linux_os/guide/services/obsolete/no_hesiod_in_nsswitch/rule.yml
> +    If a line is returned and it    contains the word <tt>hesiod</tt> in the list
```suggestion
    If a line is returned and it contains the word <tt>hesiod</tt> in the list
```

2024-03-12 09:15 UTC, vojtapolasek commented
Thank you for suggestions, applied.

2024-03-12 17:22 UTC, Mab879 approved these changes

2024-03-12 17:22 UTC, merged