Align networkmanager_dns_mode to the RHEL 9 STIG
ComplianceAsCode/content pull request #11745
Opened 2024-03-22 15:26 UTC by Mab879

#### Description:

Removes the ability to add space around the `dns=none` per the STIG SCAP content.

#### Rationale:

Fixes #11702

2024-03-25 10:28 UTC, jan-cerny commented
The problem is that the Ansible remediation still adds or doesn't remove the spaces. Ansible has an option that could be used https://docs.ansible.com/ansible/latest/collections/community/general/ini_file_module.html#parameter-no_extra_spaces. OTOH Bash remediation is OK.

2024-03-25 19:01 UTC, Mab879 commented
> The problem is that the Ansible remediation still adds or doesn't remove the spaces. Ansible has an option that could be used https://docs.ansible.com/ansible/latest/collections/community/general/ini_file_module.html#parameter-no_extra_spaces. OTOH Bash remediation is OK.

I have updated the Ansible remediation.

2024-03-26 07:39 UTC, jan-cerny requested changes

2024-03-26 07:39 UTC, jan-cerny commented on shared/macros/10-ansible.jinja
> +    ignore_spaces: false
The tests still fail.

If we do this they should stop failing:

```suggestion
    ignore_spaces: false
    no_extra_spaces: true
```

2024-03-27 09:54 UTC, jan-cerny requested changes

2024-03-27 09:54 UTC, jan-cerny commented on linux_os/guide/system/network/networkmanager/networkmanager_dns_mode/ansible/shared.yml
> +{{{ ansible_ini_file_set("/etc/NetworkManager/NetworkManager.conf", "main", "dns", "{{ var_networkmanager_dns_mode }}", true) }}}
I'm sorry I was wrong, this isn't sufficient, they still fail. We need also to update the macro here.

```suggestion
{{{ ansible_ini_file_set("/etc/NetworkManager/NetworkManager.conf", "main", "dns", "{{ var_networkmanager_dns_mode }}", description=None, ignore_spaces=True) }}}

```

2024-03-27 15:45 UTC, jan-cerny approved these changes
The Automatus CI jobs fail because it isn't possible to start the networkmanager service in a container environment that we use in the CI. I have executed the tests locally using a RHEL 9 virtual machine backed and they all passed:

```
jcerny@fedora:~/work/git/scap-security-guide (pr/11745)$ python3 tests/automatus.py rule --libvirt qemu:///system ssgts_rhel9  networkmanager_dns_mode
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/jcerny/work/git/scap-security-guide/logs/rule-custom-2024-03-27-1640/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_networkmanager_dns_mode
INFO - Script correct.pass.sh using profile (all) OK
INFO - Script correct_default.pass.sh using profile (all) OK
INFO - Script missing.fail.sh using profile (all) OK
INFO - Script wrong_value.fail.sh using profile (all) OK
INFO - Script space.fail.sh using profile (all) OK
jcerny@fedora:~/work/git/scap-security-guide (pr/11745)$ python3 tests/automatus.py rule --libvirt qemu:///system ssgts_rhel9 --remediate-using ansible  networkmanager_dns_mode
Setting console output to log level INFO
INFO - The base image option has not been specified, choosing libvirt-based test environment.
INFO - Logging into /home/jcerny/work/git/scap-security-guide/logs/rule-custom-2024-03-27-1642/test_suite.log
INFO - xccdf_org.ssgproject.content_rule_networkmanager_dns_mode
INFO - Script correct.pass.sh using profile (all) OK
INFO - Script correct_default.pass.sh using profile (all) OK
INFO - Script missing.fail.sh using profile (all) OK
INFO - Script wrong_value.fail.sh using profile (all) OK
INFO - Script space.fail.sh using profile (all) OK
```

2024-03-27 15:45 UTC, merged