Firewall technology related rules per service and package change logic accprding to interactive profile variable
ComplianceAsCode/content pull request #11818
Opened 2024-04-14 04:03 UTC by teacup-on-rockingchair

#### Description:

- Make sure that behaviour of rules about nftables,iptables and firewalld are mutually exclusive and the default behaviour of the checks and remediations is based on external interactive variable, that is part of the profile definition

#### Rationale:
- Add oval macro to check external variable vs expected value
- Add variable to set default firewall technology used
- Set relevant values for SLE platforms
- Templates for pkg installed/removed and svc enabled/disabled, guarded by ext varaiable
- The idea is the oval checks and remediation to check provided external variable, and thus honour if really to check/install/remove certain package or service
- Enable nftable service on SLE only if active firewall technology is set to be nftables
- Disable nftable service on SLE only if active firewall technology is set to be firewalld or iptables
- Removing nftable package on SLE makes sense only if active firewall technology is set to be firewalld or iptables
- Installing iptables package on SLE only if active firewall technology is set to be iptables
- Enable iptables service on SLE only if active firewall technology is set to be iptables
- Disable firewalld service on SLE only if active firewall technology is set to be nftables or iptables
- Removing  package on SLE makes sense only if active firewall technology is set to be nftables or iptables
- Enable firewalld service on SLE only if active firewall technology is set to be firewalld
- Installing firewalld package on SLE only if active firewall technology is set to be firewalld

#### Review Hints:

- The use case would be that the user will have in its profile defined default firewall technology, one of iptables,nftables,ufw, firewalld ,and if the system has been modified a non-default option for that, one can use `scap-workbench` or similar tool, or  define a new alternative profile to the original one (CIS is currently the one having conflicting rules ) , or via command line arguments of the `oscap ` tool, if that is the weapon of choice to run checks and remediations.

2024-04-28 09:29 UTC, teacup-on-rockingchair commented
/test all

2024-05-16 16:24 UTC, Xeicker commented
> should we change this pr to work across different vendors? @marcusburghardt @Mab879 @Xeicker

For the moment it is not necessary for Oracle Linux

2024-08-02 05:52 UTC, jan-cerny commented
ping

2025-01-10 07:56 UTC, marcusburghardt commented
I removed myself as assignee as, unfortunately, I won't be able to review/test it again for the next few weeks.

2025-01-17 19:44 UTC, Mab879 requested changes
Sorry, for the late review. 

Hopefully we can get this moving along again.

2025-01-17 19:44 UTC, Mab879 commented on shared/templates/package_installed_guard_var/ansible.template
> +  package:
```suggestion
  ansible.builtin.package:
```

2025-01-17 19:44 UTC, Mab879 commented on shared/templates/package_removed_guard_var/ansible.template
> +  package:
```suggestion
  ansible.builtin.package:
```

2025-01-17 19:44 UTC, Mab879 commented on shared/templates/service_enabled_guard_var/ansible.template
> +    systemd:
```suggestion
    ansible.builtin.systemd_service:
```
Modern FQCN. `ansible.builtin.systemd` may also work.

2025-01-17 19:44 UTC, Mab879 commented on shared/templates/service_enabled_guard_var/oval.template
> +{{% if target_oval_version >= [5, 11] %}}
Currently, the target version is always 5.11. We dropped 5.10 support a long time ago.

2025-01-17 19:44 UTC, Mab879 commented on linux_os/guide/system/network/network-iptables/iptables_activation/service_iptables_enabled/rule.yml
> +platform: machine and package[iptables] and service_disabled[firewalld]
Did you intent go back to `machine` vs `system_with_kernel`?

2025-01-17 19:44 UTC, Mab879 commented on linux_os/guide/system/network/network-nftables/service_nftables_enabled/rule.yml
> +platform: machine and package[nftables] and service_disabled[firewalld]
Did you intent go back to `machine` vs `system_with_kernel`?

2025-01-21 10:04 UTC, teacup-on-rockingchair commented on linux_os/guide/system/network/network-iptables/iptables_activation/service_iptables_enabled/rule.yml
> +platform: machine and package[iptables] and service_disabled[firewalld]
That was a miss during rebase thanks for raising the flag

2025-01-21 10:04 UTC, teacup-on-rockingchair commented on linux_os/guide/system/network/network-nftables/service_nftables_enabled/rule.yml
> +platform: machine and package[nftables] and service_disabled[firewalld]
That was a miss during rebase thanks for raising the flag

2025-01-21 10:05 UTC, teacup-on-rockingchair commented on shared/templates/service_enabled_guard_var/oval.template
> +{{% if target_oval_version >= [5, 11] %}}
dropped outdated code thanks 🙇

2025-01-21 16:48 UTC, Mab879 approved these changes
Waving the Automatus Tests as they pass locally.

Waving the Code Climate issues as I don't think they are worth solving.

Overriding CODEOWNERS since @teacup-on-rockingchair cannot merge his own PRs.

Thanks @teacup-on-rockingchair working on this for all this time.

2025-01-21 16:48 UTC, merged

2025-01-24 11:11 UTC, mpurg commented on shared/templates/package_installed_guard_var/bash.template
> +  if [[ "{{{ VALUE }}}" =~ ${{{ VARIABLE }}} ]]; then
@teacup-on-rockingchair I think the operation here should be flipped.
The implementation searches for VARIABLE regex inside VALUE, instead of searching for VALUE regex in VARIABLE.
If `VALUE=firewalld|nftables`, then it will match when `VARIABLE` is set to any substring of VALUE, empty string, and regex special characters.