Improve unnecessarily over-complicated regex
ComplianceAsCode/content pull request #11813
Opened 2024-04-12 09:44 UTC by marcusburghardt

#### Description:

By any reason the regex in this rule was unnecessarily super over-complicated.

This PR updates it from:
`'\s*=\s*("(?:\\"|\\\\|[^"\\\n])*"\B|[^"](?:(?:\\,|\\"|\\ |\\\\|[^", \\\n])*)\b)'`

to:
`'\s*=\s*(?:"?([^",\s]+)"?)'`

with the same effect and very likely better performance.

#### Rationale:

- Improve performance and readability
- Fixes https://issues.redhat.com/browse/RHEL-31976

#### Review Hints:

Automatus tests should be enough, but it would also be nice to play with [regex101.com](https://regex101.com/r/YcjxF3/1)

2024-04-12 12:01 UTC, marcusburghardt commented
Testing farms are failing now because we still need to fix some minor issues with https://github.com/ComplianceAsCode/content/pull/11796.

2024-04-16 09:23 UTC, jan-cerny requested changes
I have checkd the regex101.com and I have reviewed the regex. I have executed the test scenarios.

The PR looks good to me.

Please rebase this on the top of the latest upstream master branch which should bring in the sssd_enable_pam_service which should make the TF tests green.

2024-04-16 09:25 UTC, marcusburghardt commented
> I have checkd the regex101.com and I have reviewed the regex. I have executed the test scenarios.
> 
> The PR looks good to me.
> 
> Please rebase this on the top of the latest upstream master branch which should bring in the sssd_enable_pam_service which should make the TF tests green.

Done

2024-04-16 11:54 UTC, vojtapolasek commented
It looks good. I will merge it.

2024-04-16 12:17 UTC, jan-cerny approved these changes

2024-04-16 12:17 UTC, merged