Add rule file_owner_journalctl
ComplianceAsCode/content pull request #11835
Opened 2024-04-17 08:16 UTC by mpurg

#### Description:

- New rule for auditing ownership of journalctl command
- Satisfies STIG requirement UBTU-22-232100
- Based on file_owner_system_journal

2024-04-17 11:07 UTC, dodys commented
Added red-hatters and suse maintainers as this new rule might be relevant for them
@marcusburghardt @Mab879 @teacup-on-rockingchair

2024-04-19 14:48 UTC, teacup-on-rockingchair approved these changes
👍

2024-04-25 19:55 UTC, Mab879 requested changes
This PR needs a rebase on latest master.

2024-04-25 21:13 UTC, mpurg commented
@Mab879 rebased.

2024-04-26 18:40 UTC, Mab879 reviewed
One minor issue.

2024-04-26 18:40 UTC, Mab879 commented on linux_os/guide/system/logging/journald/file_owner_journalctl/rule.yml
> +title: 'Verify Owner on the journalctl command'
```suggestion
title: 'Verify Owner on the journalctl Command'
```

Title case

2024-04-30 10:23 UTC, mpurg commented on linux_os/guide/system/logging/journald/file_owner_journalctl/rule.yml
> +title: 'Verify Owner on the journalctl command'
Fixed!

2024-04-30 10:24 UTC, mpurg commented
Rebased to master due to failing tests.

2024-05-01 13:13 UTC, dodys commented
/packit build

2024-05-07 07:37 UTC, dodys approved these changes
lgtm, thanks!

2024-05-07 07:38 UTC, merged