Add new rules package_ntp_removed, package_timesyncd_removed
ComplianceAsCode/content pull request #11831
Opened 2024-04-17 07:54 UTC by mpurg

#### Description:

- Added new rules for removing packages ntp and systemd-timesyncd
- Satisfies Ubuntu 22.04 STIGs: UBTU-22-215025 UBTU-220-215020
- Based on package_ntp_installed / package_timesyncd_installed

2024-04-17 11:09 UTC, dodys commented
Added red-hatters and suse maintainers as this new rule might be relevant for them
@marcusburghardt @Mab879 @teacup-on-rockingchair

2024-04-17 17:56 UTC, Mab879 requested changes
@mpurg you will need to add these rules to the correct `component` files. `package_ntp_removed` should go in `components/ntp.yml`. `package_timesyncd_removed` should go in `components/systemd.yml`.

2024-04-18 10:25 UTC, dodys commented
/packit retest-failed

2024-04-18 15:22 UTC, Mab879 commented
/packit build

2024-04-18 17:46 UTC, Mab879 commented
@mpurg I would try rebasing on master to fix the testing farm errors.

2024-04-18 18:14 UTC, mpurg commented
@Mab879 done

2024-04-19 03:27 UTC, Mab879 commented
> @Mab879 done

That seems to fix it. Thanks!

2024-04-19 14:38 UTC, teacup-on-rockingchair approved these changes
LGTM 👍

2024-04-30 15:30 UTC, dodys commented
/packit build

2024-05-06 08:51 UTC, dodys approved these changes
lgtm, thanks!

2024-05-06 08:52 UTC, dodys commented
/packit build

2024-05-06 21:30 UTC, Mab879 commented
/packit build

2024-05-07 07:31 UTC, merged