OCP Update variable filter to consider go_template
ComplianceAsCode/content pull request #11906
Opened 2024-04-26 20:29 UTC by Vincent056

#### Description:

Update the variable filter to find if a rule is using go-template, if so find any var being used, add them to var list for that rule

2024-04-26 21:04 UTC, rhmdnd commented
/test

2024-04-26 21:05 UTC, rhmdnd commented
/test e2e-aws-ocp4-pci-dss
/test e2e-aws-ocp4-pci-dss-node

2024-04-26 21:14 UTC, Vincent056 commented
> /test e2e-aws-ocp4-pci-dss /test e2e-aws-ocp4-pci-dss-node

we have to merge https://github.com/ComplianceAsCode/content/pull/11906 before we can test

2024-04-28 03:36 UTC, xiaojiey commented
/hold for test

2024-04-28 07:14 UTC, xiaojiey commented
/unhold

2024-04-28 07:14 UTC, xiaojiey commented
/lgtm

2024-04-28 08:40 UTC, xiaojiey commented
@Vincent056 seems one issue to fix: https://codeclimate.com/github/ComplianceAsCode/content/pull/11906. Could you please take a look? Thanks.

2024-04-29 16:04 UTC, rhmdnd commented
/test e2e-aws-ocp4-pci-dss
/test e2e-aws-ocp4-pci-dss-node

2024-04-29 18:19 UTC, Vincent056 commented
/test e2e-aws-ocp4-pci-dss
/test e2e-aws-ocp4-pci-dss-node

2024-04-30 01:12 UTC, rhmdnd commented
The stig e2e failure is unrelated and being addressed in a separate PR.

2024-04-30 01:13 UTC, rhmdnd approved these changes
/lgtm

Looks good from a OpenShift content perspective.

2024-04-30 01:14 UTC, rhmdnd commented
@Mab879 does this seem reasonable from the build perspective?

2024-05-01 13:37 UTC, rhmdnd commented
@Honny1 how do you feel able this approach given the recent refactors to the build system made in https://github.com/ComplianceAsCode/content/pull/11858

2024-05-02 11:43 UTC, Honny1 requested changes
I built and compared `ocp4` ds from this PR branch and the main branch and found no problem. However, I would like to ask you to create tests for this problem to avoid similar problems in future changes. Also, I would like to ask why you are processing the DS after the build? Wouldn't it be better to extend the macros during the build?

2024-05-02 15:06 UTC, Vincent056 commented on build-scripts/build_xccdf.py
> +    for ele in rule.itertext():
they will only present in the text part of the rule

2024-05-02 15:31 UTC, Vincent056 commented on build-scripts/build_xccdf.py
> +    for ele in rule.itertext():
I think fix is also part of the rule

2024-05-02 15:41 UTC, Vincent056 commented
> I built and compared `ocp4` ds from this PR branch and the main branch and found no problem. However, I would like to ask you to create tests for this problem to avoid similar problems in future changes. Also, I would like to ask why you are processing the DS after the build? Wouldn't it be better to extend the macros during the build?

Thanks for the review, we have e2e test, but we don't run that in every PR, for example you could run `/test 4.15-e2e-aws-ocp4-high` for one of the test, I can add the unit test in another PR since this is blocking our CI and release.

The go_template is use to in our operator, so that we can process the remediation to use xccdf variables as well as other part of rule to be more dynamic.

2024-05-02 16:07 UTC, Honny1 commented
@Vincent056 
Okay, please add a unit test in another PR. 

Well, I think the `sub` element would do the same magic.  See rule: `xccdf_org.ssgproject.content_rule_enable_fips_mode` 
Or is there some other reason for this approach?

2024-05-02 17:18 UTC, Vincent056 commented
> xccdf_org.ssgproject.content_rule_enable_fips_mode

great, I will do that, we were also depending on go_templating to be able to fetch different kube API, which is defined in warning part of the rule in the compliance operator dynamically based on value of the xccdf variables, among other things

2024-05-02 20:17 UTC, Honny1 commented
@Vincent056 Okay

2024-05-02 20:17 UTC, Honny1 approved these changes

2024-05-03 07:53 UTC, yuumasato approved these changes
Thank you for the review @Honny1

/lgtm

2024-05-03 07:57 UTC, yuumasato commented
/packit help

2024-05-03 08:00 UTC, yuumasato commented
/packit retest-failed

2024-05-03 09:25 UTC, merged

2024-05-03 09:51 UTC, theboringstuff commented
This will not be included in `v0.1.73`? Is there WA for this issue? I encounter similar problem for openshift cluster
```
Fetching URI: '/api/v1/namespaces/-/pods?labelSelector=app%3Dkube-controller-manager'
debug: Applying filter '[[.items[0].spec.containers[0].args[] | select(. | match("--port=[1-9]*[1-9]+") )] | length | if . == 0 then true else false end]' to path '/api/v1/namespaces/-/pods?labelSelector=app%3Dkube-controller-manager'
debug: Error while filtering: cannot iterate over: null
debug: Persisting warnings to output file
FATAL:Error fetching resources: couldn't filter '{"kind":"PodList","apiVersion":"v1","metadata":{"resourceVersion":"190509111"},"items":[]}
': cannot iterate over: null
```

2024-05-03 14:04 UTC, yuumasato commented
As #11858 is going into 0.1.73, I think it makes sense to backport this fix there.
@ComplianceAsCode/red-hatters do you guys concur?