Fix #11902 issue
ComplianceAsCode/content pull request #11905
Opened 2024-04-26 18:20 UTC by marcofortina

#### Description:

On Ubuntu 22.04 pam_tally2 was replaced with pam_faillock and checks should be done on files referenced by the CIS guide:

```
-w /var/log/lastlog -p wa -k logins
-w /var/run/faillock -p wa -k logins
```

#### Rationale:

- Fixes #11902

#### Review Hints:

Build the product:

```
./build_product ubuntu2204
```

To test these changes with Ansible:

```
ansible-playbook build/ansible/ubuntu2204-playbook-cis_level2_server.yml --tags "audit_rules_login_events_faillock"
```

To test changes with bash, run the remediation sections: `xccdf_org.ssgproject.content_rule_audit_rules_login_events_faillock`

Expected output:

```
Title   Record Attempts to Alter Logon and Logout Events - faillock
Rule    xccdf_org.ssgproject.content_rule_audit_rules_login_events_faillock
Result  pass
```

2024-04-26 18:32 UTC, dodys requested changes
please add and remove the ids in the rule.yml files 

to help you out, take a look on:
https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/auditing/auditd_configure_rules/audit_login_events/audit_rules_login_events_faillock/rule.yml#L54
and 
https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/auditing/auditd_configure_rules/audit_login_events/audit_rules_login_events_faillog/rule.yml#L40

2024-04-26 19:12 UTC, marcofortina commented on products/ubuntu2204/profiles/cis_level2_workstation.profile
> +    - var_accounts_passwords_pam_faillock_dir=run
done

2024-04-26 20:20 UTC, marcofortina reviewed
Code reviewed

2024-04-29 08:55 UTC, marcusburghardt commented
/packit test

2024-04-29 13:51 UTC, dodys commented
/packit retest-failed

2024-04-29 15:01 UTC, dodys approved these changes
lgtm, thanks!

2024-04-29 15:01 UTC, merged