CMP-2543: Implement whitelist for configure-network-policies-namespaces
ComplianceAsCode/content pull request #11952
Opened 2024-05-07 03:08 UTC by Vincent056

Added a new varible var_network_policies_namespaces_whitelist_regex, and updated the rule 'configure_network_policies_namespaces' so user is able to excude namespaces by setting this variable to the regex of namespace they want to exclude for this rule

2024-05-13 12:52 UTC, yuumasato requested changes
Please, mention in the rule description as well that namespaces matching the variable regex are not checked for presence of a Network Policy.

2024-05-13 12:52 UTC, yuumasato commented on applications/openshift/networking/var_network_policies_namespaces_whitelist_regex.var
> +title: 'Whitelist Namespaces for Network Policies'
Let's use more inclusive and descriptive wording:

```suggestion
title: 'Namespaces Allowed Without Network Policy'
```

or
```suggestion
title: 'Namespaces exempt of Network Policies'
```

Don't  forget to rename the variable file accordingly.

2024-05-13 12:52 UTC, yuumasato commented on applications/openshift/networking/var_network_policies_namespaces_whitelist_regex.var
> +interactive: false
I guess this field is not consumed by CO, but if this should be editable by the user, this should be `true`
```suggestion
interactive: true
```

2024-05-14 08:26 UTC, yuumasato commented on applications/openshift/networking/var_network_policies_namespaces_whitelist_regex.var
> +title: 'Whitelist Namespaces for Network Policies'
@Vincent056 You forgot to rename the variable and the references to it, :grin:

2024-05-14 12:00 UTC, yuumasato requested changes
Please mention the variable in the rule description.

I have tried the rule in the cluster and it is not working for me, :(
It is always incompliant.

2024-05-15 09:08 UTC, Vincent056 commented
@yuumasato thanks for the review, this issue should be fixed now with the new commit.

```
$ oc create ns no-policy-0
$ oc create ns no-policy-1

$ ./utils/build_ds_container.py -p -d -P ocp4


cat <<EOF | oc apply -f -
apiVersion: compliance.openshift.io/v1alpha1
kind: TailoredProfile
metadata:
  name: cis-pass
  namespace: openshift-compliance
spec:
  description: Test
  setValues:
  - name: upstream-ocp4-var-network-policies-namespaces-whitelist-regex
    value: no-policy-0|no-policy-1
    rationale: test
  extends: upstream-ocp4-cis
  title: My modified nist profile with a custom value
EOF

cat <<EOF | oc apply -f -
apiVersion: compliance.openshift.io/v1alpha1
kind: TailoredProfile
metadata:
  name: cis-no-pass
  namespace: openshift-compliance
spec:
  description: Test
  extends: upstream-ocp4-cis
  title: My modified nist profile with a custom value
EOF

[vincent@node cac-content-fork]$ oc get tp
NAME          STATE
cis-no-pass   READY
cis-pass      READY

cat <<EOF | oc apply -f -
apiVersion: compliance.openshift.io/v1alpha1
kind: ScanSettingBinding
metadata:
  name: cis-test-network-policy
  namespace: openshift-compliance
profiles:
- apiGroup: compliance.openshift.io/v1alpha1
  kind: TailoredProfile
  name: cis-pass
- apiGroup: compliance.openshift.io/v1alpha1
  kind: TailoredProfile
  name: cis-no-pass
settingsRef:
  apiGroup: compliance.openshift.io/v1alpha1
  kind: ScanSetting
  name: default
EOF

[vincent@node cac-content-fork]$ oc get ssb
NAME                      STATUS
cis-test-network-policy   READY

[vincent@node cac-content-fork]$ oc get scan -w
NAME          PHASE     RESULT
cis-no-pass   RUNNING   NOT-AVAILABLE
cis-pass      RUNNING   NOT-AVAILABLE
cis-pass      AGGREGATING   NOT-AVAILABLE
cis-pass      AGGREGATING   NOT-AVAILABLE
cis-no-pass   AGGREGATING   NOT-AVAILABLE
cis-no-pass   AGGREGATING   NOT-AVAILABLE
cis-no-pass   DONE          NON-COMPLIANT
cis-pass      DONE          NON-COMPLIANT

[vincent@node cac-content-fork]$ oc get ccr | grep network-policies-n
cis-no-pass-configure-network-policies-namespaces                    FAIL     high
cis-pass-configure-network-policies-namespaces                       PASS     high

oc delete ssb cis-test-network-policy
oc delete tp cis-no-pass cis-pass
oc delete profilebundle upstream-ocp4
```

2024-05-15 10:40 UTC, yuumasato commented
/test help

2024-05-15 10:42 UTC, yuumasato commented
/test 4.13-e2e-aws-ocp4-cis
/test 4.14-e2e-aws-ocp4-cis
/test 4.15-e2e-aws-ocp4-cis
/test 4.16-e2e-aws-ocp4-cis

2024-05-15 18:08 UTC, yuumasato commented
/test 4.13-e2e-aws-ocp4-cis
/test 4.14-e2e-aws-ocp4-cis
/test 4.15-e2e-aws-ocp4-cis
/test 4.16-e2e-aws-ocp4-cis

2024-05-16 08:13 UTC, yuumasato commented
/test 4.13-e2e-aws-ocp4-cis
/test 4.14-e2e-aws-ocp4-cis
/test 4.15-e2e-aws-ocp4-cis
/test 4.16-e2e-aws-ocp4-cis

2024-05-16 09:53 UTC, yuumasato approved these changes

2024-05-16 09:53 UTC, merged