Check ufw is active
ComplianceAsCode/content pull request #11984
Opened 2024-05-09 15:09 UTC by alanmcanonical

#### Description:

- Only check whether the ufw is active after ufw service is enable instead of configuring the ufw.

#### Rationale:

- Ensure ongoing compliance with remote access policies by checking the status of Uncomplicated Firewall (ufw)

2024-05-09 19:51 UTC, Mab879 commented
/packit retest-failed

2024-05-10 09:42 UTC, dodys requested changes
just a minor fix, and after discussing to @mpurg we agreed on adding this to 20.04 stig too, as it is clearly missing. Could you add it please?

2024-05-10 09:42 UTC, dodys commented on linux_os/guide/system/network/network-ufw/check_ufw_active/rule.yml
> +    <pre>$ sudo ufw enable</pre>
missing a new line.

2024-05-10 09:49 UTC, alanmcanonical commented on linux_os/guide/system/network/network-ufw/check_ufw_active/rule.yml
> +    <pre>$ sudo ufw enable</pre>
Fixed.

2024-05-14 07:54 UTC, dodys commented
/packit build

2024-05-14 09:07 UTC, dodys approved these changes
lgtm, thanks!

2024-05-14 09:08 UTC, merged