Review and reorganize CMakeLists.txt file
ComplianceAsCode/content pull request #12000
Opened 2024-05-16 10:55 UTC by marcusburghardt

#### Description:

This PR is improving the readability of `CMakeLists.txt` basically by:
- Grouping similar entries
- Organizing the output messages
- Reviewing comments

#### Rationale:

Improve readability of `CMakeLists.txt` file to make easier to work on it.

#### Review Hints:

Besides the readability of the file and some changes in the output, the test is basically building the products and confirming everything that it still working as expected.

2024-05-17 07:00 UTC, jan-cerny requested changes

2024-05-21 09:45 UTC, marcusburghardt commented on CMakeLists.txt
> -include(CPack)
Done. Thanks

2024-05-21 09:45 UTC, marcusburghardt commented on CMakeLists.txt
> +cmake_dependent_option(ENABLE_PYTHON_COVERAGE "Enable Python tests with coverage support" ON "PY_PYTEST_COV" OFF)
Done. Thanks

2024-05-21 11:30 UTC, jan-cerny commented
/packit retest-failed

2024-05-21 11:50 UTC, jan-cerny commented
/packit build

2024-05-22 06:58 UTC, jan-cerny commented
@marcusburghardt Please have a look into the failing test `testing-farm:centos-stream-8-x86_64:/static-checks`. I have rerun it but it failed again. The error message hints that it might be legitimate:

```
-- Find Python Modules:
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PY_jinja2 (missing: PY_JINJA2)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPythonModule.cmake:40 (find_package_handle_standard_args)
  CMakeLists.txt:150 (find_python_module)
```

2024-05-23 11:02 UTC, marcusburghardt commented
> @marcusburghardt Please have a look into the failing test `testing-farm:centos-stream-8-x86_64:/static-checks`. I have rerun it but it failed again. The error message hints that it might be legitimate:
> 
> ```
> -- Find Python Modules:
> CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
>   Could NOT find PY_jinja2 (missing: PY_JINJA2)
> Call Stack (most recent call first):
>   /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
>   cmake/FindPythonModule.cmake:40 (find_package_handle_standard_args)
>   CMakeLists.txt:150 (find_python_module)
> ```

I could not reproduce it locally. I need to investigate it more in a VM similar to CI tests. Moved to Draft for now.

2024-05-28 20:07 UTC, marcusburghardt commented
I believe the issue is now fixed in the last commit. Just waiting the CI tests to confirm.
More details in the commit message.

2024-05-30 08:08 UTC, merged