Improve Rsyslog rules to support Rainer script syntax
ComplianceAsCode/content pull request #12010
Opened 2024-05-20 15:48 UTC by jan-cerny

#### Description:
Improve OVAL checks so that the rule will pass if the modern Rainer script syntax is used. Up until now these rules passed only when the legacy configuration is used.

This changes OVAL in the following rules:

- rsyslog_cron_logging
- rsyslog_encrypt_offload_actionsendstreamdriverauthmode
- rsyslog_encrypt_offload_actionsendstreamdrivermode
- rsyslog_encrypt_offload_defaultnetstreamdriver

For more details, please read commit messages of all commits.

#### Rationale:
Fixes: https://issues.redhat.com/browse/RHEL-1816

2024-05-27 09:56 UTC, marcusburghardt requested changes
Besides the comments in specific files, the remediation for rule `rsyslog_cron_logging` is not working when the `/etc/rsyslog.conf` file is deleted, more specifically in the test scenario  `no_rsyslog_file.fail.sh`. After the remediation, the rsyslog service can't be started. This issue was not introduced by this PR, but was revealed now. Could you take a look on it, please?

2024-05-27 09:56 UTC, marcusburghardt commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdriverauthmode/oval/shared.xml
> +        <ind:pattern operation="pattern match">^\s*action\(.*(?i)\btype\b(?-i)="omfwd".*(?i)\bStreamDriverAuthMode\b(?-i)="x509/name".*\)\s*$</ind:pattern>
Could you also update the rule description for RainerScript syntax, please?

2024-05-27 09:56 UTC, marcusburghardt commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdriverauthmode/oval/shared.xml
> +        <ind:pattern operation="pattern match">^\s*action\(.*(?i)\btype\b(?-i)="omfwd".*(?i)\bStreamDriverAuthMode\b(?-i)="x509/name".*\)\s*$</ind:pattern>
Same regex already used before. Could you consider to create a variable, please?

2024-05-27 09:56 UTC, marcusburghardt commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdrivermode/oval/shared.xml
> +        <ind:pattern operation="pattern match">^\s*action\(.*(?i)\btype\b(?-i)="omfwd".*(?i)\bStreamDriverMode\b(?-i)="1".*\)\s*$</ind:pattern>
Same regex used before. Could you consider to create a variable, please?

2024-05-27 09:56 UTC, marcusburghardt commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_defaultnetstreamdriver/oval/shared.xml
> +        <ind:pattern operation="pattern match">^\s*global\(.*(?i)\bDefaultNetStreamDriver\b(?-i)="gtls".*\)\s*$</ind:pattern>
Could you also update the rule description, please?

2024-05-27 09:56 UTC, marcusburghardt commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_defaultnetstreamdriver/oval/shared.xml
> +        <ind:pattern operation="pattern match">^\s*global\(.*(?i)\bDefaultNetStreamDriver\b(?-i)="gtls".*\)\s*$</ind:pattern>
Same regex used twice. Could you consider to use a variable, please?

2024-05-27 15:51 UTC, jan-cerny commented
@marcusburghardt 

 > Besides the comments in specific files, the remediation for rule rsyslog_cron_logging is not working when the /etc/rsyslog.conf file is deleted, more specifically in the test scenario no_rsyslog_file.fail.sh. After the remediation, the rsyslog service can't be started. This issue was not introduced by this PR, but was revealed now. Could you take a look on it, please?

Isn't the test scenario `no_rsyslog_file.fail.sh` stupid? It completely deletes the configuration files. I don't know if we can expect that the remediation for the rule will restore the configuration file and configure all other options that aren't directly mentioned in the rule.

2024-05-28 06:35 UTC, marcusburghardt commented
> rsyslog_cron_logging

Yes, I agree this test scenario is very weak. It is fine to remove the files in `/etc/rsyslog.d` but is not fine to remove the whole `rsyslog.conf`. The test scenario `no_cron_logging.fail.sh` seems enough to me.

Perhaps, just to keep a test without rsyslog.d files, we could just rename the `no_rsyslog_file.fail.sh` to `no_rsyslog_d_files.fail.sh` with a content similar to this:

```
#!/bin/bash

rm -rf /etc/rsyslog.d
sed -i '/^[[:space:]]*cron\.\*/d' /etc/rsyslog.conf
```

2024-05-28 06:55 UTC, marcusburghardt requested changes
Thanks @jan-cerny . It is much better after using variables for regex. Nice!!
I only suggested some comments to align the name of this rsyslog syntax to the official documentation: RainerScript

Once we solve the test scenario issue I believe we are good to merge.

2024-05-28 06:55 UTC, marcusburghardt commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_cron_logging/oval/shared.xml
> +      <criterion comment="cron is configured in /etc/rsyslog.conf using Rainer script"
```suggestion
      <criterion comment="cron is configured in /etc/rsyslog.conf using RainerScript"
```

2024-05-28 06:55 UTC, marcusburghardt commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_cron_logging/oval/shared.xml
> +      <criterion comment="cron is configured in /etc/rsyslog.d using Rainer script"
```suggestion
      <criterion comment="cron is configured in /etc/rsyslog.d using RainerScript"
```

2024-05-28 06:55 UTC, marcusburghardt commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_cron_logging/oval/shared.xml
> +  comment="cron is configured in /etc/rsyslog.conf using Rainer script"
```suggestion
  comment="cron is configured in /etc/rsyslog.conf using RainerScript"
```

2024-05-28 06:55 UTC, marcusburghardt commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_cron_logging/oval/shared.xml
> +  comment="cron is configured in /etc/rsyslog.d using Rainer script"
```suggestion
  comment="cron is configured in /etc/rsyslog.d using RainerScript"
```

2024-05-28 06:55 UTC, marcusburghardt commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_cron_logging/rule.yml
> +    If the modern syntax (Rainer script) is used:
```suggestion
    If the modern syntax (RainerScript) is used:
```

2024-05-28 06:55 UTC, marcusburghardt commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdriverauthmode/oval/shared.xml
> +                <criterion comment="Check if StreamDriverAuthMode is set to x509/name in /etc/rsyslog.conf using Rainer script"
```suggestion
                <criterion comment="Check if StreamDriverAuthMode is set to x509/name in /etc/rsyslog.conf using RainerScript"
```

2024-05-28 06:55 UTC, marcusburghardt commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdriverauthmode/oval/shared.xml
> +                <criterion comment="Check if StreamDriverAuthMode is set to x509/name in files in /etc/rsyslog.d using Rainer script"
```suggestion
                <criterion comment="Check if StreamDriverAuthMode is set to x509/name in files in /etc/rsyslog.d using RainerScript"
```

2024-05-28 06:55 UTC, marcusburghardt commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdriverauthmode/oval/shared.xml
> +                                comment="Check if StreamDriverAuthMode is set to x509/name in /etc/rsyslog.conf using Rainer script"
```suggestion
                                comment="Check if StreamDriverAuthMode is set to x509/name in /etc/rsyslog.conf using RainerScript"
```

2024-05-28 06:55 UTC, marcusburghardt commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdriverauthmode/oval/shared.xml
> +                                    comment="Check if StreamDriverAuthMode is set to x509/name in /etc/rsyslog.conf using Rainer script"
```suggestion
                                    comment="Check if StreamDriverAuthMode is set to x509/name in /etc/rsyslog.conf using RainerScript"
```

2024-05-28 06:55 UTC, marcusburghardt commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdriverauthmode/oval/shared.xml
> +                                comment="Check if StreamDriverAuthMode is set to x509/name in files in /etc/rsyslog.d using Rainer script"
```suggestion
                                comment="Check if StreamDriverAuthMode is set to x509/name in files in /etc/rsyslog.d using RainerScript"
```

2024-05-28 06:55 UTC, marcusburghardt commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdriverauthmode/oval/shared.xml
> +                                    comment="Check if StreamDriverAuthMode is set to x509/name in files in /etc/rsyslog.d using Rainer script"
```suggestion
                                    comment="Check if StreamDriverAuthMode is set to x509/name in files in /etc/rsyslog.d using RainerScript"
```

2024-05-28 06:55 UTC, marcusburghardt commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdriverauthmode/rule.yml
> +    Alternatively, use the Rainer script syntax:
```suggestion
    Alternatively, use the RainerScript syntax:
```

2024-05-28 06:55 UTC, marcusburghardt commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdrivermode/oval/shared.xml
> +                <criterion comment="Check if StreamDriverMode is set to 1 in /etc/rsyslog.conf using Rainer script"
```suggestion
                <criterion comment="Check if StreamDriverMode is set to 1 in /etc/rsyslog.conf using RainerScript"
```

2024-05-28 06:55 UTC, marcusburghardt commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdrivermode/oval/shared.xml
> +                <criterion comment="Check if StreamDriverMode is set to 1 in files in /etc/rsyslog.d using Rainer script"
```suggestion
                <criterion comment="Check if StreamDriverMode is set to 1 in files in /etc/rsyslog.d using RainerScript"
```

2024-05-28 06:55 UTC, marcusburghardt commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdrivermode/oval/shared.xml
> +                                comment="Check if StreamDriverMode is set to 1 in /etc/rsyslog.conf using Rainer script"
```suggestion
                                comment="Check if StreamDriverMode is set to 1 in /etc/rsyslog.conf using RainerScript"
```

2024-05-28 06:55 UTC, marcusburghardt commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdrivermode/oval/shared.xml
> +                                    comment="Check if StreamDriverMode is set to 1 in /etc/rsyslog.conf using Rainer script"
```suggestion
                                    comment="Check if StreamDriverMode is set to 1 in /etc/rsyslog.conf using RainerScript"
```

2024-05-28 06:55 UTC, marcusburghardt commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdrivermode/oval/shared.xml
> +                                comment="Check if StreamDriverMode is set to 1 in files in /etc/rsyslog.d using Rainer script"
```suggestion
                                comment="Check if StreamDriverMode is set to 1 in files in /etc/rsyslog.d using RainerScript"
```

2024-05-28 06:55 UTC, marcusburghardt commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_actionsendstreamdrivermode/oval/shared.xml
> +                                    comment="Check if StreamDriverMode is set to 1 in files in /etc/rsyslog.d using Rainer script"
```suggestion
                                    comment="Check if StreamDriverMode is set to 1 in files in /etc/rsyslog.d using RainerScript"
```

2024-05-28 06:55 UTC, marcusburghardt commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_defaultnetstreamdriver/oval/shared.xml
> +                <criterion comment="Check if DefaultNetstreamDriver is set to gtls in /etc/rsyslog.conf using Rainer script"
```suggestion
                <criterion comment="Check if DefaultNetstreamDriver is set to gtls in /etc/rsyslog.conf using RainerScript"
```

2024-05-28 06:55 UTC, marcusburghardt commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_defaultnetstreamdriver/oval/shared.xml
> +                <criterion comment="Check if DefaultNetstreamDriver is set to gtls in files in /etc/rsyslog.d using Rainer script"
```suggestion
                <criterion comment="Check if DefaultNetstreamDriver is set to gtls in files in /etc/rsyslog.d using RainerScript"
```

2024-05-28 06:55 UTC, marcusburghardt commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_defaultnetstreamdriver/oval/shared.xml
> +                                comment="Check if DefaultNetstreamDriver is set to gtls in /etc/rsyslog.conf using Rainer script"
```suggestion
                                comment="Check if DefaultNetstreamDriver is set to gtls in /etc/rsyslog.conf using RainerScript"
```

2024-05-28 06:55 UTC, marcusburghardt commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_defaultnetstreamdriver/oval/shared.xml
> +                                    comment="Check if DefaultNetstreamDriver is set to gtls in /etc/rsyslog.conf using Rainer script"
```suggestion
                                    comment="Check if DefaultNetstreamDriver is set to gtls in /etc/rsyslog.conf using RainerScript"
```

2024-05-28 06:55 UTC, marcusburghardt commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_defaultnetstreamdriver/oval/shared.xml
> +                                comment="Check if DefaultNetstreamDriver is set to gtls in files in /etc/rsyslog.d using Rainer script"
```suggestion
                                comment="Check if DefaultNetstreamDriver is set to gtls in files in /etc/rsyslog.d using RainerScript"
```

2024-05-28 06:55 UTC, marcusburghardt commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_encrypt_offload_defaultnetstreamdriver/oval/shared.xml
> +                                    comment="Check if DefaultNetstreamDriver is set to gtls in files in /etc/rsyslog.d using Rainer script"
```suggestion
                                    comment="Check if DefaultNetstreamDriver is set to gtls in files in /etc/rsyslog.d using RainerScript"
```

2024-05-28 08:28 UTC, jan-cerny commented
/retest

2024-05-28 08:29 UTC, jan-cerny commented
I have changed and renamed the test scenario no_rsyslog_file.fail.sh. I have changed occurrences to RainerScript.

2024-05-28 19:06 UTC, marcusburghardt approved these changes
Nice work. Thanks

2024-05-28 19:07 UTC, merged