Add Ubuntu 22.04 Automatus workflow
ComplianceAsCode/content pull request #12058
Opened 2024-06-12 08:18 UTC by alanmcanonical

#### Description:

- Add Ubuntu 22.04 Automatus workflow

#### Rationale:

- Add this workflow so that we can build and test content on Ubuntu 22.04

2024-06-12 13:19 UTC, dodys commented
@marcusburghardt @Mab879 would it be ok to add the automatus workflow for ubuntu? And could you verify it is in order like the rest?

2024-06-12 19:46 UTC, Mab879 requested changes
Thanks for the PR.

I found a few things that need some attention.

2024-06-12 19:46 UTC, Mab879 commented on .github/workflows/automatus-ubuntu2204.yaml
> +          ADDITIONAL_TEST_OPTIONS: "--duplicate-templates --remove-fips-certified --product rhel8"
```suggestion
          ADDITIONAL_TEST_OPTIONS: "--duplicate-templates --remove-fips-certified"
```
This is a workaround for Fedora and RHEL

2024-06-18 15:38 UTC, Mab879 approved these changes
LGTM.

Thanks.

2024-06-18 15:38 UTC, merged