align template systemd_dropin_configuration
ComplianceAsCode/content pull request #12054
Opened 2024-06-10 11:40 UTC by vojtapolasek

#### Description:

- correct and simplify the bash remediation for the template
- modify test scenarios

#### Rationale:

- the Bash remediation was creating invalid configuration files because they were missing the "[Journal]" section.

- https://issues.redhat.com/browse/RHEL-38531

#### Review Hints:

- test the systemd_dropin_configuration template
- also test rules journald_compress and journald_storage

#### What remains to be done?

- documentation of the template
- align Ansible remediation of the template

2024-06-28 09:25 UTC, marcusburghardt requested changes
For Ansible remediation, I believe you can use a combination of `find` and `ini_file` modules. You can also use the macro `ansible_ini_file_set` in the Playbook or create a new macro.

2024-06-28 11:31 UTC, marcusburghardt commented on shared/templates/systemd_dropin_configuration/tests/wrong_master.fail.sh
>  VALUE="{{{ VALUE }}}"
`VALUE` is not used in this test scenario. Can be removed.

2024-07-08 13:38 UTC, vojtapolasek commented
@marcusburghardt  I updated the Ansible remediation.

2024-07-10 06:53 UTC, vojtapolasek commented
OK, it seems Jinja is not permitted to be used in "when" conditionals, I will modify the Ansible.

2024-07-12 09:02 UTC, marcusburghardt requested changes
I also tested the `journald_storage` rule locally and the remediation is failing with `wrong_master.fail.sh` test scenario. The cause is that the test scenario script duplicates the `section` and `parameter` in the file and the remediation can't deal with this. We should review if this test scenario script is incorrect or if this is a valid scenario that the remediation should deal with.

2024-07-12 11:45 UTC, vojtapolasek commented on shared/macros/10-bash.jinja
> +{{% macro bash_ensure_ini_config(files, section, key, value, no_quotes=true) -%}}
My idea behind this change was alignment with the OVAL check counterpart of this macro in the scope of systemd_dropin_configuration template; oval_check_dropin_file. This macro honors no_quotes. Therefore, I think the remediation should honor no_quotes as well. Moreover, the macro I modify here is more generic, it is an ini file check. There is no standard if values should be quoted or not (https://en.wikipedia.org/wiki/INI_file#Quoted_values).

2024-07-12 11:55 UTC, vojtapolasek commented on shared/templates/systemd_dropin_configuration/ansible.template
> +  loop: "{{systemd_dropin_files_with_section.results | sum(attribute='files', start=[]) | map(attribute='path') | list }}"
Why do you think so? I have just tested it by creating two files within the dropin directory, where one had a "[Journal]" section and the other one had a different section and the remediation was applied correctly. AFAIK the "files" dictionary contains only matches, not all files examined as documented here: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/find_module.html.
But I think the regex used to search for the section can be improved, that's true. I will do that.

2024-07-12 13:23 UTC, vojtapolasek commented on shared/templates/systemd_dropin_configuration/bash.template
> +    files=DROPIN_DIR+"/oscap-remedy.conf "+DROPIN_DIR+"/*.conf "+MASTER_CFG_FILE,
Fixed.

2024-07-12 13:25 UTC, vojtapolasek commented
@marcusburghardt  regarding the test which fails for you... What I did was that I modified test scenarios to overwrite the configuration file. I think this is standard.
I also inquired about the situation when there are multiple sections with the same name within one Systemd configuration file. This is valid, although probably not encouraged and I don't think we have to test for this case. Just fyi, sections with the same name are concatenated when interpreting the file.

2024-07-15 08:25 UTC, marcusburghardt commented on docs/templates/template_reference.md
> +    If none of inspected files contains the desired section a new file called oscap-remedy.conf within the dropin directory is created.
```suggestion
    If none of inspected files contains the desired section a new file called complianceascode_hardening.conf within the dropin directory is created.
```

2024-07-15 08:36 UTC, marcusburghardt commented on shared/macros/10-bash.jinja
> +{{% macro bash_ensure_ini_config(files, section, key, value, no_quotes=true) -%}}
It seems a good case for a new macro specific for systemd files, to treat the quotes and call the `systemd_dropin_configuration` macro. But I see your point regarding the alignment to OVAL.

The ideal approach, in my perspective, would be to remove this unnecessary parameter in the whole template and macros and treat these predictable cases within the macro. However this is not the scope of this PR, not a simple refactoring and can be done later.

2024-07-15 10:42 UTC, marcusburghardt approved these changes
I have tested all the rules using this template and everything is green. There is only an small update pending in the documentation, regarding the file name.

2024-07-16 06:53 UTC, marcusburghardt commented
/packit test

2024-07-16 07:37 UTC, marcusburghardt commented
The failing CI tests are optional and I confirmed the failures are not related to this PR so they can be safely waived in this specific PR.

2024-07-16 08:02 UTC, merged

2024-07-16 08:03 UTC, marcusburghardt commented on shared/macros/10-bash.jinja
> +{{% macro bash_ensure_ini_config(files, section, key, value, no_quotes=true) -%}}
@FYI @teacup-on-rockingchair

2024-07-17 06:44 UTC, teacup-on-rockingchair commented on shared/macros/10-bash.jinja
> +{{% macro bash_ensure_ini_config(files, section, key, value, no_quotes=true) -%}}
Thanks @marcusburghardt ,  see proposed change to `oval_check_dropin_file`  in #12173