Update ansible remediation  CCE-85972-8 to support idempotency
ComplianceAsCode/content pull request #12152
Opened 2024-07-12 12:43 UTC by namoyer10

#### Description:

- Add idempotency to the users_nopasswd compliance check for CCE-85972-8.

#### Rationale:

- Ansible should be able to run over and over again on systems and return 0 changes if nothing was actually modified on the target system. The current behavior will always return a changed value.

- Fixes: Added "changed_when" logic to only report a change if the returned stdout_lines is populated with results. If no results are returned, it will report as "ok".

#### Review Hints:

Result JSON from a run with this change:
```json
{"changed": false, "cmd": ["awk", "-F:", "!$2 {print $1}", "/etc/shadow"], "delta": "0:00:00.006307", "end": "2024-07-12 08:36:16.120933", "msg": "", "rc": 0, "start": "2024-07-12 08:36:16.114626", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```

2024-07-15 11:01 UTC, marcusburghardt requested changes
Actually this doesn't affect the task idempotency, but is good to not report "changed" in a task only intended to collect information. In this case, it would be even better to have `changed_when: false` instead.

2024-07-15 12:59 UTC, namoyer10 commented
> Actually this doesn't affect the task idempotency, but is good to not report "changed" in a task only intended to collect information. In this case, it would be even better to have `changed_when: false` instead.

Good morning,

My initial thought on this was to still have the information gathering check fail when changes are needed. This will allow for easier review of failed or changed tasks by downstream projects where the remediations are combined into a single, mono-playbook for hardening purposes such as the RHEL CUI repos. From my understanding, those playbooks use the ComplianceAsCode Framework for their hardening profiles and playbooks.

If you would still like the mentioned change, let me know. Just wanted to throw out my thoughts before making changes.

2024-07-15 13:56 UTC, marcusburghardt commented
> > Actually this doesn't affect the task idempotency, but is good to not report "changed" in a task only intended to collect information. In this case, it would be even better to have `changed_when: false` instead.
> 
> Good morning,
> 
> My initial thought on this was to still have the information gathering check show "changed" when changes are needed. This will allow for easier review of failed or changed tasks by downstream projects where the remediations are combined into a single, mono-playbook for hardening purposes such as the RHEL CUI repos. From my understanding, those playbooks use the ComplianceAsCode Framework for their hardening profiles and playbooks.
> 
> If you would still like the mentioned change, let me know. Just wanted to throw out my thoughts before making changes.

Yes, since the command is not actually changing anything, but just collecting information, `changed_when: false` is better for this task and also used many times in similar cases within the project. The subsequente task, actually changes something based on the information collected from the previous task, so it will still report the status properly (skipped or changed).

2024-07-16 07:17 UTC, marcusburghardt commented on linux_os/guide/system/accounts/accounts-restrictions/password_storage/no_empty_passwords_etc_shadow/ansible/shared.yml
> +  changed_when: users_nopasswd.stdout_lines | length > 0
```suggestion
  changed_when: false
```

2024-07-18 11:14 UTC, marcusburghardt approved these changes
Thanks for the contribution @namoyer10

2024-07-18 13:03 UTC, marcusburghardt commented
The `testing-farm:centos-stream-9-x86_64:/static-checks` is failure was already fixed by 
https://github.com/ComplianceAsCode/content/pull/12174 and is not related to this PR.

Considering this PR is simple, it is safe to waive this test and merge it without rebasing it.

2024-07-18 13:04 UTC, merged