Remove Debian 10 Product
ComplianceAsCode/content pull request #12205
Opened 2024-07-22 18:35 UTC by Mab879

#### Description:
Removal of Debian 10.

#### Rationale:
Closes #12111

2024-07-23 14:23 UTC, Mab879 commented
Once approved and before merging we will need to remove the Debian 10 build job requirement.

Once this is merged then we should add the Debian 12 requirement back.

2024-07-24 07:35 UTC, jan-cerny requested changes
Please remove DEBIAN10 from build_product line 357.

2024-07-24 07:36 UTC, jan-cerny commented
I have removed the Debian 10 branch build job requirement.

2024-07-24 15:12 UTC, jan-cerny approved these changes

2024-07-24 16:22 UTC, merged