Clarify stabilization dates process for more predictability
ComplianceAsCode/content pull request #12232
Opened 2024-07-29 14:08 UTC by marcusburghardt

#### Description:

The `10_stabilization_phase.md` file is also referenced in [release_process.md](https://github.com/ComplianceAsCode/content/blob/master/docs/release_process.md#stabilization-phase) documentation.

#### Rationale:

Document agreement on a process to define the start of stabilization phase and consequently the releases.
This brings more predictability for the project releases.

#### Review Hints:

Just documentation.

2024-07-29 14:22 UTC, Mab879 approved these changes
Thanks!

2024-07-29 14:22 UTC, Mab879 requested changes

2024-07-29 14:22 UTC, Mab879 commented on docs/manual/developer/10_stabilization_phase.md
> +Stabilization Phase starts on last Monday of the first month of the quarter.
```suggestion
Stabilization Phase starts on the last Monday of the first month of the quarter.
```

2024-07-29 14:29 UTC, Mab879 approved these changes

2024-07-29 14:31 UTC, Mab879 commented
/test 4.13-images

2024-07-29 14:39 UTC, jan-cerny commented
Can you update the Duration section as well? It still talks about 2 month cadence but we have switched to quarterly releases.

2024-07-30 07:23 UTC, marcusburghardt commented
> Can you update the Duration section as well? It still talks about 2 month cadence but we have switched to quarterly releases.

Sure. I thought this part was already updated in the past. Let me check.

2024-07-30 07:41 UTC, marcusburghardt commented
> > Can you update the Duration section as well? It still talks about 2 month cadence but we have switched to quarterly releases.
> 
> Sure. I thought this part was already updated in the past. Let me check.

Done.

2024-07-30 12:29 UTC, merged