add kylin OS support
ComplianceAsCode/content pull request #12271
Opened 2024-08-06 09:48 UTC by shiryu-zhao

#### Description:

-OpenScap is a well-known security configuration baseline scanning organization in the industry. The tools provided by OpenScap provide security scanning functions for most operating systems around the world. KylinSoft also hopes to join the OpenScap family and use the powerful functions of OpenScap to complete and provide security configuration baseline scanning capabilities.

-KylinSoft is  one of the key operation system vendors in China, and Kylin Linux Advanced Server V10 is one of KylinSoft's important products, which is a robust, secure, and high-performance operating systems tailored to meet the needs of both government and enterprise users. You can learn more about in the website: https://kylinos.cn.

-In the future, the PR on openscap will be maintained and updated by members of our security technology department. 

#### Rationale:

- This PR is to build the kylin-related support framework.

#### Review Hints:

- Please review it and any feedback is my appreciate.

2024-08-06 15:08 UTC, Mab879 requested changes
Thanks for the PR. 

Do you plan on keeping this product up-to-date?

2024-08-07 06:11 UTC, shiryu-zhao commented on products/kylin/product.yml
> +pkg_manager: "dnf"
Firstly, thanks very much for your help and concern for the pr that I submitted, I will fix the issue that you mentioned above. 
Secondly, Kylin V10 is a RPM based distro, but I can not find any conflicting information.so I want to ask you for help ,please give me some tips on fixing this problem.Thank you very much!

2024-08-07 18:21 UTC, Mab879 commented on products/kylin/product.yml
> +pkg_manager: "dnf"
Your confirmation is all I need.

2024-08-08 09:35 UTC, dodys requested changes
@shiryu-zhao do not merge master into your development branch, do a rebase instead

2024-08-08 10:05 UTC, closed without merging