Slmicro5 stig add permissions audit rules support
ComplianceAsCode/content pull request #12286
Opened 2024-08-09 13:48 UTC by svet-se

#### Description:

- _Add permissions and audit rules to SLE Micro 5 STIG profile_

#### Rationale:

- _According to DISA SLE Micro 5 STIG Version 1, Release: 1 Benchmark Date: 13 Jun 2024_

2024-08-12 14:30 UTC, jan-cerny requested changes

2024-08-12 14:30 UTC, jan-cerny commented on linux_os/guide/system/software/integrity/certified-vendor/installed_OS_is_FIPS_certified/oval/shared.xml
> +      <extend_definition comment="Installed OS is SLE Mirco 5" definition_ref="installed_OS_is_slmicro5" />
s/Mirco/Micro/

2024-08-12 14:41 UTC, svet-se commented on linux_os/guide/system/software/integrity/certified-vendor/installed_OS_is_FIPS_certified/oval/shared.xml
> +      <extend_definition comment="Installed OS is SLE Mirco 5" definition_ref="installed_OS_is_slmicro5" />
Thanks @jan-cerny!

2024-08-13 06:47 UTC, jan-cerny commented
/packit build

2024-08-13 07:40 UTC, jan-cerny approved these changes

2024-08-13 07:40 UTC, merged