Skip users with ID above UID MAX on accounts_user_interactive_home_directory_defined
ComplianceAsCode/content pull request #12527
Opened 2024-10-22 21:23 UTC by Mab879

#### Description:
To skip systemd dynamic users.
Since accounts_user_interactive_home_directory_defined only works on local users this should be fine.

Since bash remediation accesses `/etc/passwd` directly and the systemd dynamic users do not show up in that file, the bash remediation was not updated.

#### Rationale:
Fix Ansible playbook failures.

2024-10-23 14:35 UTC, jan-cerny approved these changes

2024-10-25 16:41 UTC, Xeicker approved these changes
changes LGTM

2024-10-30 12:51 UTC, vojtapolasek requested changes
Nice catch with the whole dynamic uid range. But I think this needs to be fixed.

2024-10-30 12:51 UTC, vojtapolasek commented on linux_os/guide/system/accounts/accounts-session/accounts_user_interactive_home_directory_defined/ansible/shared.yml
> +    - item.value[2]|int < {{{ dynamic_uid_min }}} or item.value[2]|int > {{{ dynamic_uid_min }}}
```suggestion
    - item.value[2]|int < {{{ dynamic_uid_min }}} or item.value[2]|int > {{{ dynamic_uid_max }}}
```

2024-11-01 18:04 UTC, Mab879 commented
/packit build

2024-11-04 14:34 UTC, vojtapolasek commented
@Mab879  There is a failing Automatus test on SLE which seems valid.

2024-11-04 18:43 UTC, Mab879 commented
> @Mab879 There is a failing Automatus test on SLE which seems valid.

This isn't a new issue, it is also failing on master.

At least testing with OpenSUSE.

2024-11-05 11:52 UTC, vojtapolasek approved these changes

2024-11-05 11:53 UTC, vojtapolasek commented
OK @Mab879  merging. Thank you.

2024-11-05 11:56 UTC, vojtapolasek commented
/packit retest-failed

2024-11-05 15:03 UTC, merged