Defined notes for BSI SYS.1.6.A17
ComplianceAsCode/content pull request #12530
Opened 2024-10-23 09:51 UTC by lichtblaugue

#### Description:

Added notes and controls for BSI SYS.1.6 A17

#### Rationale:

As we have multiple customers asking for a BSI profile to be included in the compliance-operator, we are contributing a profile. To provide a better review process, the individual controle are implemented as separate PRs.

2024-10-28 20:30 UTC, sluetze commented on applications/openshift/general/sandboxed_containers_operator_configured/rule.yml
please do not add the same content, which is already existing in other PRs / commits. just rebase on that branch or wait until the other branch is merged

2024-11-28 20:30 UTC, yuumasato commented
/ok-to-test

2024-11-28 20:30 UTC, yuumasato commented
/test 4.17-e2e-aws-ocp4-bsi
/test 4.17-e2e-aws-ocp4-bsi-node
/test 4.17-e2e-aws-rhcos4-bsi

2024-11-29 14:02 UTC, yuumasato requested changes

2024-11-29 15:15 UTC, sluetze commented on applications/openshift/general/sandboxed_containers_operator_configured/tests/ocp4/e2e-remediation.sh
> +oc wait --for=condition=Updated --timeout=3600s machineconfigpool/kata-oc
Hi @yuumasato ,

this PR should not include https://github.com/ComplianceAsCode/content/pull/12530/files/8e36b6428e1e65122ec3aa8b1cac0284c06c1ad1..14ae93f598e984653248f96215f068f6f746d2e4

as this is done in https://github.com/ComplianceAsCode/content/pull/12494

I will help @lichtblaugue to remove this commits from the PR and consider your comment in the pull/12494

2024-12-03 08:57 UTC, lichtblaugue commented
Closing in favor of 
https://github.com/ComplianceAsCode/content/pull/12663

2024-12-03 08:57 UTC, closed without merging