update audit_ospp_general with the latest content
ComplianceAsCode/content pull request #12579
Opened 2024-11-06 12:12 UTC by vojtapolasek

#### Description:

- update content of audit_ospp_general and its arch specific variants from the latest content packaged in RHEL 9
- I updated rules also for RHEL 8. According to Audit SME, rules should work fine on RHEL 8 as well.

#### Rationale:

- so that end users have the latest content

- Fixes #12321 

#### Review Hints:

- compare file contents present in audit_ospp_general (or arch-specific variants) with content present in the file 30-ospp-v42.rules shipped in latest RHEL.

2024-11-06 19:01 UTC, Mab879 requested changes
Please ensure that `uid_min` is used vs `1000` in the content.

2024-11-07 16:05 UTC, vojtapolasek commented
@Mab879  Good catch, I think I fixed it.

2024-11-07 16:46 UTC, Mab879 commented on linux_os/guide/auditing/policy_rules/audit_ospp_general/rule.yml
> --a always,exit -F arch=b64 -S openat,open_by_handle_at -F a2&amp;03 -F path=/etc/passwd -F auid&gt;=" ~ uid_min ~ " -F auid!=unset -F key=user-modify
Should we keep the escape `>`?

2024-11-08 07:47 UTC, vojtapolasek commented
I thought we need to escape the ">" character, but then I noticed that in the ppc64le version of the rule it is not escaped and it works as expected... so I think we don't need it.

2024-11-08 14:09 UTC, Mab879 approved these changes
Thanks!

2024-11-08 14:53 UTC, merged