Ubuntu 24.04: Implement rule 5.3.3.2.4 Ensure password same consecutive characters is configured
ComplianceAsCode/content pull request #12747
Opened 2024-12-19 10:52 UTC by alanmcanonical

#### Description:

- Implement rule 5.3.3.2.4 Ensure password same consecutive characters is configured

#### Rationale:

- Satisfies Ubuntu 24.04 CIS control 5.3.3.2.4

2024-12-19 11:35 UTC, dodys requested changes

2024-12-19 11:35 UTC, dodys commented on controls/cis_ubuntu2404.yml
> +      - var_password_pam_maxrepeat=3
wrong place

2024-12-19 14:43 UTC, alanmcanonical commented on controls/cis_ubuntu2404.yml
> +      - var_password_pam_maxrepeat=3
Done

2024-12-20 10:48 UTC, dodys approved these changes
lgtm, thanks!

2024-12-20 10:48 UTC, merged