Ubuntu 24.04 5.3.3.4.4 Ensure pam_unix includes use_authtok
ComplianceAsCode/content pull request #12760
Opened 2024-12-21 00:18 UTC by ericeberry

#### Description:

- Ubuntu 24.04 5.3.3.4.4 Ensure pam_unix includes use_authtok

#### Rationale:

- Implement Ubuntu 24.04 5.3.3.4.4 Ensure pam_unix includes use_authtok

2025-01-08 07:36 UTC, mpurg approved these changes
Lgtm

2025-01-08 07:36 UTC, mpurg commented on shared/macros/10-bash.jinja
> -            sed -i '/Default: yes/a Priority: 257\
This change is a fix for all rules using the `bash_pam_unix_enable` macro. Please add a note to the description.

2025-01-08 09:27 UTC, dodys approved these changes
lgtm, thanks!

2025-01-08 10:19 UTC, dodys requested changes
the ctests are failing, could you please take a look?

2025-01-10 14:40 UTC, mpurg commented
@dodys ctest issue was fixed in #12796

2025-01-10 15:56 UTC, mpurg commented
@ericeberry One of the tests is failing, can you look into it please? https://github.com/ComplianceAsCode/content/actions/runs/12660335702/job/35281436920?pr=12760

2025-01-10 18:53 UTC, ericeberry commented
> @ericeberry One of the tests is failing, can you look into it please? https://github.com/ComplianceAsCode/content/actions/runs/12660335702/job/35281436920?pr=12760

Yes. I am working on that one.

2025-01-13 10:56 UTC, mpurg requested changes
OVAL needs a fix

2025-01-13 10:56 UTC, mpurg commented on linux_os/guide/system/accounts/accounts-pam/locking_out_password_attempts/accounts_password_pam_unix_authtok/oval/shared.xml
> +    <ind:pattern operation="pattern match">^[ \t]*password[ \t]+([^#\n\r]+)[ \t]+pam_unix\.so[ \t]+([^#\n\r]+[ \t]+)?use_authtok.*$</ind:pattern>
This check needs to be adjusted. The CIS rule states that the `use_authok` keyword should _not_ be added to the `Password-Initial` section. Omitting Password-Initial means that the keyword will be added to `/etc/pam.d/common-password` only when the `password.*pam_unix.so` line is _not_ the first on the stack. 

This is the reason why the test is failing after remediation on the container.
The primary block in /etc/pam.d/common-password contains only this on the default container install:
```
# here are the per-package modules (the "Primary" block)
password        [success=1 default=ignore]      pam_unix.so obscure yescrypt
```
On the VM it looks like this:
```
# here are the per-package modules (the "Primary" block)
password        requisite                       pam_pwquality.so retry=3
password        [success=2 default=ignore]      pam_unix.so obscure use_authtok try_first_pass yescrypt
password        sufficient                      pam_sss.so use_authtok
```

The test should check if there exists a preceding line that starts with `password`.

2025-01-16 17:13 UTC, dodys approved these changes
lgtm, thanks!

2025-01-17 09:26 UTC, merged