Introduced macros for working with XCCDF values into the wide content.
ComplianceAsCode/content pull request #6048
Opened 2020-09-04 11:44 UTC by matejak

Those macros always were there, and this PR makes sure that they are used, so they make the content less cryptic, and they navigate content authors that create new content based on the existing one.

2020-09-04 11:53 UTC, mildas commented
**Changes identified:**
Rule postfix_client_configure_mail_alias:
 Found change in bash remediation.
Rule postfix_network_listening_disabled:
 Templatization usage changed.
Rule chronyd_or_ntpd_set_maxpoll:
 Found change in bash remediation.
Rule chronyd_or_ntpd_specify_multiple_servers:
 Found change in bash remediation.
Rule chronyd_or_ntpd_specify_remote_server:
 Found change in bash remediation.
Rule chronyd_specify_remote_server:
 Ansible remediation changed.
 Found change in bash remediation.
Rule firewalld_sshd_port_enabled:
 Ansible remediation changed.
Rule sshd_disable_compression:
 Found change in bash remediation.
Rule sshd_set_idle_timeout:
 Templatization usage changed.
 Found change in bash remediation.
Rule sshd_set_keepalive:
 Templatization usage changed.
 Found change in bash remediation.
Rule sshd_set_max_auth_tries:
 Templatization usage changed.
 Found change in bash remediation.
Rule sshd_set_max_sessions:
 Templatization usage changed.
 Found change in bash remediation.
Rule sshd_use_approved_ciphers:
 Templatization usage changed.
 Found change in bash remediation.
Rule sshd_use_approved_macs:
 Templatization usage changed.
 Found change in bash remediation.
Rule sshd_use_priv_separation:
 Found change in bash remediation.
Rule sssd_ldap_configure_tls_ca_dir:
 Ansible remediation changed.
 Found change in bash remediation.
Rule sssd_memcache_timeout:
 Ansible remediation changed.
 Found change in bash remediation.
Rule sssd_ssh_known_hosts_timeout:
 Ansible remediation changed.
 Found change in bash remediation.
Rule banner_etc_issue:
 Ansible remediation changed.
 Found change in bash remediation.
Rule banner_etc_motd:
 Ansible remediation changed.
 Found change in bash remediation.
Rule dconf_gnome_login_banner_text:
 Ansible remediation changed.
 Found change in bash remediation.
Rule rhel6:
 The rule doesn't occur in any profile nor product.
 Found change in bash remediation.
Rule accounts_password_pam_unix_remember:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_passwords_pam_faillock_deny:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_passwords_pam_faillock_interval:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_passwords_pam_faillock_unlock_time:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_password_pam_retry:
 Ansible remediation changed.
 Found change in bash remediation.
Rule configure_opensc_card_drivers:
 Ansible remediation changed.
 Found change in bash remediation.
Rule force_opensc_card_drivers:
 Ansible remediation changed.
 Found change in bash remediation.
Rule account_disable_post_pw_expiration:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_maximum_age_login_defs:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_minimum_age_login_defs:
 Ansible remediation changed.
 Found change in bash remediation.
Rule fedora:
 The rule doesn't occur in any profile nor product.
 Found change in bash remediation.
Rule accounts_password_minlen_login_defs:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_password_warn_age_login_defs:
 Ansible remediation changed.
 Found change in bash remediation.
Rule wrlinux:
 The rule doesn't occur in any profile nor product.
 Found change in bash remediation.
Rule accounts_logon_fail_delay:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_max_concurrent_login_sessions:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_tmout:
 Templatization usage changed.
 Found change in bash remediation.
Rule accounts_umask_etc_bashrc:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_umask_etc_csh_cshrc:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_umask_etc_login_defs:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_umask_etc_profile:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_audispd_configure_remote_server:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_data_disk_error_action:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_data_disk_full_action:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_data_retention_action_mail_acct:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_data_retention_admin_space_left_action:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_data_retention_flush:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_data_retention_max_log_file:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_data_retention_max_log_file_action:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_data_retention_num_logs:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_data_retention_space_left:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_data_retention_space_left_action:
 Ansible remediation changed.
 Found change in bash remediation.
Rule rsyslog_remote_loghost:
 Ansible remediation changed.
 Found change in bash remediation.
Rule configure_firewalld_ports:
 Found change in bash remediation.
Rule umask_for_daemons:
 Found change in bash remediation.
Rule selinux_policytype:
 Found change in bash remediation.
Rule selinux_state:
 Found change in bash remediation.
Rule dconf_gnome_screensaver_idle_delay:
 Ansible remediation changed.
 Found change in bash remediation.
Rule dconf_gnome_screensaver_lock_delay:
 Found change in bash remediation.
Rule configure_crypto_policy:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_authorized_local_users:
 The rule doesn't occur in any profile nor product.
 Found change in bash remediation.
Rule accounts_authorized_local_users_sidadm_orasid:
 Found change in bash remediation.
Macro openshift_cluster_setting:
 
Macro sub_var_value:
 
Macro xccdf_value:
 

**Recommended tests to execute:**
 build_product ol8
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ol8-ds.xml chronyd_or_ntpd_specify_multiple_servers
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ol8-ds.xml chronyd_or_ntpd_specify_remote_server
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-ol8-ds.xml firewalld_sshd_port_enabled
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ol8-ds.xml sshd_disable_compression
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-ol8-ds.xml sshd_set_idle_timeout
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ol8-ds.xml sshd_set_idle_timeout
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-ol8-ds.xml sshd_set_keepalive
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ol8-ds.xml sshd_set_keepalive
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ol8-ds.xml sshd_use_priv_separation
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-ol8-ds.xml accounts_password_pam_unix_remember
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ol8-ds.xml accounts_password_pam_unix_remember
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build [...]

2020-09-04 12:14 UTC, mildas commented
**Changes identified:**
Rule postfix_client_configure_mail_alias:
 Found change in bash remediation.
Rule postfix_network_listening_disabled:
 Ansible remediation changed.
Rule chronyd_or_ntpd_set_maxpoll:
 Found change in bash remediation.
Rule chronyd_or_ntpd_specify_multiple_servers:
 Found change in bash remediation.
Rule chronyd_or_ntpd_specify_remote_server:
 Found change in bash remediation.
Rule chronyd_specify_remote_server:
 Found change in bash remediation.
 Ansible remediation changed.
Rule firewalld_sshd_port_enabled:
 Ansible remediation changed.
Rule sshd_disable_compression:
 Found change in bash remediation.
Rule sshd_set_idle_timeout:
 Found change in bash remediation.
 Templatization usage changed.
Rule sshd_set_keepalive:
 Found change in bash remediation.
 Templatization usage changed.
Rule sshd_set_max_auth_tries:
 Found change in bash remediation.
 Templatization usage changed.
Rule sshd_set_max_sessions:
 Found change in bash remediation.
 Templatization usage changed.
Rule sshd_use_approved_ciphers:
 Found change in bash remediation.
 Templatization usage changed.
Rule sshd_use_approved_macs:
 Found change in bash remediation.
 Templatization usage changed.
Rule sshd_use_priv_separation:
 Found change in bash remediation.
Rule sssd_ldap_configure_tls_ca_dir:
 Found change in bash remediation.
 Ansible remediation changed.
Rule sssd_memcache_timeout:
 Found change in bash remediation.
 Ansible remediation changed.
Rule sssd_ssh_known_hosts_timeout:
 Found change in bash remediation.
 Ansible remediation changed.
Rule banner_etc_issue:
 Found change in bash remediation.
 Ansible remediation changed.
Rule banner_etc_motd:
 Found change in bash remediation.
 Ansible remediation changed.
Rule dconf_gnome_login_banner_text:
 Found change in bash remediation.
 Ansible remediation changed.
Rule rhel6:
 Found change in bash remediation.
 The rule doesn't occur in any profile nor product.
Rule accounts_password_pam_unix_remember:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_passwords_pam_faillock_deny:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_passwords_pam_faillock_interval:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_passwords_pam_faillock_unlock_time:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_password_pam_retry:
 Found change in bash remediation.
 Ansible remediation changed.
Rule configure_opensc_card_drivers:
 Found change in bash remediation.
 Ansible remediation changed.
Rule force_opensc_card_drivers:
 Found change in bash remediation.
 Ansible remediation changed.
Rule account_disable_post_pw_expiration:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_maximum_age_login_defs:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_minimum_age_login_defs:
 Found change in bash remediation.
 Ansible remediation changed.
Rule fedora:
 Found change in bash remediation.
 The rule doesn't occur in any profile nor product.
Rule accounts_password_minlen_login_defs:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_password_warn_age_login_defs:
 Found change in bash remediation.
 Ansible remediation changed.
Rule wrlinux:
 Found change in bash remediation.
 The rule doesn't occur in any profile nor product.
Rule accounts_logon_fail_delay:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_max_concurrent_login_sessions:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_tmout:
 Found change in bash remediation.
 Templatization usage changed.
Rule accounts_umask_etc_bashrc:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_umask_etc_csh_cshrc:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_umask_etc_login_defs:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_umask_etc_profile:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_audispd_configure_remote_server:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_data_disk_error_action:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_data_disk_full_action:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_data_retention_action_mail_acct:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_data_retention_admin_space_left_action:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_data_retention_flush:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_data_retention_max_log_file:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_data_retention_max_log_file_action:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_data_retention_num_logs:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_data_retention_space_left:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_data_retention_space_left_action:
 Found change in bash remediation.
 Ansible remediation changed.
Rule rsyslog_remote_loghost:
 Found change in bash remediation.
 Ansible remediation changed.
Rule configure_firewalld_ports:
 Found change in bash remediation.
Rule umask_for_daemons:
 Found change in bash remediation.
Rule selinux_policytype:
 Found change in bash remediation.
Rule selinux_state:
 Found change in bash remediation.
Rule dconf_gnome_screensaver_idle_delay:
 Found change in bash remediation.
 Ansible remediation changed.
Rule dconf_gnome_screensaver_lock_delay:
 Found change in bash remediation.
Rule configure_crypto_policy:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_authorized_local_users:
 Found change in bash remediation.
 The rule doesn't occur in any profile nor product.
Rule accounts_authorized_local_users_sidadm_orasid:
 Found change in bash remediation.
Macro openshift_cluster_setting:
 
Macro sub_var_value:
 
Macro xccdf_value:
 

**Recommended tests to execute:**
 build_product rhel7
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-rhel7-ds.xml chronyd_specify_remote_server
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel7-ds.xml chronyd_specify_remote_server
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-rhel7-ds.xml sshd_set_max_auth_tries
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel7-ds.xml sshd_set_max_auth_tries
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-rhel7-ds.xml sssd_memcache_timeout
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel7-ds.xml sssd_memcache_timeout
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-rhel7-ds.xml sssd_ssh_known_hosts_timeout
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel7-ds.xml sssd_ssh_known_hosts_timeout
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-rhel7-ds.xml banner_etc_motd
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel7-ds.xml banner_etc_motd
 build_product rhcos4
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-rhcos4-ds.xml auditd_data_disk_error_action
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datast [...]

2020-09-07 09:02 UTC, yuumasato reviewed
LGTM

2020-09-07 11:12 UTC, mildas commented
**Changes identified:**
Rule postfix_client_configure_mail_alias:
 Found change in bash remediation.
Rule postfix_network_listening_disabled:
 Ansible remediation changed.
Rule chronyd_or_ntpd_set_maxpoll:
 Found change in bash remediation.
Rule chronyd_or_ntpd_specify_multiple_servers:
 Found change in bash remediation.
Rule chronyd_or_ntpd_specify_remote_server:
 Found change in bash remediation.
Rule chronyd_specify_remote_server:
 Ansible remediation changed.
 Found change in bash remediation.
Rule firewalld_sshd_port_enabled:
 Ansible remediation changed.
Rule sshd_disable_compression:
 Found change in bash remediation.
Rule sshd_set_idle_timeout:
 Found change in bash remediation.
 Templatization usage changed.
Rule sshd_set_keepalive:
 Found change in bash remediation.
 Templatization usage changed.
Rule sshd_set_max_auth_tries:
 Found change in bash remediation.
 Templatization usage changed.
Rule sshd_set_max_sessions:
 Found change in bash remediation.
 Templatization usage changed.
Rule sshd_use_approved_ciphers:
 Found change in bash remediation.
 Templatization usage changed.
Rule sshd_use_approved_macs:
 Found change in bash remediation.
 Templatization usage changed.
Rule sshd_use_priv_separation:
 Found change in bash remediation.
Rule sssd_ldap_configure_tls_ca_dir:
 Ansible remediation changed.
 Found change in bash remediation.
Rule sssd_memcache_timeout:
 Ansible remediation changed.
 Found change in bash remediation.
Rule sssd_ssh_known_hosts_timeout:
 Ansible remediation changed.
 Found change in bash remediation.
Rule banner_etc_issue:
 Ansible remediation changed.
 Found change in bash remediation.
Rule banner_etc_motd:
 Ansible remediation changed.
 Found change in bash remediation.
Rule dconf_gnome_login_banner_text:
 Ansible remediation changed.
 Found change in bash remediation.
Rule rhel6:
 Found change in bash remediation.
 The rule doesn't occur in any profile nor product.
Rule accounts_password_pam_unix_remember:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_passwords_pam_faillock_deny:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_passwords_pam_faillock_interval:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_passwords_pam_faillock_unlock_time:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_password_pam_retry:
 Ansible remediation changed.
 Found change in bash remediation.
Rule configure_opensc_card_drivers:
 Ansible remediation changed.
 Found change in bash remediation.
Rule force_opensc_card_drivers:
 Ansible remediation changed.
 Found change in bash remediation.
Rule account_disable_post_pw_expiration:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_maximum_age_login_defs:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_minimum_age_login_defs:
 Ansible remediation changed.
 Found change in bash remediation.
Rule fedora:
 Found change in bash remediation.
 The rule doesn't occur in any profile nor product.
Rule accounts_password_minlen_login_defs:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_password_warn_age_login_defs:
 Ansible remediation changed.
 Found change in bash remediation.
Rule wrlinux:
 Found change in bash remediation.
 The rule doesn't occur in any profile nor product.
Rule accounts_logon_fail_delay:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_max_concurrent_login_sessions:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_tmout:
 Found change in bash remediation.
 Templatization usage changed.
Rule accounts_umask_etc_bashrc:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_umask_etc_csh_cshrc:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_umask_etc_login_defs:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_umask_etc_profile:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_audispd_configure_remote_server:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_data_disk_error_action:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_data_disk_full_action:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_data_retention_action_mail_acct:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_data_retention_admin_space_left_action:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_data_retention_flush:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_data_retention_max_log_file:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_data_retention_max_log_file_action:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_data_retention_num_logs:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_data_retention_space_left:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_data_retention_space_left_action:
 Ansible remediation changed.
 Found change in bash remediation.
Rule rsyslog_remote_loghost:
 Ansible remediation changed.
 Found change in bash remediation.
Rule configure_firewalld_ports:
 Found change in bash remediation.
Rule umask_for_daemons:
 Found change in bash remediation.
Rule selinux_policytype:
 Found change in bash remediation.
Rule selinux_state:
 Found change in bash remediation.
Rule dconf_gnome_screensaver_idle_delay:
 Ansible remediation changed.
 Found change in bash remediation.
Rule dconf_gnome_screensaver_lock_delay:
 Found change in bash remediation.
Rule configure_crypto_policy:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_authorized_local_users:
 Found change in bash remediation.
 The rule doesn't occur in any profile nor product.
Rule accounts_authorized_local_users_sidadm_orasid:
 Found change in bash remediation.
Macro openshift_cluster_setting:
 
Macro sub_var_value:
 
Macro xccdf_value:
 

**Recommended tests to execute:**
 build_product sle15
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-sle15-ds.xml sshd_set_max_sessions
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-sle15-ds.xml sshd_set_max_sessions
 build_product rhel7
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-rhel7-ds.xml postfix_network_listening_disabled
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-rhel7-ds.xml chronyd_specify_remote_server
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel7-ds.xml chronyd_specify_remote_server
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-rhel7-ds.xml sssd_memcache_timeout
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel7-ds.xml sssd_memcache_timeout
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-rhel7-ds.xml sssd_ssh_known_hosts_timeout
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel7-ds.xml sssd_ssh_known_hosts_timeout
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-rhel7-ds.xml banner_etc_motd
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel7-ds.xml banner_etc_motd
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --data [...]

2020-09-08 12:39 UTC, mildas commented
**Changes identified:**
Rule postfix_client_configure_mail_alias:
 Found change in bash remediation.
Rule postfix_network_listening_disabled:
 Ansible remediation changed.
Rule chronyd_or_ntpd_set_maxpoll:
 Found change in bash remediation.
Rule chronyd_or_ntpd_specify_multiple_servers:
 Found change in bash remediation.
Rule chronyd_or_ntpd_specify_remote_server:
 Found change in bash remediation.
Rule chronyd_specify_remote_server:
 Found change in bash remediation.
 Ansible remediation changed.
Rule firewalld_sshd_port_enabled:
 Ansible remediation changed.
Rule sshd_disable_compression:
 Found change in bash remediation.
Rule sshd_set_idle_timeout:
 Found change in bash remediation.
 Templatization usage changed.
Rule sshd_set_keepalive:
 Found change in bash remediation.
 Templatization usage changed.
Rule sshd_set_max_auth_tries:
 Found change in bash remediation.
 Templatization usage changed.
Rule sshd_set_max_sessions:
 Found change in bash remediation.
 Templatization usage changed.
Rule sshd_use_approved_ciphers:
 Found change in bash remediation.
 Templatization usage changed.
Rule sshd_use_approved_macs:
 Found change in bash remediation.
 Templatization usage changed.
Rule sshd_use_priv_separation:
 Found change in bash remediation.
Rule sssd_memcache_timeout:
 Found change in bash remediation.
 Ansible remediation changed.
Rule sssd_ssh_known_hosts_timeout:
 Found change in bash remediation.
 Ansible remediation changed.
Rule banner_etc_issue:
 Found change in bash remediation.
 Ansible remediation changed.
Rule banner_etc_motd:
 Found change in bash remediation.
 Ansible remediation changed.
Rule dconf_gnome_login_banner_text:
 Found change in bash remediation.
 Ansible remediation changed.
Rule rhel6:
 Found change in bash remediation.
 The rule doesn't occur in any profile nor product.
Rule accounts_password_pam_unix_remember:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_passwords_pam_faillock_deny:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_passwords_pam_faillock_interval:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_passwords_pam_faillock_unlock_time:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_password_pam_retry:
 Found change in bash remediation.
 Ansible remediation changed.
Rule configure_opensc_card_drivers:
 Found change in bash remediation.
 Ansible remediation changed.
Rule force_opensc_card_drivers:
 Found change in bash remediation.
 Ansible remediation changed.
Rule account_disable_post_pw_expiration:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_maximum_age_login_defs:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_minimum_age_login_defs:
 Found change in bash remediation.
 Ansible remediation changed.
Rule fedora:
 Found change in bash remediation.
 The rule doesn't occur in any profile nor product.
Rule accounts_password_minlen_login_defs:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_password_warn_age_login_defs:
 Found change in bash remediation.
 Ansible remediation changed.
Rule wrlinux:
 Found change in bash remediation.
 The rule doesn't occur in any profile nor product.
Rule accounts_logon_fail_delay:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_max_concurrent_login_sessions:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_tmout:
 Found change in bash remediation.
 Templatization usage changed.
Rule accounts_umask_etc_bashrc:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_umask_etc_csh_cshrc:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_umask_etc_login_defs:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_umask_etc_profile:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_audispd_configure_remote_server:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_data_disk_error_action:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_data_disk_full_action:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_data_retention_action_mail_acct:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_data_retention_admin_space_left_action:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_data_retention_flush:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_data_retention_max_log_file:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_data_retention_max_log_file_action:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_data_retention_num_logs:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_data_retention_space_left:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_data_retention_space_left_action:
 Found change in bash remediation.
 Ansible remediation changed.
Rule rsyslog_remote_loghost:
 Found change in bash remediation.
 Ansible remediation changed.
Rule configure_firewalld_ports:
 Found change in bash remediation.
Rule umask_for_daemons:
 Found change in bash remediation.
Rule selinux_policytype:
 Found change in bash remediation.
Rule selinux_state:
 Found change in bash remediation.
Rule dconf_gnome_screensaver_idle_delay:
 Found change in bash remediation.
 Ansible remediation changed.
Rule dconf_gnome_screensaver_lock_delay:
 Found change in bash remediation.
Rule configure_crypto_policy:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_authorized_local_users:
 Found change in bash remediation.
 The rule doesn't occur in any profile nor product.
Rule accounts_authorized_local_users_sidadm_orasid:
 Found change in bash remediation.
Macro openshift_cluster_setting:
 
Macro sub_var_value:
 
Macro xccdf_value:
 

**Recommended tests to execute:**
 build_product rhel7
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-rhel7-ds.xml chronyd_specify_remote_server
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel7-ds.xml chronyd_specify_remote_server
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-rhel7-ds.xml sshd_set_max_auth_tries
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel7-ds.xml sshd_set_max_auth_tries
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-rhel7-ds.xml sssd_memcache_timeout
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel7-ds.xml sssd_memcache_timeout
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-rhel7-ds.xml sssd_ssh_known_hosts_timeout
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel7-ds.xml sssd_ssh_known_hosts_timeout
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-rhel7-ds.xml banner_etc_motd
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel7-ds.xml banner_etc_motd
 build_product ol7
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ol7-ds.xml chronyd_or_ntpd_set_maxpoll
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ol7-ds.xml sshd_disable_compression
 tests/test_suite.py rule --libvirt qemu:///system test-suite- [...]

2020-09-09 15:04 UTC, matejak commented
/retest

2020-09-10 14:49 UTC, mildas commented
**Changes identified:**
Rule postfix_client_configure_mail_alias:
 Found change in bash remediation.
Rule postfix_network_listening_disabled:
 Ansible remediation changed.
Rule chronyd_or_ntpd_set_maxpoll:
 Found change in bash remediation.
Rule chronyd_or_ntpd_specify_multiple_servers:
 Found change in bash remediation.
Rule chronyd_or_ntpd_specify_remote_server:
 Found change in bash remediation.
Rule chronyd_specify_remote_server:
 Found change in bash remediation.
 Ansible remediation changed.
Rule firewalld_sshd_port_enabled:
 Ansible remediation changed.
Rule sshd_disable_compression:
 Found change in bash remediation.
Rule sshd_set_idle_timeout:
 Found change in bash remediation.
 Templatization usage changed.
Rule sshd_set_keepalive:
 Found change in bash remediation.
 Templatization usage changed.
Rule sshd_set_max_auth_tries:
 Found change in bash remediation.
 Templatization usage changed.
Rule sshd_set_max_sessions:
 Found change in bash remediation.
 Templatization usage changed.
Rule sshd_use_approved_ciphers:
 Found change in bash remediation.
 Templatization usage changed.
Rule sshd_use_approved_macs:
 Found change in bash remediation.
 Templatization usage changed.
Rule sshd_use_priv_separation:
 Found change in bash remediation.
Rule sssd_memcache_timeout:
 Found change in bash remediation.
 Ansible remediation changed.
Rule sssd_ssh_known_hosts_timeout:
 Found change in bash remediation.
 Ansible remediation changed.
Rule banner_etc_issue:
 Found change in bash remediation.
 Ansible remediation changed.
Rule banner_etc_motd:
 Found change in bash remediation.
 Ansible remediation changed.
Rule dconf_gnome_login_banner_text:
 Found change in bash remediation.
 Ansible remediation changed.
Rule rhel6:
 The rule doesn't occur in any profile nor product.
 Found change in bash remediation.
Rule accounts_password_pam_unix_remember:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_passwords_pam_faillock_deny:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_passwords_pam_faillock_interval:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_passwords_pam_faillock_unlock_time:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_password_pam_retry:
 Found change in bash remediation.
 Ansible remediation changed.
Rule configure_opensc_card_drivers:
 Found change in bash remediation.
 Ansible remediation changed.
Rule force_opensc_card_drivers:
 Found change in bash remediation.
 Ansible remediation changed.
Rule account_disable_post_pw_expiration:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_maximum_age_login_defs:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_minimum_age_login_defs:
 Found change in bash remediation.
 Ansible remediation changed.
Rule fedora:
 The rule doesn't occur in any profile nor product.
 Found change in bash remediation.
Rule accounts_password_minlen_login_defs:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_password_warn_age_login_defs:
 Found change in bash remediation.
 Ansible remediation changed.
Rule wrlinux:
 The rule doesn't occur in any profile nor product.
 Found change in bash remediation.
Rule accounts_logon_fail_delay:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_max_concurrent_login_sessions:
 Found change in bash remediation.
Rule accounts_tmout:
 Found change in bash remediation.
 Templatization usage changed.
Rule accounts_umask_etc_bashrc:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_umask_etc_csh_cshrc:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_umask_etc_login_defs:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_umask_etc_profile:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_audispd_configure_remote_server:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_data_disk_error_action:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_data_disk_full_action:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_data_retention_action_mail_acct:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_data_retention_admin_space_left_action:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_data_retention_flush:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_data_retention_max_log_file:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_data_retention_max_log_file_action:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_data_retention_num_logs:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_data_retention_space_left:
 Found change in bash remediation.
 Ansible remediation changed.
Rule auditd_data_retention_space_left_action:
 Found change in bash remediation.
 Ansible remediation changed.
Rule rsyslog_remote_loghost:
 Found change in bash remediation.
 Ansible remediation changed.
Rule configure_firewalld_ports:
 Found change in bash remediation.
Rule umask_for_daemons:
 Found change in bash remediation.
Rule selinux_policytype:
 Found change in bash remediation.
Rule selinux_state:
 Found change in bash remediation.
Rule dconf_gnome_screensaver_idle_delay:
 Found change in bash remediation.
 Ansible remediation changed.
Rule dconf_gnome_screensaver_lock_delay:
 Found change in bash remediation.
Rule configure_crypto_policy:
 Found change in bash remediation.
 Ansible remediation changed.
Rule accounts_authorized_local_users:
 The rule doesn't occur in any profile nor product.
 Found change in bash remediation.
Rule accounts_authorized_local_users_sidadm_orasid:
 Found change in bash remediation.
Macro openshift_cluster_setting:
 
Macro sub_var_value:
 
Macro xccdf_value:
 

**Recommended tests to execute:**
 build_product ubuntu1804
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-ubuntu1804-ds.xml sshd_set_max_auth_tries
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ubuntu1804-ds.xml sshd_set_max_auth_tries
 build_product sle15
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-sle15-ds.xml sshd_set_max_sessions
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-sle15-ds.xml sshd_set_max_sessions
 build_product rhel6
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel6-ds.xml postfix_client_configure_mail_alias
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel6-ds.xml umask_for_daemons
 build_product ol7
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ol7-ds.xml chronyd_or_ntpd_set_maxpoll
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-ol7-ds.xml sshd_use_approved_ciphers
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ol7-ds.xml sshd_use_approved_ciphers
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-ol7-ds.xml sshd_use_approved_macs
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-ol7-ds.xml sshd_use_approved_macs
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-ol7-ds.xml banner_etc_issue
 tests/test_suite.py rule --libvirt qemu:///syste [...]

2020-09-10 15:41 UTC, matejak commented
/retest

2020-09-14 07:02 UTC, jan-cerny requested changes

2020-09-14 13:54 UTC, matejak commented on linux_os/guide/system/accounts/accounts-session/accounts_max_concurrent_login_sessions/rule.yml
> +    <pre>*\t\thard\tmaxlogins\tsub_var_value("var_accounts_max_concurrent_login_sessions")</pre>
That's a great catch!

2020-09-14 14:10 UTC, mildas commented
**Changes identified:**
Rule postfix_client_configure_mail_alias:
 Found change in bash remediation.
Rule postfix_network_listening_disabled:
 Ansible remediation changed.
Rule chronyd_or_ntpd_set_maxpoll:
 Found change in bash remediation.
Rule chronyd_or_ntpd_specify_multiple_servers:
 Found change in bash remediation.
Rule chronyd_or_ntpd_specify_remote_server:
 Found change in bash remediation.
Rule chronyd_specify_remote_server:
 Ansible remediation changed.
 Found change in bash remediation.
Rule firewalld_sshd_port_enabled:
 Ansible remediation changed.
Rule sshd_disable_compression:
 Found change in bash remediation.
Rule sshd_set_idle_timeout:
 Templatization usage changed.
 Found change in bash remediation.
Rule sshd_set_keepalive:
 Templatization usage changed.
 Found change in bash remediation.
Rule sshd_set_max_auth_tries:
 Templatization usage changed.
 Found change in bash remediation.
Rule sshd_set_max_sessions:
 Templatization usage changed.
 Found change in bash remediation.
Rule sshd_use_approved_ciphers:
 Templatization usage changed.
 Found change in bash remediation.
Rule sshd_use_approved_macs:
 Templatization usage changed.
 Found change in bash remediation.
Rule sshd_use_priv_separation:
 Found change in bash remediation.
Rule sssd_memcache_timeout:
 Ansible remediation changed.
 Found change in bash remediation.
Rule sssd_ssh_known_hosts_timeout:
 Ansible remediation changed.
 Found change in bash remediation.
Rule banner_etc_issue:
 Ansible remediation changed.
 Found change in bash remediation.
Rule banner_etc_motd:
 Ansible remediation changed.
 Found change in bash remediation.
Rule dconf_gnome_login_banner_text:
 Ansible remediation changed.
 Found change in bash remediation.
Rule rhel6:
 The rule doesn't occur in any profile nor product.
 Found change in bash remediation.
Rule accounts_password_pam_unix_remember:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_passwords_pam_faillock_deny:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_passwords_pam_faillock_interval:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_passwords_pam_faillock_unlock_time:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_password_pam_retry:
 Ansible remediation changed.
 Found change in bash remediation.
Rule configure_opensc_card_drivers:
 Ansible remediation changed.
 Found change in bash remediation.
Rule force_opensc_card_drivers:
 Ansible remediation changed.
 Found change in bash remediation.
Rule account_disable_post_pw_expiration:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_maximum_age_login_defs:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_minimum_age_login_defs:
 Ansible remediation changed.
 Found change in bash remediation.
Rule fedora:
 The rule doesn't occur in any profile nor product.
 Found change in bash remediation.
Rule accounts_password_minlen_login_defs:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_password_warn_age_login_defs:
 Ansible remediation changed.
 Found change in bash remediation.
Rule wrlinux:
 The rule doesn't occur in any profile nor product.
 Found change in bash remediation.
Rule accounts_logon_fail_delay:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_max_concurrent_login_sessions:
 Found change in bash remediation.
Rule accounts_tmout:
 Templatization usage changed.
 Found change in bash remediation.
Rule accounts_umask_etc_bashrc:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_umask_etc_csh_cshrc:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_umask_etc_login_defs:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_umask_etc_profile:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_audispd_configure_remote_server:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_data_disk_error_action:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_data_disk_full_action:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_data_retention_action_mail_acct:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_data_retention_admin_space_left_action:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_data_retention_flush:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_data_retention_max_log_file:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_data_retention_max_log_file_action:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_data_retention_num_logs:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_data_retention_space_left:
 Ansible remediation changed.
 Found change in bash remediation.
Rule auditd_data_retention_space_left_action:
 Ansible remediation changed.
 Found change in bash remediation.
Rule rsyslog_remote_loghost:
 Ansible remediation changed.
 Found change in bash remediation.
Rule configure_firewalld_ports:
 Found change in bash remediation.
Rule umask_for_daemons:
 Found change in bash remediation.
Rule selinux_policytype:
 Found change in bash remediation.
Rule selinux_state:
 Found change in bash remediation.
Rule dconf_gnome_screensaver_idle_delay:
 Ansible remediation changed.
 Found change in bash remediation.
Rule dconf_gnome_screensaver_lock_delay:
 Found change in bash remediation.
Rule configure_crypto_policy:
 Ansible remediation changed.
 Found change in bash remediation.
Rule accounts_authorized_local_users:
 The rule doesn't occur in any profile nor product.
 Found change in bash remediation.
Rule accounts_authorized_local_users_sidadm_orasid:
 Found change in bash remediation.
Macro openshift_cluster_setting:
 
Macro sub_var_value:
 
Macro xccdf_value:
 

**Recommended tests to execute:**
 build_product rhel8
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-rhel8-ds.xml sshd_set_max_sessions
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhel8-ds.xml sshd_set_max_sessions
 build_product debian10
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-debian10-ds.xml sshd_set_idle_timeout
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-debian10-ds.xml sshd_set_idle_timeout
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-debian10-ds.xml sshd_set_keepalive
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-debian10-ds.xml sshd_set_keepalive
 build_product rhcos4
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-rhcos4-ds.xml auditd_data_disk_error_action
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhcos4-ds.xml auditd_data_disk_error_action
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-rhcos4-ds.xml auditd_data_disk_full_action
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using bash --datastream build/ssg-rhcos4-ds.xml auditd_data_disk_full_action
 build_product ol8
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-ol8-ds.xml firewalld_sshd_port_enabled
 tests/test_suite.py rule --libvirt qemu:///system test-suite-vm --remediate-using ansible --datastream build/ssg-ol8-ds.xml accounts_umask_etc_bashrc
 tests/test_suite.py  [...]

2020-09-14 16:01 UTC, JAORMX commented
/test e2e-aws-rhcos4-e8

2020-09-15 12:09 UTC, merged

2020-09-15 12:10 UTC, jan-cerny commented
Thank you, this is a big improvement.