add rule use_pam_whell_for_su
ComplianceAsCode/content pull request #6256
Opened 2020-10-15 07:08 UTC by vojtapolasek

#### Description:

- add a rule which enforces usage of pam_wheel module for su authentication

- rule, oval, bash, ansible, tests

- add rule to rhel8 ospp

#### Rationale:

- rhel CC effort

2020-10-21 17:50 UTC, redhatrises commented
/retest

2020-10-23 11:03 UTC, mildas commented on linux_os/guide/system/accounts/accounts-restrictions/root_logins/use_pam_wheel_for_su/bash/shared.sh
> +if ! grep -q pam_wheel /etc/pam.d/su; then
This does not do what you expect - I tried this condition and it got evaluated as true when there was no `pam_wheel` and evaluated as false when `pam_wheel` was present in `/etc/pam.d/su`.

2020-10-23 11:13 UTC, mildas commented
The bash remediation script adds the required line only when a line with `pam_wheel.so` is present so it does not fix a case when there is no `pam_wheel` line.

However, I see that you have created test scenario that removes all `auth required pam_wheel.so use_uid` lines. This scenario does not hit the issue I have pointed out because the default `/etc/pam.d/su` file has `#auth       sufficient  pam_wheel.so trust use_uid ` like there.

2020-10-26 12:13 UTC, yuumasato requested changes
> The bash remediation script adds the required line only when a line with `pam_wheel.so` is present so it does not fix a case when there is no `pam_wheel` line.

Actually, I think we shouldn't remediate cases where the commented line is not there as we don't know where in the stack to put the  config  for `pam_wheel.so`.

2020-10-26 12:13 UTC, yuumasato commented on linux_os/guide/system/accounts/accounts-restrictions/root_logins/use_pam_wheel_for_su/bash/shared.sh
> +  sed '/^[[:space:]]*#[[:space:]]*auth[[:space:]]\+required[[:space:]]\+pam_wheel\.so[[:space:]]\+use_uid$/s/^#//' -i /etc/pam.d/su
The sed command won't uncomment the line when the line has spaces before '#'.

2020-10-26 12:36 UTC, mildas commented on linux_os/guide/system/accounts/accounts-restrictions/root_logins/use_pam_wheel_for_su/bash/shared.sh
> +  echo "auth             required        pam_wheel.so use_uid" >> /etc/pam.d/su
I didn't know that and it's important information for reviewing pam rules. Thanks

2020-11-02 15:05 UTC, yuumasato approved these changes

2020-11-02 15:05 UTC, merged