Add mount_option and partition rules
ComplianceAsCode/content pull request #6340
Opened 2020-11-05 13:36 UTC by vojtapolasek

#### Description:

- add following rules:

    - partition_for_boot

    - mount_option_boot_noexec

    - mount_option_boot_noauto

    - partition_for_opt

    - mount_option_opt_nosuid

    - mount_option_srv_nosuid

    - mount_option_home_noexec

    - partition_for_usr

    - mount_option_var_noexec

    

- updated mount_partition_for_srv

#### Rationale:

anssi effort

2020-11-05 15:35 UTC, yuumasato requested changes
Looks good to me, just a few typos.

2020-11-05 15:35 UTC, yuumasato commented on linux_os/guide/system/software/disk_partitioning/partition_for_usr/rule.yml
> +{{{ complete_ocil_entry_separate_partition(part="//usr") }}}
Typo, double stash in `/usr`.

2020-11-05 15:35 UTC, yuumasato commented on linux_os/guide/system/software/disk_partitioning/partition_for_usr/rule.yml
> +    PUtting it on a separate partition allows limit its size and apply
Typo, `Putting` with two upper case letters.

2020-11-05 15:35 UTC, yuumasato commented on linux_os/guide/system/software/disk_partitioning/partition_for_usr/rule.yml
> +title: 'Ensure //usr Located On Separate Partition'
Typo, double slash in `/usr`.

2020-11-05 15:50 UTC, vojtapolasek commented
Thank you, fixed.

2020-11-06 08:14 UTC, jan-cerny commented
@vojtapolasek Please remove RHEL 6 from prodtypes because RHEL 6 was completely removed.

2020-11-06 12:56 UTC, yuumasato approved these changes

2020-11-06 12:56 UTC, merged