[DO NOT MERGE] Added simple lineinfile templates.
ComplianceAsCode/content pull request #6389
Opened 2020-11-16 15:43 UTC by matejak

This PR introduces a new template, and demonstrates its usage on fitting rules. Check out test scenarios for the `accounts_passwords_pam_faillock_enforce_local` rule (introduced in #6370) to see what configurations the template can handle.

This PR conflicts with #6303 and it should be merged after the template system is restructured. Then, it will need a rebase, so for now, consider this PR as a preview and forum about the template interface and capabilities.

2020-11-27 16:04 UTC, jan-cerny requested changes
Except for that it looks fine.

2020-11-30 10:52 UTC, matejak commented on shared/templates/lineinfile/template.py
> +def lineinfile(data, lang):
This was really interesting, I have altered the template code to act more predictabley in cases like this.

2020-11-30 17:22 UTC, matejak commented
/retest

2020-12-01 10:11 UTC, matejak commented
/retest

2020-12-04 07:54 UTC, merged