create new issue template for requesting a rule
ComplianceAsCode/content pull request #6395
Opened 2020-11-18 13:07 UTC by vojtapolasek

#### Description:

- add a new issue template

- fix a typo in generic issute template

#### Rationale:

There appeared a list of questions which are often asked when a new SCAP rule is proposed. So why not to put them to test here upstream?

2020-11-18 13:19 UTC, ggbecker commented on .github/issue_template/new_rule.md
> +###Does any command need to be run?
```suggestion
### Does any command need to be run?
```

add an space between `#` and `Does`

2020-11-19 12:45 UTC, jan-cerny commented
/retest

2020-11-19 13:46 UTC, ggbecker requested changes
I think examples can be turned into comments... so people won't need to actually delete them before creating the issue.

Comments are represented by `<!-- commented text --!>`

<!-- commented text --!>

2020-11-20 14:00 UTC, vojtapolasek commented
Good suggestion, fixed.

2020-11-20 17:05 UTC, ggbecker commented on .github/issue_template/new_rule.md
> +### Is it order dependent? (does it need to be at certain place in the file?
```suggestion
### Is it order dependent? (does it need to be at certain place in the file?)
```

2020-11-23 16:05 UTC, ggbecker approved these changes
LGTM. Failing tests have no bearing to these changes.

2020-11-23 16:06 UTC, merged