update release documentation and patches
ComplianceAsCode/content pull request #6493
Opened 2020-12-18 14:07 UTC by vojtapolasek

#### Description:

- remove patch supporting for epel6
- update patch for epel7 to remove ocp4 product, it can't be built in epel7
- update documentation with above changes
- describe stabilization phase in documentation

#### Rationale:

- _Rationale here. Replace this text. Don't use the italics format!_

- Fixes # _Issue number here (e.g. #26) or remove this line if no issue exists._

2020-12-18 18:03 UTC, carlosmmatos requested changes

2020-12-18 18:03 UTC, carlosmmatos commented on release_tools/README.md
> +from the master branch into the stabilization branch. This reduces risk of
This reduces the risk of

2020-12-18 18:03 UTC, carlosmmatos commented on release_tools/README.md
> +- create a new branch called stabilization-vx.y.z, where x.y.z is the version of
Capitalize first character

2020-12-18 18:03 UTC, carlosmmatos commented on release_tools/README.md
> +- label the PR with "backported_into_stabilization"
Make sure each bullet `-` starts is capitalized for consistency.

2020-12-22 10:44 UTC, yuumasato requested changes

2020-12-22 10:44 UTC, yuumasato commented on release_tools/copr_epel7.patch
> ++sed -i 's/option(SSG_PRODUCT_OCP4 "If enabled, the OCP4 SCAP content will be built" \${SSG_PRODUCT_DEFAULT})/option(SSG_PRODUCT_OCP4 "If enabled, the OCP4 SCAP content will be built" false)/' CMakeL
It should be safer to run the  `cmake` command with `-DSSG_PRODUCT_OCP4:BOOLEAN=OFF`
` cmake -DSSG_PRODUCT_OCP4:BOOLEAN=OFF ..`

2021-01-04 14:02 UTC, vojtapolasek commented
Thank you for feedback, fixed.

2021-01-07 09:53 UTC, yuumasato approved these changes

2021-01-07 09:54 UTC, yuumasato commented
Thank you for documenting this.

2021-01-07 09:54 UTC, merged