Update selinux_confinement_of_daemons rule
ComplianceAsCode/content pull request #6695
Opened 2021-03-12 15:51 UTC by matusmarhefka

#### Description:

- The `initrc_t` context was used on RHEL5/RHEL6. Since RHEL7 the correct context for the unconfined daemons should be the `unconfined_service_t`.
- Also added test scenarios.

2021-03-15 09:31 UTC, JAORMX commented
/retest

2021-03-15 10:03 UTC, JAORMX commented
/retest

2021-03-15 10:12 UTC, vojtapolasek requested changes
Looks nice, thank you for the changes. Could you please check provided comments and add ocil to the rule?

2021-03-15 11:50 UTC, matusmarhefka commented
@vojtapolasek Thanks for the review, I've fixed the comments in OVAL and added OCIL.

2021-03-15 12:01 UTC, JAORMX commented
I have the feeling that this will start failing in RHCOS4. Let's see what the CI results say.

2021-03-15 12:05 UTC, vojtapolasek commented on linux_os/guide/system/selinux/selinux_confinement_of_daemons/oval/shared.xml
>        <criterion comment="device_t in /dev" test_ref="test_selinux_confinement_of_daemons" />
The comment with device_t is still here for me...

2021-03-15 12:12 UTC, vojtapolasek commented on linux_os/guide/system/selinux/selinux_confinement_of_daemons/rule.yml
> +ocil_clause: 'SELinux policy contains rules for all the daemons running on the system'
The ocil clause should be a sentence describing failing the check.
```suggestion
ocil_clause: 'There are unconfined daemons running on the system'
```

2021-03-15 12:17 UTC, matusmarhefka commented on linux_os/guide/system/selinux/selinux_confinement_of_daemons/oval/shared.xml
>        <criterion comment="device_t in /dev" test_ref="test_selinux_confinement_of_daemons" />
Yeah, I overlooked that.

2021-03-15 12:28 UTC, vojtapolasek commented
Thanks for the changes, now let's wait for the CI as @JAORMX  suggested.

2021-03-15 17:18 UTC, JAORMX commented
aha... from the logs: 
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/ComplianceAsCode_content/6695/pull-ci-ComplianceAsCode-content-master-e2e-aws-rhcos4-moderate/1371436752257945600/artifacts/e2e-aws-rhcos4-moderate/test/build-log.txt

It seems that the rule is failing now. This might be a legitimate issue in RHCOS. Checking the scan logs: 

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/ComplianceAsCode_content/6695/pull-ci-ComplianceAsCode-content-master-e2e-aws-rhcos4-moderate/1371436752257945600/artifacts/e2e-aws-rhcos4-moderate/gather-extra/artifacts/pods/openshift-compliance_openscap-pod-1676366449654ed76ce95ae9658bd80f7e5b7134_scanner.log

```
Title
	Ensure No Daemons are Unconfined by SELinux
Rule
	xccdf_org.ssgproject.content_rule_selinux_confinement_of_daemons
Ident
	CCE-82688-3
I: oscap: Evaluating XCCDF rule 'xccdf_org.ssgproject.content_rule_selinux_confinement_of_daemons'.
I: oscap: Evaluating definition 'oval:ssg-installed_OS_is_rhcos4:def:1': Red Hat Enterprise Linux CoreOS.
I: oscap: Definition 'oval:ssg-installed_OS_is_rhcos4:def:1' evaluated as true.
I: oscap: Evaluating definition 'oval:ssg-installed_env_is_a_machine:def:1': Check if the scan target is a machine.
I: oscap: Definition 'oval:ssg-installed_env_is_a_machine:def:1' evaluated as true.
I: oscap: Evaluating definition 'oval:ssg-installed_env_is_a_machine:def:1': Check if the scan target is a machine.
I: oscap: Definition 'oval:ssg-installed_env_is_a_machine:def:1' evaluated as true.
I: oscap: This rule requires an OCIL check. OCIL checks are not supported by OpenSCAP.
I: oscap: Evaluating definition 'oval:ssg-selinux_confinement_of_daemons:def:1': Ensure No Daemons are Unconfined by SELinux.
I: oscap:   Evaluating selinuxsecuritycontext test 'oval:ssg-test_selinux_confinement_of_daemons:tst:1': none satisfy unconfined_service_t in /proc.
I: oscap:     Querying selinuxsecuritycontext object 'oval:ssg-object_selinux_confinement_of_daemons:obj:1', flags: 0.
I: oscap:     Creating new syschar for selinuxsecuritycontext_object 'oval:ssg-object_selinux_confinement_of_daemons:obj:1'.
I: oscap:     Starting probe on URI 'queue://selinuxsecuritycontext'.
I: oscap:     Object 'oval:ssg-object_selinux_confinement_of_daemons:obj:1' has a filter that includes items conforming to state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1'.
I: oscap:     Switching probe to PROBE_OFFLINE_OWN mode.
I: oscap:     I will run selinuxsecuritycontext_probe_main:
I: oscap:     Opening file '/host/proc'.
I: oscap:     Test 'oval:ssg-test_selinux_confinement_of_daemons:tst:1' requires that zero or more objects defined by 'oval:ssg-object_selinux_confinement_of_daemons:obj:1' exist on the system.
I: oscap:     41 objects defined by 'oval:ssg-object_selinux_confinement_of_daemons:obj:1' exist on the system.
I: oscap:     All items matching object 'oval:ssg-object_selinux_confinement_of_daemons:obj:1' were collected. (flag=complete)
I: oscap:     In test 'oval:ssg-test_selinux_confinement_of_daemons:tst:1' none of the collected items must satisfy these states: 'oval:ssg-state_selinux_confinement_of_daemons:ste:1'.
I: oscap:     Entity 'type'='unconfined_service_t' of item '1000112799' matches corresponding entity in state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1'.
I: oscap:     Item '1000112799' compared to state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1' with result true.
I: oscap:     Entity 'type'='unconfined_service_t' of item '1000112800' matches corresponding entity in state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1'.
I: oscap:     Item '1000112800' compared to state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1' with result true.
I: oscap:     Entity 'type'='unconfined_service_t' of item '1000112808' matches corresponding entity in state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1'.
I: oscap:     Item '1000112808' compared to state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1' with result true.
I: oscap:     Entity 'type'='unconfined_service_t' of item '1000112809' matches corresponding entity in state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1'.
I: oscap:     Item '1000112809' compared to state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1' with result true.
I: oscap:     Entity 'type'='unconfined_service_t' of item '1000112810' matches corresponding entity in state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1'.
I: oscap:     Item '1000112810' compared to state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1' with result true.
I: oscap:     Entity 'type'='unconfined_service_t' of item '1000112811' matches corresponding entity in state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1'.
I: oscap:     Item '1000112811' compared to state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1' with result true.
I: oscap:     Entity 'type'='unconfined_service_t' of item '1000112812' matches corresponding entity in state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1'.
I: oscap:     Item '1000112812' compared to state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1' with result true.
I: oscap:     Entity 'type'='unconfined_service_t' of item '1000112813' matches corresponding entity in state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1'.
I: oscap:     Item '1000112813' compared to state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1' with result true.
I: oscap:     Entity 'type'='unconfined_service_t' of item '1000112815' matches corresponding entity in state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1'.
I: oscap:     Item '1000112815' compared to state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1' with result true.
I: oscap:     Entity 'type'='unconfined_service_t' of item '1000112814' matches corresponding entity in state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1'.
I: oscap:     Item '1000112814' compared to state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1' with result true.
I: oscap:     Entity 'type'='unconfined_service_t' of item '1000112802' matches corresponding entity in state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1'.
I: oscap:     Item '1000112802' compared to state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1' with result true.
I: oscap:     Entity 'type'='unconfined_service_t' of item '1000112803' matches corresponding entity in state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1'.
I: oscap:     Item '1000112803' compared to state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1' with result true.
I: oscap:     Entity 'type'='unconfined_service_t' of item '1000112804' matches corresponding entity in state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1'.
I: oscap:     Item '1000112804' compared to state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1' with result true.
I: oscap:     Entity 'type'='unconfined_service_t' of item '1000112805' matches corresponding entity in state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1'.
I: oscap:     Item '1000112805' compared to state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1' with result true.
I: oscap:     Entity 'type'='unconfined_service_t' of item '1000112806' matches corresponding entity in state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1'.
I: oscap:     Item '1000112806' compared to state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1' with result true.
I: oscap:     Entity 'type'='unconfined_service_t' of item '1000112807' matches corresponding entity in state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1'.
I: oscap:     Item '1000112807' compared to state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1' with result true.
I: oscap:     Entity 'type'='unconfined_service_t' of item '1000112801' matches corresponding entity in state 'oval:ssg-state_selinux_confinement_of_daemons:ste:1'.
I: oscap:     Item '1000112801' compared to s [...]

2021-03-16 06:58 UTC, JAORMX commented
/retest

2021-03-16 10:43 UTC, matusmarhefka commented
@JAORMX Have you fixed it in RHCOS? Because all checks have passed now.

2021-03-16 10:49 UTC, JAORMX commented
@matusmarhefka I think this is OK to merge. While this rule is covered in RHCOS, it's not "tested" as in, we don't take the result into account. Seems to me that this uncovered an actual issue in RHCOS which is that the kubelet is running unconfined. I'll bring this up with the appropriate team and see if we can get this fixed.

2021-03-16 10:50 UTC, JAORMX approved these changes

2021-03-16 11:21 UTC, vojtapolasek approved these changes

2021-03-16 11:21 UTC, merged