Add rules from the Policy to profiles based on prodtype
ComplianceAsCode/content pull request #6725
Opened 2021-03-19 08:22 UTC by yuumasato

#### Description:

- Profiles generated by the Controls will skip rules that are not applicable to the product being built
  - `test_controls.py`was adapted to account for this new behavior
- Added logging feature to make it easy to check rules that were skipped by a certain product
- Added ANSSI profiles for RHCOS4
  - Rules in the ANSSI policy without `prodtype: rhcos4` are not included but logged.

#### Rationale:

- This avoids cluttering the control file with Jinja2 conditionals.

#### Note:
- I'm aware  `get_rule_path_by_id()` is not efficient, but I don't know how to improve that without major changes.

2021-03-19 08:22 UTC, pep8speaks commented
Hello @yuumasato! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`build-scripts/compile_profiles.py`](https://github.com/ComplianceAsCode/content/blob/171c9a5a8c1613ff401fce141edee2d9ac695b65/build-scripts/compile_profiles.py):

> [Line 78:100](https://github.com/ComplianceAsCode/content/blob/171c9a5a8c1613ff401fce141edee2d9ac695b65/build-scripts/compile_profiles.py#L78): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (116 > 99 characters)

* In the file [`ssg/controls.py`](https://github.com/ComplianceAsCode/content/blob/171c9a5a8c1613ff401fce141edee2d9ac695b65/ssg/controls.py):

> [Line 42:22](https://github.com/ComplianceAsCode/content/blob/171c9a5a8c1613ff401fce141edee2d9ac695b65/ssg/controls.py#L42): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator
> [Line 43:25](https://github.com/ComplianceAsCode/content/blob/171c9a5a8c1613ff401fce141edee2d9ac695b65/ssg/controls.py#L43): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator
> [Line 64:27](https://github.com/ComplianceAsCode/content/blob/171c9a5a8c1613ff401fce141edee2d9ac695b65/ssg/controls.py#L64): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator

2021-03-19 15:06 UTC, JAORMX commented
/retest

2021-03-22 07:11 UTC, JAORMX approved these changes

2021-03-31 09:04 UTC, vojtapolasek requested changes
Nice work, thank you. Please see review comments and pep8 warnings.

2021-04-01 09:53 UTC, yuumasato commented on linux_os/guide/system/logging/package_rsyslog-gnutls_installed/rule.yml
> +prodtype: fedora,el8,rhel8
`el8` is a typo, it should be `ol8`.

2021-04-01 09:53 UTC, yuumasato commented on ssg/controls.py
> +                    if rule.prodtype == "all" or product in rule.prodtype:
The code evaluating the rule's eligibility for the control doesn't care about non-matching `prodtypes`, and doesn't bother itself checking if any of the non-matched `prodtypes` is valid (more on that later).

I think this check should be done elsewhere, here for example:
https://github.com/ComplianceAsCode/content/blob/3fbd2712cdfd25d7fa8eb41cad1d1689224aac42/ssg/build_yaml.py#L1087

But `Rule.validate_prodtype()` only does syntax checking (actually just no space in between prodtypes).
This method looks like a good candidate for non-existent product validation, but it is not really aware of the whole catalog of products when loading the file... 

Validating during the build seems inefficient, typos like these should probably be validated before the brunt of the build  starts...

2021-04-01 09:53 UTC, yuumasato commented on ssg/controls.py
> +                    if rule.prodtype == "all" or product in rule.prodtype:
The validation for non-existing `prodtypes` should be addressed in future work.

2021-04-01 09:57 UTC, yuumasato commented on ssg/controls.py
> +                    if rule.prodtype == "all" or product in rule.prodtype:
I'd not say that `el8` is accepted, but ignored or tollerated. The rule will not be included in the intended product, and this can be a problem.

2021-04-06 08:56 UTC, vojtapolasek approved these changes

2021-04-06 08:57 UTC, merged