fix build system to correctly parse platforms
ComplianceAsCode/content pull request #6760
Opened 2021-03-26 13:07 UTC by vojtapolasek

#### Description:
- read both "platform" and "platforms" while parsing yaml files
- then later work only with "platforms" but make sure that content of "platform" gets propagated into "platforms"

#### Rationale:

- previous introduction of multiple independent platforms in #6661  caused a breakage in platform applicability. This is the fix.

2021-03-26 13:07 UTC, pep8speaks commented
Hello @vojtapolasek! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`ssg/build_yaml.py`](https://github.com/ComplianceAsCode/content/blob/200d587bf34d280ed846fa6be9aa99fe7176c348/ssg/build_yaml.py):

> [Line 839:17](https://github.com/ComplianceAsCode/content/blob/200d587bf34d280ed846fa6be9aa99fe7176c348/ssg/build_yaml.py#L839): [E116](https://duckduckgo.com/?q=pep8%20E116) unexpected indentation (comment)

2021-03-26 15:06 UTC, yuumasato requested changes
What do you think about making `platforms` a `set()`?
I think it will simplify the code a bit.

2021-03-29 08:00 UTC, vojtapolasek commented
I pushed changes which initialize platforms as set. They are also stored as set within compiled rules... I am not sure if it breaks something, it looks like not at the first glance.

2021-03-29 09:07 UTC, yuumasato requested changes

2021-03-29 09:07 UTC, yuumasato commented on ssg/build_yaml.py
> +        if len(self.platforms) > 0:
Nitpick: an empty platform evaluates to False:
`if self.platforms:` will work the same.

2021-03-29 11:42 UTC, yuumasato approved these changes

2021-03-29 11:42 UTC, merged