Use v1beta1 for api_server_api_priority_flowschema_catch_all object
ComplianceAsCode/content pull request #6810
Opened 2021-04-08 15:18 UTC by mrogers950

v1alpha1 for FlowSchemas is deprecated and removed in kube 1.21.

2021-04-08 15:45 UTC, JAORMX approved these changes
LGTM, feel free to merge this if it passes CI.

2021-04-08 17:20 UTC, JAORMX commented
Seems this isn't working for the 4.6 CIS benchmark :/ when was this version introduced?

2021-04-08 17:39 UTC, JAORMX commented
I think we need to start introducing CPEs to distinguish between versions...

2021-04-08 17:40 UTC, mrogers950 commented
@JAORMX looks like very recently with 4.8:
```
$ oc version
Client Version: 4.8.0-0.nightly-2021-03-14-134919
Server Version: 4.8.0-0.nightly-2021-03-14-134919
Kubernetes Version: v1.20.0+e1bc274

$ oc get --raw=/apis/flowcontrol.apiserver.k8s.io/v1alpha1/flowschemas/catch-all
W0408 13:36:37.914789 3697791 warnings.go:70] flowcontrol.apiserver.k8s.io/v1alpha1 FlowSchema is deprecated in v1.20+, unavailable in v1.21+; use flowcontrol.apiserver.k8s.io/v1beta1 FlowSchema
{"kind":"FlowSchema","apiVersion":"flowcontrol.apiserver.k8s.io/v1alpha1","metadata":{"name":"catch-all","uid":"82d6a27f-6ece-4ed7-a707-9d6f38b0707b","resourceVersion":"95","generation":1,"creationTimestamp":"2021-04-08T13:45:28Z","managedFields":[{"manager":"api-priority-and-fairness-config-consumer-v1","operation":"Update","apiVersion":"flowcontrol.apiserver.k8s.io/v1beta1","time":"2021-04-08T13:45:28Z","fieldsType":"FieldsV1","fieldsV1":{"f:status":{"f:conditions":{".":{},"k:{\"type\":\"Dangling\"}":{".":{},"f:lastTransitionTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}}}}},{"manager":"api-priority-and-fairness-config-producer-v1","operation":"Update","apiVersion":"flowcontrol.apiserver.k8s.io/v1beta1","time":"2021-04-08T13:45:28Z","fieldsType":"FieldsV1","fieldsV1":{"f:spec":{"f:distinguisherMethod":{".":{},"f:type":{}},"f:matchingPrecedence":{},"f:priorityLevelConfiguration":{"f:name":{}},"f:rules":{}}}}]},"spec":{"priorityLevelConfiguration":{"name":"catch-all"},"matchingPrecedence":10000,"distinguisherMethod":{"type":"ByUser"},"rules":[{"subjects":[{"kind":"Group","group":{"name":"system:unauthenticated"}},{"kind":"Group","group":{"name":"system:authenticated"}}],"resourceRules":[{"verbs":["*"],"apiGroups":["*"],"resources":["*"],"clusterScope":true,"namespaces":["*"]}],"nonResourceRules":[{"verbs":["*"],"nonResourceURLs":["*"]}]}]},"status":{"conditions":[{"type":"Dangling","status":"False","lastTransitionTime":"2021-04-08T13:45:28Z","reason":"Found","message":"This FlowSchema references the PriorityLevelConfiguration object named \"catch-all\" and it exists"}]}}


$ oc version
Client Version: 4.8.0-0.nightly-2021-03-14-134919
Server Version: 4.8.0-0.ci-2021-04-07-212428
Kubernetes Version: v1.21.0-beta.1.1625+dd7e566dce45b9-dirty

$ oc get --raw=/apis/flowcontrol.apiserver.k8s.io/v1alpha1/flowschemas/catch-all
Error from server (NotFound): the server could not find the requested resource
```

4.6 only has alpha: https://v1-19.docs.kubernetes.io/docs/concepts/cluster-administration/flow-control/

2021-04-08 17:52 UTC, JAORMX commented
Ugh... Gotcha. This was bound to happen at some point. We'll have to create a CPE for 4.8+ and start dealing with these versioning changes that way. We'll need to reflect this in CI somehow as well

2021-04-09 08:08 UTC, JAORMX requested changes
Let's use https://github.com/ComplianceAsCode/content/pull/6813 instead. It includes this commit, and other work to get this sort of situation addressed.

2021-04-09 14:09 UTC, mrogers950 commented
superseded by https://github.com/ComplianceAsCode/content/pull/6813

2021-04-09 14:09 UTC, closed without merging