Add Rule,Remediation and Test for SLES-15-030780
ComplianceAsCode/content pull request #6934
Opened 2021-04-30 20:43 UTC by yarunachalam

#### Description:

- Add Rule,Remediation and Test for SLES-15-030780

#### Rationale:

- Add SLE15 rule for 'Record Attempts to Alter Process and Session Initiation Information btmp'

2021-05-06 10:48 UTC, jan-cerny commented
/ok-to-test

2021-05-06 10:48 UTC, jan-cerny commented
@openscap-ci test this please

2021-05-31 13:16 UTC, vojtapolasek requested changes
Thank you for the new rule. Just two small things, please see comments.

2021-05-31 13:16 UTC, vojtapolasek commented on linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_session_events_btmp/rule.yml
> +    To Check the file is being audited by performing the following command
```suggestion
    Check that the file is being audited by running the following command:
```

2021-05-31 13:16 UTC, vojtapolasek commented on linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_session_events_btmp/rule.yml
> +template:
blank line before template please

2021-06-01 20:22 UTC, yarunachalam commented on linux_os/guide/system/auditing/auditd_configure_rules/audit_rules_session_events_btmp/rule.yml
> +template:
Done

2021-06-03 09:02 UTC, vojtapolasek commented
/retest

2021-06-03 13:03 UTC, merged