SLES-15-010357 rule
ComplianceAsCode/content pull request #6952
Opened 2021-05-05 17:20 UTC by rumch-se

#### Description:

- _SLES-15-010357 rule_

#### Rationale:

- _Review required_

- Fixes # _Issue number here (e.g. #26) or remove this line if no issue exists._

2021-05-10 13:11 UTC, rumch-se commented on linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_permissions_system_commands_dirs/oval/shared.xml
> +    <unix:path operation="pattern match">^\/[s?]bin|^\/usr\/[s?]bin|^\/usr\/local\/[s?]bin</unix:path>
@jan-cerny - I fixed this

2021-05-13 10:17 UTC, vojtapolasek commented
/ok-to-test

2021-05-13 10:17 UTC, vojtapolasek commented
@openscap-ci ok to test

2021-05-13 10:18 UTC, vojtapolasek commented
@openscap-ci test this please

2021-05-13 10:36 UTC, vojtapolasek requested changes
Hello, thank you for the rule and tests, it looks really good. Please could you add just one more test which uses symlink?
Thank you.

2021-05-13 10:36 UTC, vojtapolasek commented on linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_permissions_system_commands_dirs/rule.yml
> +title: 'Verify that system commands are protected from unathorized access'
```suggestion
title: 'Verify that system commands are protected from unauthorized access'
```

2021-05-13 10:36 UTC, vojtapolasek commented on linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_permissions_system_commands_dirs/ansible/shared.yml
> +- name: "Retrive the system command files and protect them from unautorized access"
```suggestion
- name: "Retrieve the system command files and protect them from unautorized access"
```

2021-05-20 10:50 UTC, ggbecker commented
@openscap-ci test this please

2021-05-20 14:38 UTC, vojtapolasek approved these changes

2021-05-20 14:38 UTC, merged