SLES-15-010361 rule
ComplianceAsCode/content pull request #6958
Opened 2021-05-06 09:31 UTC by rumch-se

#### Description:

- _SLES-15-010361 rule_

#### Rationale:

- _Review required_

- Fixes # _Issue number here (e.g. #26) or remove this line if no issue exists._

2021-05-06 14:46 UTC, jan-cerny commented
/ok-to-test

2021-06-03 10:52 UTC, vojtapolasek requested changes
Hello, thank you for the rule. See comments please.
I have one request - if I understand it right, the rule checks for GROUP ownership, not USER ownership. If I am correct, please change the rule identifier to file_groupownership_system_commands_dirs.
Please reflect this change also in OVAL test / object / state names. Thank you.

2021-06-03 10:52 UTC, vojtapolasek commented on linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_ownership_system_commands_dirs/rule.yml
> +    All files in these directories should be owned by the <tt>root</tt> user.
```suggestion
    All files in these directories should be owned by the <tt>root</tt> group. 
```

2021-06-03 10:52 UTC, vojtapolasek commented on linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_ownership_system_commands_dirs/rule.yml
> +    by a user other than root correct its ownership with the following command:
```suggestion
    by a group other than root correct its ownership with the following command:
```

2021-06-03 10:52 UTC, vojtapolasek commented on linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_ownership_system_commands_dirs/rule.yml
> +rationale: |-
blank line before rationale please

2021-06-03 10:52 UTC, vojtapolasek commented on linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_ownership_system_commands_dirs/rule.yml
> +    If the operating system were to allow any user to make changes to software
```suggestion
    If the operating system allows any user to make changes to software
```

2021-06-03 10:52 UTC, vojtapolasek commented on linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_ownership_system_commands_dirs/rule.yml
> +ocil_clause: 'any of these files are not owned by root'
```suggestion
ocil_clause: 'any of these files are not owned by root group'
```

2021-06-03 10:52 UTC, vojtapolasek commented on linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_ownership_system_commands_dirs/rule.yml
> +    Sysem commands are stored in the following directories:
```suggestion
    System commands are stored in the following directories:
```

2021-06-03 10:52 UTC, vojtapolasek commented on linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_ownership_system_commands_dirs/rule.yml
> +    owned by root:
```suggestion
    owned by root group:
```

2021-06-03 10:52 UTC, vojtapolasek commented on linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_ownership_system_commands_dirs/ansible/shared.yml
> +- name: "Retrive the system command files and set their ownership to root"
```suggestion
- name: "Retrieve the system command files and set their group ownership to root"
```

2021-06-03 10:52 UTC, vojtapolasek commented on linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_ownership_system_commands_dirs/oval/shared.xml
> +        are owned by root.
```suggestion
        are owned by root group.
```

2021-06-03 10:52 UTC, vojtapolasek commented on linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_ownership_system_commands_dirs/oval/shared.xml
> +         belong to user with uid 0 (root) -->
```suggestion
         belong to group with gid 0 (root) -->
```

2021-06-03 12:48 UTC, rumch-se commented
Hello @vojtapolasek  - thank you very much for your proposals. I created a new commit 67f9df096 in which I integrated all changes proposed by you.

2021-06-03 13:16 UTC, vojtapolasek commented on linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_groupownership_system_commands_dirs/rule.yml
> +rationale: |-
blank line here, please

2021-06-03 13:19 UTC, vojtapolasek commented
Thank you for changes. Please could you change also test / object / state identifiers in the oval check? I recommend doing it now, cause if you later want to create another oval which checks for user ownership, there might be a clash of names.

2021-06-03 14:11 UTC, rumch-se commented
@vojtapolasek - Hello - I have done the proposed changes.

2021-06-04 06:36 UTC, vojtapolasek commented
/retest

2021-06-04 08:33 UTC, merged