configure_gnutls_crypto_policy update
ComplianceAsCode/content pull request #7048
Opened 2021-05-25 21:24 UTC by carlosmmatos

#### Description:

- The original OVAL did not do a regex check for the appropriate value. It was simply ensuring that the content of the file was correct. However, with newer versions of the crypto-policies rpm, the contents have changed, thus making this an ineffective way to check state.

#### Rationale:

- Update OVAL to ensure the string is in the file
- Update Ansible to use replace module with appropriate regexp
- Update Bash to replace (sed) incorrect entry (if found) with appropriate value
- Fixes #7038

2021-05-26 17:01 UTC, ggbecker requested changes

2021-05-27 14:50 UTC, yuumasato commented on linux_os/guide/system/software/integrity/crypto/configure_gnutls_tls_crypto_policy/oval/shared.xml
> +   <criteria/>
There is a typo, a forward slash is missing in the closing `<criteria>`.

2021-05-27 14:57 UTC, ggbecker commented on linux_os/guide/system/software/integrity/crypto/configure_gnutls_tls_crypto_policy/oval/shared.xml
> +   <criteria/>
```suggestion
   </criteria>
```

Thanks @yuumasato

2021-05-27 18:24 UTC, carlosmmatos commented
/retest

2021-05-31 14:58 UTC, ggbecker approved these changes
LGTM.

I have checked that all test scenarios pass for both remediation types. I have also tested STIG profile on a RHEL8.4.0 machine using oscap-anaconda-addon and confirm that the final result is passing.

2021-05-31 14:58 UTC, merged