OCP4: Add rules to verify legal notice
ComplianceAsCode/content pull request #7127
Opened 2021-06-17 12:19 UTC by JAORMX

This is used to address NIST SP 800-53's AC-8 control, and will verify that a
legal notice has been set on the UI either a login template or a classification
banner. For the CLI, the legal notice will use the motd capabilities.

2021-06-17 13:33 UTC, JAORMX commented
/retest

2021-06-17 16:56 UTC, JAORMX commented
/retest

2021-06-18 05:30 UTC, JAORMX commented
/retest

2021-06-18 13:47 UTC, mrogers950 approved these changes
Addressed my concerns in slack.
/lgtm

2021-06-20 14:12 UTC, JAORMX commented
/retest

2021-06-21 06:31 UTC, JAORMX commented
/retest

2021-06-21 09:45 UTC, jhrozek requested changes
looks good except for the missing CCEs

2021-06-21 09:45 UTC, jhrozek commented on applications/openshift/general/openshift_motd_exists/rule.yml
> +identifiers: {}
Please add a CCE

2021-06-21 09:45 UTC, jhrozek commented on applications/openshift/general/oauth_login_template_set/rule.yml
> +identifiers: {}
please add a CCE

2021-06-21 09:58 UTC, JAORMX commented
Pull-request updated, HEAD is now f521ebe0b69c654ff2d4f45afc0f4575d0005bb5

2021-06-21 10:19 UTC, jhrozek approved these changes
lgtm

2021-06-21 10:44 UTC, JAORMX commented
/retest

2021-06-21 12:38 UTC, JAORMX commented
/retest

2021-06-21 13:22 UTC, JAORMX commented
/retest

2021-06-21 15:14 UTC, JAORMX commented
/retest

2021-06-22 06:41 UTC, JAORMX commented
Pull-request updated, HEAD is now 2c4890592f118f05d848367e207b78f86656c2ff

2021-06-22 07:25 UTC, JAORMX commented
/retest

2021-06-22 11:30 UTC, merged