Add rule for SLES-12-030365
ComplianceAsCode/content pull request #7177
Opened 2021-06-30 12:03 UTC by anivan-suse

#### Description:

- SLES-12-030365, cce@sle12: CCE-83248-5

#### Rationale:

- sysctl_net_ipv6_conf_default_forwarding

2021-07-19 12:17 UTC, cipherboy commented
/ok-to-test

2021-07-19 12:17 UTC, cipherboy commented
@anivan-suse If you rebase this, I can go ahead and merge it. :-)

2021-07-20 12:35 UTC, jan-cerny commented
@anivan-suse Please remove the unrelated commits from the PR. You can do that by rebasing your local branch on the top of the current (updated) upstream master and pushing force to the feature branch in your GitHub fork.

2021-07-20 14:56 UTC, pep8speaks commented
Hello @anivan-suse! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:









* In the file [`tests/install_vm.py`](https://github.com/ComplianceAsCode/content/blob/b8a549db3c1e92a1cf488969eded00abc848d2ea/tests/install_vm.py):

> [Line 198:100](https://github.com/ComplianceAsCode/content/blob/b8a549db3c1e92a1cf488969eded00abc848d2ea/tests/install_vm.py#L198): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (395 > 99 characters)

2021-07-21 07:49 UTC, jan-cerny commented
@anivan-suse I can see that you have tried to rebased it somehow, but I still can see various "Merge ..." commits in the list of the commits of this PR. Please remove them, a PR with "Merge" or "Fix conflicts" or similar commits can't be accepted.

2021-07-23 15:02 UTC, anivan-suse commented
Hey @jan-cerny, thanks for the info! I tried to rebase following [this](https://github.com/ComplianceAsCode/content/pull/7164#issuecomment-870686684) comment I had previously, but it did not get rid of the Merge commits. Do you know how I might best be able to get rid of them? Thanks!

2021-07-26 08:55 UTC, jan-cerny commented
> Hey @jan-cerny, thanks for the info! I tried to rebase following [this](https://github.com/ComplianceAsCode/content/pull/7164#issuecomment-870686684) comment I had previously, but it did not get rid of the Merge commits. Do you know how I might best be able to get rid of them? Thanks!

Hi @anivan-suse , you can do similar steps as in the comment you linked, but use an interactive rebase using the `-i` option instead of the automated rebase . When you run `git rebase -i upstream/master`, your editor will open and you will be able to remove the commits.  I think that this article explains it well: https://hackernoon.com/beginners-guide-to-interactive-rebasing-346a3f9c3a6d

2021-08-19 20:04 UTC, Mab879 requested changes

2021-08-19 20:04 UTC, Mab879 commented on linux_os/guide/system/network/network-ipv6/configuring_ipv6/sysctl_net_ipv6_conf_default_forwarding/rule.yml
> +    stigid@sle12: SLES-12-030365
This needs to be sorted and please remove the extra `stigid@sle12`.

2021-08-24 18:23 UTC, Mab879 approved these changes
Thank you!

2021-08-24 18:24 UTC, merged