Split RHEL 7 CIS profile - section 5
ComplianceAsCode/content pull request #7193
Opened 2021-07-02 11:35 UTC by vojtapolasek

#### Description:

- update the policy file
- add or correct cis references in rule.yml files

#### Rationale:

CIS split effort

2021-07-02 13:47 UTC, yuumasato requested changes
Made some general comments.
The only change I see as essential is the `pam_unix.so` with `remember`.

2021-07-07 12:41 UTC, yuumasato reviewed
LGTM
@vojtapolasek please rebase and fix the conflicts, :)

2021-07-07 12:41 UTC, yuumasato commented on controls/cis_rhel7.yml
> +      Usage of pam_unix.so module is not deprecated and is not supported by this policy interpretation.
I think you meant that use of pam_unix.so with remember is deprecated.

2021-07-07 13:32 UTC, vojtapolasek commented
Thank you for the review. I think we do not have rule for checking of SSH exchange key algorithms as you suggested in one of your comments.

2021-07-07 15:23 UTC, yuumasato approved these changes

2021-07-07 15:23 UTC, merged