New rule for RHEL-08-010350
ComplianceAsCode/content pull request #7216
Opened 2021-07-07 15:35 UTC by Mab879

#### Description:

New rule to check the group ownership of library directories and files.

2021-07-07 16:08 UTC, ggbecker commented
I think this open PR is proposing the same rule: https://github.com/ComplianceAsCode/content/pull/7179 we can combine them together

2021-07-08 00:22 UTC, Mab879 commented
This rule is slightly different. We need to check files not the directories like in #7179, per the STIG.

2021-07-12 11:10 UTC, vojtapolasek requested changes
Hello, thank you for the rule. Please see comments. Most of them are just cosmetical. I am just not understanding how the test case correct_permissions.pass.sh should exactly work.

2021-07-12 11:10 UTC, vojtapolasek commented on linux_os/guide/system/permissions/files/permissions_within_important_dirs/file_groupownership_library_dirs/tests/correct_permissions.pass.sh
> +     touch $LIBDIR/LIBDIR
Maybe this might be clearer?
```suggestion
     touch $LIBDIR/testfile
```

2021-07-12 18:50 UTC, Mab879 commented
Closing this one out in favor of #7231.

2021-07-12 18:50 UTC, closed without merging