split CIS for rhel7 - section 6
ComplianceAsCode/content pull request #7219
Opened 2021-07-08 11:47 UTC by vojtapolasek

#### Description:

- update the control file
- update rule references

#### Rationale:

CIS split effort

2021-07-08 12:33 UTC, yuumasato requested changes
LGTM, just one fix on the CCE files is needed.

2021-07-08 12:33 UTC, yuumasato commented on shared/references/cce-redhat-avail.txt
> +CCE-83449-9
I think this bunch of added CCEs should not be here.
I was added in 55817077aa4c5446b83a3453f04a6b8438cc4b1e

2021-07-09 10:31 UTC, vojtapolasek commented
I believe I fixed it.

2021-07-09 11:55 UTC, yuumasato approved these changes

2021-07-09 11:55 UTC, merged