Add initial Ubuntu 20.04 STIG Profile
ComplianceAsCode/content pull request #7220
Opened 2021-07-08 16:53 UTC by dodys

#### Description:

This pull request adds initial Ubuntu 20.04 STIG profile based on the existing profile mechanism. 

Additionally, this pull request adds missing STIG references and Ubuntu prodtypes to rules used in these profiles so they could build. This is done using automated tooling previously upstreamed (or attempted to be, see the failed autorefer pull request in #6908). Note that sorting of references was not done, as that PR isn't yet merged (#6882) either.

Note: At this point in time, the profiles themselves are completed, but testing of all rules &c for Ubuntu applicability/functionality is not yet done and obviously not all rule changes have yet been upstreamed (though, numerous changes have been made internally). If you'd like us to mark it documentation_complete: false as a result, let us know.

#### Rationale:

- Maintaining prodtypes and references downstream, even with utilities to help, has resulted in significant merge conflicts. Contributing the profiles to the community and upstreaming the prodtypes/reference changes alone will help with that effort significantly.

```
Co-Authored-By: Alexander Scheel <alex.scheel@canonical.com>
Co-Authored-By: Vern Hart <vern.hart@canonical.com>
Signed-off-by: Eduardo Barretto <eduardo.barretto@canonical.com>
```

2021-07-08 16:54 UTC, cipherboy commented
/ok-to-test

2021-07-08 16:57 UTC, cipherboy approved these changes
Commenting my affirmation that this matches what I reviewed internally and I reviewed it when merging there. :-) Thanks @dodys!

2021-07-08 17:09 UTC, cipherboy requested changes
Looks like we broke SLE12, I'd drop the prodtyper commit and regenerate it, looks like we removed sle12 from file_groupownership_system_commands_dirs. :/

2021-07-08 17:26 UTC, cipherboy approved these changes
This looks better and all products build. 

```
[1004/1004] [man-page] generating man page
real 336.76
user 2011.62
sys 270.11
Test project /home/cipherboy/GitHub/dodys/scap-security-guide/build
        Start   1: sanity-ssg-tables-table-macos1015-nistrefs.html
        Start   2: sanity-ssg-tables-table-macos1015-nistrefs-moderate.html
        Start   3: sanity-ssg-tables-table-macos1015-cces.html
        Start   4: sanity-ssg-tables-table-rhcos4-nistrefs.html
```


Thanks for the quick update, @dodys!

2021-07-15 21:30 UTC, cipherboy commented
Build of all products looks good:

<details>
<summary> Build </summary>

```
start dir: /home/cipherboy/GitHub/dodys/scap-security-guide
git root: /home/cipherboy/GitHub/dodys/scap-security-guide
cc path: /usr/bin/gcc
cflags: 
cxx path: /usr/bin/g++
cxxflags: 
python path: /usr/bin/python3
cmake args: -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DPYTHON_EXECUTABLE=/usr/bin/python3 -DSSG_JINJA2_CACHE_DIR=~/.ssg_jinja_cache -DENABLE_TESTING=ON
make args: -j 10
ninja args: -j 10
ctest args:  --output-on-failure -j 4
do_env: true
do_clean: true
do_prep: true
do_build: true
do_test: true
do_rpm: false
do_deb: false
do_sdeb: false
Prepping with cmake/ninja
-- Setting build type to 'Release' as none was specified.
-- SCAP Security Guide 0.1.57
-- (see /home/cipherboy/GitHub/dodys/scap-security-guide/docs/manual/developer_guide.adoc for build instructions)
-- 
-- Found PythonInterp: /usr/bin/python3 (found version "3.9.5") 
-- Found PY_yaml: /usr/lib/python3/dist-packages/yaml  
-- Found PY_jinja2: /usr/lib/python3/dist-packages/jinja2  
-- Found PY_pytest: /usr/lib/python3/dist-packages/pytest  
-- Could NOT find PY_pytest_cov (missing: PY_PYTEST_COV) 
-- Could NOT find PY_json2html (missing: PY_JSON2HTML) 
-- Found PY_sphinx: /usr/lib/python3/dist-packages/sphinx  
-- Could NOT find PY_sphinxcontrib.autojinja (missing: PY_SPHINXCONTRIB.AUTOJINJA) 
-- Could NOT find PY_sphinx_rtd_theme (missing: PY_SPHINX_RTD_THEME) 
-- Found PY_recommonmark: /usr/lib/python3/dist-packages/recommonmark  
CMake Warning at CMakeLists.txt:166 (message):
  Won't build OCP4 content as it requires an OpenSCAP version with OCP4
  support.  See also:
  https://github.com/ComplianceAsCode/content/issues/6798.  n.b.: if 1.3.4
  fails to build OCP4 content, please update to 1.3.5


-- CMake:
-- build type: Release
-- generator: Ninja
-- source directory: /home/cipherboy/GitHub/dodys/scap-security-guide
-- build directory: /home/cipherboy/GitHub/dodys/scap-security-guide/build
--  
-- Tools:
-- python: /usr/bin/python3 (version: 3.9.5)
-- python yaml module: /usr/lib/python3/dist-packages/yaml
-- python jinja2 module: /usr/lib/python3/dist-packages/jinja2
-- oscap: /usr/bin/oscap (version: 1.2.17)
-- xsltproc: /usr/bin/xsltproc
-- xmllint: /usr/bin/xmllint
-- xmlwf: /usr/bin/xmlwf
-- sed: /usr/bin/sed
-- shellcheck (optional): /usr/bin/shellcheck
-- linkchecker (optional): LINKCHECKER_EXECUTABLE-NOTFOUND
-- grep (optional): /usr/bin/grep
-- python pytest module (optional): /usr/lib/python3/dist-packages/pytest
-- ansible-playbook module (optional): /usr/bin/ansible-playbook
-- ansible-lint module (optional): ANSIBLE_LINT_EXECUTABLE-NOTFOUND
-- yamllint module (optional): /usr/bin/yamllint
-- BATS framework (optional): BATS_EXECUTABLE-NOTFOUND
-- python sphinx module (optional): /usr/lib/python3/dist-packages/sphinx
-- python sphinxcontrib.autojinja module (optional): 
-- python sphinx_rtd_theme module (optional): 
-- python recommonmark module (optional): /usr/lib/python3/dist-packages/recommonmark
--  
-- Build options:
-- SSG vendor string: ssgproject
-- Target OVAL version: 5.11
-- Build SCAP 1.2 source data streams: ON
-- OVAL schematron validation: ON
-- shellcheck bash fixes validation: OFF
-- SVG logo in XCCDFs: ON
-- Separate SCAP files: ON
-- Ansible Playbooks: ON
-- Ansible Playbooks Per Rule: OFF
-- Bash scripts: ON
-- jinja2 cache: enabled
-- jinja2 cache dir: /home/cipherboy/.ssg_jinja_cache
--  
-- Products:
-- Chromium: ON
-- Debian 9: ON
-- Debian 10: ON
-- Example: OFF
-- Fedora: ON
-- Firefox: ON
-- JBoss Fuse 6: ON
-- JRE: ON
-- MacOS 1015: ON
-- OCP4: OFF
-- RHCOS4: ON
-- Oracle Linux 7: ON
-- Oracle Linux 8: ON
-- openSUSE: ON
-- RHEL 7: ON
-- RHEL 8: ON
-- RHEL 9: ON
-- RHOSP10: ON
-- RHOSP13: ON
-- RHV 4: ON
-- SUSE 12: ON
-- SUSE 15: ON
-- Ubuntu 16.04: ON
-- Ubuntu 18.04: ON
-- Ubuntu 20.04: ON
-- McAfee VSEL: ON
-- WRLinux 8: ON
-- WRLinux 1019: ON
--  
-- Scanning for dependencies of chromium fixes (bash, ansible, puppet, anaconda, ignition, kubernetes and blueprint)...
-- Scanning for dependencies of debian9 fixes (bash, ansible, puppet, anaconda, ignition, kubernetes and blueprint)...
-- Scanning for dependencies of debian10 fixes (bash, ansible, puppet, anaconda, ignition, kubernetes and blueprint)...
-- Scanning for dependencies of fedora fixes (bash, ansible, puppet, anaconda, ignition, kubernetes and blueprint)...
-- Scanning for dependencies of firefox fixes (bash, ansible, puppet, anaconda, ignition, kubernetes and blueprint)...
-- Scanning for dependencies of fuse6 fixes (bash, ansible, puppet, anaconda, ignition, kubernetes and blueprint)...
-- Scanning for dependencies of jre fixes (bash, ansible, puppet, anaconda, ignition, kubernetes and blueprint)...
-- Scanning for dependencies of macos1015 fixes (bash, ansible, puppet, anaconda, ignition, kubernetes and blueprint)...
-- Scanning for dependencies of rhcos4 fixes (bash, ansible, puppet, anaconda, ignition, kubernetes and blueprint)...
-- Scanning for dependencies of ol7 fixes (bash, ansible, puppet, anaconda, ignition, kubernetes and blueprint)...
-- Scanning for dependencies of ol8 fixes (bash, ansible, puppet, anaconda, ignition, kubernetes and blueprint)...
-- Scanning for dependencies of opensuse fixes (bash, ansible, puppet, anaconda, ignition, kubernetes and blueprint)...
-- Scanning for dependencies of rhel7 fixes (bash, ansible, puppet, anaconda, ignition, kubernetes and blueprint)...
-- Scanning for dependencies of rhel8 fixes (bash, ansible, puppet, anaconda, ignition, kubernetes and blueprint)...
-- Scanning for dependencies of rhel9 fixes (bash, ansible, puppet, anaconda, ignition, kubernetes and blueprint)...
-- Scanning for dependencies of rhosp10 fixes (bash, ansible, puppet, anaconda, ignition, kubernetes and blueprint)...
-- Scanning for dependencies of rhosp13 fixes (bash, ansible, puppet, anaconda, ignition, kubernetes and blueprint)...
-- Scanning for dependencies of rhv4 fixes (bash, ansible, puppet, anaconda, ignition, kubernetes and blueprint)...
-- Scanning for dependencies of sle12 fixes (bash, ansible, puppet, anaconda, ignition, kubernetes and blueprint)...
-- Scanning for dependencies of sle15 fixes (bash, ansible, puppet, anaconda, ignition, kubernetes and blueprint)...
-- Scanning for dependencies of ubuntu1604 fixes (bash, ansible, puppet, anaconda, ignition, kubernetes and blueprint)...
-- Scanning for dependencies of ubuntu1804 fixes (bash, ansible, puppet, anaconda, ignition, kubernetes and blueprint)...
-- Scanning for dependencies of ubuntu2004 fixes (bash, ansible, puppet, anaconda, ignition, kubernetes and blueprint)...
-- Scanning for dependencies of vsel fixes (bash, ansible, puppet, anaconda, ignition, kubernetes and blueprint)...
-- Scanning for dependencies of wrlinux8 fixes (bash, ansible, puppet, anaconda, ignition, kubernetes and blueprint)...
-- Scanning for dependencies of wrlinux1019 fixes (bash, ansible, puppet, anaconda, ignition, kubernetes and blueprint)...
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_CXX_COMPILER
    CMAKE_C_COMPILER
    ENABLE_TESTING


-- Build files have been written to: /home/cipherboy/GitHub/dodys/scap-security-guide/build
real 1.18
user 0.98
sys 0.20
Building with ninja
[190/1004] [rhel8-content] compiling profiles
Not building profile from /home/cipherboy/GitHub/dodys/scap-security-guide/products/rhel8/./profiles/ospp-mls.profile: documentation not complete and not a debug build
[198/1004] [rhel9-content] compiling profiles
Not building profile from /home/cipherboy/GitHub/dodys/scap-security-guide/products/rhel9/./profiles/ospp-mls.profile: documentation not complete and not a debug build
[1004/1004] [man-page] generating man page
real 311.38
user 2012.09
sys 281.94
Test project /home/cipherboy/GitHub/dodys/scap-security-guide/build
        Start   1: sanity-ssg-tables-table-macos1015-nistrefs.html
        Start   2 [...]

2021-07-15 22:02 UTC, yuumasato approved these changes
LGTM.

I also did some sample sanity testing with compare_ds.py and see no unexpected changes.

2021-07-15 22:04 UTC, merged