Add rule for RHEL-08-020300
ComplianceAsCode/content pull request #7289
Opened 2021-07-26 19:27 UTC by Mab879

#### Description:

Added rule for RHEL-08-020300 for preventing the use of dictionary words for passwords.

#### Rationale:
STIG reference: 
- https://vaulted.io/library/disa-stigs-srgs/red_hat_enterprise_linux_8_security_technical_implementation_guide/V-230377

2021-07-27 07:53 UTC, jan-cerny requested changes

2021-07-27 07:53 UTC, jan-cerny commented on linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_dictcheck/tests/enable.pass.sh
> +echo "dictcheck=0" > /etc/security/pwquality.conf
This test fails because there should be 1.

2021-07-28 12:39 UTC, jan-cerny approved these changes
Thank you for your pull request.

2021-07-28 12:39 UTC, merged

2021-08-09 13:30 UTC, mildas commented
@Mab879 @jan-cerny Please, when a new STIG rule is being added, don't forget to add SRG to `references` section in `rule.yml`.