WIP: grub2 bootloader argument template uefi support
ComplianceAsCode/content pull request #7394
Opened 2021-08-16 19:33 UTC by freddieRv

#### Description:

- Add support fort both BIOS/UEFI in grub2_bootloader_argument oval template
-  Created uefi and non-uefi versions of following rules:
    - grub2_enable_iommu_force
    - grub2_kernel_trust_cpu_rng
    - grub2_pti_argument
    - grub2_vsyscall_argument
- Updated rule.yml files to use grub2_boot_path and grub2_uefi_boot_path respectively
- Added an 'id_suffix' to oval definition in grub2_bootloader_argument oval template so that there are no repeated id's between the uefi and non-uefi rules

#### Rationale:

- Even after #6986, the grub2_bootloader_argument template supported only the config path defined in `grub2_boot_path` at product level. With this update, the uefi and non-uefi versions of the rules use `grub2_boot_path` and `grub2_uefi_boot_path` respectively.

- Fixes #6716

2021-08-16 19:36 UTC, freddieRv commented on shared/templates/grub2_bootloader_argument/template.py
> +
This feels a bit hacky. Another approach could be to add the `id_suffix` as another template parameter

2021-08-19 14:45 UTC, cipherboy commented on linux_os/guide/system/bootloader-grub2/non-uefi/file_groupowner_grub2_cfg/rule.yml
> +    {{{ describe_file_group_owner(file=grub2_boot_path+"/grub.cfg", group="root") }}}
Damn I messed that up. Great catch @freddieRv!

2021-09-06 15:14 UTC, matejak commented
/ok-to-test

2021-09-06 15:53 UTC, matejak commented on linux_os/guide/system/bootloader-grub2/uefi/grub2_uefi_kernel_trust_cpu_rng/oval/shared.xml
> +  <local_variable id="var_kernel_config_file" comment="the config file for currently running kernel" datatype="string" version="1">
Unfortunately, we can't detect identical OVAL objects and deduplicate them. The variable existing twice in the OVAL (although it is a "local" variable) creates problems, so you can work around this by duplicating it under a different name:

```suggestion
  <local_variable id="var_{{{ rule_id }}}_kernel_config_file" comment="the config file for currently running kernel" datatype="string" version="1">
```

2021-09-06 15:54 UTC, matejak commented on linux_os/guide/system/bootloader-grub2/uefi/grub2_uefi_kernel_trust_cpu_rng/oval/shared.xml
> +    <ind:filepath operation="equals" var_ref="var_kernel_config_file" />
```suggestion
    <ind:filepath operation="equals" var_ref="var_{{{ rule_id }}}_kernel_config_file" />
```

2021-09-06 15:56 UTC, matejak commented on shared/templates/grub2_bootloader_argument/oval.template
> +        <criterion test_ref="test_grub2_{{{ SANITIZED_ARG_NAME + ID_SUFFIX }}}_argument_grub_cfg"
This `SANITIZED_ARG_NAME + ID_SUFFIX` is very ugly, just use jinja's `{{% set unique_oval_id_stem=SANITIZED_ARG_NAME + ID_SUFFIX %}} (or something like that) -  that will be much better

2021-09-06 15:58 UTC, matejak commented on linux_os/guide/system/bootloader-grub2/uefi/grub2_uefi_enable_iommu_force/rule.yml
> +    cce@rhel9: CCE-83844-1
How come that those CCEs have appeared here, but they are not taken from the CCE pool?

You can either remove them, or you can assign them using the `utils/fix_rules.py` script (but you may need to rebase before that).

2021-09-06 15:58 UTC, matejak requested changes
Thank you for the PR, we appreciate it, some things need to be fixed, but the direction is good overall.

2021-09-08 16:07 UTC, freddieRv commented
Thank you for the feedback @matejak ! I will address your comments and push the new changes shortly

2022-04-26 12:17 UTC, matejak commented
The PR has developed conflicts, and it hasn't been active for a long period of time. I am closing it, but don't hesitate to reopen if conflicts are resolved, and feedback is somehow addressed.

2022-04-26 12:17 UTC, closed without merging