Convert Bash functions file include_mount_options_functions to a Jinja macro
ComplianceAsCode/content pull request #7401
Opened 2021-08-17 14:00 UTC by j-ode

#### Description:

- Converted an include file containing bash functions include_mount_options_functions to a jinja macro and replaced the inclusion of said file with macro invocation.

#### Rationale:

- #7348

2021-08-17 15:51 UTC, jan-cerny commented
It's an elegant solution which would allow you to proceed quickly. But, when I see it, I think it's not friendly to the developers that will want to use it, because they would have to open the macro definition and understand the bash code there. I think we should break it down and create a separate jinja macro for each of the small functions.

2021-08-24 13:10 UTC, jan-cerny requested changes

2021-08-24 13:11 UTC, jan-cerny commented
@j-ode Also, after you do the changes, please rebase on the latest master.

2021-08-25 15:30 UTC, matejak commented on shared/macros-bash.jinja
> +{{% macro bash_ensure_mount_option_for_vfstype(_vfstype, _new_opt, _filesystem, _type) -%}}
Moreover, if you rename `new_opt` to `new_mount_options`, then there will be nothing to document in that docstring.

Also use this opportunity to go through old comments and check out whether they make sense. What is referred to as "filesystem" is correct wrt `/etc/fstab` manpage, but I think that many people can confuse this with the "type" parameter. I highly recommend to include an example of fstab lines that show where arguments end up where.

2021-08-25 15:34 UTC, matejak commented on shared/templates/mount_option/bash.template
> +		{{{ bash_assert_mount_point_in_fstab( MOUNTPOINT ) }}}
You can use e.g. https://cryptic-cliffs-32040.herokuapp.com/ to learn about how the dashes (e.g. `{{{- bash_assert_mount_point_in_fstab( MOUNTPOINT ) -}}}`) that eat leading or trailing whitespace work.

2021-08-30 06:39 UTC, jan-cerny commented
Thank you very much for your pull request.

2021-08-30 06:39 UTC, merged