Base the RHEL9 CIS preview on RHEL8
ComplianceAsCode/content pull request #7415
Opened 2021-08-19 15:23 UTC by matejak

The previous "RHEL9 CIS profile" was the projection of the former RHEL8 profile, so it was quite misleading.

This PR harnesses our policy files to get a RHEL9 projection of the current RHEL8 CIS.

Another option could be to remove the profile files completely, as unlike e.g. ANSSI profiles, CIS is released for a particular product, not for a general Linux system that is then interpreted on a product-by-product basis. And a rela CIS benchmark for RHEL9 doesn't exist.

2021-08-20 13:14 UTC, matusmarhefka commented
@matejak We will need also kickstart files.

2021-08-23 08:09 UTC, yuumasato approved these changes
LGTM.

2021-08-23 08:11 UTC, yuumasato commented
@matejak There are rules missing CCEs. From the ctest logs:
```
xccdf_org.ssgproject.content_rule_accounts_password_pam_pwhistory_remember_password_auth
xccdf_org.ssgproject.content_rule_accounts_password_pam_pwhistory_remember_system_auth
xccdf_org.ssgproject.content_rule_root_path_no_dot
xccdf_org.ssgproject.content_rule_file_permissions_efi_grub2_cfg
xccdf_org.ssgproject.content_rule_sshd_set_loglevel_verbose
xccdf_org.ssgproject.content_rule_sshd_set_maxstartups
```

2021-08-23 10:56 UTC, matusmarhefka commented on products/rhel9/kickstart/ssg-rhel9-cis_workstation_l1-ks.cfg
> +logvol / --fstype=xfs --name=LogVol06 --vgname=VolGroup --size=10240 --grow
As we don't have other partitions, what about increasing this to make it bigger? Minimal disk size requirement should be 20 GiB so I think we can go with the initial `size=16896`. The same would apply also for the server l1.

2021-08-23 16:17 UTC, matusmarhefka commented on products/rhel8/kickstart/ssg-rhel8-cis-ks.cfg
> +logvol / --fstype=xfs --name=LogVol06 --vgname=VolGroup --size=16896 --grow
This should remain 10240.

2021-08-23 16:20 UTC, matusmarhefka requested changes

2021-08-23 16:20 UTC, matusmarhefka commented on products/rhel8/kickstart/ssg-rhel8-cis_workstation_l2-ks.cfg
> +logvol / --fstype=xfs --name=LogVol06 --vgname=VolGroup --size=16896 --grow
This should also remain 10240.

2021-08-23 16:20 UTC, matusmarhefka commented on products/rhel9/kickstart/ssg-rhel9-cis-ks.cfg
> +logvol / --fstype=xfs --name=LogVol06 --vgname=VolGroup --size=16896 --grow
This should remain 10240.

2021-08-23 16:20 UTC, matusmarhefka commented on products/rhel9/kickstart/ssg-rhel9-cis_workstation_l2-ks.cfg
> +logvol / --fstype=xfs --name=LogVol06 --vgname=VolGroup --size=16896 --grow
And the same, it should remain 10240.

2021-08-24 09:40 UTC, matusmarhefka approved these changes

2021-08-24 12:04 UTC, merged