Convert perform_audit_rules_privileged_commands_remediation bash function to a Jinja macro
ComplianceAsCode/content pull request #7491
Opened 2021-08-31 11:14 UTC by j-ode

#### Description:

- Converted the perform_audit_rules_privileged_commands_remediation bash remediation function to a jinja macro and replaced all function calls in other files with a macro invocation, as well as removed unnecessary sourcing of the /usr/share/scap-security-guide/remediation_functions folder.

#### Rationale:

- #7348

2021-08-31 11:58 UTC, jan-cerny commented on shared/macros-bash.jinja
> +{{%- endif %}}
I have a new idea that we could check that it's one of "auditctl" and "augenrules" and produce an error when the macro is used with some different value as a parameter.

Something like:

```
{{% if tool == "auditctl" %}}
...
{{% elif tool == "augenrules" %}}
...
{{%- else -%}}
{{{ raise("Unknown tool used: " + tool) }}}
{{%- endif %}}

```

The `raise()` is already used in other macros in this file so you can get inspired.

2021-08-31 11:58 UTC, jan-cerny commented on shared/macros-bash.jinja
> +	# Return match only if whole sbinary definition matched (not in the case just prefix matched!!!)
Use spaces for indentation.

2021-08-31 11:58 UTC, jan-cerny commented on shared/macros-bash.jinja
> +
trailing whitespace

2021-08-31 12:59 UTC, jan-cerny requested changes

2021-08-31 12:59 UTC, jan-cerny commented on shared/macros-bash.jinja
> +    {{{ varname }}}="{{{ value }}}"
Please don't change unrelated macros.

2021-09-02 08:57 UTC, j-ode commented on shared/macros-bash.jinja
> +    {{{ varname }}}="{{{ value }}}"
Reverted changes in commit 1a81452

2021-09-02 10:59 UTC, jan-cerny approved these changes

2021-09-02 11:00 UTC, merged