OL7 DISA STIG v2r4 update
ComplianceAsCode/content pull request #7496
Opened 2021-08-31 23:04 UTC by freddieRv

#### Description:

- Bump OL7 stig profile version to v2r4
- Update OL7 DISA STIG manual reference
- Remove OL7 DISA ID from `package_MFEhiplsm_installed` and add it to `package_mcafeetp_installed`
- Add following rules to OL7 stig profile:
  - `sudo_require_reauthentication`
  - `auditd_overflow_action`
  - `accounts_authorized_local_users`
  - `package_mcafeetp_installed`
  - `agent_mfetpd_running`
- Update DISA IDs on grub2 admin username uefi and non-uefi rules
- Also update `rsyslog_cron_logging` remediation to add service restart
- Also update wording on `accounts_users_home_files_ownership` to align with DISA STIG 

#### Rationale:

- OL profiles effort

2021-09-01 11:12 UTC, jan-cerny requested changes

2021-09-01 11:12 UTC, jan-cerny commented on linux_os/guide/system/accounts/accounts-restrictions/accounts_authorized_local_users/rule.yml
> +    stigid@l7: OL07-00-020270
This should be `stigid@ol7`.

2021-09-01 15:01 UTC, freddieRv commented on linux_os/guide/system/accounts/accounts-restrictions/accounts_authorized_local_users/rule.yml
> +    stigid@l7: OL07-00-020270
Good catch! Thank you. Addressed.

2021-09-01 15:27 UTC, freddieRv commented
commit dab7debbd00da287ae209c9f887ddfe956a074e8 fixes the issue described in https://github.com/ComplianceAsCode/content/pull/7495 the right way

2021-09-03 07:34 UTC, jan-cerny approved these changes

2021-09-03 07:34 UTC, merged