Level 2 rules for CIS
ComplianceAsCode/content pull request #7610
Opened 2021-09-22 08:29 UTC by Achilleasein

#### Description:

- _Level 2 rules for CIS_

2021-09-22 08:52 UTC, Achilleasein commented
We can probably squish the tests into one.

2021-09-22 08:53 UTC, jan-cerny commented
Hello, please follow https://chris.beams.io/posts/git-commit/.

2021-09-22 11:31 UTC, matusmarhefka commented
@Achilleasein Actually your test scripts are in wrong directory (`bash`), they should go into `tests` directory.

2021-09-22 11:41 UTC, matusmarhefka requested changes

2021-09-22 11:41 UTC, matusmarhefka commented on linux_os/guide/system/accounts/accounts-physical/require_emergency_target_auth/bash/cis_rhel7_require_emergency_target_auth.fail.sh
> +#!/bin/bash
I think we don't need another fail scenario, there is already one and we can make it applicable to all RHEL versions by modifying `platforms` metadata to contain `multi_platform_rhel`. (pass scenarios still need to be separate for RHEL7 and RHEL8).

2021-09-22 11:41 UTC, matusmarhefka commented on linux_os/guide/system/accounts/accounts-physical/require_emergency_target_auth/bash/cis_rhel7_require_emergency_target_auth.pass.sh
> +# profiles = xccdf_org.ssgproject.content_profile_cis
I think we can remove this, it should work for any profile selecting this rule.

2021-09-22 11:48 UTC, matusmarhefka commented on linux_os/guide/system/accounts/accounts-physical/require_emergency_target_auth/bash/cis_rhel7_require_emergency_target_auth.fail.sh
> +#!/bin/bash
Pretty much same applies also to the `require_singleuser_auth` rule.

2021-09-23 12:18 UTC, matusmarhefka commented
Please move your changes in your fork from master into another branch, I would also change the name of the test scripts, they don't need to contain rule ID, file names are missing pass/fail at the end and also remove `cis` from the file name as they are applicable also to other profiles. So change it to something like `rhel7_correct_value.pass.sh`.

2021-09-23 12:42 UTC, closed without merging