Implement partially Req 3.4 PCIDSS
ComplianceAsCode/content pull request #7803
Opened 2021-10-29 11:43 UTC by sherine-k

#### Description:

- This PR mainly contains implementation of requirement 3.4.1
- It also answers requirements 3.1->3.4 of the PCIDSS certification

2021-11-01 06:39 UTC, JAORMX commented
/retest

Timed out setting IdP. This is unrelated to the rules that were added here.

2021-11-01 16:38 UTC, jhrozek commented
This seems related:
```
     helpers.go:804: Result - Name: e2e-pci-dss-fips-mode-enabled - Status: FAIL - Severity: high
    helpers.go:807: E2E-FAILURE: The expected result for the fips_mode_enabled rule didn't match. Expected 'PASS', Got 'FAIL' 
```

2021-11-02 08:06 UTC, JAORMX commented on controls/pcidss_ocp4.yml
> +    - fips_mode_enabled
This makes FIPS mandatory for PCI-DSS

2021-11-02 09:29 UTC, sherine-k commented
/retest

2021-11-02 11:20 UTC, JAORMX requested changes

2021-11-02 11:20 UTC, JAORMX commented on applications/openshift/integrity/crypto/ebs_encryption_enabled/rule.yml
> +title: Ensure that FIPS mode is enabled on worker nodes
@sherine-k remember to update the title and description here.

2021-11-02 13:43 UTC, JAORMX reviewed
A minor comment left. Gotta change the title and description of one rule still. The rest looks good to me.

2021-11-02 13:43 UTC, JAORMX commented on applications/openshift/integrity/crypto/machine_volume_encrypted/rule.yml
> +title: Ensure that FIPS mode is enabled on worker nodes
This still refers to FIPS

2021-11-02 17:44 UTC, JAORMX commented
/retest

2021-11-02 19:23 UTC, JAORMX commented
/retest

Timed out applying remediations

2021-11-03 06:48 UTC, JAORMX commented
/retest

2021-11-03 08:23 UTC, JAORMX commented
```
cce CCE-85861-3 is included in files: 
 - applications/openshift/integrity/crypto/storageclass_encryption_enabled/rule.yml
 - applications/openshift/integrity/crypto/luks_enabled_on_all_nodes/rule.yml
```

2021-11-03 09:25 UTC, sherine-k commented
/retest

2021-11-03 11:14 UTC, JAORMX approved these changes

2021-11-03 11:58 UTC, JAORMX commented
/retest

Timed out remediating

2021-11-03 16:23 UTC, sherine-k commented
/retest

2021-11-04 05:48 UTC, JAORMX commented
/retest

2021-11-04 07:34 UTC, sherine-k commented
/retest

2021-11-04 09:26 UTC, merged