SLE15 Add rsh and talk server remove rules to HIPAA profile
ComplianceAsCode/content pull request #7813
Opened 2021-11-02 06:53 UTC by teacup-on-rockingchair

#### Description:

- Add rules for rsh and talk server to SLE15 HIPAA profile

#### Rationale:

- add existing rules to profile, adapt and test

2021-11-02 13:50 UTC, vojtapolasek commented
/ok-to-test

2021-11-04 08:10 UTC, vojtapolasek requested changes
Thank you for the contribution, just a small correction to keep everything in order.

2021-11-04 08:10 UTC, vojtapolasek commented on linux_os/guide/services/obsolete/r_services/package_rsh-server_removed/rule.yml
> +prodtype: ol7,ol8,rhel7,rhel8,rhel9,rhv4,ubuntu2004,wrlinux1019,sle15
Please sort prodtypse alphabetically.

2021-11-04 10:24 UTC, teacup-on-rockingchair commented on linux_os/guide/services/obsolete/r_services/package_rsh-server_removed/rule.yml
> +prodtype: ol7,ol8,rhel7,rhel8,rhel9,rhv4,ubuntu2004,wrlinux1019,sle15
Thanks done it in a97f867

2021-11-04 15:35 UTC, vojtapolasek approved these changes

2021-11-04 15:35 UTC, vojtapolasek commented
Please rebase, then it can be merged.

2021-11-05 05:51 UTC, teacup-on-rockingchair commented
> Please rebase, then it can be merged.

Done !

2021-11-09 11:39 UTC, merged