Remove testoval
ComplianceAsCode/content pull request #7822
Opened 2021-11-03 10:44 UTC by matejak

See also #2940 - testoval is broken and not used by anything / anyone.

Content authors should use the [SSG test suite](https://github.com/ComplianceAsCode/content/blob/master/tests/README.md) for testing OVALs and remediations.

2021-11-03 11:23 UTC, ggbecker commented
Looks like some of the removed code is still relevant for tests. The rules dir json can't be generated and many subsequent tests fail because they rely on this file to exist.

https://github.com/ComplianceAsCode/content/runs/4091361762

```
 56/232 Test  #62: test-rule-dir-json .......................................................***Failed    1.04 sec
Error while loading /__w/content/content/products/chromium/guide/chromium/chromium_blacklist_extension_installation/oval/chromium.xml
Traceback (most recent call last):
  File "/__w/content/content/utils/rule_dir_json.py", line 232, in <module>
    main()
  File "/__w/content/content/utils/rule_dir_json.py", line 192, in main
    rule_obj['ovals'], oval_products = handle_ovals(given_products, product_yamls, rule_obj)
  File "/__w/content/content/utils/rule_dir_json.py", line 120, in handle_ovals
    platforms = ssg.oval.applicable_platforms(oval_path)
  File "/__w/content/content/ssg/oval.py", line 49, in applicable_platforms
    raise e
  File "/__w/content/content/ssg/oval.py", line 45, in applicable_platforms
    oval_tree = ET.fromstring(header + body + footer)
NameError: name 'ET' is not defined
```

also

```
----------------------------- Captured stderr call -----------------------------
Error while loading /__w/content/content/tests/unit/ssg-module/data/group_dir/rule_dir/oval/rhel.xml
_________________________ test_find_existing_testfile __________________________

    def test_find_existing_testfile():
>       assert ssg.oval.find_testfile("disable_prelink.xml")
E       AttributeError: module 'ssg.oval' has no attribute 'find_testfile'

../../tests/unit/ssg-module/test_oval.py:25: AttributeError
_______________________ test_dont_find_missing_testfile ________________________

    def test_dont_find_missing_testfile():
>       assert ssg.oval.find_testfile("disable_prelinkxxx.xml") is None
E       AttributeError: module 'ssg.oval' has no attribute 'find_testfile'

../../tests/unit/ssg-module/test_oval.py:29: AttributeError
```

2021-11-04 08:53 UTC, jan-cerny requested changes
The testoval.py is still mentioned in the comment in ssg/build_ovals.py on line 158. Can you investigate that?

2021-11-05 17:03 UTC, matejak commented
> The testoval.py is still mentioned in the comment in ssg/build_ovals.py on line 158. Can you investigate that?

The comment probably refers to `replace_external_vars` that has been removed as part of this PR. I am not sure what to do with it. The comment suggests that some of external variables usage has been motivated by the testoval tool.
It would be probably enough to include one external var declaration per benchmark, i.e. not per rule that uses it, but we like the latter because of better readability.

2021-11-09 14:44 UTC, jan-cerny approved these changes

2021-11-09 14:44 UTC, merged