fix enable_fix_mode remediations
ComplianceAsCode/content pull request #7936
Opened 2021-11-30 08:27 UTC by vojtapolasek

#### Description:

- modify Bash and Ansible remediations of enable_fips_mode
- apart from running fips-mode-setup --enable, it now applies also the cryptopolicy configured in the profile.

#### Rationale:

- the previous implementation only used the fips-mode-setup utility to enable the FIPS mode. However, this utility always configures the "fips" cryptopolicy. However, some profiles (such as OSPP), uses a policy based on "fips" - "fips:ospp". This policy is based on "fips", it is even stricter. But due to hardcoded configuration of "fips" policy done by fips-mode-setup, the remediation always resulted in error.
- This implementation should not cause problems even if the profile for some reason tries to use FIPS mode and at the same time it tries to use policy not based on fips. In that case, the check test_system_crypto_policy_value will always make rule fail.

2021-11-30 08:28 UTC, vojtapolasek commented
I am aware that I used copy paste. We can consider macro.

2021-11-30 10:39 UTC, yuumasato commented on linux_os/guide/system/software/integrity/fips/enable_fips_mode/ansible/shared.yml
> +    line: "{{ var_system_crypto_policy }}"
I believe you need to instantiate `var_system_crypto_policy`

2021-11-30 10:56 UTC, yuumasato reviewed
I'd also update the rule description and mention that the crypto policy is expected to match `var_system_crypto_policy`

2021-12-10 15:34 UTC, vojtapolasek commented
I have updated the remediation and rule description. I was thinking about having there some Jinja conditional based on the value of var_system_crypto_policy... something like if the policy is set to FIPS, there will be no additional sentence. If there is a different policy, the sentence mentioning that the rule additionally configures a cryptography policy  would be added. But I am not sure if the build system actually supports different rule description for different profiles.

2021-12-13 13:27 UTC, yuumasato requested changes

2021-12-13 13:27 UTC, yuumasato commented on linux_os/guide/system/software/integrity/fips/enable_fips_mode/rule.yml
> +    To verify that cryptography policy has been configured correctly, run the
```suggestion
    To verify that the cryptographic policy has been configured correctly, run the
```

2021-12-13 13:27 UTC, yuumasato commented
> I was thinking about having there some Jinja conditional based on the value of var_system_crypto_policy... something like if the policy is set to FIPS, there will be no additional sentence. If there is a different policy, the sentence mentioning that the rule additionally configures a cryptography policy would be added. But I am not sure if the build system actually supports different rule description for different profiles.

I don't think this is possible with XCCDF.
The Jinja macros and conditionals are processed during content build time.
And the dynamicity of the rule descriptions at rule evaluation time are provided by `xccdf:sub` which only provides simple text substitution. AFAIK XCCDF doesn't support complex processing in the rule descriptions.

2021-12-15 10:12 UTC, vojtapolasek commented
I have accepted your suggestion. HOwever, I noticed that the variable does not show in ocil. However, it is displayed correctly in the rule description. Is that expected?

2021-12-15 10:48 UTC, yuumasato commented
> I have accepted your suggestion. HOwever, I noticed that the variable does not show in ocil. However, it is displayed correctly in the rule description. Is that expected?

Kind of :(
https://github.com/ComplianceAsCode/content/issues/4354

2021-12-15 10:49 UTC, yuumasato approved these changes

2021-12-15 11:19 UTC, yuumasato commented
/retest

2021-12-15 12:27 UTC, yuumasato commented
Seems like `ci/prow/e2e-aws-rhcos4-moderate` is failing on infra.

2021-12-15 12:28 UTC, merged