Add "Manual" Control status and update RHEL8 CIS Control file
ComplianceAsCode/content pull request #8004
Opened 2021-12-15 16:27 UTC by yuumasato

#### Description:

- Adds a new Control Status `manual` to use in items that do not expect automation
- Add `manual` status to Manual items from RHEL8 CIS
- Update `controleval.py` script to compute the `manual` status
- Select rules and update status of `6.2.7`, `6.2.8` and `6.2.20`.

#### Rationale:

- Update RHEL8 CIS state

2021-12-15 16:40 UTC, yuumasato commented
Output of `controleva.py`
```
$ python3 utils/controleval.py stats  -i cis_rhel8 -l l2_server -p rhel8
Total controls = 237
Applicable = 100.0% -- 237 / 237
Assessed = 74.68% -- 177 / 237

Automated = 68.78% -- 163 / 237
Manual = 10.13% -- 24 / 237
Supported = 0.0% -- 0 / 237
Documentation = 0.0% -- 0 / 237
Inherently Met = 0.0% -- 0 / 237
Partial = 5.91% -- 14 / 237
Missing: 1.8.1.3, 1.8.1.6, 3.4.2.2, 3.4.2.3, 3.4.3.2, 3.4.3.3, 3.4.3.4, 3.4.3.6, 3.4.3.7, 3.4.3.8, 3.4.4.1.1, 3.4.4.1.2, 3.4.4.1.4, 3.4.4.1.5, 3.4.4.2.1, 3.4.4.2.2, 3.4.4.2.4, 3.4.4.2.5, 4.1.13, 4.1.16, 4.2.1.3, 4.2.3, 5.2.15, 5.2.2, 5.2.3, 5.3.1, 5.3.2, 5.3.3, 5.4.2, 5.5.1.5, 6.2.1, 6.2.10, 6.2.12, 6.2.14, 6.2.19, 6.2.9
```

2021-12-15 17:32 UTC, Mab879 requested changes
Other than than the missing CCEs, this looks good to me.

2021-12-15 17:32 UTC, Mab879 commented on controls/cis_rhel8.yml
>        - accounts_user_interactive_home_directory_exists
This might be the source of the missing cce.

2021-12-15 18:34 UTC, yuumasato commented on utils/controleval.py
> +    print("Missing:", ", ".join(sorted(str(c.id) for c in applicablelist - assessedlist)))
I forgot to mention that the change in line 69 fixes an issue when processing CIS control files:
```
python3 utils/controleval.py stats  -i cis_rhel7 -l l2_server -p rhel7
Total controls = 248
Applicable = 100.0% -- 248 / 248
Assessed = 70.97% -- 176 / 248

Automated = 63.71% -- 158 / 248
Supported = 0.0% -- 0 / 248
Documentation = 0.0% -- 0 / 248
Inherently Met = 0.0% -- 0 / 248
Partial = 7.26% -- 18 / 248
Traceback (most recent call last):
  File "/home/wsato/git/content/utils/controleval.py", line 123, in <module>
    main()
  File "/home/wsato/git/content/utils/controleval.py", line 119, in main
    subcmds[args.subcmd](controls_manager, args)
  File "/home/wsato/git/content/utils/controleval.py", line 82, in stats
    calculate_stats(ctrls)
  File "/home/wsato/git/content/utils/controleval.py", line 68, in calculate_stats
    print("Missing:", ", ".join(sorted(c.id for c in applicablelist - assessedlist)))
TypeError: '<' not supported between instances of 'float' and 'str'

```

2021-12-15 22:27 UTC, Mab879 commented
/retest

2021-12-16 14:15 UTC, yuumasato commented
Just resolved a conflict with the added CIS references.

2021-12-16 21:22 UTC, Mab879 commented
/retest

2021-12-17 01:58 UTC, Mab879 approved these changes

2021-12-17 01:58 UTC, merged