Introduce a shellcheck test
ComplianceAsCode/content pull request #8032
Opened 2022-01-06 15:57 UTC by matejak

Review all generated remediations by shellcheck, and fix issues this test uncovers.

2022-01-10 13:03 UTC, matejak commented on cmake/SSGCommon.cmake
> +        # Doesn't work, as the glob is evaluated at cmake-time instead of test exec time
It's written in the PR description - perhaps somebody can point out how to make this work. If not, it will be removed before un-drafting this PR.

2022-01-10 13:06 UTC, matejak commented on shared/macros-bash.jinja
> +{{% macro pam_faillock_stuff(remediation)  %}}
yes, and name sucks too.
If this macro is not made obsolete by other PRs s.a. #8040 then I will fix it, but I think that commits touching PAM will probably get dropped.

2022-01-21 11:28 UTC, matejak commented
The PR is quite huge, because it introduces the test and also fixes issues that it discovers. One possible way of getting forward could be to nominate individual commits to become separate PRs that could be readily merged.

2022-02-22 10:47 UTC, jan-cerny requested changes
Focus on failing test scenarios. Then, you can split it as you wish.

2022-02-22 10:47 UTC, jan-cerny commented on linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_interactive_users/bash/shared.sh
> +{{% call iterate_over_command_output("dir", "awk -F':' '{ if ($3 >= {{{ uid_min }}} && $3 != 65534) print $6}' /etc/passwd") -%}}
The uid_min won't get expanded.

2022-02-23 12:32 UTC, matejak commented
I think that it doesn't make sense to split the PR further - we can proceed with it as it is.

2022-02-24 14:43 UTC, jan-cerny approved these changes

2022-02-24 14:43 UTC, merged