Document GHA release process
ComplianceAsCode/content pull request #8096
Opened 2022-01-24 14:31 UTC by yuumasato

#### Description:

- Update documentation on release process
- Remove unused tooling

#### Rationale:

- Docs should be up to date

2022-01-24 14:32 UTC, yuumasato commented
The `release_tools` directory is kinda empty, where should the `release_tools/README.md` be moved and renamed to?

2022-01-24 14:52 UTC, Mab879 commented
We could add section to the Developer Guide at https://complianceascode.readthedocs.io/en/latest/ for the release docs.

2022-04-12 12:26 UTC, ggbecker requested changes
Since `release_tools/README.md` is being removed, you need to delete it from here:

https://github.com/ComplianceAsCode/content/blob/33949fb588c22da73c82bce4ddd75798a3568d60/docs/conf.py#L19-L21

2022-04-12 12:26 UTC, ggbecker commented on docs/index.rst
> +    docs/release_process
```suggestion
    release_process
```

the context is already `docs` directory

2022-04-12 12:40 UTC, ggbecker requested changes

2022-04-12 12:40 UTC, ggbecker commented on docs/release_process.md
> +Everybody is welcome to test the stabilization branch and propose fixes.
```suggestion
Before each release we initiate a stabilization period which is typically two weeks long.
A stabilization branch is branched from master and more extensive testing is done on the content.
The goal is to have space and time to find and fix issues before the release.
Everyone is welcome to test the stabilization branch and propose fixes.
```

2022-04-12 12:40 UTC, ggbecker commented on docs/release_process.md
> +  This makes the milestone less visible and reduces chance of PRs and Issues being added to it
```suggestion
  This makes the milestone less visible and reduces the chance of PRs and Issues being added to it
```

2022-04-12 12:40 UTC, ggbecker commented on docs/release_process.md
> +  It is still possible to add itens to the closed Milestone, just select it in the `closed` tab.
```suggestion
  It is still possible to add items to the closed Milestone, just select it in the `closed` tab.
```

2022-04-12 12:40 UTC, ggbecker commented on docs/release_process.md
> +- Announce start of stabilization period on the mailing list
```suggestion
- Announce the start of stabilization period on the mailing list
```

2022-04-12 12:40 UTC, ggbecker commented on docs/release_process.md
> +General rule is that the PR Titles will compose the body of the changelog.
```suggestion
The general rule is that the PR Titles will compose the body of the changelog.
```

2022-04-12 12:40 UTC, ggbecker commented on docs/release_process.md
> +- Create and push **vX.Y.Z** tag to the GitHub repo. Wait for the release action
```suggestion
- Create and push a **vX.Y.Z** tag to the GitHub repo. Wait for the release action
```

2022-04-13 14:49 UTC, merged