Moved chromium bash remediations to jinja
ComplianceAsCode/content pull request #8135
Opened 2022-02-01 14:16 UTC by j-ode

#### Description:

- Replaced repetitive chromium bash remediations with a new jinja macro invocation
- Also fixed some issues with chromium remediations

#### Rationale:

- Better readability and easier creation of new remediations
- Removes duplicated code

#### Conflicts:

@matejak has changed 4 chromium remedations in #8032. I already fixed chromium_http_authentication, where there was an obvious naming mistake, but as for chromium_blacklist_extension_installation and chromium_disable_plugin_blacklist, I am not sure what those changes do, especially the triple quoting of the POL_SETTING variable which seems to be a simple string. Also chromium_policy_file was changed, not sure if only for syntactic reasons. @matejak do you think I should add all your changes to these new macro invocations?

2022-02-02 07:39 UTC, jan-cerny commented on shared/macros-bash.jinja
> +grep -q {{{ pol_setting }}} {{{ chrome_pol_dir }}}/{{{ chrome_pol_file }}}
here remove `/` as well

2022-02-02 07:39 UTC, jan-cerny commented on products/chromium/guide/chromium/chromium_default_search_provider_name/bash/chromium.sh
> +{{{ bash_chromium_pol_setting("chrome_stig_policy.json", "/etc/chromium/policies/managed/", "DefaultSearchProviderName", "$(echo ${var_default_search_provider_name} | sed 's/\//\\\/\\/')", "${var_def
For better readability I would extract the subshell command output to a separate variable and then pass the variable in.

2022-02-02 07:39 UTC, jan-cerny commented on products/chromium/guide/chromium/chromium_blacklist_extension_installation/bash/chromium.sh
> +{{{ bash_chromium_pol_setting("chrome_stig_policy.json", "/etc/chromium/policies/managed/", "ExtensionInstallBlacklist", "\[\"*\"\]") }}}
All files in our project should have a newline at the end of the file.

2022-02-02 07:39 UTC, jan-cerny commented on shared/macros-bash.jinja
> +   sed -i -e '/{/a \  "'{{{ pol_setting }}}'": '{{{ pol_setting_val_edit }}}',' {{{ chrome_pol_dir }}}/{{{ chrome_pol_file }}}
and here

2022-02-07 08:40 UTC, jan-cerny commented
> @matejak has changed 4 chromium remedations in https://github.com/ComplianceAsCode/content/pull/8032. I already fixed chromium_http_authentication, where there was an obvious naming mistake, but as for chromium_blacklist_extension_installation and chromium_disable_plugin_blacklist, I am not sure what those changes do, especially the triple quoting of the POL_SETTING variable which seems to be a simple string. Also chromium_policy_file was changed, not sure if only for syntactic reasons. @matejak do you think I should add all your changes to these new macro invocations?

Yes, I think that would be ideal. You can also try to install ShellCheck and run ShellCheck on that yourself.

@matejak you were mentioned so do you have any opinion?

2022-02-08 13:17 UTC, jan-cerny commented on shared/macros-bash.jinja
> +{{%- macro bash_chromium_pol_setting(chrome_pol_file, chrome_pol_dir, pol_setting, pol_setting_val, pol_setting_val_edit=pol_setting_val) %}}
pol_setting_val_edit isn't documented

2022-02-09 08:44 UTC, jan-cerny requested changes
You requested a review from me, but at the same time the PR is in the draft state, ie. you didn't mark the PR as a ready for review. Make up your mind.

The commit messages should be written in an imperative form. For example, instead of "**Moved** repetitive chromium bash remediations to a single jinja macro" you should use "**Move** repetitive chromium bash remediations to a single jinja macro". Also, the commit messages should explain why is something happening instead of obvious what is happening. This article will help you to write excellent commits: https://cbea.ms/git-commit/ I recommend reading it, it's an amazing article.

2022-02-09 08:44 UTC, jan-cerny commented on shared/macros-bash.jinja
> +<<<<<<< HEAD
Watch carefully!

2022-02-09 08:44 UTC, jan-cerny commented on shared/macros-bash.jinja
> +{{%- macro bash_chromium_pol_setting(chrome_pol_file, chrome_pol_dir, pol_setting, pol_setting_val, pol_setting_val_edit=None) %}}
Thumbs up for inventing the workaround!

2022-02-09 14:11 UTC, j-ode commented
/retest

2022-02-09 16:11 UTC, j-ode commented
/retest

2022-02-09 18:34 UTC, j-ode commented
/retest

2022-02-10 07:33 UTC, jan-cerny approved these changes

2022-02-10 07:33 UTC, merged

2022-02-15 13:05 UTC, matejak commented on shared/macros-bash.jinja
> +{{ pol_setting_val_edit=pol_setting_val }}
This clearly doesn't work.

2022-02-15 13:06 UTC, matejak commented on shared/macros-bash.jinja
> +   sed -i -e '/{/a \  "'{{{ pol_setting }}}'": '{{{ pol_setting_val_edit }}}',' {{{ chrome_pol_dir }}}{{{ chrome_pol_file }}}
`pol_setting` is a static string, so we don't need this gymnastics with quotes in case it is a variable.

2022-02-15 13:07 UTC, matejak commented on shared/macros-bash.jinja
> +if ! [ $? -eq 0 ] ; then
One could call grep directly instead of asking for the return code later.