Introduce nonzero_check var to accounts_password template
ComplianceAsCode/content pull request #8164
Opened 2022-02-04 22:13 UTC by Xeicker

#### Description:

- Added nonzero_check variable with default value set to False to the accounts_password template. And implement conditionally this behavior in which OVAL checks if the value obtained is different to 0.This could be useful to future rules since zero is a special value in a few related configurations
- This new variable has been implemented in the accounts_password_pam_maxclassrepeat rule

#### Rationale:

- For OL7 the STIG id OL07-00-010190 needs to check both if maxclassrepeat is less than 4 and different to 0. For this reason included the variable nonzero_check with default value False this way the rule keeps using the template accounts_password without modifying other rules behaviour

2022-02-04 22:13 UTC, pep8speaks commented
Hello @Xeicker! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`shared/templates/accounts_password/template.py`](https://github.com/ComplianceAsCode/content/blob/aae3558d4acf77154e49b37b1bd43ea5f438a08c/shared/templates/accounts_password/template.py):

> [Line 6:100](https://github.com/ComplianceAsCode/content/blob/aae3558d4acf77154e49b37b1bd43ea5f438a08c/shared/templates/accounts_password/template.py#L6): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (110 > 99 characters)

2022-02-04 22:24 UTC, ggbecker commented on linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_maxclassrepeat/rule.yml
> +        nonzero_check@ol7: "true"
```suggestion
        nonzero_check: "true"
```

I believe this change can be applied to all products. RHEL STIG also brings this change in the latest releases. Please update the description accordingly as well.

2022-02-04 22:28 UTC, Mab879 commented
/ok-to-test

2022-02-07 14:05 UTC, ggbecker requested changes
1 - Can you please add documentation for this new template attribute here: https://github.com/ComplianceAsCode/content/blame/master/docs/templates/template_reference.md#L3

2 - At the same place above, please update the `Languages` to `Ansible, Bash, OVAL` since the template provides all these languages and the section was outdated apparently.

3 - Please update the rule's description to in sync with what the OVAL check does. Include in the description that the value `0` is not accepted as a compliant value.

2022-02-08 12:13 UTC, ggbecker commented
> 1 - Can you please add documentation for this new template attribute here: https://github.com/ComplianceAsCode/content/blame/master/docs/templates/template_reference.md#L3
> 
> 2 - At the same place above, please update the `Languages` to `Ansible, Bash, OVAL` since the template provides all these languages and the section was outdated apparently.
> 
> 3 - Please update the rule's description to in sync with what the OVAL check does. Include in the description that the value `0` is not accepted as a compliant value.

I took the liberty to push some commits to address the requests because it also benefits other products and we want to merge this ASAP. Thanks for opening this.

2022-02-08 12:13 UTC, ggbecker approved these changes

2022-02-08 17:36 UTC, Xeicker commented
> I took the liberty to push some commits to address the requests because it also benefits other products and we want to merge this ASAP. Thanks for opening this.

Sorry you needed to do so. I wasn't near to a computer these days

2022-02-09 14:40 UTC, yuumasato commented on shared/templates/accounts_password/oval.template
> +  <ind:textfilecontent54_state id="state_password_pam_{{{ VARIABLE }}}_zero_boundary" version="1">
You can also add the state `state_password_pam_{{{ VARIABLE }}}_zero_boundary` to the test `test_password_pam_pwquality_{{{ VARIABLE }}}`. Then the object will have to conform to both states.

If you'd like to be more explicit `state_operator="AND"` could be added to the test too.
Example of `state_operator` use: https://github.com/ComplianceAsCode/content/blob/2b022d2af8c5c3f18b2bc123df3638b90248a532/linux_os/guide/system/accounts/accounts-restrictions/root_logins/no_shelllogin_for_systemaccounts/oval/shared.xml#L155

2022-02-09 14:40 UTC, yuumasato commented on docs/templates/template_reference.md
> +        **zero_boundary_operation** parameter (default value: `"false"`)
Would it make sense to get rid of `check_zero_boundary` and just use `zero_boundary_operation`?
(Suggestion) And maybe rename it to `zero_comparison_operation`

2022-02-09 14:40 UTC, yuumasato commented on docs/templates/template_reference.md
> +    configuration in `/etc/security/pwquality.conf`.
Maybe we should add to the template description that it only compares the parameter value against the xccdf variable, that it does not check the value of the parameter in relation to zero.
And to compare the parameter value against zero, `zero_boundary_operation` needs to be set.

2022-02-09 14:40 UTC, yuumasato commented on docs/templates/template_reference.md
> +        set to `"true"` it will test if the value respects the a zero
text suggestion: test if the parameter value respects the `zero_boundary_operation` when compared to zero.

2022-02-09 17:02 UTC, yuumasato approved these changes

2022-02-09 17:03 UTC, merged