Remove missing parameter pass from SSH rules
ComplianceAsCode/content pull request #8179
Opened 2022-02-08 12:40 UTC by ggbecker

#### Description:

- Remove missing parameter pass from SSH rules. Require explicit configuration setting in files.

#### Rationale:

- Related to: https://github.com/ComplianceAsCode/content/pull/8127

2022-02-11 12:39 UTC, jhrozek commented
/retest
the OCP CI should now be fixed (if not, maybe rebasing on master to make sure the current OCP fixes are pulled in should help)

2022-03-28 10:50 UTC, pep8speaks commented
Hello @ggbecker! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`shared/templates/sshd_lineinfile/template.py`](https://github.com/ComplianceAsCode/content/blob/286debde5537ff2abbc7d8c9d08496ac9cc2f2ad/shared/templates/sshd_lineinfile/template.py):

> [Line 7:100](https://github.com/ComplianceAsCode/content/blob/286debde5537ff2abbc7d8c9d08496ac9cc2f2ad/shared/templates/sshd_lineinfile/template.py#L7): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (108 > 99 characters)

2022-04-06 13:42 UTC, ggbecker commented
/retest

2022-04-13 19:21 UTC, Mab879 commented
/retest

2022-04-19 19:53 UTC, Mab879 requested changes
This will be nice addition to the project. 

Please rebase this PR and I will review.

2022-04-20 16:04 UTC, ggbecker commented
> This will be nice addition to the project.
> 
> Please rebase this PR and I will review.

Rebased.

2022-04-22 16:31 UTC, Mab879 approved these changes

2022-04-22 16:32 UTC, Mab879 commented
/retest

2022-04-23 01:56 UTC, Mab879 requested changes

2022-04-23 01:56 UTC, Mab879 commented on shared/templates/sshd_lineinfile/template.py
> +    is_default_value = parse_template_boolean_value(data, parameter="is_default_value", default_value=False)
Line is too long, 107 > 99. Might be worth it to break it up.

2022-05-02 21:22 UTC, Mab879 approved these changes

2022-05-02 21:22 UTC, merged