Fix bug 1195533
ComplianceAsCode/content pull request #8217
Opened 2022-02-14 10:20 UTC by anivan-suse

#### Description:
Add bash remediation for rule: file_etc_security_opasswd

#### Rationale:
- Fixes # Bug 1195533: https://bugzilla.suse.com/show_bug.cgi?id=1195533

2022-02-15 10:22 UTC, matejak requested changes
Thank you for your PR, there are just some minor issues that can be fixed easily, plus a suggestion to remove comments.

2022-02-15 10:22 UTC, matejak commented on linux_os/guide/system/permissions/files/permissions_important_account_files/file_etc_security_opasswd/bash/shared.sh
> +# platform = multi_platform_sle
I suggest to leave `multi_platform_all` here - the applicability of the remediation is already restricted by the applicability of the rule. The fix doesn't contain anything that is SLE-specific and not part of the rule scope.

2022-02-15 10:22 UTC, matejak commented on linux_os/guide/system/permissions/files/permissions_important_account_files/file_etc_security_opasswd/bash/shared.sh
> +# Owner group mode root.root 0600
The remediation code explains itself quite clearly, so I suggest to get rid of those comments.

2022-02-15 10:22 UTC, matejak commented on linux_os/guide/system/permissions/files/permissions_important_account_files/file_etc_security_opasswd/bash/shared.sh
> +chown root.root /etc/security/opasswd
The user-group separator is `:` already for some time, and [usage of dot is discouraged](https://www.gnu.org/software/coreutils/manual/html_node/chown-invocation.html).

2022-03-04 16:33 UTC, matejak commented
Thank you for fixing the remediation, it looks good now, but please give us a test scenario as well.

2022-05-13 14:51 UTC, brett060102 commented
This PR can be closed. The issue was addressed in PR https://github.com/ComplianceAsCode/content/pull/8552

2022-05-13 15:02 UTC, closed without merging