fix aide_build_database rule and remediation to work with sles 12 and 15
ComplianceAsCode/content pull request #8287
Opened 2022-03-03 17:56 UTC by brett060102

aide_build_database check and remediation  which is in the cis profile for sle12 and sle15 does not work for SLE 12/15.

#### Description:

- There were a number of issues:
-  oval/shared.xml
   assumeed aide.conf had:
        @@define DBDIR /path
        database_out=file:@@{DBDIR}/filename
        database=file:@@{DBDIR}/filename
SLE 12 and 15 does not use: :@@{DBDIR} it just has:
         database_out=file:/pathfile
         database=file:/path/file

- in remediation
1:  bash was not enabled for sle
2: sle uses /var/lib/aide/aide.db.new and /var/lib/aide/aide.db not /var/lib/aide/aide.db.new.gz and /var/lib/aide/aide.db.gz
3: path to aide is /usr/bin/aide as opposed to /usr/sbin/aide --init

- in the rule.yml:
   Need to make sle aware for file name and path differences.
   Since .gx nv not gz also applied to ubuntu needed to re-code some
   {{% if not in product %}} to
   {{% if 'ubuntu' in product or 'sle' in product %}}

#### Rationale:

- get aide_build_database working for sle 12/15

2022-03-04 13:24 UTC, jan-cerny commented
/ok-to-test

2022-03-04 21:29 UTC, Mab879 requested changes
Thanks for the PR. Just one minor change to keep everything consistent.

2022-03-04 21:29 UTC, Mab879 commented on linux_os/guide/system/software/integrity/software-integrity/aide/aide_build_database/ansible/shared.yml
> +{{% if 'sle' in product %}}
```suggestion
{{% if 'ubuntu' in product or 'sle' in product %}}
```

2022-03-04 22:33 UTC, brett060102 commented
Accepted suggestion. Thought about that initially, but don't like changing behavior for releases that I am not working on.

2022-03-07 17:11 UTC, brett060102 commented
@Mab879 requested change has been made.

2022-03-07 20:05 UTC, Mab879 approved these changes
Thanks!

2022-03-07 20:05 UTC, merged