Fix accounts_umask_etc_bashrc to work with sle12/15
ComplianceAsCode/content pull request #8297
Opened 2022-03-07 00:32 UTC by brett060102

sles 12/15 uses /etc/bash.bashrc not /etc/bashrc

#### Description:

- sles 12/15 uses /etc/bash.bashrc not /etc/bashrc

1: update tests and remediation to handle /etc/bash.bashrc
2: change platform to be multi_platform_all in bash remediation to match
   ansible code.

#### Rationale:

- get accounts_umask_etc_bashrc working for sle12/15

2022-03-07 13:46 UTC, Mab879 commented
/ok-to-test

2022-03-09 09:31 UTC, jan-cerny requested changes
@brett060102 Can you add this change also to `rule.yml` of this rule to make the rule description aligned with bash/ansible?

2022-03-09 14:40 UTC, brett060102 commented
@jan-cerny Thank you and done.

2022-03-09 15:44 UTC, jan-cerny approved these changes
great!

2022-03-09 15:44 UTC, merged