Add auid criteria to rules related to syscall audit rules
ComplianceAsCode/content pull request #8327
Opened 2022-03-10 18:39 UTC by Xeicker

#### Description:

-  Added the auid criteria:` -F auid>=1000 -F auid!=unset`. To the rules `audit_rules_kernel_module_loading_init`, `audit_rules_kernel_module_loading_finit` and `audit_rules_kernel_module_loading_delete`

#### Rationale:

- This is to make those rules compliant with DISA's STIG requirementes OL08-00-030360, OL08-00-030380 and OL08-00-030390 for ol8; and RHEL-08-030360 and RHEL-08-030390 for rhel8

2022-03-24 16:43 UTC, vojtapolasek commented
/ok-to-test

2022-03-25 08:32 UTC, JAORMX commented
/ok-to-test

2022-03-25 10:24 UTC, ggbecker commented
I'm pushing for this change to be applied as well for STIG EL7. This way we don't need the jinja macros and it makes the content more accurate. Unfortunately the change takes some time to propagate so we will need to live with these ifs for some time.

2022-03-29 08:01 UTC, vojtapolasek commented
/retest

2022-03-29 08:53 UTC, vojtapolasek requested changes
Hello, thank you for the changes, they look sane.
However, it would be good if you could modify tests as well. You will have to create another set of tests. One will be for OL8 and RHEL8,  other will be for the rest.
You can see example of such tests here:
https://github.com/ComplianceAsCode/content/tree/master/linux_os/guide/system/auditing/grub2_audit_argument/tests
Notice the
```
# platform = Red Hat Enterprise Linux 7
```
and similar lines at the top of test scenarios.

2022-03-29 17:14 UTC, Xeicker commented
> Hello, thank you for the changes, they look sane. However, it would be good if you could modify tests as well. You will have to create another set of tests. One will be for OL8 and RHEL8, other will be for the rest. You can see example of such tests here: https://github.com/ComplianceAsCode/content/tree/master/linux_os/guide/system/auditing/grub2_audit_argument/tests Notice the
> 
> ```
> # platform = Red Hat Enterprise Linux 7
> ```
> 
> and similar lines at the top of test scenarios.

I was considering to use JINJA instead, as in https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/services/dhcp/disabling_dhcp_server/service_dhcpd_disabled/tests/service_enabled.fail.sh

Because in this case there are many platforms that should be included in previous tests and only RHEL8 and OL8 for the new ones. So the JINJA approach would be easier

2022-03-30 08:15 UTC, vojtapolasek commented
OK, that is a solution as well. Let's try and see.

2022-04-04 09:18 UTC, vojtapolasek commented
/retest

2022-04-04 10:39 UTC, vojtapolasek commented
Hello,
thank you for tests. There is one more thing to get done - test scenarios have to account for the case when the directory /etc/audit/rules.d does not exist. Can you add some condition at the begining of scenarios to create it?
Thank you.

2022-04-04 14:48 UTC, vojtapolasek commented
/retest

2022-04-05 09:43 UTC, vojtapolasek commented
/retest

2022-04-05 09:56 UTC, vojtapolasek approved these changes
I am approving this. thank you for all the changes. the failing tests are not related to the rules you have modified, it might be problemin the algorithm which selects rules to test.
Let's wait for the Openshift CI.

2022-04-06 06:37 UTC, vojtapolasek commented
There are temporary problems with Openshift CI and rule modifications do not touch OCP content. Merging.

2022-04-06 06:37 UTC, merged