Update package_krb5-server_removed
ComplianceAsCode/content pull request #8452
Opened 2022-03-28 23:16 UTC by Xeicker

#### Description:

- Update the rule with DISA's content as this is not used by any other product/profile. Select the rule for ol8 and rhel8 STIG profiles

#### Rationale:

- This rule complies with OL08-00-010163 & RHEL-08-010163

2022-03-29 12:35 UTC, Mab879 commented
/ok-to-test

2022-03-30 10:07 UTC, vojtapolasek requested changes
Hello,
thank you very much for the contribution. Please see comments.

2022-03-30 10:07 UTC, vojtapolasek commented on products/rhel8/profiles/stig.profile
> +    - package_krb5-server_removed
Thank you very much for enhancing the RHEL8 profile as well.
We have some additional tests for RHEL profiles to ensure that they do not get modified by accident. We store current compiled version of the profile (without comments etc) in tests/data/profile_stability/rhel8/stig.profile.
Could you please do the following:
1. ./build_product rhel8
2. cp build/rhel8/profiles/stig.profile tests/data/profile_stability/rhel8/stig.profile
3. the same for stig_gui.profile cause it extends the stig profile
4. commit

Thank you.

2022-03-30 21:16 UTC, Xeicker commented on linux_os/guide/services/kerberos/package_krb5-server_removed/rule.yml
> -    {{{ describe_package_remove(package="krb5-server") }}}
I think no strong reason. I restored it as it was

2022-03-30 21:16 UTC, Xeicker commented on linux_os/guide/services/kerberos/package_krb5-server_removed/rule.yml
> +    Unapproved mechanisms that are used for authentication to the cryptographic
I think no strong reason. I restored it as it was

2022-03-31 11:44 UTC, vojtapolasek commented
Hello, thank for fixes. I see you took the CCE from the cce-redhat-avail.txt. But you have to actually use the cce by putting the 
```
identifiers:
    cce@rhel8: <PUT CCE HERE>
```
into the rule.yml file for the rule. I am sorry if I did not explain this clearly before.

2022-03-31 16:38 UTC, Xeicker commented
Apparently I restored too much in rule.yml, sorry

2022-04-01 12:56 UTC, vojtapolasek commented
/retestHello, thank for fixes. I see you took the CCE from the cce-redhat-avail.txt. But you have to actually use the cce by putting the 
```
identifiers:
    cce@rhel8: <PUT CCE HERE>
```
into the rule.yml file for the rule. I am sorry if I did not explain this clearly before.

2022-04-01 12:58 UTC, vojtapolasek approved these changes
Looks good now, thank you.

2022-04-01 12:59 UTC, vojtapolasek commented
/retest

2022-04-04 09:23 UTC, vojtapolasek commented
/retest

2022-04-05 11:34 UTC, vojtapolasek commented
/retestH

2022-04-06 06:53 UTC, merged