Update SRG-OS-000324-GPOS-00125 for RHEL 9
ComplianceAsCode/content pull request #8491
Opened 2022-04-04 21:00 UTC by Mab879

#### Description:
- Update SRG-OS-000324-GPOS-00125 for RHEL 9
- Add fix tools rules in SRG-OS-000324-GPOS-00125

#### Rationale:

RHEL 9 STIG

2022-04-05 11:27 UTC, ggbecker commented on controls/stig_rhel9/SRG-OS-000324-GPOS-00125.yml
>              - package_sudo_installed
Cross referencing this SRG with the rules listed here I noticed that in RHEL8 STIG for example, only 
```
            - sysctl_fs_protected_hardlinks
            - sysctl_fs_protected_symlinks
```
have the SRG mapped, other rules don't have it. In RHEL7 STIG there are four items that have this SRG, we may want to double check this. We may want to check if rules here are actually applicable to RHEL8/RHEL9 some of them are enabled in RHEL8/9 content but maybe they don't make sense anymore.

2022-04-05 11:28 UTC, ggbecker commented on controls/stig_rhel9/SRG-OS-000324-GPOS-00125.yml
>              - package_sudo_installed
this should help us quickly identify rules and their SRG mapping: https://github.com/ComplianceAsCode/content/pull/8493

it wouldn't solve everything though

2022-04-06 09:57 UTC, jan-cerny requested changes

2022-04-06 09:57 UTC, jan-cerny commented on linux_os/guide/system/permissions/files/sysctl_fs_protected_symlinks/rule.yml
> +    Verify the operating system is configured to enable DAC on hardlinks with the following commands:
```suggestion
    Verify the operating system is configured to enable DAC on symlinks with the following commands:
```

2022-04-06 09:57 UTC, jan-cerny commented on linux_os/guide/system/software/sudo/package_sudo_installed/rule.yml
> +    {{{ describe_package_remove(package="sudo") }}}
You want to install sudo, not to remove sudo.

2022-04-20 08:28 UTC, jan-cerny commented
@Mab879 it needs one more rebase :crying_cat_face:

2022-04-22 08:12 UTC, jan-cerny approved these changes

2022-04-22 08:12 UTC, merged