Update SRG-OS-000114-GPOS-00059 for RHEL 9 STIG
ComplianceAsCode/content pull request #8505
Opened 2022-04-07 08:51 UTC by jan-cerny

#### Description:

adds fix texts, Ansible remediations, fixes OCIL

#### Rationale:

RHEL 9 STIG

2022-04-07 13:09 UTC, Mab879 reviewed
Just a few comments. If you can provide a source for device IDs that would be helpful.

2022-04-08 18:56 UTC, Mab879 commented on linux_os/guide/system/software/gnome/gnome_media_settings/dconf_gnome_disable_automount_open/rule.yml
> +    First, add or update the following section
That sounds reasonable.

2022-04-11 13:49 UTC, Mab879 commented
/retest

2022-04-11 15:37 UTC, jan-cerny commented
/retest

2022-04-13 12:53 UTC, jan-cerny commented
/retest

2022-04-19 08:48 UTC, jan-cerny commented
I have rebased this pull request on the top of the currrent master branch and I have replaced fix by fixtext and resolved conflict with moving Jinja macro to a different file.

2022-04-19 13:42 UTC, jan-cerny commented
/retest

2022-04-19 17:08 UTC, Mab879 requested changes
Just one minor change requested.

Thanks for the PR.

2022-04-19 17:08 UTC, Mab879 commented on linux_os/guide/system/permissions/mounting/service_autofs_disabled/rule.yml
> +    Configure the operating system to disable the ability to automount devices.
```suggestion
    Configure {{{ full_name }}} to disable the ability to automount devices.
```

2022-04-20 12:03 UTC, Mab879 approved these changes

2022-04-20 12:03 UTC, Mab879 commented
/retest

2022-04-20 17:46 UTC, Mab879 commented
@jan-cerny Can you take look a the merge conflict?

2022-04-22 07:48 UTC, jan-cerny commented
/retest

2022-04-22 07:48 UTC, jan-cerny commented
Hi, it's now rebased again.

2022-04-22 19:17 UTC, Mab879 commented
/retest

2022-04-25 13:00 UTC, Mab879 commented
/retest

2022-04-25 19:30 UTC, Mab879 commented
So those OpenShift CI errors are giving me some pause before I merged them.

@rhmdnd or @Vincent056 I think these failures might be valid, can you please confirm?

2022-04-28 06:11 UTC, jan-cerny commented
I have resolved the conflict and I have rebased on the top of the latest upstream branch.

2022-04-29 12:14 UTC, Mab879 commented
/retest

2022-04-29 17:25 UTC, Vincent056 commented
Since https://github.com/ComplianceAsCode/content/pull/8564 has just merged, the test should pass once this PR rebase.

2022-05-02 10:46 UTC, jan-cerny commented
I have rebased on the top of the latest upstream branch.

2022-05-02 13:37 UTC, Mab879 commented
/retest

2022-05-02 16:27 UTC, Mab879 commented
Waving SSGTS, the tests pass locally.

2022-05-02 16:27 UTC, merged