Update SRG-OS-000142-GPOS-00071 for RHEL9 STIG
ComplianceAsCode/content pull request #8537
Opened 2022-04-12 14:59 UTC by jan-cerny

#### Description:

* Create a jinja macro for fix for sysctl rules
* Add fix to rule
* Update title

#### Rationale:

RHEL 9 STIG

2022-04-12 17:43 UTC, Mab879 requested changes

2022-04-12 17:43 UTC, Mab879 commented on shared/macros.jinja
> +:type value: str
Please add a blank link before the closing tag of the docstring. See the [style guide](https://complianceascode.readthedocs.io/en/latest/manual/developer/04_style_guide.html#jinja).

2022-04-12 17:43 UTC, Mab879 commented on linux_os/guide/system/network/network-kernel/network_host_and_router_parameters/sysctl_net_ipv4_tcp_syncookies/rule.yml
> +   Configure {{{ full_name }}} to use TCP Syncookies on IPv4 interfaces.
```suggestion
   Configure {{{ full_name }}} to use TCP SYN cookies.
```
Also applies on IPv6 as well. See https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt. Search for IPv6.

2022-04-13 12:19 UTC, jan-cerny commented
removed ivp4 and fixed coding style

2022-04-13 17:04 UTC, Mab879 approved these changes

2022-04-13 19:16 UTC, merged