Enable bash remediation for SUSE smartcard_pam_enabled
ComplianceAsCode/content pull request #8547
Opened 2022-04-13 20:38 UTC by brett060102

create smartcard_pam_enabled/bash/shared.sh
which includes both sle and ubuntu remediations
use jinja ifs and remove
smartcard_pam_enabled/bash/ubuntu.sh
since that is now in shared.sh

Update test code to support sle.

#### Description:

- Update bash remediation to support sle

#### Rationale:

- ansible not installed by dfault on SLE12/15

2022-04-14 12:09 UTC, Mab879 commented
/ok-to-test

2022-04-19 20:07 UTC, Mab879 requested changes
Thanks for the PR. Just a couple of changes requested to make the content more maintainable.

2022-04-19 20:07 UTC, Mab879 commented on linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_pam_enabled/tests/commented.fail.sh
> +{{% if product in ["ubuntu1604", "ubuntu1804", "ubuntu2004"] %}}
```suggestion
{{% if 'ubuntu' in product %}}
```

2022-04-19 20:07 UTC, Mab879 commented on linux_os/guide/system/accounts/accounts-physical/screen_locking/smart_card_login/smartcard_pam_enabled/bash/shared.sh
> +{{% if product in ["ubuntu1604", "ubuntu1804", "ubuntu2004"] %}}
```suggestion
{{% if 'ubuntu' in product %}}
```

2022-04-20 19:25 UTC, brett060102 commented
@Mab879 do you want the same {{% if 'ubuntu' in product %}} made to the testing code?

2022-04-21 17:50 UTC, brett060102 commented
/retest

2022-04-21 19:57 UTC, Mab879 commented
> @Mab879 do you want the same {{% if 'ubuntu' in product %}} made to the testing code?

That would be a good idea

2022-04-21 21:57 UTC, brett060102 commented
@Mab879 done.

2022-04-26 13:04 UTC, brett060102 commented
@Mab879 This one is now ready for re-review.

2022-04-26 22:22 UTC, brett060102 commented
/retest

2022-04-27 16:31 UTC, brett060102 commented
@Mab879 How does this PR look to you now.

2022-04-27 17:54 UTC, Mab879 approved these changes

2022-04-27 17:55 UTC, merged