Generalize SRG mapping creation
ComplianceAsCode/content pull request #8562
Opened 2022-04-14 16:10 UTC by ggbecker

#### Description:

- Add new option `controls_dir` to specify which directory the control files should be loaded.
- Move the `stig_rhel9` folder to `srg_os`
- Create a debug profile for SRG mapping based rules
- Replace the operating system with full_name variable

2022-04-14 19:14 UTC, Mab879 commented
I would suggest that name of the folder be `srg_gpos` to better match the DISA SRG for general purpose operating systems.

2022-04-19 12:19 UTC, ggbecker commented
> I would suggest that name of the folder be `srg_gpos` to better match the DISA SRG for general purpose operating systems.

Done

2022-04-19 16:02 UTC, Mab879 requested changes
One minor wording change and request for tests on the new key for controls.

2022-04-19 16:02 UTC, Mab879 commented on controls/srg_gpos/SRG-OS-000079-GPOS-00047.yml
> +            To prevent the compromise of authentication information, such as passwords during the authentication process, the feedback from the {{{ full_name }}} must not provide any information allo
```suggestion
            To prevent the compromise of authentication information, such as passwords during the authentication process, the feedback from {{{ full_name }}} must not provide any information allowing an unauthorized user to compromise the authentication mechanism.
```

2022-04-20 11:19 UTC, ggbecker commented on controls/srg_gpos/SRG-OS-000079-GPOS-00047.yml
> +            To prevent the compromise of authentication information, such as passwords during the authentication process, the feedback from the {{{ full_name }}} must not provide any information allo
done by rebase

2022-04-20 11:20 UTC, ggbecker commented on ssg/controls.py
> +        controls_dir = yaml_contents.get("controls_dir")
done in https://github.com/ComplianceAsCode/content/pull/8562/commits/5d5b5deb6e38dadcc0e1e023e10c4c0ea199cf66

and please check if this other commit makes sense: 

https://github.com/ComplianceAsCode/content/pull/8562/commits/5333187ba8ee03e9efa79648c37a0499e66ed54f

2022-04-20 13:45 UTC, Mab879 approved these changes

2022-04-20 13:56 UTC, merged