Bad use of double quotes in rsyslog_files_permissions/bash/shared.sh
ComplianceAsCode/content pull request #8601
Opened 2022-04-24 14:09 UTC by brett060102

In our testing the log files specified in /etc/rsyslog.d/ were not getting remediated.
The issue is with line:
    RSYSLOG_CONFIGS+=("${RSYSLOG_ETC_CONFIG}" "${RSYSLOG_INCLUDE_CONFIG[@]}" "${RSYSLOG_INCLUDE[@]}")
which produces a RSYSLOG_CONFIGS of
    /etc/rsyslog.conf /run/rsyslog/additional-log-sockets.conf /etc/rsyslog.d/*.conf /etc/rsyslog.d/*.frule

line:
    RSYSLOG_CONFIGS+=(${RSYSLOG_ETC_CONFIG} ${RSYSLOG_INCLUDE_CONFIG[@]} ${RSYSLOG_INCLUDE[@]})
poduces:
    /etc/rsyslog.conf /run/rsyslog/additional-log-sockets.conf /etc/rsyslog.d/21-cloudinit.conf /etc/rsyslog.d/remote.conf /etc/rsyslog.d/acpid.frule /etc/rsyslog.d/firewall.frule /etc/rsyslog.d/NetworkManager.frule

Use find to capture effected conf and frule files.

#### Description:

- recode config file handle to use find as opposed to shell expansion for getting list of config files.

#### Rationale:

- current *.conf and *.frule handling not working
-

2022-04-25 02:44 UTC, brett060102 commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_files_permissions/bash/shared.sh
> +     RSYSLOG_FILES+=("${RSYSLOG_FILES[@]}" "${FINDOUT[@]}")
I don't know why the \" are needed, but they are; code does not work without them. I have tested the result on SLE15 and Ubuntu 20.04 and it works as expected on both. And passes spell check.

2022-04-25 13:35 UTC, brett060102 commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_files_permissions/bash/shared.sh
> +     RSYSLOG_FILES+=("${RSYSLOG_FILES[@]}" "${FINDOUT[@]}")
Code updated so comment above no longer applies.

2022-04-25 15:57 UTC, brett060102 commented
/retest

2022-04-26 12:36 UTC, brett060102 commented
@yuumasato Can you please look at this and see if it looks like an acceptable solution to the issue in https://github.com/ComplianceAsCode/content/pull/8574 I does take care of the issue I was seeing and passes shellcheck.
Thank  you.
@brett060102

2022-04-26 18:02 UTC, Mab879 commented
/ok-to-test

2022-04-26 18:59 UTC, brett060102 commented
@Mab879 Tank you.

2022-04-27 16:52 UTC, yuumasato requested changes
@brett060102 So the problem seems to be the expansion of globs in arrays, and double quoting the array causes the glob not to expand.

In RHEL, the default config file contains `include(file="/etc/rsyslog.d/*.conf" mode="optional")`, 
and due to the double quoting this gets in the for loop without being expanded.
`echo ${RSYSLOG_CONFIGS[@]}` and `echo "${RSYSLOG_CONFIGS[@]}"` expands differently.

With https://github.com/ComplianceAsCode/content/commit/33fa9020e7ee006df6c01812188c5e4335cd6c66#diff-b3a261983f580c0a14bfe622685710b716ddddb53814265f52bac6b39ffa0d67R15 the glob expansion got broken.

I think I see another issue in line 15, the `+=` causes the files to be added multiple times, changing it to `=` seemed to solved it for me. Do you also see files added multiple times?
` RSYSLOG_CONFIGS=("${RSYSLOG_ETC_CONFIG}" "${RSYSLOG_INCLUDE_CONFIG[@]}" "${RSYSLOG_INCLUDE[@]}")`

Could you just add a comment clarifying that `RSYSLOG_CONFIGS` may have globs and the added `for` loop adds the explicit file paths ?
I'm good with the proposed solution, pinging @matejak to double check.

This bug took some time to be found and fixed, could you add a test scenario so that this problem does not manifest again? We don't have any test scenario with a glob in the `include()` or `$IncludeConfig`.
I think one pass and fail test scenarios will suffice.

2022-04-27 21:37 UTC, brett060102 commented
Code changes are up. I can get the tests up tomorrow.

2022-04-28 14:14 UTC, brett060102 commented
@yuumasato test for wildcards in include are up.

2022-04-29 10:34 UTC, yuumasato approved these changes
LGTM, thank you very much for adding the test!

2022-04-29 10:38 UTC, yuumasato commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_files_permissions/bash/shared.sh
>  RSYSLOG_CONFIGS+=("${RSYSLOG_ETC_CONFIG}" "${RSYSLOG_INCLUDE_CONFIG[@]}" "${RSYSLOG_INCLUDE[@]}")
@brett060102 One more thing I noticed, I think the `+`  be dropped here too, do you agree?

2022-04-29 11:36 UTC, matejak commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_files_permissions/bash/shared.sh
> +     RSYSLOG_FILES=("${RSYSLOG_FILES[@]}" "${FINDOUT[@]}")
```suggestion
     RSYSLOG_FILES+=("${FINDOUT[@]}")
```

I see that in the PR description there were mentions of duplicates when using `+=`, but that was probably caused by missing initialization of the array, so an earlier remediation influenced its contents. This proposed change should result in an exactly the same behavior, could you please comment on that?

2022-04-29 11:39 UTC, matejak commented on linux_os/guide/system/logging/ensure_rsyslog_log_file_configuration/rsyslog_files_permissions/bash/shared.sh
> +declare -a RSYSLOG_FILES
```suggestion
RSYSLOG_FILES=()
```

Declaration doesn't empty the variable if it already exists. What about initializing it right away with an empty array?

2022-04-29 11:45 UTC, matejak commented
> I think I see another issue in line 15, the += causes the files to be added multiple times, changing it to = seemed to solved it for me. Do you also see files added multiple times?

The commit didn't change the behavior, but it is probably true that the previous behavior was wrong already. I would blame the missing initialization.

I am not sure about expanding the wildcard if there is an option to have a literal asterisk in the configuration - the remediation-time expansion "freezes" the configuration in time, so when one adds another config file to that directory, it won't work, although other config files next to it work.

2022-04-29 13:41 UTC, brett060102 reviewed
Accept review suggestions, more efficient  handling of RSYSLOG_FILES

2022-04-29 14:28 UTC, brett060102 commented
@matejak The code updates have been made. I am not sure I understand the comment:
"I am not sure about expanding the wildcard if there is an option to have a literal asterisk in the configuration - the remediation-time expansion "freezes" the configuration in time, so when one adds another config file to that directory, it won't work, although other config files next to it work."

Ubuntu has:
/etc/rsyslog.conf
$IncludeConfig /etc/rsyslog.d/*.conf
SUSE has:
$IncludeConfig /etc/rsyslog.d/*.conf
$IncludeConfig /etc/rsyslog.d/*.frule

So, the wildcards are normal.

The rough flow here is: check /etc/rsyslog.conf  for includes. If includes are wildcards, then expand the wildcards to get a full list of files that define rsyslog log files. Those are then processed to get a list of logfiles that are checked to make sure they have then right privs set.

But this is all done when remediation is run and not when remediation is built. So, the list of log files to check is determined when remediation is run. If a new config which defines a new log file is added after remediation is initially run,  then the new log file would not be checked and remediated until the next remediation run.

Am I missing your point here?
Thanks.

2022-04-29 15:25 UTC, matejak commented
> ... Those are then processed to get a list of logfiles that are checked to make sure they have then right privs set.

Sorry, I have misunderstood how the remediation works. Thanks for clarifying it, I have no further objections.

2022-05-02 07:47 UTC, merged