configure_openssl_crypto_policy: OpenSSL v3.0 has = in include
ComplianceAsCode/content pull request #8608
Opened 2022-04-25 07:56 UTC by maage

#### Description:

Default crypto-policies uses '.include =' in Fedora 35.

#### Rationale:

.include is in OpenSSL v1.1.1
https://www.openssl.org/docs/man1.1.1/man5/config.html

.include [=] pathname is in OpenSSL v3.0
https://www.openssl.org/docs/man3.0/man5/config.html

2022-04-26 08:59 UTC, vojtapolasek commented
/ok-to-test

2022-04-27 08:24 UTC, vojtapolasek requested changes
Hi, thank you for the change, it looks good. I tested it and it should work both for openssl 1.x and 3.x.
Just one thing, could you please give the test scenario some more readable name? Something like include_with_equal_sign?
Thanks.

2022-04-28 10:10 UTC, maage commented
Renamed as suggested.

2022-04-28 14:04 UTC, vojtapolasek approved these changes

2022-04-28 14:04 UTC, merged

2022-04-29 08:44 UTC, maage commented
Thanks