Update SRG-OS-000080-GPOS-00048 for RHEL 9 STIG
ComplianceAsCode/content pull request #8616
Opened 2022-04-25 15:58 UTC by jan-cerny

#### Description:
* Rework OCIL to be more aligned with actual OVAL check
* add fixtext to rules relevant to this SRG
* minor fixes

For more details, please read commit messages of all commits.

#### Rationale:
RHEL 9 STIG

2022-04-27 18:21 UTC, Mab879 requested changes

2022-04-28 08:08 UTC, jan-cerny commented on linux_os/guide/system/bootloader-grub2/non-uefi/grub2_password/rule.yml
> +    $ sudo grub2-mkconfig -o {{{ grub2_uefi_boot_path }}}/grub.cfg
Yes!

2022-05-03 08:15 UTC, jan-cerny commented
After #8628 has been merged I have rebased this PR on master, and extended the macro grub_command and used it in the rules modified in this PR.

2022-05-03 13:16 UTC, jan-cerny commented
rebase it again

2022-05-05 13:01 UTC, Mab879 requested changes

2022-05-05 13:01 UTC, Mab879 commented on linux_os/guide/system/bootloader-grub2/uefi/grub2_uefi_admin_username/rule.yml
> +    Configure the system to require a grub bootloader password for the grub superuser account.
```suggestion
    Configure the system to have a unique username for the grub superuser account.
```

2022-05-06 15:42 UTC, Mab879 requested changes

2022-05-06 15:42 UTC, Mab879 commented on linux_os/guide/system/bootloader-grub2/uefi/grub2_uefi_admin_username/rule.yml
> +    Configure the system to have a unique username for the grub superuser account.
```suggestion
    Configure {{{ full_name }}} to have a unique username for the grub superuser account.
```

2022-05-06 15:42 UTC, Mab879 commented on linux_os/guide/system/bootloader-grub2/non-uefi/grub2_password/rule.yml
> +    Configure the system to require a grub bootloader password for the grub superuser account.
```suggestion
    Configure {{{ full_name }}} to require a grub bootloader password for the grub superuser account.
```

2022-05-16 07:51 UTC, jan-cerny commented
The operating system is now replaced by full_name.

2022-05-16 14:35 UTC, Mab879 approved these changes

2022-05-16 19:09 UTC, Mab879 commented
@jan-cerny The errors from content test filtering concerning me. 

@ggbecker @mildas Any thoughts?

2022-05-19 08:09 UTC, jan-cerny commented
I have rebased the PR on the top of the current upstream master.

2022-05-25 21:19 UTC, Mab879 approved these changes

2022-05-25 21:19 UTC, merged