Update SRG-OS-000377-GPOS-00162 for RHEL 9 STIG
ComplianceAsCode/content pull request #8625
Opened 2022-04-26 10:51 UTC by jan-cerny

#### Description:
Update rule sssd_certificate_verification
- fix typos
- add fixtext
- this rule is parametrized by a variable so let's use the vairable
- set the variable in the referenced SRG

Rule install_smartcard_packages doesn't need changes and rule dconf_gnome_enable_smartcard_auth will be updated by https://github.com/ComplianceAsCode/content/pull/8624.

#### Rationale:
RHEL 9 STIG

2022-04-26 11:24 UTC, ggbecker requested changes

2022-04-26 11:24 UTC, ggbecker commented on controls/srg_gpos/SRG-OS-000377-GPOS-00162.yml
>              - dconf_gnome_enable_smartcard_auth
```suggestion
```

Please remove this rule from all the SRGs. No RHEL8 profiles use this rule and this is probably not applicable to RHEL9.

There are three occurrences `SRG-OS-000375-GPOS-00160,SRG-OS-000376-GPOS-00161,SRG-OS-000377-GPOS-00162`

2022-04-27 06:44 UTC, jan-cerny commented
I have removed rule dconf_enable_smartcard_auth from SRGs.

2022-04-27 09:20 UTC, ggbecker approved these changes

2022-04-27 09:20 UTC, merged