Update SRG-OS-000423-GPOS-00187 for RHEL 9 STIG
ComplianceAsCode/content pull request #8641
Opened 2022-04-27 10:58 UTC by jan-cerny

#### Description:
Update OCIL and add fixtext and update ssh_client_reky_limit and configure_gnutls_tls_crypto_policy.

Rule configure_bind_crypto_policy will be updated by https://github.com/ComplianceAsCode/content/pull/8627.

#### Rationale:
RHEL 9 STIG

2022-04-27 17:48 UTC, Mab879 requested changes

2022-04-27 17:48 UTC, Mab879 commented on linux_os/guide/services/ssh/ssh_client/ssh_client_rekey_limit/rule.yml
> +    Configure the system to force a frequent session key renegotiation for SSH connections to the server by adding or modifying the following line in the "/etc/ssh/sshd_config" file:
```suggestion
    Configure {{{ full_name }}} to force a frequent session key renegotiation for SSH connections to the server by adding or modifying the following line in the "/etc/ssh/sshd_config" file:
```

2022-04-27 17:48 UTC, Mab879 commented on controls/srg_gpos/SRG-OS-000423-GPOS-00187.yml
>              - ssh_client_rekey_limit
Looking at the RHEL8 STIG `SRG-OS-000424-GPOS-00188` keeps to be applicable for `ssh_client_rekey_limit` as well.

2022-04-28 09:51 UTC, jan-cerny commented
I have dd ssh_client_rekey_limit to SRG-OS-000424-GPOS-00188

2022-04-29 12:10 UTC, Mab879 approved these changes

2022-04-29 12:11 UTC, merged