Update SRG-OS-000480-GPOS-00225 for RHEL 9 STIG
ComplianceAsCode/content pull request #8646
Opened 2022-04-27 14:10 UTC by jan-cerny

#### Description:
add fixtexts

#### Rationale:
RHEL 9 STIG

2022-04-27 20:21 UTC, Mab879 reviewed
`accounts_password_pam_retry` doesn't seem to be related to me, should we remove it?

I feel the same way as `accounts_password_pam_enforce_root`, but not as strongly

2022-04-28 09:31 UTC, jan-cerny commented
For me the accounts_password_pam_retry isn't related to dictionary words but I think that accounts_password_pam_enforce_root enforces password quality requirements including dictionary words check on root user.

2022-04-28 09:38 UTC, jan-cerny commented
I have removed accounts_password_pam_retry.

2022-04-28 17:27 UTC, Mab879 requested changes
Minor changel lets clean up the rule while we are here.

2022-04-28 17:27 UTC, Mab879 commented on linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_retry/rule.yml
>      This would appear as <tt>retry=3</tt>, or a lower value.
```suggestion
    This would appear as <tt>retry={{{ xccdf_value("var_password_pam_retry") }}}</tt>, or a lower value.
```

2022-04-29 07:35 UTC, ggbecker commented
> This datastream diff is auto generated by the check `Compare DS/Generate Diff`
> Click here to see the full diff
> 
> ```diff
> OCIL for rule 'xccdf_org.ssgproject.content_rule_accounts_password_pam_retry' differs:
> --- old datastream
> +++ new datastream
> @@ -4,6 +4,6 @@
>  
>  The retry parameter will indicate how many attempts are permitted.
>  The DoD required value is less than or equal to 3.
> -This would appear as retry=3, or a lower value.
> +This would appear as retry=, or a lower value.
>  Is it the case that it is not the required value?
> ```

It's hit us again: https://github.com/ComplianceAsCode/content/issues/4354

Luckily it doesn't interfere with the RHEL9 STIG process. But we should eventually fix this.

2022-04-29 12:24 UTC, Mab879 commented
@ggbecker Since this breaks the content should we revert the use variables in the OCIL?

2022-04-29 13:54 UTC, merged