Update SRG-OS-000073-GPOS-00041 for RHEL 9 STIG
ComplianceAsCode/content pull request #8716
Opened 2022-05-05 15:04 UTC by jan-cerny

#### Description:
Update OCIL and add a fixtext

#### Rationale:
 RHEL 9 STIG

2022-05-05 15:52 UTC, Mab879 requested changes
One question about quoiting in the OCIL clause.

2022-05-05 15:52 UTC, Mab879 commented on linux_os/guide/system/accounts/accounts-pam/set_password_hashing_algorithm/set_password_hashing_algorithm_logindefs/rule.yml
> +ocil_clause: '"ENCRYPT_METHOD" is not set to SHA512'
```suggestion
ocil_clause: 'ENCRYPT_METHOD is not set to SHA512'
```
In `set_password_hashing_algorithm_libuserconf` the config key is not in quotes.

2022-05-06 09:04 UTC, jan-cerny commented
I have removed quotes and separated the condition for password-auth config file and used XCCDF variable in fixtext.

2022-05-06 12:21 UTC, Mab879 approved these changes

2022-05-06 12:22 UTC, Mab879 commented
@jan-cerny It looks like this PR needs a rebase.

2022-05-06 13:05 UTC, jan-cerny commented
rebased

2022-05-06 15:34 UTC, merged