OCP:Add s390x CPE
ComplianceAsCode/content pull request #8728
Opened 2022-05-09 08:02 UTC by Vincent056

Added ocp4-node-not-s390x and ocp4-node-s390x CPEs

2022-05-10 06:21 UTC, Vincent056 commented
The CI failure doesn't seem like to be related to this PR, I see there is a fix coming up for the issue here: https://github.com/ComplianceAsCode/content/pull/8718

2022-05-10 06:28 UTC, vojtapolasek commented
Hello, just FYI, you can already use combinations of already existing platforms. e.g.
platform: ocp4-node and (not s390x)
where ocp4-node and  s390x are separate platforms.
In this way, you will not duplicate code.
More info here: https://complianceascode.readthedocs.io/en/latest/manual/developer/06_contributing_with_content.html#rules

2022-05-10 07:03 UTC, Vincent056 commented
> Hello, just FYI, you can already use combinations of already existing platforms. e.g.
> platform: ocp4-node and (not s390x)
> where ocp4-node and s390x are separate platforms.
> In this way, you will not duplicate code.
> More info here: https://complianceascode.readthedocs.io/en/latest/manual/developer/06_contributing_with_content.html#rules

Aha, thanks for the info, that’s nice, I didn’t know this is already implemented, it was wip last time I looked at it. I will update the code to use it

2022-05-10 16:46 UTC, rhmdnd requested changes
One minor change in the e2e tests.

2022-05-10 16:46 UTC, rhmdnd commented on linux_os/guide/services/ssh/ssh_server/sshd_disable_rhosts/tests/ocp4/e2e.yml
> +default_result: FAIl
nit: FAIL

2022-05-11 05:09 UTC, Vincent056 commented
/retest

2022-05-11 22:16 UTC, Vincent056 commented
/retest

2022-05-12 18:02 UTC, Vincent056 commented on shared/references/cce-redhat-avail.txt
> -CCE-85928-0
just fixed that

2022-05-12 20:04 UTC, Vincent056 commented
/retest

2022-05-13 00:29 UTC, Vincent056 commented
/retest

2022-05-16 10:59 UTC, jhrozek commented
I think the rules are fine and we can merge them, but it also looks like we have an issue with some of the sysctls checks:
```
    helpers.go:807: Result - Name: e2e-e8-master-sysctl-kernel-yama-ptrace-scope - Status: FAIL - Severity: medium
    helpers.go:814: E2E-FAILURE: The expected result for the sysctl_kernel_yama_ptrace_scope rule didn't match. Expected 'PASS', Got 'FAIL'
```
and:
```
    helpers.go:807: Result - Name: e2e-high-master-sysctl-kernel-core-pattern - Status: FAIL - Severity: medium
    helpers.go:814: E2E-FAILURE: The expected result for the sysctl_kernel_core_pattern rule didn't match. Expected 'PASS', Got 'FAIL'
```

2022-05-16 17:24 UTC, Vincent056 commented
> what do you think is a better tracker? Upstream issue here or a CMP jira?

let's merge this, I will create a Jira ticket to track sysctl, it doesn't seem the CI is passing for sysctl fix https://github.com/ComplianceAsCode/content/pull/8718

2022-05-16 19:35 UTC, jhrozek commented
> > what do you think is a better tracker? Upstream issue here or a CMP jira?
> 
> let's merge this, I will create a Jira ticket to track sysctl, it doesn't seem the CI is passing for sysctl fix #8718

OK, thank you.

2022-05-16 21:04 UTC, rhmdnd approved these changes

2022-05-16 21:05 UTC, merged

2022-05-17 09:39 UTC, yuumasato commented
As mentioned above, the sysctl errors in rules `sysctl_kernel_yama_ptrace_scope` and `sysctl_kernel_core_pattern` should be fixed by #8718