Cleanup custom kernel_module_disabled scenarios
ComplianceAsCode/content pull request #8753
Opened 2022-05-11 10:58 UTC by vojtapolasek

#### Description:

- create test scenarios for kernel_module_disabled template
- remove custom test scenarios

#### Rationale:

cleanup

2022-05-11 15:37 UTC, yuumasato requested changes

2022-05-11 15:37 UTC, yuumasato commented on shared/templates/kernel_module_disabled/tests/file_not_there.fail.sh
> +rm -f /etc/modprobe.d/{{{ KERNMODULE }}}.conf
This test should probably go through all of the directories checked, not just `/etc/modprobe.d`.

And looking at the check, it looks for any `*.conf` file with `install {{{ KERNMODULE }}}`.
So the test should remove any `*.conf` files in any of the directories checked with `install {{{ KERNMODULE }}}`.

2022-05-11 15:37 UTC, yuumasato commented on linux_os/guide/system/network/network-uncommon/kernel_module_firewire-core_disabled/tests/kernel_module_preparation.sh
> -        done
This snippet can be reused in the test scenarios to handle all the directories the OVAL checks.

2022-05-11 15:37 UTC, yuumasato commented on shared/templates/kernel_module_disabled/tests/file_not_there.fail.sh
> +rm -f /etc/modprobe.d/{{{ KERNMODULE }}}.conf
The `kernel_module_preparation.sh` has some code that can be reused.

2022-05-11 15:37 UTC, yuumasato commented on shared/templates/kernel_module_disabled/tests/comment.fail.sh
> +fi
This should go through all checked directories.

2022-05-12 13:22 UTC, vojtapolasek commented
I think I addressed your feedback. Tests now change all relevant directories.

2022-05-13 08:30 UTC, yuumasato approved these changes

2022-05-13 08:30 UTC, merged