Rework tarball generation
ComplianceAsCode/content pull request #8883
Opened 2022-06-03 07:46 UTC by jan-cerny

#### Description:
During the test run setup, a tarball with test scenarios and test
data is created and uploaded to the test backend. With this patch,
the tarball will no longer contain test scenarios for the rules that
won't be tested. Also, we will avoid processing test scenarios and
rules twice, we will reuse processed test scenarios that we have
loaded in memory at the moment of the tarball creation.

#### Rationale:

Fixes: #8765

It makes a test run faster by 12 seconds.

2022-06-03 08:16 UTC, pep8speaks commented
Hello @jan-cerny! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`tests/ssg_test_suite/rule.py`](https://github.com/ComplianceAsCode/content/blob/284db0a2036115a5ff482bceceef234c96e9eba2/tests/ssg_test_suite/rule.py):

> [Line 349:17](https://github.com/ComplianceAsCode/content/blob/284db0a2036115a5ff482bceceef234c96e9eba2/tests/ssg_test_suite/rule.py#L349): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 366:5](https://github.com/ComplianceAsCode/content/blob/284db0a2036115a5ff482bceceef234c96e9eba2/tests/ssg_test_suite/rule.py#L366): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)

2022-07-01 16:20 UTC, matejak requested changes
I have identified a couple of issues related to readability, but the PR is great, thank you very much!

2022-07-01 16:20 UTC, matejak commented on tests/ssg_test_suite/rule.py
> +                scenario.override_profile(self.scenarios_profile)
override_profile is a modify operation, somehow unexpected in a method of the `get` type. Not sure what to do about it - maybe rename get to prepare?

2022-07-01 16:20 UTC, matejak commented on tests/ssg_test_suite/rule.py
> +                        scenario.matches_platform(self.benchmark_cpes)):
maybe extract that ugly condition, so one could read `if self._scenario_wanted_and_applicable(scenario):`

2022-07-01 16:20 UTC, matejak commented on tests/ssg_test_suite/common.py
> +            if test_case.endswith(".swp"):
`vim` is not that special, why not to use this opportunity to introduce a `if file_known_as_useless(test_case):` function that will make it easier to exclude more patterns?

2022-07-01 16:20 UTC, matejak commented on tests/ssg_test_suite/rule.py
> +    def _get_rule_test_content(self, rule):
CodeClimate is complaining about complexity of the function. If you don't see any meaningful way how to reduce it except refactoring the "if with and", then please also modify the codeclimate yaml to soften its settings accordingly. That coplexity would be somehow acceptable.

2022-07-04 09:22 UTC, jan-cerny commented
I have tried to address the comments and I have fixed the PEP 8 problem. I don't think that _get_rule_test_content is overly complex.

2022-07-04 15:12 UTC, matejak approved these changes

2022-07-04 15:13 UTC, matejak commented
Thank you for improving Automatus as well as helping to calibrate our code analysis tool!

2022-07-04 15:13 UTC, merged