products/alinux2 && controls: Add CIS Alibaba Cloud Linux (Aliyun Linux) 2 profiles
ComplianceAsCode/content pull request #8896
Opened 2022-06-06 06:09 UTC by hustliyilin

CIS Aliyun Linux 2 Benchmark v1.0.0
(https://workbench.cisecurity.org/benchmarks/2228) was published
on Aug 16th 2019. Aliyun Linux 2 is compatible with CentOS 7 and it's
further renamed as Alibaba Cloud Linux 2.

I add the CIS Alibaba Cloud Linux (Aliyun Linux) 2 controls in the OpenSCAP
according to CIS Aliyun Linux 2 Benchmark v1.0.0
(https://workbench.cisecurity.org/benchmarks/2228)

Fixes: #8895 

Signed-off-by: YiLin.Li <YiLin.Li@linux.alibaba.com>
Signed-off-by: YuQing.Yang <yyq0391@163.com>

#### Description:

- _Description here. Replace this text. Don't use the italics format!_

#### Rationale:

- _Rationale here. Replace this text. Don't use the italics format!_

- Fixes # _Issue number here (e.g. #26) or remove this line if no issue exists._

2022-06-07 06:46 UTC, vojtapolasek requested changes
Hello, thank you for this new profile. Well done.
There is one thing I would like to ask you to do:
When you use a rule within the new profile, it needs to get also the correct CIS reference.
For example the rule kernel_module_squashfs_disabled is assigned to CIS control 1.1.1. So you need to add 
cis@alinux2: 1.1.1
into the "references" section. Please note that you have to keep references in alphabetical order.
I believe that after this change the PR will be reade to merge.

2022-06-07 13:32 UTC, JAORMX commented
/ok-to-test

2022-06-08 09:47 UTC, vojtapolasek reviewed
Looks nice. Just some nitpicks and it will be ready to be merged.

2022-06-08 09:47 UTC, vojtapolasek commented on controls/cis_alinux2.yml
> +version: '1.0,0'
```suggestion
version: '1.0.0'
```

2022-06-08 09:47 UTC, vojtapolasek commented on products/alinux2/profiles/cis.profile
> +metadata:
We would like to have note who is the maintainer of a profile. Therefore, we use the "SMEs" section in profile metadata.
You can see an example here:
https://github.com/ComplianceAsCode/content/blob/master/products/rhel8/profiles/cis.profile
Could you add this section with at least one github handle?

2022-06-08 10:50 UTC, hustliyilin commented
> Looks nice. Just some nitpicks and it will be ready to be merged.

Hi @vojtapolasek ,

Thanks for your review. I already updated the codes and force-pushed this pr. Could you review it again ? Thanks a lot.

2022-06-08 12:39 UTC, merged