[WIP] Update the control status with not applicable for OCP4 controls
ComplianceAsCode/content pull request #8952
Opened 2022-06-14 15:22 UTC by DhritiShikhar

#### Description:

- Update the control status with `not applicable`

#### Rationale:

- OCP4 STIG content

2022-06-14 19:50 UTC, jhrozek commented
/ok-to-test

2022-06-15 05:16 UTC, DhritiShikhar commented
/retest

2022-06-15 08:10 UTC, jhrozek requested changes
You missed 385, it seems.

2022-06-16 09:49 UTC, DhritiShikhar commented
> You missed 385, it seems.

Thanks. Added 385 and cross checked once again if I missed any other control

2022-06-16 19:29 UTC, merged