Update SRG-APP-000092-CTR-000165 for OCP4 STIG
ComplianceAsCode/content pull request #8969
Opened 2022-06-16 07:04 UTC by DhritiShikhar

#### Description:

- automated check present -> added the rule

#### Rationale:

- OCP4 STIG content

2022-06-16 19:17 UTC, jhrozek requested changes

2022-06-16 19:17 UTC, jhrozek commented on controls/srg_ctr/SRG-APP-000092-CTR-000165.yml
> +  - cluster_logging_operator_exists
typo: the rule is called `cluster_logging_operator_exist` (no `s`). Please also add the SRG reference to the rule.

2022-06-16 19:17 UTC, jhrozek commented on controls/srg_ctr/SRG-APP-000092-CTR-000165.yml
> +  - audit_log_forwarding_enables
This rule doesn't contain an SRG reference to this control. Can you also check, while you are touching that rule, if the other two SRG references make sense for the rule?

2022-06-16 19:21 UTC, jhrozek commented
/ok-to-test

2022-06-16 19:27 UTC, jhrozek commented on controls/srg_ctr/SRG-APP-000092-CTR-000165.yml
> +    https://docs.openshift.com/container-platform/4.8/logging/cluster-logging-external.html
Let's also use unversioned doc link

2022-06-30 14:17 UTC, jan-cerny commented
@DhritiShikhar What are your plans?

2022-07-26 13:32 UTC, jhrozek commented
> @DhritiShikhar What are your plans?

Dhriti no longer works at RH and I had a long vacation. Sorry about the delay, I'm working through the PRs now.

2022-07-26 15:17 UTC, jhrozek commented
The latest push also includes content from PR #8970 so that we don't have a conflict between the two.

2022-07-28 11:35 UTC, jhrozek commented
/test e2e-aws-ocp4-stig-node

2022-07-28 13:59 UTC, jhrozek approved these changes
I adressed my own concerns, so I'm gong to push this PR...

2022-07-28 14:07 UTC, merged