Update SRG-APP-000069-CTR-000125 for OCP4 STIG
ComplianceAsCode/content pull request #8977
Opened 2022-06-16 10:58 UTC by DhritiShikhar

#### Description:

- added check and fixtext
- 
#### Rationale:

- OCP4 STIG content

2022-06-16 19:38 UTC, jhrozek commented
/ok-to-test

2022-06-16 19:39 UTC, jhrozek requested changes
same comments as in PR #8976

2022-07-18 13:51 UTC, jan-cerny commented
Hi @DhritiShikhar and @jhrozek, this PR seems to be stuck. Is there something blocking? What are your plans?

2022-07-29 07:04 UTC, jhrozek approved these changes

2022-07-29 07:10 UTC, merged