RHEL8 STIG: Install redhat gpg key
ComplianceAsCode/content pull request #8993
Opened 2022-06-20 10:13 UTC by yuumasato

#### Description:

- Select rule `ensure_redthat_gpgkey_installed` in RHEL8 STIG

#### Rationale:

- The errors occur even during the remediation run that enabled `gpgcheck=1`.
```console
Title
	Install the tmux Package
Rule
	xccdf_org.ssgproject.content_rule_package_tmux_installed
Ident
	CCE-80644-8
Result
	error
```
- Although the RHEL8 STIG doesn't explicitly instruct to install Red Hat's gpg key, it is necessary when gpgcheck is enabled by rule  `ensure_gpgcheck_globally_activated`
```console
[root@localhost ~]# yum install tmux
Updating Subscription Management repositories.

You have enabled checking of packages via GPG keys. This is a good thing.
However, you do not have any GPG public keys installed. You need to download
the keys for packages you wish to install and install them.
You can do that by running the command:
    rpm --import public.gpg.key

Alternatively you can specify the url to the key you would like to use
for a repository in the 'gpgkey' option in a repository section and YUM
will install it for you.

For more information contact your distribution or package provider.                            
```

- This was originally selected in DRAFT RHEL8 STIG, but was unselected once RHEL8 STIG V1R1 came out.

2022-06-20 10:24 UTC, mildas requested changes
Add the rule to `tests/data/profile_stability/rhel8/stig_gui.profile` and `tests/data/profile_stability/rhel8/stig.profile`

2022-06-20 14:30 UTC, jan-cerny commented
@mildas Do you want to be a volunteer?

2022-06-21 12:41 UTC, vojtapolasek approved these changes
LGTM now.

2022-06-23 11:19 UTC, mildas approved these changes

2022-06-23 11:19 UTC, merged