Create rule to cover OL08-00-030030
ComplianceAsCode/content pull request #9001
Opened 2022-06-20 22:26 UTC by Xeicker

#### Description:

- Add rule `postfix_client_configure_mail_alias_postmaster`

#### Rationale:

- This is to cover the DISA STIG ID `OL08-00-030030` for Oracle Linux 8

2022-06-21 15:43 UTC, Mab879 commented on linux_os/guide/services/mail/postfix_client/postfix_client_configure_mail_alias_postmaster/rule.yml
> +
The `srg_requirement` should be similar to the title in the STIG.

2022-06-21 16:50 UTC, Xeicker commented on linux_os/guide/services/mail/postfix_client/postfix_client_configure_mail_alias_postmaster/rule.yml
> +
Didn't find the guidelines about how this field should be, I added it based on how others look and this clue

2022-06-22 07:08 UTC, jan-cerny approved these changes

2022-06-22 07:12 UTC, jan-cerny requested changes

2022-06-22 07:12 UTC, jan-cerny commented on linux_os/guide/services/mail/postfix_client/postfix_client_configure_mail_alias_postmaster/ansible/shared.yml
> +
The fail seems to be legitimate:

```
183/246 Test #184: rhel8-ansible-assert-playbooks-schema ....................................***Failed    6.73 sec
Error processing /__w/content/content/build/rhel8/playbooks/all/postfix_client_configure_mail_alias_postmaster.yml: Did not found key(s) in comments: complexity, disruption, strategy, reboot
```

Please could you add the headers, for example:

```
# reboot = false
# strategy = restrict
# complexity = low
# disruption = low
```

2022-06-22 07:12 UTC, jan-cerny commented on linux_os/guide/services/mail/postfix_client/postfix_client_configure_mail_alias_postmaster/bash/shared.sh
> +
Missing complexity , strategy, disruption, etc.

2022-07-01 07:50 UTC, jan-cerny approved these changes

2022-07-01 07:50 UTC, merged

2022-07-01 09:12 UTC, ggbecker commented
we should probably use this rule in RHEL8 STIG as well: https://stigs.mab879.com/products/rhel8/v1r6/RHEL-08-030030/