Add 4.11 test manifests to several rules
ComplianceAsCode/content pull request #9014
Opened 2022-06-22 13:28 UTC by jhrozek

#### Description:

We had versioned test results for these rules, but didn't add the 4.11
manifests. This patch adds them.

The only rule I didn't touch was the flowcontrol one which needs to be
adjusted for 4.11.

#### Rationale:

- OCP tests currently don't work on 4.11

2022-06-22 14:40 UTC, Mab879 requested changes
Please ensure that all files end with a single newline.

2022-06-22 16:34 UTC, jhrozek commented
> Please ensure that all files end with a single newline.

Sure, I can do that, I just wonder if that's a new requirement? None of the existing test files have the newline (not that it should cause some problems, I just wonder if I should go and add a `\n` to the existing test manifests..)

2022-06-22 16:37 UTC, jhrozek commented
I've never seen the OCP CI be so flaky. CO didn't come up on any of the clusters.
/retest

2022-06-23 14:37 UTC, jhrozek commented
@Mab879 I verified that the extra newline works fine with our e2e tests, added it and pushed a new version.

I'm also fine with adding the extra newline to all existing test manifests if need be, but I'd prefer to do so in a separate PR (this PR would help us enable 4.11 in CI so I'd like to get it merged soonish..)

2022-06-23 15:15 UTC, jhrozek commented
Aaaaand we're back to the operator index being fubar, so CO didn't install in ANY test. Let's just hit CI again until it's green..grrrr...
/retest

2022-06-23 17:57 UTC, jhrozek commented
/retest

2022-06-23 19:24 UTC, jhrozek commented
/retest

2022-06-23 20:43 UTC, jhrozek commented
/retest

2022-06-24 03:57 UTC, jhrozek commented
@Vincent056 @rhmdnd PTAL and merge

2022-06-27 17:33 UTC, Vincent056 approved these changes
/lgtm

2022-06-27 17:34 UTC, merged