Update faillock related macros
ComplianceAsCode/content pull request #9139
Opened 2022-07-12 18:47 UTC by Xeicker

#### Description:
- Make faillock related macros manage the edge cases:
  - When the user had set options in pam files, but faillock.conf was available
  - When the option is not a number
  - Remove pam option when the option doesn't have a value associated

#### Rationale:

- As stated in `pam_faillock` man page, modifying pam_faillock options from pam files is still possible but not recommended.
- This prepares for the `dir` option which isn't a number
- Doing this it was found that when a pam option didn't have a value associated, the macro `bash_remove_pam_module_option_configuration` wasn't working

2022-07-14 10:08 UTC, marcusburghardt requested changes
Thanks @Xeicker . I just included some small comments.

2022-07-14 16:07 UTC, Xeicker commented on shared/macros/10-bash.jinja
> +        sed -i --follow-symlinks 's|^\s*\({{{ option }}}\s*=\s*\)\(\S\+\)|\1'"{{{ value }}}"'|g' $FAILLOCK_CONF
this was thinking in the `dir` option, which could use non-alpha-numeric characters.

2022-07-15 09:25 UTC, marcusburghardt commented on shared/macros/10-bash.jinja
> +        sed -i --follow-symlinks 's|^\s*\({{{ option }}}\s*=\s*\)\(\S\+\)|\1'"{{{ value }}}"'|g' $FAILLOCK_CONF
Never mind. I forgot this case. : )

2022-07-15 10:07 UTC, marcusburghardt approved these changes
Thanks @Xeicker . I will just wait the tests to finish.

2022-07-15 12:01 UTC, marcusburghardt commented
Besides the CI tests I also tested critical PAM rules in local VMs and everything worked fine. Thanks @Xeicker

2022-07-15 12:01 UTC, merged