Make audit AArch64 specific rules RHEL9 only
ComplianceAsCode/content pull request #9188
Opened 2022-07-20 08:41 UTC by vojtapolasek

#### Description:

- change prodtype to rhel9 and return back rhel8 CCEs
- for non-aarch64 rules, in case of rhel9, make them not applicable so that they do not override each other
- remove rules from rhel8 profile

#### Rationale:

Architecture specific audit files are not present on RHEL8.

2022-07-22 11:42 UTC, ggbecker commented
changed the milestone to 0.1.63 as this PR is going to be in the stabilization branch as well.

2022-07-25 14:12 UTC, jan-cerny requested changes
The code looks good but please resolve the conflicts.

2022-07-25 15:13 UTC, vojtapolasek commented
@jan-cerny  I rebased and conflicts should be fixed.

2022-07-26 08:54 UTC, jan-cerny approved these changes

2022-07-26 08:55 UTC, merged