WIP: modify OSPP rules concerning coredumps
ComplianceAsCode/content pull request #9285
Opened 2022-08-03 09:09 UTC by vojtapolasek

#### Description:

- drop following rules from RHEL9 OSPP
  - coredump_disable_storage
  - coredump_disable_backtraces
- modify the rule sysctl_kernel_core_pattern to use an XCCDF variable instead. Use the empty string in OSPP profiles. Leave the value for STIG profiles as is.

#### Rationale:

https://bugzilla.redhat.com/show_bug.cgi?id=2081688

2022-08-03 14:50 UTC, vojtapolasek commented
@jan-cerny  I think that we are facing a problem. There is an XCCDF variable which has the | character inside. It seems to be OK for HTML guides and Bash profile scripts, but it causes problems when generating Ansible playbooks for profiles. It seems that Ansible does not like the unescaped |. I think the problem might be in Openscap generating the fix.
Do you agree?

2022-08-05 06:48 UTC, jan-cerny commented
We have discussed this with @vojtapolasek and also with a whole team on 2022-08-04 and we think that the options are:
* try to workaround it in the build system based on the variables value
* or create a special rule for OSPP that won't use variables

But the proper solution seems to be to fix in OpenSCAP, so I opened a ticket with them in https://github.com/OpenSCAP/openscap/issues/1879

2022-08-05 09:07 UTC, vojtapolasek commented
I created a new rule sysctl_kernel_core_pattern_empty_string. The PR has changed including description.@jan-cerny  I think that we are facing a problem. There is an XCCDF variable which has the | character inside. It seems to be OK for HTML guides and Bash profile scripts, but it causes problems when generating Ansible playbooks for profiles. It seems that Ansible does not like the unescaped |. I think the problem might be in Openscap generating the fix.
Do you agree?

2022-08-08 06:53 UTC, vojtapolasek commented
/retest

2022-08-09 13:13 UTC, yuumasato commented
@vojtapolasek There is an unrelated commit in fd75c2c in the PR.

2022-08-09 13:50 UTC, yuumasato requested changes

2022-08-09 13:50 UTC, yuumasato commented on linux_os/guide/system/permissions/restrictions/sysctl_kernel_core_uses_pid/rule.yml
> +    {{{ ocil_sysctl_option_value(sysctl="kernel.core_pattern", value=0) }}}
It should be `kernel.core_uses_pid`.

2022-08-09 13:50 UTC, yuumasato commented on linux_os/guide/system/permissions/restrictions/sysctl_kernel_core_uses_pid/rule.yml
> +ocil_clause: 'the returned line does not have a value of 0, or a line is not returned and the need for core dumps is not documented with the Information System Security Officer (ISSO) as an operation
Please, add line breaks to the OCIL clause.

2022-08-09 14:44 UTC, vojtapolasek commented
@yuumasato  thanks for the review, I fixed ocils.

2022-08-09 15:23 UTC, yuumasato commented on linux_os/guide/system/permissions/restrictions/sysctl_kernel_core_uses_pid/rule.yml
> +ocil_clause: 'the returned line does not have a value of 0, or a line is not returned and the need for core dumps is not documented with the Information System Security Officer (ISSO) as an operation
@vojtapolasek You missed this ocil_clause, :)

2022-08-09 15:39 UTC, vojtapolasek commented
@yuumasato  ocils should be ok now

2022-08-09 20:51 UTC, yuumasato approved these changes

2022-08-09 20:52 UTC, merged