Use data stream to verify references
ComplianceAsCode/content pull request #9293
Opened 2022-08-04 11:31 UTC by jan-cerny

We will use SCAP source data stream as an input for verify-references
test instead of the XCCDF 1.1 file. We will have to do small updates
in verify_references.py. This change will help us to remove outdated
XCCDF 1.1 from the project.

2022-08-05 14:05 UTC, vojtapolasek requested changes
Good job! Please fix issues reported by Codeclimate. And a small nitpick, see comment.

2022-08-05 14:05 UTC, vojtapolasek commented on build-scripts/verify_references.py
> +               check_content_ref_href_attr.startswith("security-data-oval-com.redhat.rhsa-") or \
Please update also the comment just above this conditional.

2022-08-09 13:44 UTC, pep8speaks commented
Hello @jan-cerny! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`build-scripts/verify_references.py`](https://github.com/ComplianceAsCode/content/blob/71b7f11ce4cfa202fd222afe1e2ffe00093536fa/build-scripts/verify_references.py):

> [Line 105:100](https://github.com/ComplianceAsCode/content/blob/71b7f11ce4cfa202fd222afe1e2ffe00093536fa/build-scripts/verify_references.py#L105): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (104 > 99 characters)
> [Line 212:100](https://github.com/ComplianceAsCode/content/blob/71b7f11ce4cfa202fd222afe1e2ffe00093536fa/build-scripts/verify_references.py#L212): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (102 > 99 characters)

2022-08-09 13:45 UTC, jan-cerny commented
I have updated the comment, fixed the code climate problems and rebased this pull request on the top of the latest upstream master branch.

2022-08-09 13:47 UTC, jan-cerny commented
I have avoid very long lines by renaming varaible

2022-08-09 15:21 UTC, vojtapolasek approved these changes
Looks good, thank you.

2022-08-09 15:21 UTC, merged