feature: ssg parsing: add sometimes external_variable related asserts
ComplianceAsCode/content pull request #9353
Opened 2022-08-16 17:18 UTC by maage

#### Description:

Add two assertions to help when editing OVAL files.

#### Rationale:

Provide some info what might be wrong. It helps to write files faster.

I hit those when external_variable definitions were not right. I decided
to leave them as asserts. I guess these points can be hit via other cases
and so stacktrace is nice to have then too.

You can hit those at least:
- datatype is not known, for example ""
- external_variable is missing
- external_variable id is wrong
- test id is wrong

2022-08-16 17:18 UTC, pep8speaks commented
Hello @maage! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`ssg/build_renumber.py`](https://github.com/ComplianceAsCode/content/blob/ff334c8480ebf0adf192523ac00c8a483d5671f7/ssg/build_renumber.py):

> [Line 415:100](https://github.com/ComplianceAsCode/content/blob/ff334c8480ebf0adf192523ac00c8a483d5671f7/ssg/build_renumber.py#L415): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (117 > 99 characters)

* In the file [`ssg/parse_oval.py`](https://github.com/ComplianceAsCode/content/blob/ff334c8480ebf0adf192523ac00c8a483d5671f7/ssg/parse_oval.py):

> [Line 59:100](https://github.com/ComplianceAsCode/content/blob/ff334c8480ebf0adf192523ac00c8a483d5671f7/ssg/parse_oval.py#L59): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (103 > 99 characters)

2022-08-17 08:12 UTC, jan-cerny requested changes
Unfortunately we can't use the f-strings within the build system because Python 2 doesn't support it, please change the messages to use the `%` or `.format` style instead

2022-08-17 12:16 UTC, maage commented
Requested change should be now addressed. I also addressed style issue raised by codeclimate.

2022-08-17 13:01 UTC, jan-cerny approved these changes

2022-08-17 13:02 UTC, merged

2022-08-17 13:02 UTC, maage commented
Thanks