Mask sensitive objects
ComplianceAsCode/content pull request #9364
Opened 2022-08-17 14:34 UTC by marcusburghardt

#### Description:

In some rules, sensitive information might be shown in reports, even when they are not necessary.
It was included the `mask` parameter to hidden sensitive information from reports.

#### Rationale:

- Fixes #8902

2022-08-17 15:05 UTC, marcusburghardt commented
Ok. Let me check why it is failing in container and adjust the test scenario script.

2022-08-18 15:59 UTC, marcusburghardt commented
/retest

2022-08-19 13:16 UTC, yuumasato requested changes
Looks great, just one small thing necessary.

2022-08-19 13:16 UTC, yuumasato commented on linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_set_max_life_existing/bash/shared.sh
> +chage -M $var_accounts_maximum_age_login_defs $i
Update `fixtext` in the rule too.

2022-08-19 13:28 UTC, marcusburghardt commented on linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_set_max_life_existing/bash/shared.sh
> +chage -M $var_accounts_maximum_age_login_defs $i
Done

2022-08-19 13:48 UTC, yuumasato approved these changes

2022-08-19 16:23 UTC, merged