Implement DISA Firefox STIG V6R3
ComplianceAsCode/content pull request #9383
Opened 2022-08-22 20:10 UTC by lenox-joseph

#### Description:

- Implements the DISA STIG for Mozilla Firefox, V6R3.
- Removes old rule checks that are no longer in force.
- Uses generated Python2/3 scripts to implement remediation. 

#### Rationale:

- The Mozilla Firefox STIG has moved to use a JSON-based administrative policy file instead of mozilla.cfg, etc, for most application changes.
    - This JSON file is more complicated than the existing scripting used for Google Chrome (nested attributes), so the existing mechanisms don't work well.
- These changes bring the checks up to parity and remediation with all checks in V6R3 manual STIG (V6R2 benchmark).
- Changing JSON files via Bash scripts is, in a word, nightmarish, with the most prevalent shell setups only really handling parsing and not edit/writing (and those are a lot of library things to put into a template) via a template.

2022-08-22 20:10 UTC, pep8speaks commented
Hello @lenox-joseph! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`shared/templates/firefox_policy-setting/template.py`](https://github.com/ComplianceAsCode/content/blob/c9bfb8c4196d227088e26205dd2628db50389314/shared/templates/firefox_policy-setting/template.py):

> [Line 110:96](https://github.com/ComplianceAsCode/content/blob/c9bfb8c4196d227088e26205dd2628db50389314/shared/templates/firefox_policy-setting/template.py#L110): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2022-08-22 21:35 UTC, lenox-joseph commented
FYI codeclimate here is going to conflict with PEP8 as it wants indentations that are incorrect.

2022-08-22 21:50 UTC, lenox-joseph commented
@Mab879 @matejak FYI this is the replacement for #8271

2022-08-24 12:00 UTC, jan-cerny requested changes

2022-08-24 14:53 UTC, lenox-joseph commented on products/firefox/guide/firefox/firefox_policy-verification/rule.yml
> +description: "Firefox can be configured to prompt the user to choose a certificate\nto present to a website when asked. To enable certificate verification, \nset <tt>security.default_personal_cert</t
@jan-cerny  Thanks for the notice; I'd adapted the existing text and didn't see the control character.

2022-08-24 15:14 UTC, lenox-joseph commented on products/firefox/guide/firefox/firefox_policy-verification/rule.yml
> +description: "Firefox can be configured to prompt the user to choose a certificate\nto present to a website when asked. To enable certificate verification, \nset <tt>security.default_personal_cert</t
@jan-cerny   Fixed, and I went ahead and fixed the other legacy instance in the product.

2022-08-25 14:36 UTC, jan-cerny approved these changes

2022-08-25 14:42 UTC, merged