Use XCCDF 1.2 to generate STIG HTML tables
ComplianceAsCode/content pull request #9406
Opened 2022-08-25 13:33 UTC by jan-cerny

#### Description:
We will use Jinja 2 instead of XSLT transformations to generate STIG HTML tables.

We will use ssg-${PRODUCT}-xccdf-1.2.xml to generate table-${PRODUCT}-stig.html. Note that the stig_overlay.xml file remains in the XCCDF 1.1 namespace, but the temporary internal file unlinked-stig-xccdf.xml will now be in XCCDF 1.2 namespace.

This PR supersedes PR https://github.com/ComplianceAsCode/content/pull/9322. The reason for replacing the PR by new PR is that the previous PR tried to modify the XSLT template, but it would break the manual STIG table and it wasn't easy to adapt the template to work with XML files which will now be each in a different namespace.

For more details, please read commit messages of each commit.

#### Rationale:
This reduces our dependency on XCCDF 1.1 so it will help us to remove the XCCDF 1.1 format in future.

2022-08-26 08:46 UTC, yuumasato requested changes

2022-08-26 08:46 UTC, yuumasato commented on cmake/SSGCommon.cmake
> +        COMMAND "${XSLTPROC_EXECUTABLE}" -stringparam overlay "${CMAKE_BINARY_DIR}/${PRODUCT}/overlays/stig_overlay.xml" --stringparam ocil-document "${CMAKE_CURRENT_BINARY_DIR}/ocil-linked.xml" --ou
Maybe you should add a `DEPENDS "${CMAKE_CURRENT_BINARY_DIR}/ocil-linked.xml"`?

2022-08-26 08:46 UTC, yuumasato commented on utils/tables/stig_template.html
> +{{% endblock %}}
`newline` missing at the end

2022-08-26 13:31 UTC, jan-cerny commented on utils/tables/stig_template.html
> +	<td><pre>{{{ rule["check"] }}}</pre></td>
This is something from the category "works fine on my machine" :smile: :smile: , I hope that adding the dependency to CMake will help.

2022-08-29 07:39 UTC, yuumasato commented on utils/tables/stig_template.html
> +	<td><pre>{{{ rule["check"] }}}</pre></td>
Works on my machine now, :smile:

2022-08-29 07:40 UTC, yuumasato approved these changes

2022-08-29 07:40 UTC, merged