Remove jinja condition to make rule applicability to all products in Kerberos rules
ComplianceAsCode/content pull request #9412
Opened 2022-08-26 09:56 UTC by ggbecker

#### Description:

- Remove jinja condition to make rule applicability to all products in Kerberos rules.

#### Rationale:

- The applicability should be there for all products, not only part of them. For example RHEL9 and OL9 should have a more recent version of the package so it should return not applicable.

2022-08-29 11:32 UTC, ggbecker commented
@Xeicker FYI, I'm removing the jinja conditions here since it should be applicable to all products and the version of the package will determine the applicability...

2022-08-29 15:35 UTC, yuumasato reviewed
The changes LGTM.

But as distros adopt newer versions of `krb5` this rule will not be needed anymore.
So how about also restricting the products this rule is available for?

We should avoid removing the rule from a product that already released with this rule.
But explicitly listing the current prodtypes, should avoid automatically adding these rules to new products, or product versions.
And then, in 10 years, when all current products are EOL, these rules can be deleted, :)

2022-08-29 15:42 UTC, ggbecker commented
> The changes LGTM.
> 
> But as distros adopt newer versions of `krb5` this rule will not be needed anymore. So how about also restricting the products this rule is available for?
> 
> We should avoid removing the rule from a product that already released with this rule. But explicitly listing the current prodtypes, should avoid automatically adding these rules to new products, or product versions. And then, in 10 years, when all current products are EOL, these rules can be deleted, :)

a comment on the `prodtype` can help preventing people from adding new products in the future, but it's not bulletproof. Some kind of negate mechanism would be the best, like: `!rhel10`

2022-09-26 09:48 UTC, marcusburghardt commented
> > The changes LGTM.
> > But as distros adopt newer versions of `krb5` this rule will not be needed anymore. So how about also restricting the products this rule is available for?
> > We should avoid removing the rule from a product that already released with this rule. But explicitly listing the current prodtypes, should avoid automatically adding these rules to new products, or product versions. And then, in 10 years, when all current products are EOL, these rules can be deleted, :)
> 
> a comment on the `prodtype` can help preventing people from adding new products in the future, but it's not bulletproof. Some kind of negate mechanism would be the best, like: `!rhel10`

I would prefer to work with "allow list" instead "deny list". We already know the current relevant products, but we don't know about future products. Also, working with "deny list", technically we should increase the list whenever a new product appears.I believe this is avoidable maintenance. In any case, the comment on `prodtype` is handy.

2022-10-04 10:21 UTC, ggbecker commented
I have refreshed the PR with some more changes and I believe it should be good to go.

2022-10-05 16:38 UTC, yuumasato commented on linux_os/guide/services/kerberos/kerberos_disable_no_keytab/rule.yml
> +prodtype: ol7,ol8,rhel7,rhel8,rhel9
`rhcos4` also selects this rule

2022-10-07 16:13 UTC, ggbecker commented
There was a problem in the CPE conditionals which hopefully is fixed by: [b042cbb](https://github.com/ComplianceAsCode/content/pull/9412/commits/b042cbb39aec04680d6fb8982f710cfd5d9491da)

```
         Start 186: rhel9-bash-shellcheck
185/262 Test #186: rhel9-bash-shellcheck .................................................***Failed   19.60 sec

In /__w/content/content/build/rhel9/fixes/bash/kerberos_disable_no_keytab.sh line 3:
if [ ! -f /.dockerenv ] && [ ! -f /run/.containerenv ] && { (  ); }; then
                                                            ^-- SC1073: Couldn't parse this explicit subshell. Fix to allow more checks.
                                                                ^-- SC1072: Unexpected keyword/token. Fix any mentioned problems and try again.


In /__w/content/content/build/rhel9/fixes/bash/package_krb5-workstation_removed.sh line 7:
if (  ); then
   ^-- SC1073: Couldn't parse this explicit subshell. Fix to allow more checks.
       ^-- SC1072: Unexpected keyword/token. Fix any mentioned problems and try again.

For more information:
  https://www.shellcheck.net/wiki/SC1072 -- Unexpected keyword/token. Fix any...
  https://www.shellcheck.net/wiki/SC1073 -- Couldn't parse this explicit subs...
```

2022-10-07 16:13 UTC, ggbecker commented on linux_os/guide/services/kerberos/kerberos_disable_no_keytab/rule.yml
> +prodtype: ol7,ol8,rhel7,rhel8,rhel9
added back

2022-10-14 08:22 UTC, jan-cerny requested changes

2022-10-14 08:22 UTC, jan-cerny commented on ssg/build_cpe.py
> +
Please add unit tests that cover your changes in the build_cpe.py.

2022-10-14 13:45 UTC, jan-cerny commented
The Code Climate issues can be waived - the 2 sections in code marked as duplicate actually works with different type and unifying them would not improve the readability; and changing CPEALLogicalTest is out of scope of this PR.

2022-10-17 06:58 UTC, jan-cerny approved these changes
Thanks, the unit test is spot in!

2022-10-17 06:59 UTC, merged