Improve ansible remediation of accounts_umask_etc_login_defs
ComplianceAsCode/content pull request #9490
Opened 2022-09-07 16:58 UTC by ggbecker

#### Description:

- Improve ansible remediation of accounts_umask_etc_login_defs.
  - Correctly replace wrong values
  - Do not attempt to change a file that already has a valid configuration

#### Rationale:

- Regex 101 Example: https://regex101.com/r/T0xVnu/1

- Fixes: #9456

This PR can inspire fixes for other similar rules as well. https://github.com/ComplianceAsCode/content/issues/9456#issuecomment-1239355682

2022-09-08 11:08 UTC, marcusburghardt requested changes
The Ansible playbook can be simplified using only the `lineinfile` module.

2022-09-08 12:19 UTC, ggbecker commented on linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_login_defs/ansible/shared.yml
> +- name: Replace user UMASK in /etc/login.defs
There can have multiple UMASK defined in the file IMO, each of them can be on a different trigger situation, so it's better to make sure all of them have the correct value.

2022-09-08 12:19 UTC, ggbecker commented on linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_login_defs/ansible/shared.yml
> +    regexp: ^(?!#)(\s*)UMASK\s+.*
Done

2022-09-08 12:19 UTC, ggbecker commented on linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_login_defs/ansible/shared.yml
>    lineinfile:
Done

2022-09-08 12:21 UTC, ggbecker commented on linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_login_defs/ansible/shared.yml
> +- name: Check if UMASK is already correctly set
I'm struggling to make it work, maybe I need some more help here. Also, it may not align with multiple occurrences if found as stated below.

2022-09-08 12:26 UTC, marcusburghardt commented on linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_login_defs/ansible/shared.yml
> +- name: Replace user UMASK in /etc/login.defs
Ok. It is fine if more UMASK entries are expected.

2022-09-08 12:28 UTC, marcusburghardt commented on linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_login_defs/ansible/shared.yml
> +- name: Check if UMASK is already correctly set
Correct. The lineinfile module only changes one single line per time. If more lines are expected to be changed, the replace module is indeed the best option. Let me test the playbook locally here.

2022-09-08 12:37 UTC, ggbecker commented on linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_login_defs/ansible/shared.yml
> +- name: Replace user UMASK in /etc/login.defs
we even have the test scenario with multiple entries: https://github.com/ComplianceAsCode/content/blob/master/linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_login_defs/tests/wrong_multiple.fail.sh

2022-09-09 13:22 UTC, marcusburghardt requested changes

2022-09-09 13:22 UTC, marcusburghardt commented on linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_login_defs/ansible/shared.yml
> +- name: Check if UMASK is already correctly set
@ggbecker , I could only check this now. So, basically the playbook can be simplified. You don't need to check of the parameter is already correct in a separate task. The replace and lineinfile modules will already do that. Here is an example of a simplified playbook:
```
    - name: Check if UMASK is already set
      ansible.builtin.lineinfile:
        path: /etc/login.defs
        regexp: ^(\s*)UMASK\s+.*
        state: absent
      check_mode: true
      changed_when: false
      register: result_umask_is_set

    - name: Replace user UMASK in /etc/login.defs
      ansible.builtin.replace:
        path: /etc/login.defs
        regexp: ^(\s*)UMASK(\s+).*
        replace: \g<1>UMASK\g<2>{{ var_accounts_user_umask }}
      when:
      - result_umask_is_set.found > 0

    - name: Ensure the Default UMASK is Appended Correctly
      ansible.builtin.lineinfile:
        create: true
        path: /etc/login.defs
        line: UMASK {{ var_accounts_user_umask }}
      when:
      - result_umask_is_set.found == 0
```

2022-09-22 15:02 UTC, marcusburghardt approved these changes
Thanks @ggbecker

2022-09-22 15:04 UTC, merged