Update chronyd_client_only to align with RHEL9 STIG
ComplianceAsCode/content pull request #9500
Opened 2022-09-12 10:00 UTC by dahaic

2022-09-12 18:31 UTC, Mab879 requested changes
Minor change to the path.

2022-09-12 18:31 UTC, Mab879 commented on linux_os/guide/services/ntp/chronyd_client_only/rule.yml
> +    Configure {{{ full_name }}} to disable the chrony daemon from acting as a server by adding/modifying the following line in the /etc/chrony.conf file:
```suggestion
    Configure {{{ full_name }}} to disable the chrony daemon from acting as a server by adding/modifying the following line in the {{{ chrony_conf_path }}} file:
```

2022-09-19 14:31 UTC, dahaic commented on linux_os/guide/services/ntp/chronyd_client_only/rule.yml
> +    Configure {{{ full_name }}} to disable the chrony daemon from acting as a server by adding/modifying the following line in the /etc/chrony.conf file:
Fixed (both occurrences), thank you!

2022-09-20 16:28 UTC, Mab879 approved these changes

2022-09-20 16:28 UTC, merged