Update rules for RHEL 9 STIG
ComplianceAsCode/content pull request #9512
Opened 2022-09-12 15:03 UTC by jan-cerny

#### Description:
According to feedback from DISA we updated some rules and their OCIL, fixtext, SRG requirements, etc.

#### Rationale:
Update the rules for RHEL 9 STIG.

2022-09-14 16:34 UTC, Mab879 requested changes
Thanks for the PR; I left a few comments throughout.

2022-09-14 16:34 UTC, Mab879 commented on linux_os/guide/system/accounts/accounts-pam/password_quality/password_quality_pwquality/accounts_password_pam_ucredit/rule.yml
> +    $ sudo grep ucredit /etc/security/pwquality.conf /etc/security/pwquality.conf/*.conf
This may be in the spreadsheet, but we should not allow obvious errors in our content.

2022-09-14 16:34 UTC, Mab879 commented on linux_os/guide/system/accounts/accounts-restrictions/accounts_authorized_local_users/rule.yml
> +srg_requirement: |-
Please revert this change.

2022-09-14 16:34 UTC, Mab879 commented on linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_bashrc/rule.yml
> +    Note: If the value of the "umask" parameter is set to "000" "/etc/bashrc" file, the Severity is raised to a CAT I.
With this specific STIG language should we move this content to the `checktext` key?

2022-09-14 16:34 UTC, Mab879 commented on linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_csh_cshrc/rule.yml
> +    Note: If the value of the "umask" parameter is set to "000" "/etc/csh.cshrc" file, the Severity is raised to a CAT I.
With this specific STIG language should we move this content to the `checktext` key?

2022-09-14 16:34 UTC, Mab879 commented on linux_os/guide/system/accounts/accounts-session/user_umask/accounts_umask_etc_login_defs/rule.yml
> +    Note: If the value of the "UMASK" parameter is set to "000" in "/etc/login.defs" file, the Severity is raised to a CAT I.
With this specific STIG language should we move this content to the `checktext` key?

2022-09-14 16:34 UTC, Mab879 commented on linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_data_disk_full_action_stig/rule.yml
> +    disk_full_action = HALT
Can we just update the variable?

2022-09-15 13:25 UTC, jan-cerny commented
I have tried to address the feedback in the new commits.

2022-09-19 16:11 UTC, Mab879 requested changes
Just one minor change is requested so that we don't lose some work.

2022-09-19 16:11 UTC, Mab879 commented on linux_os/guide/system/accounts/accounts-restrictions/accounts_authorized_local_users/rule.yml
> -srg_requirement: '{{{ full_name }}} must not have unnecessary accounts.'
I belive that this should still be here.

2022-09-20 08:16 UTC, jan-cerny commented
I have add back SRG requirement to accounts_authorized_local_users.

2022-09-20 11:41 UTC, Mab879 approved these changes

2022-09-20 11:41 UTC, merged