Update auditd_data_retention_max_log_file_action_stig OVAL to accept expected values from RHEL9 STIG profile
ComplianceAsCode/content pull request #9557
Opened 2022-09-23 11:27 UTC by ggbecker

#### Description:
- Update auditd_data_retention_max_log_file_action_stig OVAL to accept expected values from RHEL9 STIG profile.
- Both rotate and single should be accepted.

#### Rationale:

- No failing rule in Centos Stream 9 testing farm STIG profile.

2022-09-23 12:47 UTC, jan-cerny requested changes
The CI fail looks legit, the rule now allows "rotate" and "single" values, but
- the test scenario max_log_file_action_single.pass.sh sets the value to "syslog" and "syslog" isn't allowed value so it should be renamed to a "fail.sh" test scenario, and the name is confusing as it contains "single" so it should be renamed to max_log_file_action_syslog.fail.sh, In addition, the `variables`  setting in the test scenario header should be changed to either "rotate" or "single" so that the remediation would be able to configure a correct value.
- the test scenario max_log_file_action_not_there.fail.sh also fails because of the `variables`  setting in the test scenario header , it again should be changed to either "rotate" or "single" so that the remediation would be able to configure a correct value.

2022-09-23 14:29 UTC, ggbecker commented
> The CI fail looks legit, the rule now allows "rotate" and "single" values, but
> 
>     * the test scenario max_log_file_action_single.pass.sh sets the value to "syslog" and "syslog" isn't allowed value so it should be renamed to a "fail.sh" test scenario, and the name is confusing as it contains "single" so it should be renamed to max_log_file_action_syslog.fail.sh, In addition, the `variables`  setting in the test scenario header should be changed to either "rotate" or "single" so that the remediation would be able to configure a correct value.
> 
>     * the test scenario max_log_file_action_not_there.fail.sh also fails because of the `variables`  setting in the test scenario header , it again should be changed to either "rotate" or "single" so that the remediation would be able to configure a correct value.

I made the changes locally but forgot to save the file, that's why they didn't get updated. Let's see how they behave now.

2022-09-26 08:17 UTC, ggbecker commented
Results look good now, the rule is not being reported as failure anymore in the STIG hardening test and test scenarios are all passing.

```
:: [ 14:42:54 ] :: [   FAIL   ] :: Rules not passing after remediation:
xccdf_org.ssgproject.content_rule_rpm_verify_permissions - fail
xccdf_org.ssgproject.content_rule_firewalld_sshd_port_enabled - fail 
:: [ 14:42:54 ] :: [  BEGIN   ] :: Collecting system information with sos report :: actually running 'sos report -z xz --tmp-dir . --batch --skip-plugins cloud_init,i18n,jars,oddjob,soundcard,xen --since 20220923144119 &>sos_report.log'
:: [ 14:43:43 ] :: [   PASS   ] :: Collecting system information with sos report (Expected 0, got 0)
```

2022-09-26 12:37 UTC, jan-cerny approved these changes

2022-09-26 12:37 UTC, merged