Create unit tests for ssg.id_translate
ComplianceAsCode/content pull request #9624
Opened 2022-10-04 12:41 UTC by jan-cerny

#### Description:
Create unit tests for ssg.id_translate

#### Rationale:
Increases testing of build scripts.

2022-10-05 15:39 UTC, jan-cerny commented
I have rebased this PR on the top of the latest upstream branch to include the fix for the duplicate CCE problems.

2022-10-06 08:49 UTC, matejak requested changes
Thank you for the PR, I have some questions and suggestions though.
My main concern is that these tests are not really readable, and that they may be fragile.

It may be that there is no other way, but we need to look into that.

2022-10-06 08:49 UTC, matejak commented on tests/unit/ssg-module/test_id_translate.py
> +def test_tagname_to_abbrev():
Wouldn't it be better to define a mapping `tagname->expected abbreviation, and just iterate over the pairs?

2022-10-06 08:49 UTC, matejak commented on tests/unit/ssg-module/data/draft_oval.xml
> +<?xml version="1.0"?>
What about editing the OVAL, so it contains less verbose and more versatile data? For example, the ID could be rewritten to `RULE_ID`, and things that are not tested and not required by the build system code for smooth finish could get removed from the XML file.

2022-10-06 08:49 UTC, matejak commented on tests/unit/ssg-module/test_id_translate.py
> +def test_idtranslator_translate_oval(idtranslator, oval_tree):
I see that this test takes an OVAL tree, and "translates" it, whatever it means.
I would expect this test to focus on expected differences between original and translated (or expected lack of differences). Instead, the test is mainly about making sure that the translated tree has certain properties, and it does so without referencing the original.

2022-10-07 13:10 UTC, jan-cerny commented
I have refactor the test using a dictionary and I have removed some data from OVAL to reduce test data input and I have changed the unit tests for `translate()` and I have rebased on the latest upstream master.

2022-10-12 11:33 UTC, jan-cerny commented
@matejak I have add a test that uses the xml diff using the xmldiff library.

Also, I have rebased this PR on the top of the latest upstream master branch.

2022-10-18 07:18 UTC, jan-cerny commented
Based on discussion with the team I have removed the tests that check
expected properties of the output XML tree from the translate method,
because we will prefer the test based on xmldiff that allows us to
compare the expected diff with the actual diff.

2022-10-18 07:18 UTC, jan-cerny commented
@matejak Are there any further changes needed?

2022-10-20 06:56 UTC, jan-cerny commented on tests/unit/ssg-module/test_id_translate.py
> +    }
@matejak said that it would be better if the expected items are removed from the diff and finally it would be checked if the diff is empty.

2022-10-20 07:35 UTC, jan-cerny commented
I have removed the expected items from the diff

2022-10-20 11:54 UTC, matejak approved these changes

2022-10-20 11:55 UTC, matejak commented
Thank you for the PR with those tests, I appreciate them, and we can think of any possible improvements of their readability later - it is important to start with something solid first, and this is what the PR brings.

2022-10-20 11:55 UTC, merged