Add unit tests for ssg/build_renumber.py
ComplianceAsCode/content pull request #9632
Opened 2022-10-05 10:19 UTC by jan-cerny

#### Description:
Add unit tests for ssg/build_renumber.py
#### Rationale:
increase testing of build scripts

2022-10-05 15:43 UTC, jan-cerny commented
I have add a fix for the Code climate.

2022-10-12 06:43 UTC, jan-cerny commented
For some unknown reason the CI is stuck. Can you please rebase and push force it?

2022-10-12 06:45 UTC, jan-cerny commented
I have rebased this PR on the top of the latest upstream master branch.

2022-10-20 13:56 UTC, matejak requested changes
Looks great, just one small request.

2022-10-20 13:56 UTC, matejak commented on tests/unit/ssg-module/test_build_renumber.py
> +def xccdf_with_invalid_cce():
Would it be possible to add a test of `verify_correct_form_of_referenced_cce_identifiers` with a rule without a CCE?

2022-10-20 14:06 UTC, jan-cerny commented
I have add a test with a rule without CCE

2022-10-20 15:55 UTC, matejak approved these changes

2022-10-20 15:55 UTC, matejak commented
Perfect, great test coverage. Thank you for the PR!

2022-10-20 15:55 UTC, merged