Add pci-dss rule
ComplianceAsCode/content pull request #9745
Opened 2022-10-28 18:57 UTC by anivan-suse

#### Description:

- securetty_root_login_console_only
- sshd_limit_user_access

#### Rationale:

2022-10-31 09:04 UTC, jan-cerny commented
@anivan-suse Please take a look into this, the PR effectively doesn't make any changes. Probably a wrong rebase or a conflict with a previous PR?

2022-10-31 11:16 UTC, anivan-suse commented
> @anivan-suse Please take a look into this, the PR effectively doesn't make any changes. Probably a wrong rebase or a conflict with a previous PR?

Oh strange I will look into it. The commits add some CCEIDs, but it says 0 files changed. I'll check. Thanks!

2022-10-31 12:23 UTC, jan-cerny requested changes
Thnaks, now you need to add commit here that will remove the newly assigned CCEs from shared/references/cce-sle12-avail.txt and shared/references/cce-sle15-avail.txt

2022-11-01 08:39 UTC, jan-cerny approved these changes

2022-11-01 08:39 UTC, merged