Add new loopback rule
ComplianceAsCode/content pull request #9768
Opened 2022-11-05 11:47 UTC by anivan-suse

#### Description:

Add new rule to PCI-DSS
- set_loopback_traffic
- set_ipv6_loopback_traffic

2022-11-07 11:10 UTC, ggbecker commented on linux_os/guide/system/network/network-iptables/iptables_activation/set_loopback_traffic/rule.yml
> +    result in being locked out of the system.
```suggestion
        Changing firewall settings while connected over network can 
        result in being locked out of the system.
```

2022-11-10 16:27 UTC, jan-cerny requested changes

2022-11-10 16:27 UTC, jan-cerny commented on controls/cis_sle_15.yml
> +    rule:
This should be `rules:`.

2022-11-14 12:54 UTC, jan-cerny requested changes

2022-11-14 12:54 UTC, jan-cerny commented on controls/cis_sle_15.yml
> +    rule:
There should be `rules`, not `rule`.

2022-11-14 16:16 UTC, jan-cerny commented
The CI fail in Fedora rawhide is unrelated to this PR, it's caused by libxml2 ABI break, see https://bugzilla.redhat.com/show_bug.cgi?id=2139546

2022-11-14 16:16 UTC, merged