Add Refchecker to Tests
ComplianceAsCode/content pull request #9862
Opened 2022-11-22 20:48 UTC by Mab879

#### Description:

* Fix `utils/refchecker.py`
* Add `utils/refchecker.py` checks for RHEL7 and RHEL8 CIS profiles

#### Rationale:

* Make `utils/refchecker.py` useful
* Help find bugs sooner

#### Review Hints:
* Remove the CIS keys from a file like `linux_os/guide/system/software/integrity/crypto/configure_crypto_policy/rule.yml`, and it should make the tests fail.

2022-11-23 10:48 UTC, jan-cerny requested changes
I have run some of the tests on the RHEL 8 content and when I intentionally removed some CIS references from rules the test started to fail as is expected.

2022-11-23 10:48 UTC, jan-cerny commented on tests/CMakeLists.txt
> +    set_tests_properties("refchecker-rhel8-cis_workstation_l1" PROPERTIES LABELS quick)
Can we create a macro for the tests that call refchecker.py? That would reduce the repeating code.

2022-11-23 10:48 UTC, jan-cerny commented on tests/CMakeLists.txt
> +        COMMAND env "PYTHONPATH=$ENV{PYTHONPATH}" "${PYTHON_EXECUTABLE}" "${CMAKE_SOURCE_DIR}/utils/refchecker.py" --json "${CMAKE_SOURCE_DIR}/build/rule_dirs.json" --build-config-yaml "${CMAKE_BINAR
You test `cis_server_l1` for RHEL 8 for the second time, you want to test server profile level 2 instead which has just `cis` profile ID.

2022-11-23 10:48 UTC, jan-cerny commented on utils/refchecker.py
> +CONTROLS_DIR = os.path.join(SSG_ROOT, 'controls')
We probably should use double quotes because we use them in all other string literals in this script.

2022-11-29 17:42 UTC, Mab879 commented
/packit build

2022-11-30 16:19 UTC, marcusburghardt commented
@jan-cerny , I saw you already reviewed this PR once. Are you comfortable to assign it to yourself?

2022-12-07 09:57 UTC, jan-cerny approved these changes
I have run the tests locally and if I break something they start to fail as expected. Also, I have seen that they run in GitHub Actions.

2022-12-07 09:58 UTC, merged