SLE 12/15 CCE and CIS numbers for the CIS group job schedulers
ComplianceAsCode/content pull request #9883
Opened 2022-11-25 09:20 UTC by rumch-se

#### Description:

- _Assignment of CCE numbers or update/add of CIS numbers to the SLE 12/15 rules which a part of CIS group 5.1 Configure time-based job schedulers _

#### Rationale:

- Some of SLE 12/15 rules which a part of CIS group 5.1 Configure time-based job schedulers did not have CCE numbers assigned or their CIS numbers were not correct 

#### Review Hints:

- _Review hints here. Replace this text. Don't use the italics format!_

- _Use this optional section to give any relevant information which could help the reviewer to more quickly and assertively understand and test the changes._

- _Good examples are useful commands, if it is better to review all commits together or in a suggested sequence, any relevant discussion in other PRs or issues, etc._

2022-12-02 12:24 UTC, rumch-se commented
Hello @marcusburghardt
I have done rebase.
Have a nice day
Rumen

2022-12-05 07:39 UTC, rumch-se commented
Hello @marcusburghardt
I have done rebase.
Have a nice day
Rumen

2022-12-05 09:50 UTC, marcusburghardt requested changes

2022-12-05 09:50 UTC, marcusburghardt commented on shared/references/cce-sle12-avail.txt
> -CCE-92275-7
You are probably removing more CCEs than necessary in this PR. Could you check, please?

2022-12-05 09:50 UTC, marcusburghardt commented on shared/references/cce-sle15-avail.txt
> -CCE-91391-3
You are probably removing more CCEs than necessary in this PR. Could you check, please?

2022-12-08 12:09 UTC, rumch-se commented
Hello @marcusburghardt 
I have done rebase and now the numbers used for the rules correspond to the numbers taken from the files with available numbers.
Have a nice day
Rumen

2022-12-08 12:21 UTC, marcusburghardt approved these changes
Thanks

2022-12-08 13:18 UTC, merged