CCE and CIS codes for SLE 12/15 rules which belong to CIS group 5.2 c…
ComplianceAsCode/content pull request #9885
Opened 2022-11-25 10:57 UTC by rumch-se

…onfigure ssh server

#### Description:

- _Assignment of CCE/CIS numbers or CIS numbers update_

#### Rationale:

- Some of SLE 12/15 rules did not have CCE/CIS numbers assigned or some of CIS numbers were not correct 

#### Review Hints:

- _Review hints here. Replace this text. Don't use the italics format!_

- _Use this optional section to give any relevant information which could help the reviewer to more quickly and assertively understand and test the changes._

- _Good examples are useful commands, if it is better to review all commits together or in a suggested sequence, any relevant discussion in other PRs or issues, etc._

2022-12-02 12:24 UTC, rumch-se commented
Hello @marcusburghardt
I have done rebase.
Have a nice day
Rumen

2022-12-05 07:44 UTC, rumch-se commented
Hello @marcusburghardt
I have done rebase.
Have a nice day
Rumen

2022-12-05 09:51 UTC, marcusburghardt requested changes

2022-12-05 09:51 UTC, marcusburghardt commented on shared/references/cce-sle12-avail.txt
> -CCE-92281-5
You are probably removing more CCEs than necessary in this PR. Could you check, please?

2022-12-05 09:51 UTC, marcusburghardt commented on shared/references/cce-sle15-avail.txt
> -CCE-91397-0
You are probably removing more CCEs than necessary in this PR. Could you check, please?

2022-12-09 07:37 UTC, rumch-se commented
Good morning @marcusburghardt 
I have done necessary changes and now CCE codes taken from the files with available numbers correspond to the codes used in the rules.
Have a nice day
Rumen

2022-12-09 09:15 UTC, marcusburghardt approved these changes

2022-12-09 09:15 UTC, merged