CCE and CIS numbers assignments for SLE 12/15 rules which belong to u…
ComplianceAsCode/content pull request #9888
Opened 2022-11-25 14:14 UTC by rumch-se

…ser and group settings

#### Description:

- _ Small updates related to SLE 12/15 rules which are part of CIS group 6.2 User and Group Settings _

#### Rationale:

- Some of the SLE 12/15 rules do not have CCE/CIS numbers assigned or CIS numbers are not correct  

#### Review Hints:

- _Review hints here. Replace this text. Don't use the italics format!_

- _Use this optional section to give any relevant information which could help the reviewer to more quickly and assertively understand and test the changes._

- _Good examples are useful commands, if it is better to review all commits together or in a suggested sequence, any relevant discussion in other PRs or issues, etc._

2022-11-29 12:53 UTC, marcusburghardt commented on shared/references/cce-sle12-avail.txt
> -CCE-92227-8
It seems more CCEs were removed from this list than included in the rule.yml files in this PR. Is that intentional?

2022-12-02 12:25 UTC, rumch-se commented
Hello @marcusburghardt
I have done rebase.
Have a nice day
Rumen

2022-12-05 07:55 UTC, rumch-se commented
Hello @marcusburghardt
I have done rebase.
Have a nice day
Rume

2022-12-05 09:52 UTC, marcusburghardt requested changes

2022-12-05 09:52 UTC, marcusburghardt commented on shared/references/cce-sle12-avail.txt
> -CCE-92296-3
You are probably removing more CCEs than necessary in this PR. Could you check, please?

2022-12-05 09:52 UTC, marcusburghardt commented on shared/references/cce-sle15-avail.txt
> -CCE-91409-3
You are probably removing more CCEs than necessary in this PR. Could you check, please?

2022-12-09 15:24 UTC, rumch-se commented
Hello @marcusburghardt 
I have done expected changes. I do believe that now everything is OK.
Have a nice day
Rumen

2022-12-12 10:20 UTC, marcusburghardt approved these changes

2022-12-12 10:20 UTC, merged