CCE / CIS numbers for SLE 12/15 rules which belong to CIS group Initi…
ComplianceAsCode/content pull request #9900
Opened 2022-11-28 12:59 UTC by rumch-se

…al setup

#### Description:

- _Assignment of CCE/CIS numbers to SLE 12/15 rules which are part of CIS group 1 Initial Setup _

#### Rationale:

- Some of the SLE 12/15 rules do not have CCE numbers assigned or their CIS numbers have to be updated 

#### Review Hints:

- _Review hints here. Replace this text. Don't use the italics format!_

- _Use this optional section to give any relevant information which could help the reviewer to more quickly and assertively understand and test the changes._

- _Good examples are useful commands, if it is better to review all commits together or in a suggested sequence, any relevant discussion in other PRs or issues, etc._

2022-11-30 12:31 UTC, marcusburghardt commented
/packit build

2022-11-30 13:00 UTC, marcusburghardt requested changes
Many CCEs are removed from the list but not used in any rules included in this PR.

2022-12-01 15:20 UTC, rumch-se commented on shared/references/cce-sle15-avail.txt
> -CCE-91349-1
PR 9874
rule - banner_etc_motd

2022-12-01 15:20 UTC, rumch-se commented on shared/references/cce-sle12-avail.txt
> -CCE-92227-8
PR 9874
rule - banner_etc_motd

2022-12-02 12:26 UTC, rumch-se commented
Hello @marcusburghardt
I have done rebase.
Have a nice day
Rumen

2022-12-02 13:13 UTC, marcusburghardt commented
> Hello @marcusburghardt I have done rebase. Have a nice day Rumen

Hi @rumch-se , it PR is removing more CCEs from the list than using them in the rules. Could you take a look, please?

2022-12-05 08:01 UTC, rumch-se commented
Hello @marcusburghardt 
The rebase was done
Have a nice day
Rumen

2022-12-13 08:23 UTC, rumch-se commented
Good morning @marcusburghardt 
I have done a rebase of this PR.
Have a nice day
Rumen

2022-12-14 09:00 UTC, marcusburghardt approved these changes

2022-12-14 09:01 UTC, marcusburghardt commented
/packit retest-failed

2022-12-14 10:13 UTC, merged