New template `param_value_in_file` and audispd remote daemon rules
ComplianceAsCode/content pull request #9925
Opened 2022-12-05 09:57 UTC by yuumasato

#### Description:

- Add new template for `param = value` in file.
  - This template covers a different use case than `lineinfile` template.
  - `param_value_in_file` can correct confl
- Docs to come
- More audispd rules to come

#### Rationale:

- Template `lineinfile` doesn' cover the audispd rules very well.
  - The audispd config files alreay contain a line `active = no` and `lineinfile` template would add a new line `active = yes` instead of updating the `active` param with value `yes`.

#### Review Hints:

- `python3  tests/automatus.py rule --libvirt qemu:///session rhel79 --datastream build/ssg-rhel7-ds.xml --dontclean auditd_audispd_remote_daemon_activated`

2022-12-08 08:48 UTC, yuumasato commented
I'm aware of the ansible schema fail and am currently investigating.

2022-12-08 08:57 UTC, yuumasato commented on shared/templates/param_value_in_file/template.py
> +        data["prefix_regex"] = "^\s*"
Fixed.

2022-12-08 08:57 UTC, yuumasato commented
> I'm aware of the ansible schema fail and am currently investigating.

This should be solved now.

2022-12-08 10:23 UTC, yuumasato commented
The Automatus fails happen because the rules are available for rhel7 only.

2022-12-08 11:07 UTC, ggbecker commented
> The Automatus fails happen because the rules are available for rhel7 only.

In case of the [Automatus Fedora](https://github.com/ComplianceAsCode/content/actions/runs/3646753113/jobs/6158230796) check, it uses the RHEL7 content as expected but it fails on the test scenario set up, mainly because the expected file doesn't exist:

From logs:
```
##### auditd_audispd_remote_daemon_activated / wrong_value.fail.sh #####
ssh -o Port=33619 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@localhost cd /root/ssgts/auditd_audispd_remote_daemon_activated; SHARED=/root/ssgts/shared bash -x wrong_value.fail.sh
STDERR: Warning: Permanently added '[localhost]:33619' (ECDSA) to the list of known hosts.
+ sed -i /active/d /etc/audisp/plugins.d/au-remote.conf
sed: can't read /etc/audisp/plugins.d/au-remote.conf: No such file or directory
+ echo 'active = wrong_value'
```

One thing it can be improved is that the test scenario makes sure that the path+file from the template input exists and the test scenario can be properly instantiated

2022-12-08 17:19 UTC, vojtapolasek requested changes
Thank you for this new template, it looks very elegant with those macros.
Just small nitpicks, see comments.

2022-12-08 17:59 UTC, yuumasato commented on linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_remote_daemon_direction/rule.yml
> +    to understand the directon of events.
Thank addressed in 98d0ff5e256cbdfaa3c4afb727962c6dd9dc4372

2022-12-08 17:59 UTC, yuumasato commented on linux_os/guide/system/auditing/configure_auditd_data_retention/auditd_audispd_remote_daemon_activated/rule.yml
> +    Restart the <tt>auditd</tt> service:
Thank addressed in 98d0ff5e256cbdfaa3c4afb727962c6dd9dc4372

2022-12-09 08:12 UTC, vojtapolasek commented
/retest

2022-12-09 09:39 UTC, yuumasato commented
/retest

2022-12-09 13:04 UTC, vojtapolasek commented
/retest

2022-12-09 14:12 UTC, vojtapolasek commented
The Openshift CI has some temporary problem. They are working on a fix.

2022-12-12 10:14 UTC, yuumasato commented
@vojtapolasek I guess we can merge this. The PR is adding a new template a a new rules applicable for RHEL7 only.
And some of the early commits passed most of the Openshift CI.

2022-12-12 10:47 UTC, vojtapolasek approved these changes

2022-12-12 10:48 UTC, vojtapolasek commented
I agree. I hope it would take shorter to fix the issue. I am merging.a

2022-12-12 10:48 UTC, merged