accounts_password_set_min_life_existing: Avoid system accounts
ComplianceAsCode/content pull request #9955
Opened 2022-12-12 11:08 UTC by dodys

#### Description:

- Same principle as PR #9954 but for accounts_password_set_min_life_existing.

2022-12-13 16:14 UTC, dodys commented
/retest

2022-12-14 08:34 UTC, marcusburghardt requested changes
The errors in `testing-farm:centos-stream-8-x86_64` and `testing-farm:centos-stream-9-x86_64` seems to be legit. The rule is still failing after the Ansible remediation. Could you check it, please?

2022-12-14 11:09 UTC, dodys commented
@marcusburghardt I'm not really sure why it is failing for fedora and CentOS, do you have any idea?

2022-12-14 12:38 UTC, marcusburghardt commented
> @marcusburghardt I'm not really sure why it is failing for fedora and CentOS, do you have any idea?

No yet but I can take a look on this.

2022-12-16 20:16 UTC, freddieRv commented
Hi! Doing some testing on our side with these commits backported we found an issue were the `correct_stig_noninteractive.pass.sh` test results in a false negative when there are no interactive users on the system (other than root).

This issue is also present on the `accounts_password_set_max_life_existing` rule with the changes from #9954 

Changing the `check_existence` attribute of the OVAL tests to `any_exist` fixes this. However with this change the `incorrect_min_pass_age.fail.sh` test reports that "_Rule evaluation resulted in pass, instead of expected fail during initial stage_". An interactive user could be added on this test to make sure there is at least one ill-configured user to fail the test.

2022-12-19 10:15 UTC, dodys commented
> Hi! Doing some testing on our side with these commits backported we found an issue were the `correct_stig_noninteractive.pass.sh` test results in a false negative when there are no interactive users on the system (other than root).
> 
> This issue is also present on the `accounts_password_set_max_life_existing` rule with the changes from #9954
> 
> Changing the `check_existence` attribute of the OVAL tests to `any_exist` fixes this. However with this change the `incorrect_min_pass_age.fail.sh` test reports that "_Rule evaluation resulted in pass, instead of expected fail during initial stage_". An interactive user could be added on this test to make sure there is at least one ill-configured user to fail the test.

Thanks Freddie for testing this PR. Indeed your suggestions make sense, so I add a new commit changing the existence check to `any_exist` and simplified to `incorrect_min_pass_age.fail.sh` test.
Let me know in case of issues.
I will be doing the same for max life.

2023-01-05 11:22 UTC, marcusburghardt requested changes
Please, take a look in the comments from #9954

2023-01-06 08:19 UTC, marcusburghardt commented on linux_os/guide/system/accounts/accounts-restrictions/password_expiration/accounts_password_set_min_life_existing/tests/incorrect_min_pass_age.fail.sh
> +useradd testuser_123
```suggestion
USERNAME="testuser_123"
useradd $USERNAME
echo "cac_test_pass" | passwd --stdin $USERNAME
```

2023-01-06 15:12 UTC, marcusburghardt approved these changes
Thanks for the improvements in this rule @dodys .

2023-01-06 15:12 UTC, merged