Added a new rule package_tcp_wrappers_removed
ComplianceAsCode/content pull request #9981
Opened 2022-12-16 07:58 UTC by rumch-se

#### Description:

- _A new rule as a part of CIS profile for SLE 12/SLE 15 _

#### Rationale:

- The rule supports CIS requirement 2.1.1 Ensure xinetd is not installed (Automated)

2023-01-04 20:29 UTC, Mab879 requested changes
Please resolve the merge conflicts and respond to the instances of `xinetd` in the new rule.

2023-01-04 20:29 UTC, Mab879 commented on linux_os/guide/services/obsolete/inetd_and_xinetd/package_tcp_wrappers_removed/rule.yml
> +    Removing the <tt>xinetd</tt> package decreases the risk of the
```suggestion
    Removing the <tt>tcpd</tt> package decreases the risk of the
```

2023-01-04 20:29 UTC, Mab879 commented on linux_os/guide/services/obsolete/inetd_and_xinetd/package_tcp_wrappers_removed/rule.yml
> +    xinetd service's accidental (or intentional) activation.
```suggestion
    tcpd service's accidental (or intentional) activation.
```

2023-01-04 20:29 UTC, Mab879 commented on shared/references/cce-sle15-avail.txt
> -CCE-92476-1
Please check this, as there are merge conflicts.

2023-01-10 07:51 UTC, rumch-se commented
Hello @Mab879 
I have done rebase. Because tcpd and xinetd are connected, I have tried to provide more details why we have to remove tcpd after the removal of xinetd. CIS covers only the removal of xinetd.
Have a nice day
Rumen

2023-01-10 16:36 UTC, Mab879 approved these changes
LGTM. Thanks for the PR!

2023-01-10 16:38 UTC, Mab879 commented
Automatus failures are expected due to the prodtype.

2023-01-10 17:41 UTC, merged